force-app/main/default/objects/FS_Brandset__c/FS_Brandset__c.object-meta.xml
<CustomObject>
    <description>FS_Brandset</description>
    <label>Brandset</label>
    <nameField>
        <label>Brandset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brandsets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Brandsets_Cartridges__c/FS_Brandsets_Cartridges__c.object-meta.xml
<CustomObject>
    <label>Brandset-Cartridges</label>
    <nameField>
        <displayFormat>BC-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brandset-Cartridges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Brandsets_Cartridges__c/fields/FS_Brandset__c.field-meta.xml
<CustomField>
    <fullName>FS_Brandset__c</fullName>
    <label>Brandset</label>
    <referenceTo>FS_Brandset__c</referenceTo>
    <relationshipLabel>Cartridges</relationshipLabel>
    <relationshipName>Cartridge_Brandsets_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Brandsets_Cartridges__c/fields/FS_Cartridge__c.field-meta.xml
<CustomField>
    <fullName>FS_Cartridge__c</fullName>
    <label>Cartridge</label>
    <referenceTo>FS_Cartridge__c</referenceTo>
    <relationshipLabel>Brandsets</relationshipLabel>
    <relationshipName>Cartridge_Brandsets_Associations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Cartridge__c/FS_Cartridge__c.object-meta.xml
<CustomObject>
    <label>Cartridge</label>
    <nameField>
        <label>Cartridge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cartridges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FSCloneBrandsetController.cls
/***************************************************************************
 Name         : FSCloneBrandsetController
 Created By   : Infosys Limited
 Description  : Controller for FSCloneBrandsetPage
 Created Date : Sept 21,2016
 Modified By  : 
**************************************************************************/
public class FSCloneBrandsetController{

    public  FS_brandset__c brandset{get;set;}
    public ID newRecordId {get;set;}
    public  FSCloneBrandsetController(final apexPages.StandardController controller){
        // get record reference
        brandset = (FS_Brandset__c)controller.getRecord();               
    }
    
    
     /*
    * @MethodName - save
    * @Description - To Clone the existing  Brandset  with Brandset Cartridges records
    * @Return - PageReference*/
       
    public pageReference save(){
        final FS_brandset__c brandsetClone=brandset.clone(false,true);
         
        try{
            insert brandsetClone;
            newRecordId = brandsetClone.id;
            final List<FS_Brandsets_Cartridges__c> clonedBrandCarts = new List<FS_Brandsets_Cartridges__c>();
            
            for(FS_Brandsets_Cartridges__c brandCarts : [SELECT Id, FS_Brandset__c,FS_Cartridge__c 
                                                          FROM FS_Brandsets_Cartridges__c 
                                                          WHERE FS_Brandset__c = : brandset.Id]){
                                                 
                final FS_Brandsets_Cartridges__c clonedSObject = brandCarts.clone(false,true);
                clonedSObject.FS_Brandset__c =  brandsetClone.Id;
                clonedBrandCarts.add(clonedSObject);
            }
            insert clonedBrandCarts ;
        }
        
        catch(DMLException ex){
            
           ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Another Brandset with the same name already exists.Please choose another name.'));
            ApexErrorLogger.addApexErrorLog('FET','FSCloneBrandsetController','save','Insertion','Medium',ex,'NA');
            return null;
        }
        return new PageReference('/'+brandsetClone.id);
    }
    
    
}