force-app/main/default/objects/FS_Brandset__c/FS_Brandset__c.object-meta.xml
<CustomObject>
    <description>FS_Brandset</description>
    <label>Brandset</label>
    <nameField>
        <label>Brandset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brandsets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Brandset__c/fields/FS_Country__c.field-meta.xml
<CustomField>
    <fullName>FS_Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AD</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AG</fullName>
            </value>
            <value>
                <fullName>AI</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AN</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AQ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>AX</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BJ</fullName>
            </value>
            <value>
                <fullName>BL</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BN</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>US</fullName>
                <default>true</default>
                <label>US</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Brandset__c/fields/FS_Description__c.field-meta.xml
<CustomField>
    <fullName>FS_Description__c</fullName>
    <label>Brandset Desc</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FS_Brandset__c/fields/FS_Effective_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Effective_Start_Date__c</fullName>
    <inlineHelpText>Date when Brandset becomes available for commercial use</inlineHelpText>
    <label>Commercial Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Brandset__c/fields/FS_Platform__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform__c</fullName>
    <description>Platform</description>
    <label>Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Brandsets_Cartridges__c/FS_Brandsets_Cartridges__c.object-meta.xml
<CustomObject>
    <label>Brandset-Cartridges</label>
    <nameField>
        <displayFormat>BC-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brandset-Cartridges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Brandsets_Cartridges__c/fields/FS_Brandset__c.field-meta.xml
<CustomField>
    <fullName>FS_Brandset__c</fullName>
    <label>Brandset</label>
    <referenceTo>FS_Brandset__c</referenceTo>
    <relationshipLabel>Cartridges</relationshipLabel>
    <relationshipName>Cartridge_Brandsets_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Brandsets_Cartridges__c/fields/FS_Cartridge__c.field-meta.xml
<CustomField>
    <fullName>FS_Cartridge__c</fullName>
    <label>Cartridge</label>
    <referenceTo>FS_Cartridge__c</referenceTo>
    <relationshipLabel>Brandsets</relationshipLabel>
    <relationshipName>Cartridge_Brandsets_Associations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Cartridge__c/FS_Cartridge__c.object-meta.xml
<CustomObject>
    <label>Cartridge</label>
    <nameField>
        <label>Cartridge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cartridges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Cartridge__c/fields/FS_Country__c.field-meta.xml
<CustomField>
    <fullName>FS_Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AD</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AG</fullName>
            </value>
            <value>
                <fullName>AI</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AN</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AQ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>AX</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BJ</fullName>
            </value>
            <value>
                <fullName>BL</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BN</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
            <value>
                <fullName>US</fullName>
                <default>true</default>
                <label>US</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Cartridge__c/fields/FS_Description__c.field-meta.xml
<CustomField>
    <fullName>FS_Description__c</fullName>
    <label>Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/FS_Cartridge__c/fields/FS_Flavor__c.field-meta.xml
<CustomField>
    <fullName>FS_Flavor__c</fullName>
    <label>Flavor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Cartridge__c/fields/FS_Platform__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform__c</fullName>
    <description>Platform</description>
    <label>Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2000</fullName>
            </value>
            <value>
                <fullName>3000</fullName>
            </value>
            <value>
                <fullName>7000</fullName>
            </value>
            <value>
                <fullName>8000</fullName>
            </value>
            <value>
                <fullName>9000</fullName>
            </value>
            <value>
                <fullName>9100</fullName>
            </value>
            <value>
                <fullName>3100</fullName>
            </value>
            <value>
                <fullName>6000</fullName>
            </value>
            <value>
                <fullName>7100</fullName>
            </value>
            <value>
                <fullName>6050</fullName>
                <isActive>false</isActive>
                <label>6050</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Platform_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3100</fullName>
    </customValue>
    <customValue>
        <fullName>6000</fullName>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
    </customValue>
    <customValue>
        <fullName>7100</fullName>
    </customValue>
    <customValue>
        <fullName>8000</fullName>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
    </customValue>
    <masterLabel>Platform Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FSCloneBrandsetControllerTest.cls
/**************************************************************************
Name         : FSCloneBrandsetControllerTest
Created By   : Alisha Gupta
Description  : Test class of FSCloneBrandsetController
Created Date : Sept 21, 2016
****************************************************************************/
@isTest
public class FSCloneBrandsetControllerTest{
    
    private static  FS_brandset__c brandsetName=new FS_Brandset__c();
    public static void testRecords(){
        //custom setting trigger switch
        FSTestFactory.createTestDisableTriggerSetting();
        
        //create test record
        brandsetName.FS_Country__c='US';       
        brandsetName.FS_Description__c='test record'+math.random();
        brandsetName.FS_Platform__c='7000';
        brandsetName.FS_Effective_Start_Date__c=system.today();
        insert brandsetName;
        
        final FS_Cartridge__c cart=new FS_Cartridge__c();
        cart.FS_Country__c='US';
        cart.FS_Platform__c='7000';
        cart.fs_flavor__c='nothing';
        insert cart;
        final FS_Brandsets_Cartridges__c brandsetCart=new FS_Brandsets_Cartridges__c();
        brandsetCart.FS_Brandset__c=brandsetName.id;
        brandsetCart.FS_Cartridge__c=cart.id;
        insert brandsetCart;
    }
    
    private static testMethod void testCloneRec(){
        
        //insert test records;
        testRecords();
        final Profile sysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
        final User sysAdminUser=FSTestFactory.createUser(sysAdmin.id);
        insert sysAdminUser;
        
        system.runAs(sysAdminUser){
            Test.StartTest();
            final ApexPages.StandardController con = new ApexPages.StandardController(brandsetName);
            // create the controller
            final FSCloneBrandsetController fsController=new FSCloneBrandsetController(con);
            
            final PageReference ref = fsController.Save();
            // create the matching page reference
            
            final PageReference redir = new PageReference('/'+fsController.newRecordId);
            
            // make sure the user is sent to the correct url
            System.assertEquals(ref.getUrl(),redir.getUrl());
            
            // check that the new Brandset is created
            final FS_brandset__c newBset = [select id from FS_brandset__c where id = :fsController.newRecordId];
            System.assertNotEquals(newBset.id, null);
            // check that the new Brandset cartridge is created
            final List<FS_Brandsets_Cartridges__c> newBC = [Select id From FS_Brandsets_Cartridges__c where FS_brandset__c = :newBset.id];
            System.assertEquals(newBC.size(),1);  
            
            Test.StopTest();
        }
        
    }
    
    private static testMethod void testCloneRec1()
    {
        //testRecords();
        final ApexPages.StandardController con = new ApexPages.StandardController(brandsetName);
        final FSCloneBrandsetController fsController=new FSCloneBrandsetController(con);
        
        Test.StartTest();
        
        
        final FS_brandset__c test1 = new FS_brandset__c();
        fsController.brandset = test1;
        fsController.Save();
        Test.stopTest();
        System.assertNotEquals(NULL,fsController.brandset); 
    }
    
}