force-app/main/default/objects/FS_Brandset__c/FS_Brandset__c.object-meta.xml
<CustomObject>
    <description>FS_Brandset</description>
    <label>Brandset</label>
    <nameField>
        <label>Brandset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brandsets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Brandset__c/fields/FS_Brandset_Number__c.field-meta.xml
<CustomField>
    <fullName>FS_Brandset_Number__c</fullName>
    <description>Brandset number</description>
    <displayFormat>B-{0000}</displayFormat>
    <externalId>true</externalId>
    <label>Brandset#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Flavor_Change_New__c/FS_Flavor_Change_New__c.object-meta.xml
<CustomObject>
    <description>desc</description>
    <label>Flavor Change Line</label>
    <nameField>
        <displayFormat>FCN-{0000}</displayFormat>
        <label>Flavor Change Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flavor Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Flavor_Change_New__c/fields/FS_BS_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_BS_Effective_Date__c</fullName>
    <label>Brandset Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Flavor_Change_New__c/fields/FS_Final_Approval__c.field-meta.xml
<CustomField>
    <fullName>FS_Final_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Final Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Flavor_Change_New__c/fields/FS_Hide_Show_Water_Button__c.field-meta.xml
<CustomField>
    <fullName>FS_Hide_Show_Water_Button__c</fullName>
    <label>New Non-Branded Water</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hide</fullName>
            </value>
            <value>
                <fullName>Show</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Flavor_Change_New__c/fields/FS_New_Brandset__c.field-meta.xml
<CustomField>
    <fullName>FS_New_Brandset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Brandset</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>FS_Brandset__c.FS_Platform_Applicable__c</field>
            <operation>contains</operation>
            <valueField>$Source.FS_Platform__c</valueField>
        </filterItems>
        <filterItems>
            <field>FS_Brandset__c.FS_Platform_Applicable__c</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>FS_Brandset__c.Available_for_Selection__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FS_Brandset__c</referenceTo>
    <relationshipLabel>Flavor Changes (New Brandset)</relationshipLabel>
    <relationshipName>Flavor_Changes_New3_del1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Flavor_Change_New__c/fields/FS_Outlet_Dispenser__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_Dispenser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet Dispenser</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>please select only 7000,8000,9000 Outlet Dispenser</errorMessage>
        <filterItems>
            <field>FS_Outlet_Dispenser__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>7000, 8000, 9000, CCNA Dispenser</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipLabel>Flavor Changes</relationshipLabel>
    <relationshipName>Flavor_Changes_New</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Flavor_Change_New__c/fields/FS_WA_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_WA_Effective_Date__c</fullName>
    <label>Non-Branded Water Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/FSFlavorChangeOD.cls
/*********************************************************************************************************
Name         : FSFlavorChangeOD
Created By   : Infosys Limited 
Created Date : 23-Dec-2016
Usage        : Extension for FSFlavorChangeOD, Displays list of Flavor Changes that are approved to OD level

***********************************************************************************************************/

public class FSFlavorChangeOD {

    public FS_Outlet_Dispenser__c outletDispenser{set;get;}
    
    public FSFlavorChangeOD(ApexPages.standardController controller){
         outletDispenser= (FS_Outlet_Dispenser__c) controller.getRecord();
         
    }
    
    public List<FS_Flavor_Change_New__c> getFlavorChanges(){
        return [SELECT ID,name,FS_New_Brandset__c,FS_New_Brandset__r.name,FS_New_Brandset__r.FS_Brandset_number__c,
                FS_BS_Effective_Date__c,FS_Hide_Show_Water_Button__c,
                FS_WA_Effective_Date__c FROM FS_Flavor_Change_New__c WHERE FS_Final_Approval__c=true AND 
                FS_Outlet_Dispenser__c =:outletDispenser.Id ORDER BY  LastModifiedDate DESC];
    }
}