force-app/main/default/objects/Case/fields/Dispenser_serial_number__c.field-meta.xml
<CustomField>
    <fullName>Dispenser_serial_number__c</fullName>
    <inlineHelpText>8 character alpha-numeric dispenser serial number. Separate multiple dispensers by comma.</inlineHelpText>
    <label>Dispenser serial number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FACT_Case_Type__c.field-meta.xml
<CustomField>
    <fullName>FACT_Case_Type__c</fullName>
    <label>Case Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Connectivity Issue</fullName>
            </value>
            <value>
                <fullName>Enrollment Issue</fullName>
            </value>
            <value>
                <fullName>Consumption Issue</fullName>
            </value>
            <value>
                <fullName>Alignment Issue</fullName>
            </value>
            <value>
                <fullName>Brand Selection</fullName>
            </value>
            <value>
                <fullName>Relocation / AMOA</fullName>
            </value>
            <value>
                <fullName>Software / Content</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FS_ACN__c.field-meta.xml
<CustomField>
    <fullName>FS_ACN__c</fullName>
    <formula>FS_Outlet_Dispenser__r.FS_ACN_NBR__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ACN#</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_Address__c.field-meta.xml
<CustomField>
    <fullName>FS_Address__c</fullName>
    <formula>FS_Outlet_Dispenser__r.FS_Outlet__r.CCR_Address__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_Outlet_Name__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_Name__c</fullName>
    <formula>FS_Outlet_Dispenser__r.FS_Name1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Outlet Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_SAP__c.field-meta.xml
<CustomField>
    <fullName>FS_SAP__c</fullName>
    <formula>FS_Outlet_Dispenser__r.FS_Outlet__r.FS_SAP_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SAP#</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>FS_Serial_Number__c</fullName>
    <formula>FS_Outlet_Dispenser__r.FS_Serial_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Serial Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Email_Details__c/Email_Details__c.object-meta.xml
<CustomObject>
    <label>Case Email Notification</label>
    <nameField>
        <displayFormat>Email - {0000}</displayFormat>
        <label>Email Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Email Notifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Email_Details__c/fields/Closure_Mail_Flag__c.field-meta.xml
<CustomField>
    <fullName>Closure_Mail_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox for mentioning whether Case Closure email has sent or not.</description>
    <label>Case Closure Email Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Email_Details__c/fields/Creation_Mail_Flag__c.field-meta.xml
<CustomField>
    <fullName>Creation_Mail_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox for mentioning whether Case Creation email has sent or not.</description>
    <label>Case Creation Email Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Email_Details__c/fields/Parent_Case__c.field-meta.xml
<CustomField>
    <fullName>Parent_Case__c</fullName>
    <description>Master-Detail relationship for the holding Case object.</description>
    <label>Parent Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case Email Notifications</relationshipLabel>
    <relationshipName>Email_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Email_Details__c/fields/Send_Email__c.field-meta.xml
<CustomField>
    <fullName>Send_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox to hold whether user has to be notified with the Email or not.</description>
    <label>Send Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Email_Details__c/fields/User_Email__c.field-meta.xml
<CustomField>
    <fullName>User_Email__c</fullName>
    <description>Text field used for saving the user&#39;s email id.</description>
    <label>User Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Email_Details__c/fields/User_Name__c.field-meta.xml
<CustomField>
    <fullName>User_Name__c</fullName>
    <description>Text field for storing user name.</description>
    <label>User Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Email_Details__c/fields/User_Role__c.field-meta.xml
<CustomField>
    <fullName>User_Role__c</fullName>
    <description>Text field for storing user role.</description>
    <label>User Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FS_EmailUserListController.cls
/**************************************************************************************
Apex Class Name     : FS_EmailUserListController
Function            : This is a controller class for FS_VF_EmailUserList visual force page.
					  This class is used to update the user list in Case Email Notification object connected to Case object.
					  Also this class is used for sending case creation email to selected users.
Author				: Infosys
Modification Log    :
* Developer         : Date             Description
* ----------------------------------------------------------------------------                 
* Sunil TD	          07/25/2017       Original Version for implementing send email functionality for FACT cases.
*************************************************************************************/

public class FS_EmailUserListController {
    
    public Case caseData{get;set;}
    public Case selectCaseData{get;set;}
    public Id caseID {get;set;}
    public List<userDetails> usersInfo{get;set;}
    public List<Email_Details__c> usersToBeUpdated{get;set;}
    public transient List<Messaging.SingleEmailMessage> mailList;
    public static final String Fact_Case_Create_Notification = 'Fact_Case_Create_Notification';
    public static final String New_String = 'New';
    public static final String Project_Name = 'Freestyle Support 2017';
    public static final String FS_EmailUserListController = 'FS_EmailUserListController';
    public static final String NA = 'NA';
    public static final String Medium = 'Medium';
    public static final String selectCaseDataFetch = 'selectCaseDataFetch';
    public static final String fetchEmailDetails = 'fetchEmailDetails';
    public static final String saveSendEmail = 'saveSendEmail';
    public static final String checkUserPresent = 'checkUserPresent';
    public static final String FS_EmailUserListControllerConst = 'FS_EmailUserListController';
    
    public FS_EmailUserListController(ApexPages.StandardController controller)
    {
        try
        {
            caseID = apexpages.currentpage().getparameters().get('id');
            this.caseData = [Select Id from Case where Id=:caseID];
            selectCaseDataFetch();
            usersInfo = fetchEmailDetails();
        }
        catch(Exception ex)
        {
            system.debug('Exception'+ex.getMessage());
            ApexErrorLogger.addApexErrorLog(Project_Name,FS_EmailUserListController,FS_EmailUserListControllerConst,NA,Medium,ex,NA);
        }
    }
    
    /*****************************************************************************************
    	Method : selectCaseDataFetch
    	Description : Method for fetching values for the case record.
    ******************************************************************************************/
    public void selectCaseDataFetch()
    {
        try
        {
            selectCaseData = [Select Id,Status,CaseNumber,FS_Serial_Number__c,Subject,Description,FS_ACN__c,FS_SAP__c,
                              FS_Outlet_Name__c,FS_Address__c,FACT_Case_Type__c,Dispenser_serial_number__c 
                              from Case where Id=:caseData.Id];
        }
        catch(System.QueryException ex)
        {
            system.debug('System.QueryException : ' + ex.getMessage());
            ApexErrorLogger.addApexErrorLog(Project_Name,FS_EmailUserListController,selectCaseDataFetch,NA,Medium,ex,NA);
        }
    }
    
    /*****************************************************************************************
    	Method : fetchEmailDetails
    	Description : Method to fetch the list of users from Case Email Notification object 
					  related to Case object.
    ******************************************************************************************/
    public List<userDetails> fetchEmailDetails()
    {
        List<userDetails> userDetailList = new List<userDetails>();
        try
        {
            List<Email_Details__c> emailDetailList = [Select Id,User_Name__c,User_Role__c,User_Email__c,Send_Email__c,
                                                      Creation_Mail_Flag__c,Closure_Mail_Flag__c from Email_Details__c 
                                                      where Parent_Case__c=:caseData.Id];
            if(!emailDetailList.isEmpty())
            {
                for(Email_Details__c emailList : emailDetailList)
                {
                    userDetails userRecord = new userDetails();
                    userRecord.emailDetail = emailList;
                    userRecord.userName = emailList.User_Name__c;
                    userRecord.userEmailId = emailList.User_Email__c;
                    userRecord.userRole = emailList.User_Role__c;
                    if(emailList.Send_Email__c)
                    {
                        userRecord.userPresent = true;
                    }
                    else
                    {
                        userRecord.userPresent = false;
                    }
                    
                    userDetailList.add(userRecord);
                }
            }
        }
        catch(System.QueryException ex)
        {
            system.debug('System.QueryException : ' + ex.getMessage());
            ApexErrorLogger.addApexErrorLog(Project_Name,FS_EmailUserListController,fetchEmailDetails,NA,Medium,ex,NA);
        }
        return userDetailList;
    }
    
    /*****************************************************************************************
    	Method : saveSendEmail
    	Description : Method to save the users selected from visual force page and send 
					  case creation email if mail notification has not sent previously.
    ******************************************************************************************/
    public pageReference saveSendEmail()
    {
        try
        {
            usersToBeUpdated = new List<Email_Details__c>();
            mailList = new List<Messaging.SingleEmailMessage>();
            FSCaseManagementHelper helperMethod = new FSCaseManagementHelper();
            List<String> emailRolesList = helperMethod.getAllEmailRoles(true,false,false);
            Set<String> emailRolesSet = new Set<String>();
            EmailTemplate template = [SELECT Id,HtmlValue,Body,Subject FROM EmailTemplate WHERE 
                                      developername =: Fact_Case_Create_Notification];
            emailRolesSet.addAll(emailRolesList);
            
            if(!usersInfo.isEmpty())
            {
                for(userDetails user : usersInfo)
                {
                    checkUserPresent(user,emailRolesSet,template);
                }
            }
            if(!mailList.isEmpty())
            {
                Messaging.SendEmail(mailList);
            }
            if(!usersToBeUpdated.isEmpty())
            {
                update usersToBeUpdated;
            }
        }
        catch(system.EmailException ex)
        {
            system.debug('system.EmailException : ' + ex.getMessage());
            ApexErrorLogger.addApexErrorLog(Project_Name,FS_EmailUserListController,saveSendEmail,NA,Medium,ex,NA);
        }
        //return new PageReference('javascript:window.opener.location.reload(); window.self.close();');
        return new PageReference('javascript:window.self.close();');
    }
    
    /*****************************************************************************************
    	Method : checkUserPresent
    	Description : Method to check the users for whom case creation mail has to be sent 
					  and call the mail sending method.
    ******************************************************************************************/
    public void checkUserPresent(userDetails user,Set<String> emailRolesSet,EmailTemplate template)
    {
        try
        {
            if(user.userPresent)
            {
                if(selectCaseData.status == New_String && user.emailDetail.Creation_Mail_Flag__c != true)
                {
                    if(!emailRolesSet.isEmpty() && emailRolesSet.contains(user.userRole))
                    {
                        user.emailDetail.Creation_Mail_Flag__c = true;
                        user.emailDetail.Send_Email__c = true;
                        usersToBeUpdated.add(user.emailDetail);
                        mailList.add(FS_SendEmail_Helper.replaceMergeFieldValues(user.userName,user.userEmailId,
                                                                                 template,selectCaseData,false,null,null,false));
                    }
                    else
                    {
                        user.emailDetail.Send_Email__c = true;
                        usersToBeUpdated.add(user.emailDetail);
                    }
                }
                else
                {
                    user.emailDetail.Send_Email__c = true;
                    usersToBeUpdated.add(user.emailDetail);
                }
            }
            else
            {
                user.emailDetail.Send_Email__c = false;
                usersToBeUpdated.add(user.emailDetail);
            }
        }
        catch(NullPointerException ex)
        {
            system.debug('NullPointerException : ' + ex.getMessage());
            ApexErrorLogger.addApexErrorLog(Project_Name,FS_EmailUserListController,checkUserPresent,NA,Medium,ex,NA);
        }
    }
    
    public class userDetails
    {
        public Email_Details__c emailDetail{get;set;}
        public String userName{get;set;}
        public String userEmailId{get;set;}
        public String userRole{get;set;}
        public Boolean userPresent{get;set;}
    }

}