force-app/main/default/objects/Case/fields/Dispenser_serial_number__c.field-meta.xml
<CustomField>
    <fullName>Dispenser_serial_number__c</fullName>
    <inlineHelpText>8 character alpha-numeric dispenser serial number. Separate multiple dispensers by comma.</inlineHelpText>
    <label>Dispenser serial number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_Dispenser_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Dispenser_Type__c</fullName>
    <description>FS Dispenser Type</description>
    <inlineHelpText>Please enter dispenser type</inlineHelpText>
    <label>FS Dispenser Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2000 Series</fullName>
            </value>
            <value>
                <fullName>3100 Series</fullName>
            </value>
            <value>
                <fullName>6000 Series</fullName>
            </value>
            <value>
                <fullName>7000 Series</fullName>
            </value>
            <value>
                <fullName>7100 Series</fullName>
            </value>
            <value>
                <fullName>8000 Series</fullName>
            </value>
            <value>
                <fullName>9000 Series</fullName>
            </value>
            <value>
                <fullName>9100 Series</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FS_Outlet_Dispenser__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_Dispenser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>To find OD Reference, Click on Search Icon to find OD Record by Serial# or ACN#</inlineHelpText>
    <label>OD Reference (Customer ACN)</label>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>FS_Serial_Number__c</fullName>
    <formula>FS_Outlet_Dispenser__r.FS_Serial_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Serial Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseToOutletdispenser__c/CaseToOutletdispenser__c.object-meta.xml
<CustomObject>
    <description>This is a junction object between case object and outlet dispenser object</description>
    <label>Case To OD</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case To Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseToOutletdispenser__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>Parent case</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case To Outlet Dispensers</relationshipLabel>
    <relationshipName>CaseToOutletdispensers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CaseToOutletdispenser__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Case_To_Outletdispensers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseToOutletdispenser__c/fields/FS_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>FS_Serial_Number__c</fullName>
    <formula>Outlet_Dispenser__r.FS_Serial_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Serial Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseToOutletdispenser__c/fields/Outlet_Dispenser__c.field-meta.xml
<CustomField>
    <fullName>Outlet_Dispenser__c</fullName>
    <label>Outlet Dispenser</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Customer__c</field>
            <operation>equals</operation>
            <valueField>FS_Outlet_Dispenser__c.FS_Outlet__c</valueField>
        </filterItems>
        <filterItems>
            <field>FS_Outlet_Dispenser__c.FS_IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipName>CaseToOutletdispensers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CaseToOutletdispenser__c/fields/Serial_Number_Text__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number_Text__c</fullName>
    <label>Serial Number Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Date_Status__c.field-meta.xml
<CustomField>
    <fullName>FS_Date_Status__c</fullName>
    <label>MDM Registered Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Dispenser_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Dispenser_Type__c</fullName>
    <description>Dispenser Type</description>
    <formula>IF(RecordType.Name=&#39;BoE Dispenser&#39;, TEXT(FS_Model__c), FS_Equip_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dispenser Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Equip_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Equip_Type__c</fullName>
    <description>equip type</description>
    <inlineHelpText>This is the JDE Equipment Type value</inlineHelpText>
    <label>Equipment Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_IsActive__c.field-meta.xml
<CustomField>
    <fullName>FS_IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>active or inactive</description>
    <label>Active (A) / Inactive (I)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Name1__c.field-meta.xml
<CustomField>
    <fullName>FS_Name1__c</fullName>
    <description>Outlet Name</description>
    <formula>FS_Outlet__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>NAME1</inlineHelpText>
    <label>Outlet Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <description>Outlet field.</description>
    <label>Outlet</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 3) OR (2 AND 4 AND (5 OR 7)) OR (2 AND 4 AND 6)</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for Outlet.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Outlet</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Outlet</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>7000, 8000, 9000, CCNA Dispenser</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Dispenser</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value>No, Yes</value>
        </filterItems>
        <filterItems>
            <field>Account.Is_Default_FET_International_Outlet__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlet Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Serial_Number2__c.field-meta.xml
<CustomField>
    <fullName>FS_Serial_Number2__c</fullName>
    <description>Serial Number/Asset Tag.</description>
    <label>JDE Serial Number/Asset Tag</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>FS_Serial_Number__c</fullName>
    <formula>FS_Serial_Number2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Serial Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Status__c.field-meta.xml
<CustomField>
    <fullName>FS_Status__c</fullName>
    <description>Status.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Enroll</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Hibernate</fullName>
            </value>
            <value>
                <fullName>Wakeup</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Booking Complete</fullName>
            </value>
            <value>
                <fullName>Dispenser Pickup</fullName>
            </value>
            <value>
                <fullName>Dispenser Delivered</fullName>
            </value>
            <value>
                <fullName>In Inventory</fullName>
            </value>
            <value>
                <fullName>Assigned to Outlet</fullName>
            </value>
            <value>
                <fullName>Winterized</fullName>
            </value>
            <value>
                <fullName>Rough Stock</fullName>
            </value>
            <value>
                <fullName>Remaned</fullName>
            </value>
            <value>
                <fullName>To be scrapped by Bottler</fullName>
            </value>
            <value>
                <fullName>To be scrapped by CM</fullName>
            </value>
            <value>
                <fullName>Confirmed Scrapped</fullName>
            </value>
            <value>
                <fullName>Sold to Bottler</fullName>
            </value>
            <value>
                <fullName>Purchased from Bottler</fullName>
            </value>
            <value>
                <fullName>To be Remanufactured</fullName>
            </value>
            <value>
                <fullName>Unenrolled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Outlet_City__c.field-meta.xml
<CustomField>
    <fullName>Outlet_City__c</fullName>
    <formula>FS_Outlet__r.ShippingCity</formula>
    <label>Outlet City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SEMultiDispensers.cls
/*********************************************************************************************************
Apex Class Name     : SEMultiDispensers
Function            : This is a controller class for Visual force page that allows Add/Delete Multiple dispensers for EMT cases.
Author				: Infosys
Modification Log    :
* Developer         : Date             Description
* ----------------------------------------------------------------------------                 
* Mahender	          11/17/2016       This class supports the Visualforce page by supplying the list of 
									   Outlet Dispensers filtered by selected Outlet in the page.
* Sunil TD	          08/07/2017       Updated the class for fetching Outlet Dispensers data based on the selected 
									   Outlet Dispenser's Outlet record.
***********************************************************************************************************/

global without sharing class SEMultiDispensers {
    
    public boolean isRender{get;set;}
    public List<DispenserWrapper> selectDispensersWrapper {get;set;}
    public list<FS_Outlet_Dispenser__c> outletDispenserList{get;set;}
    public Id accountID{get;set;}
    public String dispenserId{get;set;}
    public Id caseID {get;set;}
    
    //Using a wrapper class this constructor sends the list of already selected and un selected dispensers list
    public SEMultiDispensers(ApexPages.StandardController controller)
    {
        try
        {
            selectDispensersWrapper =new List<DispenserWrapper>();
            List<CaseToOutletdispenser__c> caseToODRecords = new List<CaseToOutletdispenser__c>();
            Set<String> serialNumberSet = new Set<String>();
            dispenserId= apexpages.currentpage().getparameters().get('dispenserid');
            FS_Outlet_Dispenser__c dis = [SELECT FS_Outlet__c,FS_Serial_Number2__c FROM FS_Outlet_Dispenser__c WHERE name =:dispenserId];
            accountID = dis.FS_Outlet__c;
            caseID = apexpages.currentpage().getparameters().get('id');
            case cas=[select FS_Outlet_Dispenser__c,Dispenser_serial_number__c,FS_Outlet_Dispenser__r.FS_Serial_Number2__c from case where id=:caseID ];
            isRender=false;
            
            //Select all the Active Outlet Dispensers at outlet level. Assuming that not more than 100 OD's exists in an outlet.
            outletDispenserList= [select FS_Date_Status__c,FS_Name1__c ,FS_Equip_Type__c,FS_Outlet__c ,FS_Status__c ,
                                  FS_Dispenser_Type__c ,Outlet_City__c ,id, name,FS_Serial_Number2__c,FS_IsActive__c from FS_Outlet_Dispenser__c 
                                  where FS_Outlet__c=:accountID /*AND FS_IsActive__c = true*/ ORDER BY FS_Name1__c ASC NULLS FIRST limit 100];
            if(outletDispenserList.size()<1)
            {
                isRender=true;
            }
            
            caseToODRecords = [select Id,FS_Serial_Number__c from CaseToOutletdispenser__c where Case__c =: caseID];
            if(!caseToODRecords.isEmpty())
            {
                for(CaseToOutletdispenser__c record : caseToODRecords)
                {
                    serialNumberSet.add(record.FS_Serial_Number__c);
                }
            }
            
            for (FS_Outlet_Dispenser__c oDispenser: outletDispenserList)
            {
                DispenserWrapper d=new DispenserWrapper ();
                d.dispenser=oDispenser;
                d.checked=false;
                d.disableDispenser = false;
                if(!serialNumberSet.isEmpty() && !string.isEmpty(oDispenser.FS_Serial_Number2__c) &&
                   serialNumberSet.contains(oDispenser.FS_Serial_Number2__c))
                {
                    d.checked =true;
                }
                if(cas.FS_Outlet_Dispenser__r != null && oDispenser.FS_Serial_Number2__c != null &&
                   cas.FS_Outlet_Dispenser__r.FS_Serial_Number2__c == oDispenser.FS_Serial_Number2__c)
                {
                    d.disableDispenser = true; 
                }
                selectDispensersWrapper.add(d);
            }
        }
        catch(DmlException ex)
        {
            system.debug('DmlException : ' + ex.getMessage());
        }
    }
    
    /*****************************************************************************************
    Method : deleteJunctionRecords
    Description : Method to delete records from Case To Outlet Dispensers for particular Case record.
    ******************************************************************************************/
    public static void deleteJunctionRecords(Id caseRecordID)
    {
        try
        {
            list<CaseToOutletdispenser__c> deletionList=new list<CaseToOutletdispenser__c>();
            deletionList=[SELECT Id FROM CaseToOutletdispenser__c WHERE Case__c = :caseRecordID];
            delete deletionList;
        }
        Catch(Exception e)
        {
            system.debug('Error while deleting the junction object records'+e.getMessage());
        }
    }
    
    /*****************************************************************************************
    Method : updateDispenserSerialNumber
    Description : Method to update Dispenser Serial Number in Case record.
    ******************************************************************************************/
    public static Case updateDispenserSerialNumber(Id caseRecordID,String selectedSerialNumber)
    {
        case caseRecord;
        try
        {
            id caseID = caseRecordID;
            caseRecord=[select AccountId,Dispenser_serial_number__c from case where id=:caseID];
            selectedSerialNumber=selectedSerialNumber.removeEnd(',');
            if(selectedSerialNumber.length() > 254)
            {
                selectedSerialNumber = selectedSerialNumber.left(252);
            }
            caseRecord.Dispenser_serial_number__c=selectedSerialNumber;
            update caseRecord;
        }
        catch(Exception e)
        {
            system.debug('Error while updating the case record:'+e.getMessage());
        }
        return caseRecord;
    }
    
    /*****************************************************************************************
    Method : setSerialNumber
    Description : This method is to save the selected dispensers to the case object and 
				  Insert Case To OutletDispensers Junction object as per requirement
    ******************************************************************************************/
    @RemoteAction
    global static void setSerialNumber(Id caseid,String zpls, Id accID) {
        try{
            Case caseValue;
            list<string> selectSerialNumberList = new list<string>();
            list<CaseToOutletdispenser__c> iterationList = new list<CaseToOutletdispenser__c>();
            list<FS_Outlet_Dispenser__c> serialNumberIterationList = new list<FS_Outlet_Dispenser__c>();
            Integer i;
            Integer j;
            
            deleteJunctionRecords(caseid);
            caseValue = updateDispenserSerialNumber(caseid,zpls);
            
            selectSerialNumberList=zpls.split(',');
            
            serialNumberIterationList = [select Id,FS_IsActive__c,FS_Name1__c,FS_Serial_Number2__c from FS_Outlet_Dispenser__c 
                                where FS_Serial_Number2__c IN :selectSerialNumberList AND FS_Outlet__c=:accID
                                         /*AND FS_IsActive__c = true*/ ORDER BY FS_Name1__c ASC NULLS FIRST];
            i = serialNumberIterationList.size();
            j = 0;
            
            //This for loop inserts the junction object records with the individual serial numbers that the case object contains
            for(string s:selectSerialNumberList)
            {
                CaseToOutletdispenser__c caseJunct = new CaseToOutletdispenser__c();
                if(j<i)
                {
                    caseJunct.Case__c = caseid;
                    caseJunct.Customer__c = caseValue.AccountId;
                    caseJunct.Outlet_Dispenser__c = serialNumberIterationList[j].id;
                    caseJunct.Serial_Number_Text__c = serialNumberIterationList[j].FS_Serial_Number2__c;
                    j++;
                }
                iterationList.add(caseJunct);
            }
            Database.insert(iterationList);
        }
        catch(Exception e)
        {
            system.debug(e.getMessage());
        }
    }
    
    //This is a child Wrapper class to containt the selected dispensers list along with checkbox              
    public class DispenserWrapper {
        public FS_Outlet_Dispenser__c dispenser{get; set;}
        public Boolean checked {get; set;}
        public Boolean disableDispenser{get;set;}
    }
}