force-app/main/default/objects/FS_OD_Settings__c/FS_OD_Settings__c.object-meta.xml
<CustomObject>
    <description>OD Settings</description>
    <label>OD Settings</label>
    <nameField>
        <displayFormat>ODS-{0000000}</displayFormat>
        <label>OD Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OD Settings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_OD_Settings__c/fields/Revoke_Artifacts__c.field-meta.xml
<CustomField>
    <fullName>Revoke_Artifacts__c</fullName>
    <defaultValue>&quot;No&quot;</defaultValue>
    <label>Revoke Artifacts</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Revoke Now</fullName>
            </value>
            <value>
                <fullName>Revoke At Next Install</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FOT_UpdateSettings_Batch.cls
global class FOT_UpdateSettings_Batch implements Database.Batchable<sObject>{
/****************************************************************************
//Intialize the batch
/***************************************************************************/
	  global String query;
    
/****************************************************************************
//Start the batch
/***************************************************************************/
    
    global Database.QueryLocator Start(Database.BatchableContext bc) {
        query = 'SELECT  id, name, Revoke_Artifacts__c FROM FS_OD_Settings__c';
        return Database.getQueryLocator(query); 
    }

/****************************************************************************
//Execute batch
/***************************************************************************/
    
    global void execute(Database.BatchableContext bc, List<FS_OD_Settings__c> odSettingList) {
        for(FS_OD_Settings__c editableSetting: odSettingList)
        {
            editableSetting.Revoke_Artifacts__c = 'No';
        }
        update odSettingList;
    }
    
/****************************************************************************
Finish batch
*****************************************************************************/
    
    global void finish(Database.BatchableContext bc) {
        
        
    }
}