force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Equip_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Equip_Type__c</fullName>
    <description>equip type</description>
    <inlineHelpText>This is the JDE Equipment Type value</inlineHelpText>
    <label>Equipment Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <description>Outlet field.</description>
    <label>Outlet</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 3) OR (2 AND 4 AND (5 OR 7)) OR (2 AND 4 AND 6)</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for Outlet.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Outlet</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Outlet</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>7000, 8000, 9000, CCNA Dispenser</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Dispenser</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value>No, Yes</value>
        </filterItems>
        <filterItems>
            <field>Account.Is_Default_FET_International_Outlet__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlet Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Valid_Fill__c.field-meta.xml
<CustomField>
    <fullName>FS_Valid_Fill__c</fullName>
    <label>Valid Fill Required</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Valid_Fill_New__c.field-meta.xml
<CustomField>
    <fullName>FS_Valid_Fill_New__c</fullName>
    <label>Valid Fill.</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Valid_Fill_Settings_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Valid_Fill_Settings_Effective_Date__c</fullName>
    <inlineHelpText>Enter the date format in mm/dd/yyyy</inlineHelpText>
    <label>Valid Fill Settings Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 OR 2) AND 4) OR 3 OR 5</booleanFilter>
        <errorMessage>The installation referenced by this dispenser is linked to a different outlet than the outlet on the dispenser.</errorMessage>
        <filterItems>
            <field>FS_Installation__c.FS_Outlet__c</field>
            <operation>equals</operation>
            <valueField>$Source.FS_Outlet__c</valueField>
        </filterItems>
        <filterItems>
            <field>FS_Installation__c.FS_New_Outlet__c</field>
            <operation>equals</operation>
            <valueField>$Source.FS_Outlet__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Dispenser</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>CCNA Dispenser, 7000, 8000, 9000</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Installed Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/FS_Valid_Fill__c.object-meta.xml
<CustomObject>
    <label>Valid Fill</label>
    <nameField>
        <displayFormat>VF-{0000}</displayFormat>
        <label>Valid Fill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Valid Fill</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Valid_Fill__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Post-Install Valid Fill</relationshipLabel>
    <relationshipName>Vailid_Fill</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/fields/FS_Outlet_Dispenser__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_Dispenser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet Dispenser</label>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipLabel>Post Install Valid Fill</relationshipLabel>
    <relationshipName>Valid_Fill</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/fields/Valid_Fill_Request_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Valid_Fill_Request_Approval_Status__c</fullName>
    <label>Valid Fill</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FSBatchClearValidFillOD.cls
/*
Cancel Valid Fill form on all levels
Author: 
Date:05/06/2015

Modified: Neel 9/28/2018 As part of FET 5.2 FFET 1302. Enable 9100 platform type on valid fill.

*/
global class FSBatchClearValidFillOD implements  Database.Batchable<sObject>, Database.Stateful{
    
    public String vfid;
    public Set<Id> setOutletIds;
    global String validFill7k=Schema.SObjectType.FS_Valid_Fill__c.getRecordTypeInfosByName().get(FSConstants.RECTYPE_7k).getRecordTypeId();
    global String validFill8k=Schema.SObjectType.FS_Valid_Fill__c.getRecordTypeInfosByName().get(FSConstants.RECTYPE_8k).getRecordTypeId();
    global String validFill9k=Schema.SObjectType.FS_Valid_Fill__c.getRecordTypeInfosByName().get(FSConstants.RECTYPE_9k).getRecordTypeId();
    global String validFill91k=Schema.SObjectType.FS_Valid_Fill__c.getRecordTypeInfosByName().get(FSConstants.RECTYPE_91k).getRecordTypeId();
    
    
    
    //Constructor
    public FSBatchClearValidFillOD (String vfid, Set<Id> setOutletIds) {
        this.vfid=vfid ;
        this.setOutletIds = setOutletIds;
    }
    
    /****************************************************************************
//Start the batch and query
/***************************************************************************/
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        
        return Database.getQueryLocator([Select Id,FS_Equip_Type__c,Installation__c,FS_Outlet__c From FS_Outlet_Dispenser__c Where FS_Outlet__c = :setOutletIds]);
        
    }
    
    /****************************************************************************
//Process a batch
/***************************************************************************/
    global void execute(Database.BatchableContext BC, List<sObject> postInstallList){
        
        List<FS_Outlet_Dispenser__c> ListOD = new List<FS_Outlet_Dispenser__c>();
        FS_Valid_Fill__c VF= (FS_Valid_Fill__c)Database.query(FSUtil.getSelectQuery('FS_Valid_Fill__c') + ' where id=:vfid')[0];
        
        for(FS_Outlet_Dispenser__c OD : (List<FS_Outlet_Dispenser__c >)postInstallList){
            System.debug('ODFS_Equip_Type__c:'+OD.FS_Equip_Type__c);
            
            if((VF.recordtypeid ==validFill7k && OD.FS_Equip_Type__c==FSConstants.RECTYPE_7k) || (VF.recordtypeid ==validFill8k  && OD.FS_Equip_Type__c==FSConstants.RECTYPE_8k) || 
               (VF.recordtypeid ==validFill9k && OD.FS_Equip_Type__c==FSConstants.RECTYPE_9k) || (VF.recordtypeid ==validFill91k && OD.FS_Equip_Type__c==FSConstants.RECTYPE_91k)){
                   if(VF.Valid_Fill_Request_Approval_Status__c!=null){
                       OD.FS_Valid_Fill_New__c=null;
                       OD.FS_Valid_Fill_Settings_Effective_Date__c=null;  
                   }
                   ListOD.add(OD);
               }   
            
        }
        try{
            Update ListOD;
        }
        Catch(Exception ex)
        {
            ApexErrorLogger.addApexErrorLog(FSConstants.FET,'FSBatchClearValidFillOD','Execute','Outlet Dispense',FSConstants.MediumPriority,ex,'NA');
            
        }
        
    }
    
    /****************************************************************************
//finish the batch
/***************************************************************************/
    global void finish(Database.BatchableContext BC){
        
    }
    
    
}