force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_ACN_NBR__c.field-meta.xml
<CustomField>
    <fullName>FS_ACN_NBR__c</fullName>
    <description>Customer  ACN</description>
    <formula>FS_Outlet__r.FS_ACN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Populated by the ACN Number found on the Outlet Record.</inlineHelpText>
    <label>Outlet ACN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Equip_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Equip_Type__c</fullName>
    <description>equip type</description>
    <inlineHelpText>This is the JDE Equipment Type value</inlineHelpText>
    <label>Equipment Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Serial_Number2__c.field-meta.xml
<CustomField>
    <fullName>FS_Serial_Number2__c</fullName>
    <description>Serial Number/Asset Tag.</description>
    <label>JDE Serial Number/Asset Tag</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ODsearchController.cls
//----------------------------------------------//
//Descripton: To get list of Oulet Dispensers matching with the 
//            serial number entered by user
//Class Name: ODsearchController
//Created on: 23rd Aug 2017
//Author:Infosys
//-----------------------------------------------//

public class ODsearchController 
{   
    @AuraEnabled
    public static List<FS_Outlet_Dispenser__c> searchDisp(string serialNum){
        if( serialNum.length() > 0 ){
            String dispQueryStr='%' + serialNum + '%';
            
            // Query the dispensers matching with complete serial number or partial serial number
            List<FS_Outlet_Dispenser__c> dispenserslist=[select id, Name ,FS_Serial_Number2__c, FS_ACN_NBR__c, FS_Equip_Type__c  
                                                         from FS_Outlet_Dispenser__c 
                                                         where FS_Serial_Number2__c like :dispQueryStr];
            
            return dispenserslist;    
        }
        else{
            return null;
        }
    }
    
}