force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Apply_to_all_dispensers_in_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Apply_to_all_dispensers_in_Outlet__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Apply to all dispensers in Outlet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_isReviewed__c.field-meta.xml
<CustomField>
    <fullName>FS_isReviewed__c</fullName>
    <label>isReviewed</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Loc_Finder_Reviewed_On__c.field-meta.xml
<CustomField>
    <fullName>FS_Loc_Finder_Reviewed_On__c</fullName>
    <label>Loc Finder Reviewed On</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Loc_Finder_ReviewedBy__c.field-meta.xml
<CustomField>
    <fullName>FS_Loc_Finder_ReviewedBy__c</fullName>
    <label>Loc Finder ReviewedBy</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FOT_LocationFinderPageController.cls
public class FOT_LocationFinderPageController{
    
    public FS_Outlet_Dispenser__c outDisp;

    public FOT_LocationFinderPageController(ApexPages.StandardController controller) {
        this.outDisp = (FS_Outlet_Dispenser__c)controller.getRecord();
        /*if(this.outDisp.FS_isReviewed__c != 'Yes'){
           this.outDisp.FS_Apply_to_all_dispensers_in_Outlet__c = true;
        }*/
		System.debug('outDisp' + outDisp);        
    }

    public PageReference saveDispenserLocation(){
        try{
            outDisp.FS_isReviewed__c = 'Yes';
            outDisp.FS_Loc_Finder_Reviewed_On__c= System.Now();
            outDisp.FS_Loc_Finder_ReviewedBy__c= UserInfo.getName();
            update outDisp;
        }catch(exception ex){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, ex.getMessage()));
            return null;
        }
        return null;
    }   
}