force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_ACN_NBR__c.field-meta.xml
<CustomField>
    <fullName>FS_ACN_NBR__c</fullName>
    <description>Customer  ACN</description>
    <formula>FS_Outlet__r.FS_ACN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Populated by the ACN Number found on the Outlet Record.</inlineHelpText>
    <label>Outlet ACN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Equip_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Equip_Type__c</fullName>
    <description>equip type</description>
    <inlineHelpText>This is the JDE Equipment Type value</inlineHelpText>
    <label>Equipment Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Serial_Number2__c.field-meta.xml
<CustomField>
    <fullName>FS_Serial_Number2__c</fullName>
    <description>Serial Number/Asset Tag.</description>
    <label>JDE Serial Number/Asset Tag</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FetchODList.cls
//-------------------------------------------//
//Descripton: To get barcode matchig Oulet Dispensers
//Class Name: FetchODList
//Created on: 23rd Aug 2017
//Author:Infosys
//-------------------------------------------//

public class FetchODList {
    @AuraEnabled public String errString {get;set;}
    @AuraEnabled public List<FS_Outlet_Dispenser__c> listOutlets{get;set;}
    
    @AuraEnabled
    public static FetchODList BarcodeMatchODList(String barCode) {
        FetchODList obj = new FetchODList();
        String nullStr='NULL';
        Integer zeroVal=0;
        
        try{            
            // Query the dispensers matching with barcode
            obj.listOutlets  = [select id,Name,FS_ACN_NBR__c,FS_Serial_Number2__c,FS_Equip_Type__c  from FS_Outlet_Dispenser__c where FS_Serial_Number2__c LIKE :barCode];
            }
        catch(Exception e ){
            system.debug('from catch');
        }
        
        // Set warning message based on barcode value. 
        if(barCode == nullStr) // when barcode is 'NULL'
        {            
            obj.errString=Label.UnableToReadBarcode;
        }
        else if( obj.listOutlets.size() == zeroVal ) // when barcode doesn't have any matching records
        {         
            obj.errString=Label.NoMatchingDispensers;
        }
        
        return obj;        
    }    
}