force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Status__c.field-meta.xml
<CustomField>
    <fullName>FS_Status__c</fullName>
    <description>Status.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Enroll</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Hibernate</fullName>
            </value>
            <value>
                <fullName>Wakeup</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Booking Complete</fullName>
            </value>
            <value>
                <fullName>Dispenser Pickup</fullName>
            </value>
            <value>
                <fullName>Dispenser Delivered</fullName>
            </value>
            <value>
                <fullName>In Inventory</fullName>
            </value>
            <value>
                <fullName>Assigned to Outlet</fullName>
            </value>
            <value>
                <fullName>Winterized</fullName>
            </value>
            <value>
                <fullName>Rough Stock</fullName>
            </value>
            <value>
                <fullName>Remaned</fullName>
            </value>
            <value>
                <fullName>To be scrapped by Bottler</fullName>
            </value>
            <value>
                <fullName>To be scrapped by CM</fullName>
            </value>
            <value>
                <fullName>Confirmed Scrapped</fullName>
            </value>
            <value>
                <fullName>Sold to Bottler</fullName>
            </value>
            <value>
                <fullName>Purchased from Bottler</fullName>
            </value>
            <value>
                <fullName>To be Remanufactured</fullName>
            </value>
            <value>
                <fullName>Unenrolled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Re_Manufactured__c.field-meta.xml
<CustomField>
    <fullName>Re_Manufactured__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Re-Manufactured</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Removed_Returned_Date__c.field-meta.xml
<CustomField>
    <fullName>Removed_Returned_Date__c</fullName>
    <label>Removed/Returned Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/WebServiceHelper.cls
global class WebServiceHelper{
    
    Webservice static String reAssignDispenser(String id){
        Map <String, Schema.SObjectType> schemaMap = Schema.getGlobalDescribe();
        Map <String, Schema.SObjectField> fieldMap = SchemaMap.get('FS_Outlet_Dispenser__c').getDescribe().fields.getMap();
        String csv = '';      
        List<FS_Outlet_Dispenser__c> dispenserListToUpsert = new List<FS_Outlet_Dispenser__c>();  
        for(Schema.SObjectField sfield : fieldMap.Values()){
            csv = csv + ',' + sField;            
        }        
        String queryStr = 'SELECT ' + csv.replaceFirst(',', '') + ' FROM FS_Outlet_Dispenser__c WHERE Id = \'' + ID + '\'';         
        List<FS_Outlet_Dispenser__c> dispenser = Database.query(queryStr);
        if(!dispenser.get(0).Re_Manufactured__c){
            return 'Error';
        }
        FS_Outlet_Dispenser__c newdisp = dispenser.get(0).clone(false,true,false,false);
        newDisp.Removed_Returned_Date__c = null;
        dispenser.get(0).FS_Status__c = 'Assigned to Outlet';
        //dispenser.get(0).WarehouseName = null;
        dispenserListToUpsert.add(newDisp);
        dispenserListToUpsert.addAll(dispenser);
        upsert dispenserListToUpsert;
        return newDisp.id;
        
    }
    
    
    WebService static String shippingFormGenerationNotification(String id) {
        String returnStr = '';
        List<EmailTemplate> templateList = [SELECT Id FROM EmailTemplate WHERE DeveloperName = 'Shipping_Form_Generation']; 
        //create a mail object to send a single email.
        Group grp = [SELECT id FROM Group WHERE Name = 'Shipping form Coordinator Group'];
        List<GroupMember> grpMember = [SELECT UserOrGroupId FROM GroupMember WHERE GroupId =: grp.id];        
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
       
        //set the email properties
        List<String> addresses = new List<String>();
        List<ID> userIDList = new List<ID>();
        for(GroupMember grpMem : grpMember){
            userIDList.add(grpMem.UserOrGroupId);
        }
        List<User> users = [Select Email,firstName,lastName from User WHERE id in :userIDList];
        for(User usr : users){
            addresses.add(usr.Email);            
        }
        addresses.add(UserInfo.getUserEmail());
        List<Contact> cntList = [select id, Email from Contact where email != null limit 1];
        mail.setToAddresses(addresses);        
        mail.setTemplateId(templateList.get(0).Id);
        mail.setTargetObjectId(cntList.get(0).id);
        mail.setWhatId(id);
        //send the email
        try{
	        Savepoint sp = Database.setSavepoint();
	        if(!Test.isRunningTest()){
	            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail } );// Dummy email send
	        }
	        Database.rollback(sp);
	        
	        //Send Actual email        
	        Messaging.SingleEmailMessage emailToSend = new Messaging.SingleEmailMessage();        
	        emailToSend.setToAddresses(mail.getToAddresses());        
	        emailToSend.setPlainTextBody(mail.getPlainTextBody());        
	        emailToSend.setHTMLBody(mail.getHTMLBody());        
	        emailToSend.setSubject(mail.getSubject());
	        if(!Test.isRunningTest()){
	            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { emailToSend} );	            
	        }
	        returnStr = 'Success';
        }Catch(Exception ex){
        	system.debug('Exception in notifying Coordinator');
        	returnStr = 'Error';
        }
        return returnStr;
       }
    }