force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_ACN_NBR__c.field-meta.xml
<CustomField>
    <fullName>FS_ACN_NBR__c</fullName>
    <description>Customer  ACN</description>
    <formula>FS_Outlet__r.FS_ACN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Populated by the ACN Number found on the Outlet Record.</inlineHelpText>
    <label>Outlet ACN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_IsActive__c.field-meta.xml
<CustomField>
    <fullName>FS_IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>active or inactive</description>
    <label>Active (A) / Inactive (I)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Migration_to_AW_Complete__c.field-meta.xml
<CustomField>
    <fullName>FS_Migration_to_AW_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Migration to AW Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Migration_to_AW_Required__c.field-meta.xml
<CustomField>
    <fullName>FS_Migration_to_AW_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Migration to AW Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <description>Outlet field.</description>
    <label>Outlet</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 3) OR (2 AND 4 AND (5 OR 7)) OR (2 AND 4 AND 6)</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for Outlet.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Outlet</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Outlet</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>7000, 8000, 9000, CCNA Dispenser</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Dispenser</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value>No, Yes</value>
        </filterItems>
        <filterItems>
            <field>Account.Is_Default_FET_International_Outlet__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlet Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Pending_Migration_to_AW__c.field-meta.xml
<CustomField>
    <fullName>FS_Pending_Migration_to_AW__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pending Migration to AW</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FS_Data_Migration_8K_9K.cls
global with sharing class FS_Data_Migration_8K_9K implements Database.Batchable<sObject>, Database.AllowsCallouts{
    
    public List<Id> dispenserIds=new List<Id>(); //Added to facilitate single record callout to AW.10th June 2016
    
    public FS_Data_Migration_8K_9K(final List<Id> dispenserIds){
      this.dispenserIds=dispenserIds;
    }
    
    public FS_Data_Migration_8K_9K(){
      
    }
    
    global Database.QueryLocator start(final Database.BatchableContext BC){
        String query;
        if(dispenserIds.isEmpty()){
            query= 'SELECT Id, FS_Outlet__c, FS_ACN_NBR__c '
                        + ' FROM FS_Outlet_Dispenser__c '  
                        + ' WHERE FS_Migration_to_AW_Required__c = TRUE ' 
                        + '   AND FS_Pending_Migration_to_AW__c= TRUE '
                        + '   AND FS_Migration_to_AW_Complete__c = FALSE '
                        + '   AND FS_IsActive__c = TRUE ';
        }
        else{
            query= 'SELECT Id, FS_Outlet__c, FS_ACN_NBR__c '
                        + ' FROM FS_Outlet_Dispenser__c '  
                        + ' WHERE FS_Migration_to_AW_Required__c = TRUE ' 
                        + '   AND FS_Pending_Migration_to_AW__c= TRUE '
                        + '   AND FS_Migration_to_AW_Complete__c = FALSE '
                        + '   AND FS_IsActive__c = TRUE '
                        + '   AND Id IN:dispenserIds ';
        }

        return Database.getQueryLocator(query);
    }

    global void execute(final Database.BatchableContext BC, final List<sObject> scope) {
       try {
            final List<FS_Outlet_Dispenser__c> beList = (List<FS_Outlet_Dispenser__c>)scope;
            final List<FS_Outlet_Dispenser__c> updateOD = new List<FS_Outlet_Dispenser__c> ();
            final Set<Id> setDispenserIds = new Set<Id>();
            
            for(FS_Outlet_Dispenser__c obj : beList) {
                    setDispenserIds.add(obj.Id);
            }
            
            if(beList.size() > 0){
                FSFETNMSConnector.isUpdateSAPIDBatchChange = true;
                FSFETNMSConnector.airWatchSynchronousCall(setDispenserIds,NULL);       
            }
            
            for(FS_Outlet_Dispenser__c updateflag : beList){
                updateflag.FS_Migration_to_AW_Complete__c = true;
                updateOD.add(updateflag);
            }
            
            UPDATE updateOD;        
       } catch(Exception exp) {
            System.debug('FS_Data_Migration_8K_9K#Exception occurred- '+exp);
       }
    }

    global void finish(final Database.BatchableContext BC){
        
    }

}