force-app/main/default/objects/FS_Initial_Order_Setting__c/FS_Initial_Order_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Initial Order Setting</label>
</CustomObject>

force-app/main/default/objects/FS_Initial_Order_Setting__c/fields/FS_New_Install_Record_Type_Id__c.field-meta.xml
<CustomField>
    <fullName>FS_New_Install_Record_Type_Id__c</fullName>
    <label>New Install Record Type Id</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Initial_Order_Setting__c/fields/FS_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>FS_Record_Id__c</fullName>
    <label>Record Id</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Initial_Order_Setting__c/fields/Installation_Id__c.field-meta.xml
<CustomField>
    <fullName>Installation_Id__c</fullName>
    <label>Installation Id</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Initial_Order_Setting__c/fields/Installation_Name__c.field-meta.xml
<CustomField>
    <fullName>Installation_Name__c</fullName>
    <label>Installation Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>FS_Record_ID__c</fullName>
    <label>Record ID#</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FS_RedirectInitialRecordController.cls
public class FS_RedirectInitialRecordController {      
    public Pagereference redirectInitalOrder() {
        Pagereference page;
        String installationId=FSConstants.BLANKVALUE;
        installationId = ApexPages.currentPage().getParameters().get('recordId');
        final FS_Initial_Order_Setting__c settingRec = FS_Initial_Order_Setting__c.getOrgDefaults();
        
        If(installationId != null && installationId != '') {
            for(FS_Installation__c inst : [SELECT Id,Name,RecordType.Name FROM FS_Installation__c WHERE Id =: installationId]) {               
                If(inst.RecordType.Name == FSConstants.NEWINSTALLATION) {                    
                    page = new Pagereference('/'+settingRec.FS_Record_Id__c+'/e?RecordType='+settingRec.FS_New_Install_Record_Type_Id__c
                                             +'&'+settingRec.Installation_Id__c+'='+installationId+'&'+settingRec.Installation_Name__c+'=' + inst.Name);
                }
            }
        }
        else{
            final ApexPages.Message msg = new Apexpages.Message(Apexpages.severity.Error, 'Error occured');
            ApexPages.addMessage(msg);           
        }
        return page;
    }
}