force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_DispOrder1__c.field-meta.xml
<CustomField>
    <fullName>FS_DispOrder1__c</fullName>
    <inlineHelpText>This reflects the quantity of dispensers specified on the related Equipment Package</inlineHelpText>
    <label>Dispensers QTY 1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_DispOrder2__c.field-meta.xml
<CustomField>
    <fullName>FS_DispOrder2__c</fullName>
    <inlineHelpText>This reflects the quantity of dispensers specified on the related Equipment Package</inlineHelpText>
    <label>Dispensers QTY 2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_DispOrder3__c.field-meta.xml
<CustomField>
    <fullName>FS_DispOrder3__c</fullName>
    <inlineHelpText>This reflects the quantity of dispensers specified on the related Equipment Package</inlineHelpText>
    <label>Dispensers QTY 3</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_DispRequested1__c.field-meta.xml
<CustomField>
    <fullName>FS_DispRequested1__c</fullName>
    <inlineHelpText>This reflects the quantity of dispensers originally requested at CIF level</inlineHelpText>
    <label># of Dispenser 1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_DispRequested2__c.field-meta.xml
<CustomField>
    <fullName>FS_DispRequested2__c</fullName>
    <inlineHelpText>This reflects the quantity of dispensers originally requested at CIF level</inlineHelpText>
    <label># of Dispenser 2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_DispRequested3__c.field-meta.xml
<CustomField>
    <fullName>FS_DispRequested3__c</fullName>
    <inlineHelpText>This reflects the quantity of dispensers originally requested at CIF level</inlineHelpText>
    <label># of Dispenser 3</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Market_Activation_override__c.field-meta.xml
<CustomField>
    <fullName>FS_Market_Activation_override__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Please ensure proper exception approval has been obtained prior to overriding the Market Activation Date</inlineHelpText>
    <label>Market Activation Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Mrkt_ActiveDate1__c.field-meta.xml
<CustomField>
    <fullName>FS_Mrkt_ActiveDate1__c</fullName>
    <label>Market Activation Date 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Mrkt_ActiveDate2__c.field-meta.xml
<CustomField>
    <fullName>FS_Mrkt_ActiveDate2__c</fullName>
    <label>Market Activation Date 2</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Mrkt_ActiveDate3__c.field-meta.xml
<CustomField>
    <fullName>FS_Mrkt_ActiveDate3__c</fullName>
    <label>Market Activation Date 3</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Mrkt_Override1__c.field-meta.xml
<CustomField>
    <fullName>FS_Mrkt_Override1__c</fullName>
    <description>Market Activation Override 1</description>
    <formula>AND(Text(FS_Platform1__c) &lt;&gt;&quot;&quot;,FS_Market_Activation_override__c,OR(FS_Mrkt_ActiveDate1__c &gt; FS_Scheduled_Install_Date__c, ISNULL(FS_Mrkt_ActiveDate1__c) ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market Activation Override 1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Mrkt_Override2__c.field-meta.xml
<CustomField>
    <fullName>FS_Mrkt_Override2__c</fullName>
    <formula>AND(Text(FS_Platform2__c) &lt;&gt;&quot;&quot;,FS_Market_Activation_override__c,OR(FS_Mrkt_ActiveDate2__c &gt; FS_Scheduled_Install_Date__c, ISNULL(FS_Mrkt_ActiveDate2__c) ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market Activation Override 2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Mrkt_Override3__c.field-meta.xml
<CustomField>
    <fullName>FS_Mrkt_Override3__c</fullName>
    <formula>AND(Text(FS_Platform3__c) &lt;&gt;&quot;&quot;,FS_Market_Activation_override__c,OR(FS_Mrkt_ActiveDate3__c &gt; FS_Scheduled_Install_Date__c, ISNULL(FS_Mrkt_ActiveDate3__c) ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Market Activation Override 3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Platform1__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform1__c</fullName>
    <label>Platform 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Platform2__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform2__c</fullName>
    <label>Platform 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Platform3__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform3__c</fullName>
    <label>Platform 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Scheduled_Install_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Scheduled_Install_Date__c</fullName>
    <description>This is the replacement of the install date formula field. Which contains latest reschedule date.</description>
    <label>Scheduled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/Type_of_Dispenser_Platform__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Dispenser_Platform__c</fullName>
    <description>multi select pick list</description>
    <label>Platform Type/s</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_IP_Equipment_Package__c/FS_IP_Equipment_Package__c.object-meta.xml
<CustomObject>
    <label>Equipment Package</label>
    <nameField>
        <displayFormat>IP_EQP-{0000}</displayFormat>
        <label>Equipment Package Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_IP_Equipment_Package__c/fields/FS_Installation__c.field-meta.xml
<CustomField>
    <fullName>FS_Installation__c</fullName>
    <label>Installation</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Equipment Packages</relationshipLabel>
    <relationshipName>Equipment_Packages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_IP_Equipment_Package__c/fields/FS_Planned_Topmount_Icemakers__c.field-meta.xml
<CustomField>
    <fullName>FS_Planned_Topmount_Icemakers__c</fullName>
    <label># Planned Top Mount Ice Makers</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Platform_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3100</fullName>
    </customValue>
    <customValue>
        <fullName>6000</fullName>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
    </customValue>
    <customValue>
        <fullName>7100</fullName>
    </customValue>
    <customValue>
        <fullName>8000</fullName>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
    </customValue>
    <masterLabel>Platform Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FS_PlatformDetailsInstallationAura.cls
public class FS_PlatformDetailsInstallationAura {
    
    public FS_PlatformDetailsInstallationAura(){        
    }  
    
    @AuraEnabled
    public Static  List<WrapperClass> FSPlatformDetailsInstallationExtension(id RecordId) {  
        List<WrapperClass> wrapperIns = new List<WrapperClass>();
        String RecName = '';
        FS_Installation__c installRecord=new FS_Installation__c();
        //Installation Instance to store data specific to Platform
        FS_Installation__c newInstall; 
        //Top Mount IceMaker Map  Sprint 5 - 507
        Map<String,FS_IP_Equipment_Package__c> eqpMap=new Map<String,FS_IP_Equipment_Package__c>();
        // List to Store Platform Names
        List<String> platformList=new List<String>{'Platform 1','Platform 2','Platform 3'};
            // Querying the installation record with required details to show 
            installRecord=[SELECT Id,RecordType.name,FS_Platform1__c,FS_Platform2__c,FS_Platform3__c,Type_of_Dispenser_Platform__c,FS_DispRequested1__c,FS_DispRequested2__c, 
                           FS_DispRequested3__c,FS_DispOrder1__c,FS_DispOrder2__c,FS_DispOrder3__c,FS_Mrkt_ActiveDate1__c,FS_Mrkt_ActiveDate2__c,FS_Mrkt_ActiveDate3__c,
                           FS_Scheduled_Install_Date__c,FS_Market_Activation_override__c,FS_Mrkt_Override1__c,FS_Mrkt_Override2__c,FS_Mrkt_Override3__c
                           FROM FS_Installation__c WHERE Id=:RecordId limit 1];
        RecName = installRecord.RecordType.name;
        //Sprint 5 - 507
        for(FS_IP_Equipment_Package__c eqp:[select id,name,FS_Platform_Type__c,FS_Installation__c,FS_Planned_Topmount_Icemakers__c from FS_IP_Equipment_Package__c where FS_Installation__c=:RecordId]){
            eqpMap.put(eqp.FS_Platform_Type__c, eqp);
        }
        // Checking Platform 1 value of Installation record Null or Not
        if(installRecord.FS_Platform1__c!=FSConstants.NULLVALUE){
            //Sprint 5 - 507
            Decimal topMount;
            topMount=eqpMap.containsKey(installRecord.FS_Platform1__c)?eqpMap.get(installRecord.FS_Platform1__c).FS_Planned_Topmount_Icemakers__c:null;                
            
            newInstall=new FS_Installation__c(FS_Platform1__c=installRecord.FS_Platform1__c,FS_Mrkt_ActiveDate1__c=installRecord.FS_Mrkt_ActiveDate1__c,
                                              FS_DispRequested1__c=installRecord.FS_DispRequested1__c,FS_DispOrder2__c=topMount,
                                              FS_DispOrder1__c=installRecord.FS_DispOrder1__c,FS_Market_Activation_override__c=installRecord.FS_Mrkt_Override1__c);
        }
        else{
            newInstall=new FS_Installation__c();
        }                
        wrapperIns.add(new WrapperClass(platformList[0] , newInstall , RecName));
        // Checking Platform 2 value of Installation record Null or Not
        if(installRecord.FS_Platform2__c!=FSConstants.NULLVALUE){
            //Sprint 5 - 507
            Decimal topMount;
            topMount=eqpMap.containsKey(installRecord.FS_Platform2__c)?eqpMap.get(installRecord.FS_Platform2__c).FS_Planned_Topmount_Icemakers__c:null;                
            
            newInstall=new FS_Installation__c(FS_Platform1__c=installRecord.FS_Platform2__c,FS_Mrkt_ActiveDate1__c=installRecord.FS_Mrkt_ActiveDate2__c,
                                              FS_DispRequested1__c=installRecord.FS_DispRequested2__c,FS_DispOrder2__c=topMount,
                                              FS_DispOrder1__c=installRecord.FS_DispOrder2__c,FS_Market_Activation_override__c=installRecord.FS_Mrkt_Override2__c);
        }
        else{
            newInstall=new FS_Installation__c();
        }
        wrapperIns.add(new WrapperClass(platformList[1], newInstall, RecName));
        // Checking Platform 3 value of Installation record Null or Not
        if(installRecord.FS_Platform3__c!=FSConstants.NULLVALUE){ 
            //Sprint 5 - 507
            Decimal topMount;
            topMount=eqpMap.containsKey(installRecord.FS_Platform3__c)?eqpMap.get(installRecord.FS_Platform3__c).FS_Planned_Topmount_Icemakers__c:null;        
            newInstall=new FS_Installation__c(FS_Platform1__c=installRecord.FS_Platform3__c,FS_Mrkt_ActiveDate1__c=installRecord.FS_Mrkt_ActiveDate3__c,
                                              FS_DispRequested1__c=installRecord.FS_DispRequested3__c,FS_DispOrder2__c=topMount,
                                              FS_DispOrder1__c=installRecord.FS_DispOrder3__c,FS_Market_Activation_override__c=installRecord.FS_Mrkt_Override3__c);
        }
        else{
            newInstall=new FS_Installation__c();
        }            
        wrapperIns.add(new WrapperClass(platformList[2] , newInstall, RecName));
        return wrapperIns;
    }   
    
    public class WrapperClass{
        public WrapperClass(String name , FS_Installation__c install, String Rectypename){
            this.name = name ; 
            this.install = install ;
            this.Rectypename = Rectypename;
        }
        @AuraEnabled
        public String name {get;set;}
        @AuraEnabled
        public FS_Installation__c install {get;set;}
        @AuraEnabled
        public String Rectypename {get;set;}
    } 
    
    @AuraEnabled
    public Static String HelpText(String FieldAPI){
        String Field_Name = '';
        if(FieldAPI == 'FS_DispRequested1__c'){
            Field_Name= FS_Installation__c.FS_DispRequested1__c.getDescribe().getInlineHelpText();
        }
        if(FieldAPI == 'FS_DispOrder1__c'){
            Field_Name= FS_Installation__c.FS_DispOrder1__c.getDescribe().getInlineHelpText();
        }
        return Field_Name;
    }
}