force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installations (Outlet)</relationshipLabel>
    <relationshipName>Installations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Valid_Fill__c.field-meta.xml
<CustomField>
    <fullName>FS_Valid_Fill__c</fullName>
    <label>Valid Fill</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>46245 : Valid Fill Conversion Kit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/FS_Valid_Fill__c.object-meta.xml
<CustomObject>
    <label>Valid Fill</label>
    <nameField>
        <displayFormat>VF-{0000}</displayFormat>
        <label>Valid Fill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Valid Fill</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Valid_Fill__c/fields/FS_Cancel_Valid_Fill__c.field-meta.xml
<CustomField>
    <fullName>FS_Cancel_Valid_Fill__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Cancelled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/fields/FS_Installation__c.field-meta.xml
<CustomField>
    <fullName>FS_Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Post Install Valid Fill</relationshipLabel>
    <relationshipName>Valid_Fill</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Post-Install Valid Fill</relationshipLabel>
    <relationshipName>Vailid_Fill</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/fields/FS_RcdIDForCncl__c.field-meta.xml
<CustomField>
    <fullName>FS_RcdIDForCncl__c</fullName>
    <label>Record ID For Cancel</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FSBatchCancelValidFill.cls
/*
Cancel Flavour Changes form on all levels
Author: 
Date:05/06/2015
*/
global class FSBatchCancelValidFill implements  Database.Batchable<sObject>, Database.Stateful{
    
    public String cancelId;
    public String vfid;
    public Set<Id> setoutletIds = new Set<Id>();
    
    //Constructor
    public FSBatchCancelValidFill(String cancelId) {
        this.cancelId =cancelId;
        this.vfid=cancelId;
    }
    
    /****************************************************************************
//Start the batch and query
/***************************************************************************/
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        cancelId =[SELECT FS_RcdIDForCncl__c FROM FS_Valid_Fill__c WHERE id=:cancelId].FS_RcdIDForCncl__c;  
        
        return Database.getQueryLocator([Select Id,FS_Cancel_Valid_Fill__c,FS_Outlet__c,FS_Installation__c,FS_RcdIDForCncl__c From FS_Valid_Fill__c Where FS_RcdIDForCncl__c=:cancelId AND FS_RcdIDForCncl__c!='']);
        
    }
    
    /****************************************************************************
//Process a batch
/***************************************************************************/
    global void execute(Database.BatchableContext BC, List<sObject> validFillList){
        List<FS_Valid_Fill__c> lstCancelVF= new List<FS_Valid_Fill__c>();
        List<FS_Valid_Fill__c> vflist;
        Set<Id> IDSet=new Set<Id>(); 
        for(FS_Valid_Fill__c  vf:(List<FS_Valid_Fill__c >)validFillList){
            IDSet.add(vf.id);
        }
        vflist= Database.query(FSUtil.getSelectQuery('FS_Valid_Fill__c') + ' where id=:IDSet');
        for(FS_Valid_Fill__c ValidFill : vflist){
            ValidFill.FS_Cancel_Valid_Fill__c=true; 
            lstCancelVF.add(ValidFill);         
            if(ValidFill.FS_Outlet__c != null){
                setoutletIds.add(ValidFill.FS_Outlet__c);
            }
        }
        try{
            if(!lstCancelVF.isEmpty()){
                Update lstCancelVF;
            }
        }
        Catch(Exception ex)
        {
            ApexErrorLogger.addApexErrorLog(FSConstants.FET,'FSBatchCancelValidFill','Execute','Valid Fill',FSConstants.MediumPriority,ex,'NA');
            
        }
        
    }
    
    /****************************************************************************
//finish the batch
/***************************************************************************/
    global void finish(Database.BatchableContext BC){
        Database.executeBatch(New FSBatchClearValidFillOD (vfid, setoutletIds),200);
    }
}