force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <displayFormat>EP-{0000}</displayFormat>
    <label>Execution Plan#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan_Final_Approval_PM__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan_Final_Approval_PM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Execution Plan Final Approval (PM)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Execution Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlet Info Summary</relationshipLabel>
    <relationshipName>Outlet_Info_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan_Final_Approval_PM__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan_Final_Approval_PM__c</fullName>
    <description>Execution Plan Final Approval (PM)</description>
    <label>Execution Plan Final Approval (PM)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Mail_to_Outlet_Address__c.field-meta.xml
<CustomField>
    <fullName>FS_Mail_to_Outlet_Address__c</fullName>
    <label>Packet Mailed to Outlet Address</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Original_Install_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Original_Install_Date__c</fullName>
    <label>Initially Scheduled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Rush_Install_Reason__c.field-meta.xml
<CustomField>
    <fullName>FS_Rush_Install_Reason__c</fullName>
    <label>Rush Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Store Opening</fullName>
            </value>
            <value>
                <fullName>Marketing/Media</fullName>
            </value>
            <value>
                <fullName>Remodel</fullName>
            </value>
            <value>
                <fullName>Legacy Equipment Failure</fullName>
            </value>
            <value>
                <fullName>Customer Request</fullName>
            </value>
            <value>
                <fullName>Rebuild</fullName>
            </value>
            <value>
                <fullName>Health Inspection</fullName>
            </value>
            <value>
                <fullName>Coordinator Error</fullName>
            </value>
            <value>
                <fullName>NRA</fullName>
            </value>
            <value>
                <fullName>SA Not Uploaded</fullName>
            </value>
            <value>
                <fullName>Customer Unable to Pour Product</fullName>
            </value>
            <value>
                <fullName>Limited Dispenser Accessibility</fullName>
            </value>
            <value>
                <fullName>External Process Failure</fullName>
            </value>
            <value>
                <fullName>Acts of God</fullName>
            </value>
            <value>
                <fullName>Trade Show</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_SA_Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_SA_Completed_Date__c</fullName>
    <label>SA Completed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_SA_Scheduled_On_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_SA_Scheduled_On_Date__c</fullName>
    <label>Original SA Scheduled On Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Trainer__c.field-meta.xml
<CustomField>
    <fullName>FS_Trainer__c</fullName>
    <description>Trainer</description>
    <label>Trainer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>COM</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Not Needed / 2nd Install</fullName>
            </value>
            <value>
                <fullName>Not needed(used for 2nd disp in loc)</fullName>
            </value>
            <value>
                <fullName>Service Provider</fullName>
            </value>
            <value>
                <fullName>EcoSure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/Overall_Status2__c.field-meta.xml
<CustomField>
    <fullName>Overall_Status2__c</fullName>
    <label>Transaction Status</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FSExecutionPlanStatusIndicatorTest.cls
/******************************************** 
Name         : FSExecutionPlanStatusIndicatorTest
Created By   : Sunil (Appiro)
Created Date : Dec. 16, 2013
Usage        : Unit test coverage of FSExecutionPlanStatusIndicatorExtension
*************************************************/
@isTest 
private class FSExecutionPlanStatusIndicatorTest {
    public static final String APPROVED='Approved';
    public static final String STORE='Store Opening';
    public static final String BLUE='blue';
    public static final String GREEN='green';
    public static final String REDCOLR='red';
    public static final String YELLOW='yellow';
    public static final String GRAY='gray';
    public static List<Id> idsList;
    public static List<Id> accountId;
   	public static FS_Execution_Plan__c exePlan;
    public static List<FS_Installation__c> installList;
    public static FSExecutionPlanStatusIndicatorExtension obj;
 
    
    private static testmethod void testMethodSAScheduledBlue(){
        final Profile sysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
		final User sysAdminUser=FSTestFactory.createUser(sysAdmin.id);
		insert sysAdminUser;

        System.runAs(sysAdminUser) {
        accountId=FSEPStatusIndicatorTest_TestData.loadTestData();
        installList=new List<FS_Installation__c>();
        exePlan = FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,accountId[0], false);
        exePlan.FS_Execution_Start_Date__c = System.today().addDays(-1);   
        Test.startTest();
        insert exePlan;    
         
        final FS_Installation__c installation3 = FSTestUtil.createInstallationAcc(FSConstants.NEWINSTALLATION,exePlan.Id,accountId[1], false);
        installation3.FS_SA_Scheduled_On_Date__c = System.today().addDays(-30);
        installation3.FS_SA_Completed_Date__c = System.today().addDays(-30);
        installation3.FS_Original_Install_Date__c = System.today().addDays(-30);
        installation3.FS_Execution_Plan_Final_Approval_PM__c=APPROVED;
        installation3.FS_Rush_Install_Reason__c=STORE;
        installation3.FS_Trainer__c='Not Needed / 2nd Install';
        installList.add(installation3); 
        
        final FS_Installation__c installation4 = FSTestUtil.createInstallationAcc(FSConstants.NEWINSTALLATION,exePlan.Id, accountId[1], false);
        installation4.FS_SA_Completed_Date__c = System.today().addDays(-50);
        installation4.FS_Original_Install_Date__c = System.today().addDays(-50);
        installation4.FS_Execution_Plan_Final_Approval_PM__c=APPROVED;
        installation4.FS_Rush_Install_Reason__c=STORE;
        installList.add(installation4);        
        
        final FS_Installation__c installation5 = FSTestUtil.createInstallationAcc(FSConstants.NEWINSTALLATION,exePlan.Id,accountId[1], false);
        installation5.FS_SA_Scheduled_On_Date__c = System.today().addDays(-60);
        installation5.FS_Original_Install_Date__c = System.today().addDays(-60);
        installation5.FS_Execution_Plan_Final_Approval_PM__c=APPROVED;
        installation5.FS_Rush_Install_Reason__c=STORE;
        installList.add(installation5);
        
        final FS_Installation__c installation6 = FSTestUtil.createInstallationAcc(FSConstants.NEWINSTALLATION,exePlan.Id,accountId[1], false);
        installation6.FS_SA_Scheduled_On_Date__c = System.today().addDays(-60);
        //installation6.FS_ReschedInstallDate7__c = System.today();
        //installation6.FS_Reason_for_Reschedule_7__c = 'HFCS not on-site';
        installation6.FS_Execution_Plan_Final_Approval_PM__c=APPROVED;
        installation6.FS_Rush_Install_Reason__c=STORE;
        installList.add(installation6);         
        
        final FS_Installation__c installation10 = FSTestUtil.createInstallationAcc(FSConstants.NEWINSTALLATION,exePlan.Id,accountId[1], false);
        installation10.FS_SA_Scheduled_On_Date__c = System.today().addDays(-60);
        installation10.FS_Mail_to_Outlet_Address__c = 'Test';
        installation10.Overall_Status2__c = FSConstants.IPCOMPLETE ;
        installation10.FS_Execution_Plan_Final_Approval_PM__c=APPROVED;
        installList.add(installation10);
 		        
        insert installList;        
        obj=FSEPStatusIndicatorTest_TestData.executeMethod(exePlan);
        Test.stopTest();
        system.assertEquals(BLUE, obj.colorSAScheduled);
        }
    }
    
    private static testmethod void testMethodSAScheduled2Blue(){
        final Profile sysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
		final User sysAdminUser=FSTestFactory.createUser(sysAdmin.id);
		insert sysAdminUser;

        System.runAs(sysAdminUser) {
        accountId=FSEPStatusIndicatorTest_TestData.loadTestData();
        idsList=new List<Id>();
        installList=new List<FS_Installation__c>();        
        exePlan = FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,accountId[0], false);
        exePlan.FS_Execution_Start_Date__c = System.today().addDays(1);    	
        Test.startTest();
        insert exePlan; 
        
        idsList.add(exePlan.Id);
        idsList.add(accountId[1]);
        installList=FSEPStatusIndicatorTest_TestData.createInst(idsList,2);        
        insert installList;        
        obj=FSEPStatusIndicatorTest_TestData.executeMethod(exePlan);
        Test.stopTest();
        system.assertEquals(BLUE, obj.colorSAScheduled);
        }
    }
    
    private static testmethod void testMethodSAScheduled20Blue(){
        final Profile sysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
		final User sysAdminUser=FSTestFactory.createUser(sysAdmin.id);
		insert sysAdminUser;

        System.runAs(sysAdminUser) {
        accountId=FSEPStatusIndicatorTest_TestData.loadTestData();
        idsList=new List<Id>();
        installList=new List<FS_Installation__c>();        
        exePlan = FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,accountId[0], false);
        exePlan.FS_Execution_Start_Date__c = System.today().addDays(1); 
        Test.startTest();
        insert exePlan; 
         
        idsList.add(exePlan.Id);
        idsList.add(accountId[1]);
        installList=FSEPStatusIndicatorTest_TestData.createInst(idsList,20);        
        insert installList;        
        obj=FSEPStatusIndicatorTest_TestData.executeMethod(exePlan);
        Test.stopTest();
        system.assertEquals(BLUE, obj.colorSAScheduled);
        }
    }
    
    private static testmethod void testMethodSAScheduled2Red(){
        final Profile sysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
		final User sysAdminUser=FSTestFactory.createUser(sysAdmin.id);
		insert sysAdminUser;

        System.runAs(sysAdminUser) {
        accountId=FSEPStatusIndicatorTest_TestData.loadTestData();
        idsList=new List<Id>();
        List<FS_Installation__c> installList=new List<FS_Installation__c>();        
        exePlan = FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,accountId[0], false);
        exePlan.FS_Execution_Start_Date__c = System.today().addDays(-10);    
        Test.startTest();
        insert exePlan;
        
        idsList.add(exePlan.Id);
        idsList.add(accountId[1]);
        installList=FSEPStatusIndicatorTest_TestData.createInst(idsList,2);        
        insert installList;       
        obj=FSEPStatusIndicatorTest_TestData.executeMethod(exePlan);
        Test.stopTest();
        system.assertEquals(REDCOLR, obj.colorSAScheduled);
        }
    }
    
    private static testmethod void testMethodSAScheduled20Red(){
        final Profile sysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
		final User sysAdminUser=FSTestFactory.createUser(sysAdmin.id);
		insert sysAdminUser;

        System.runAs(sysAdminUser) {
        accountId=FSEPStatusIndicatorTest_TestData.loadTestData();
        idsList=new List<Id>();
        List<FS_Installation__c> installList=new List<FS_Installation__c>();        
        exePlan = FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,accountId[0], false);
        exePlan.FS_Execution_Start_Date__c = System.today().addDays(-10);  
        Test.startTest();
        insert exePlan;
        
        idsList.add(exePlan.Id);
        idsList.add(accountId[1]);
        installList=FSEPStatusIndicatorTest_TestData.createInst(idsList,20);        
        insert installList;        
        obj=FSEPStatusIndicatorTest_TestData.executeMethod(exePlan);
        Test.stopTest();
        system.assertEquals(REDCOLR, obj.colorSAScheduled);
        }
    } 
    
    private static testmethod void testMethodSAScheduled2Yellow(){
        final Profile sysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
		final User sysAdminUser=FSTestFactory.createUser(sysAdmin.id);
		insert sysAdminUser;

        System.runAs(sysAdminUser) {
        accountId=FSEPStatusIndicatorTest_TestData.loadTestData();
        idsList=new List<Id>();
        List<FS_Installation__c> installList=new List<FS_Installation__c>();        
        exePlan = FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,accountId[0], false);
        exePlan.FS_Execution_Start_Date__c = System.today().addDays(-3);    
        Test.startTest();
        insert exePlan;
        
        idsList.add(exePlan.Id);
        idsList.add(accountId[1]);
        installList=FSEPStatusIndicatorTest_TestData.createInst(idsList,2);        
        insert installList;        
        obj=FSEPStatusIndicatorTest_TestData.executeMethod(exePlan);
        Test.stopTest();
        system.assertEquals(YELLOW, obj.colorSAScheduled);
        }
    }
    
    private static testmethod void testMethodSAScheduled20Yellow(){
        final Profile sysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
		final User sysAdminUser=FSTestFactory.createUser(sysAdmin.id);
		insert sysAdminUser;

        System.runAs(sysAdminUser) {
        accountId=FSEPStatusIndicatorTest_TestData.loadTestData();
        idsList=new List<Id>();
        List<FS_Installation__c> installList=new List<FS_Installation__c>();        
        exePlan = FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,accountId[0], false);
        exePlan.FS_Execution_Start_Date__c = System.today().addDays(-3);    
        Test.startTest();
        insert exePlan;
        
        idsList.add(exePlan.Id);
        idsList.add(accountId[1]);
        installList=FSEPStatusIndicatorTest_TestData.createInst(idsList,20);        
        insert installList;        
        FSEPStatusIndicatorTest_TestData.executeMethod(exePlan);
        system.assertEquals(20, [select id,name from FS_Installation__c where FS_Execution_Plan__c=:exePlan.Id].size());
        Test.stopTest();
        }
    }  
    
    private static testmethod void testMethodSAComplete20Yellow(){
        final Profile sysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
		final User sysAdminUser=FSTestFactory.createUser(sysAdmin.id);
		insert sysAdminUser;

        System.runAs(sysAdminUser) {
        accountId=FSEPStatusIndicatorTest_TestData.loadTestData();
        idsList=new List<Id>();
        List<FS_Installation__c> installList=new List<FS_Installation__c>();        
        exePlan = FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,accountId[0], false);
        exePlan.FS_Execution_Start_Date__c = System.today().addDays(-18);  
        Test.startTest();
        insert exePlan;
        
        idsList.add(exePlan.Id);
        idsList.add(accountId[1]);
        installList=FSEPStatusIndicatorTest_TestData.createInst(idsList,20);        
        insert installList;
        obj=FSEPStatusIndicatorTest_TestData.executeMethod(exePlan);
        Test.stopTest();
        system.assertEquals(YELLOW, obj.colorSAComplete);
        }
    }
    
    private static testmethod void testMethodSAComplete20Red(){
        final Profile sysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
		final User sysAdminUser=FSTestFactory.createUser(sysAdmin.id);
		insert sysAdminUser;

        System.runAs(sysAdminUser) {
        accountId=FSEPStatusIndicatorTest_TestData.loadTestData();
        idsList=new List<Id>();
        List<FS_Installation__c> installList=new List<FS_Installation__c>();        
        exePlan = FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,accountId[0], false);
        exePlan.FS_Execution_Start_Date__c = System.today().addDays(-21);    	
        insert exePlan;
        
        idsList.add(exePlan.Id);
        idsList.add(accountId[1]);
        installList=FSEPStatusIndicatorTest_TestData.createInstOther(idsList,20,0);        
        insert installList;
        obj=FSEPStatusIndicatorTest_TestData.executeMethod(exePlan);
        system.assertEquals(REDCOLR, obj.colorSAComplete); 
        }
    }
    
    private static testmethod void testMethodSAComplete2Yellow(){
        final Profile sysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
		final User sysAdminUser=FSTestFactory.createUser(sysAdmin.id);
		insert sysAdminUser;

        System.runAs(sysAdminUser) {
        accountId=FSEPStatusIndicatorTest_TestData.loadTestData();
        idsList=new List<Id>();
        List<FS_Installation__c> installList=new List<FS_Installation__c>();        
        exePlan = FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,accountId[0], false);
        exePlan.FS_Execution_Start_Date__c = System.today().addDays(-9);    	
        insert exePlan;
        
        idsList.add(exePlan.Id);
        idsList.add(accountId[1]);
        installList=FSEPStatusIndicatorTest_TestData.createInstOther(idsList,2,0);        
        insert installList;
        obj=FSEPStatusIndicatorTest_TestData.executeMethod(exePlan);
        system.assertEquals(YELLOW, obj.colorSAComplete);
        }
    }
    
    
}