force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <displayFormat>EP-{0000}</displayFormat>
    <label>Execution Plan#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Start_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Execution Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlet Info Summary</relationshipLabel>
    <relationshipName>Outlet_Info_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/FSExecutionPlanStatusIndicatorTest2.cls
/******************************************** 
Name         : FSExecutionPlanStatusIndicatorTest2
Created By   : Infosys Limited
Created Date : Sep. 19, 2017
Usage        : Unit test coverage of FSExecutionPlanStatusIndicatorExtension
************************************************/


@isTest
public class FSExecutionPlanStatusIndicatorTest2 {
    
    public static final String APPROVED='Approved';
    public static final String STORE='Store Opening';
    public static final String BLUE='blue';
    public static final String GREEN='green';
    public static final String REDCOLR='red';
    public static final String YELLOW='yellow';
    public static final String GRAY='gray';
    public static List<Id> idsList;
    public static List<Id> accountId;
    public static FS_Execution_Plan__c exePlan;
    public static List<FS_Installation__c> installList;
    public static FSExecutionPlanStatusIndicatorExtension obj;
    
    private static testmethod void testMethodApproved20Green(){
        
        final Profile sysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
        final User sysAdminUser=FSTestFactory.createUser(sysAdmin.id);
        insert sysAdminUser;
        
        System.runAs(sysAdminUser) {
            accountId=FSEPStatusIndicatorTest_TestData.loadTestData();
            List<FS_Installation__c> installList=new List<FS_Installation__c>(); 
            idsList=new List<Id>();
            exePlan = FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,accountId[0], false);
            exePlan.FS_Execution_Start_Date__c = System.today().addDays(-25);    	
            insert exePlan;
            
            Test.startTest();
            idsList.add(exePlan.Id);
            idsList.add(accountId[1]);
            installList=FSEPStatusIndicatorTest_TestData.createInstOther(idsList,20,3);         
            insert installList;        
            obj=FSEPStatusIndicatorTest_TestData.executeMethod(exePlan);
            Test.stopTest();
            system.assertEquals(GREEN, obj.colorEPApproved);
        }
    }
    
    private static testmethod void testMethodApproved2Blue(){
        final Profile sysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
        final User sysAdminUser=FSTestFactory.createUser(sysAdmin.id);
        insert sysAdminUser;
        
        System.runAs(sysAdminUser) {
            accountId=FSEPStatusIndicatorTest_TestData.loadTestData();
            List<FS_Installation__c> installList=new List<FS_Installation__c>(); 
            idsList=new List<Id>();
            exePlan = FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,accountId[0], false);
            exePlan.FS_Execution_Start_Date__c = System.today().addDays(-17);    	
            insert exePlan;
            Test.startTest();
            idsList.add(exePlan.Id);
            idsList.add(accountId[1]);
            installList=FSEPStatusIndicatorTest_TestData.createInstOther(idsList,2,2);         
            insert installList;        
            obj=FSEPStatusIndicatorTest_TestData.executeMethod(exePlan);
            Test.stopTest();
            system.assertEquals(BLUE, obj.colorEPApproved);
        }
    }
    
    private static testmethod void testMethodApproved2Yellow(){
        final Profile sysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
        final User sysAdminUser=FSTestFactory.createUser(sysAdmin.id);
        insert sysAdminUser;
        
        System.runAs(sysAdminUser) {
            
            accountId=FSEPStatusIndicatorTest_TestData.loadTestData();
            List<FS_Installation__c> installList=new List<FS_Installation__c>(); 
            idsList=new List<Id>();
            exePlan = FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,accountId[0], false);
            exePlan.FS_Execution_Start_Date__c = System.today().addDays(-19);    	
            insert exePlan;
            Test.startTest();
            idsList.add(exePlan.Id);
            idsList.add(accountId[1]);
            installList=FSEPStatusIndicatorTest_TestData.createInstOther(idsList,2,2);         
            insert installList;        
            obj=FSEPStatusIndicatorTest_TestData.executeMethod(exePlan);
            Test.stopTest();
            system.assertEquals(YELLOW, obj.colorEPApproved);
        }
    }
    
    private static testmethod void testMethodApproved2Red(){
        final Profile sysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
        final User sysAdminUser=FSTestFactory.createUser(sysAdmin.id);
        insert sysAdminUser;
        
        System.runAs(sysAdminUser) {
            
            accountId=FSEPStatusIndicatorTest_TestData.loadTestData();
            List<FS_Installation__c> installList=new List<FS_Installation__c>(); 
            idsList=new List<Id>();
            exePlan = FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,accountId[0], false);
            exePlan.FS_Execution_Start_Date__c = System.today().addDays(-26);    	
            insert exePlan;
            Test.startTest();
            idsList.add(exePlan.Id);
            idsList.add(accountId[1]);
            installList=FSEPStatusIndicatorTest_TestData.createInstOther(idsList,2,2);         
            insert installList;        
            obj=FSEPStatusIndicatorTest_TestData.executeMethod(exePlan);
            Test.stopTest();
            system.assertEquals(REDCOLR, obj.colorEPApproved);
        }
    }
    
    private static testmethod void testMethodApproved2Green(){
        final Profile sysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
        final User sysAdminUser=FSTestFactory.createUser(sysAdmin.id);
        insert sysAdminUser;
        
        System.runAs(sysAdminUser) {
            accountId=FSEPStatusIndicatorTest_TestData.loadTestData();
            List<FS_Installation__c> installList=new List<FS_Installation__c>(); 
            idsList=new List<Id>();
            exePlan = FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,accountId[0], false);
            exePlan.FS_Execution_Start_Date__c = System.today().addDays(-26);    	
            insert exePlan;
            Test.startTest();
            idsList.add(exePlan.Id);
            idsList.add(accountId[1]);
            installList=FSEPStatusIndicatorTest_TestData.createInstOther(idsList,2,3);         
            insert installList;        
            obj=FSEPStatusIndicatorTest_TestData.executeMethod(exePlan);
            Test.stopTest();
            system.assertEquals(GREEN, obj.colorEPApproved);
        }
    }
    
    private static testmethod void testMethodScheduled2Blue(){
        final Profile sysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
        final User sysAdminUser=FSTestFactory.createUser(sysAdmin.id);
        insert sysAdminUser;
        
        System.runAs(sysAdminUser) {
            accountId=FSEPStatusIndicatorTest_TestData.loadTestData();
            List<FS_Installation__c> installList=new List<FS_Installation__c>(); 
            idsList=new List<Id>();
            exePlan = FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,accountId[0], false);
            exePlan.FS_Execution_Start_Date__c = System.today().addDays(-22);    	
            insert exePlan;
            Test.startTest();
            idsList.add(exePlan.Id);
            idsList.add(accountId[1]);
            installList=FSEPStatusIndicatorTest_TestData.createInstOther(idsList,2,3);         
            insert installList;        
            obj=FSEPStatusIndicatorTest_TestData.executeMethod(exePlan);
            Test.stopTest();
            system.assertEquals(BLUE, obj.colorScheduled);
        }
    }
    
    private static testmethod void testMethodScheduled2Yellow(){
        final Profile sysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
        final User sysAdminUser=FSTestFactory.createUser(sysAdmin.id);
        insert sysAdminUser;
        
        System.runAs(sysAdminUser) {
            accountId=FSEPStatusIndicatorTest_TestData.loadTestData();
            List<FS_Installation__c> installList=new List<FS_Installation__c>(); 
            idsList=new List<Id>();
            exePlan = FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,accountId[0], false);
            exePlan.FS_Execution_Start_Date__c = System.today().addDays(-24);    	
            insert exePlan;
            Test.startTest();
            idsList.add(exePlan.Id);
            idsList.add(accountId[1]);
            installList=FSEPStatusIndicatorTest_TestData.createInstOther(idsList,2,3);         
            insert installList;        
            obj=FSEPStatusIndicatorTest_TestData.executeMethod(exePlan);
            Test.stopTest();
            system.assertEquals(YELLOW, obj.colorScheduled);
        }
    }
    
    private static testmethod void testMethodScheduled2Green(){
        final Profile sysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
        final User sysAdminUser=FSTestFactory.createUser(sysAdmin.id);
        insert sysAdminUser;
        
        System.runAs(sysAdminUser) {
            accountId=FSEPStatusIndicatorTest_TestData.loadTestData();
            List<FS_Installation__c> installList=new List<FS_Installation__c>(); 
            idsList=new List<Id>();
            exePlan = FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,accountId[0], false);
            exePlan.FS_Execution_Start_Date__c = System.today().addDays(-23);    	
            insert exePlan;
            Test.startTest();
            idsList.add(exePlan.Id);
            idsList.add(accountId[1]);
            installList=FSEPStatusIndicatorTest_TestData.createInstOther(idsList,2,4);         
            insert installList;        
            obj=FSEPStatusIndicatorTest_TestData.executeMethod(exePlan);
            Test.stopTest();
            system.assertEquals(GREEN, obj.colorScheduled);
        }
    }
    
    private static testmethod void testMethodSAComplete2Red(){
        final Profile sysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
        final User sysAdminUser=FSTestFactory.createUser(sysAdmin.id);
        insert sysAdminUser;
        
        System.runAs(sysAdminUser) {
            accountId=FSEPStatusIndicatorTest_TestData.loadTestData();
            List<FS_Installation__c> installList=new List<FS_Installation__c>(); 
            idsList=new List<Id>();
            exePlan = FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,accountId[0], false);
            exePlan.FS_Execution_Start_Date__c = System.today().addDays(-22);    	
            insert exePlan;
            Test.startTest();
            idsList.add(exePlan.Id);
            idsList.add(accountId[1]);
            installList=FSEPStatusIndicatorTest_TestData.createInstOther(idsList,20,3);         
            insert installList;        
            obj=FSEPStatusIndicatorTest_TestData.executeMethod(exePlan);
            Test.stopTest();
            system.assertEquals(REDCOLR, obj.colorSAComplete);
        }
    }
    
    private static testmethod void testMethodScheduled20Yellow(){
        final Profile sysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
        final User sysAdminUser=FSTestFactory.createUser(sysAdmin.id);
        insert sysAdminUser;
        
        System.runAs(sysAdminUser) {
            accountId=FSEPStatusIndicatorTest_TestData.loadTestData();
            List<FS_Installation__c> installList=new List<FS_Installation__c>(); 
            idsList=new List<Id>();
            exePlan = FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,accountId[0], false);
            exePlan.FS_Execution_Start_Date__c = System.today().addDays(-29);    	
            insert exePlan;
            Test.startTest();
            idsList.add(exePlan.Id);
            idsList.add(accountId[1]);
            installList=FSEPStatusIndicatorTest_TestData.createInstOther(idsList,20,3);         
            insert installList;        
            obj=FSEPStatusIndicatorTest_TestData.executeMethod(exePlan);
            Test.stopTest();
            system.assertEquals(YELLOW, obj.colorScheduled);
        }
    }
}