force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <displayFormat>EP-{0000}</displayFormat>
    <label>Execution Plan#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlet Info Summary</relationshipLabel>
    <relationshipName>Outlet_Info_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/Platform_change_approved__c.field-meta.xml
<CustomField>
    <fullName>Platform_change_approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Platform change approved?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/Type_of_Dispenser_Platform__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Dispenser_Platform__c</fullName>
    <description>multi select pick list</description>
    <label>Platform Type/s</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Platform_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3100</fullName>
    </customValue>
    <customValue>
        <fullName>6000</fullName>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
    </customValue>
    <customValue>
        <fullName>7100</fullName>
    </customValue>
    <customValue>
        <fullName>8000</fullName>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
    </customValue>
    <masterLabel>Platform Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FSExecutionPlanInlineWarningTest.cls
@isTest
public class FSExecutionPlanInlineWarningTest {
    
    private static Profile fetSysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_FETADMIN);
    
    @testSetup
    public static void createData(){
        //create EP and IP
        FSTestFactory.createCommonTestRecords();
    }   
    
    public static testMethod void displayWarning(){
        //get the Ep
        final FS_Execution_Plan__c exep = [select id from FS_Execution_Plan__c];
        //get the IP
        final FS_Installation__c install = [Select Type_of_Dispenser_Platform__c from FS_Installation__c];
        //mismatch the platform
        install.Type_of_Dispenser_Platform__c='7000;8000';
        install.Platform_change_approved__c=true;
        update install;
        //run the controller
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
        system.runAs(fetSysAdminUser){
            final ApexPages.StandardController standCon = new ApexPages.StandardController(exep);
            final FSExecutionPlanInlineWarningController controller = new FSExecutionPlanInlineWarningController(standCon);            
            controller.checkSyncValues();  
        }
    }
}