force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Age__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Age__c</fullName>
    <formula>TODAY() -  FS_Execution_Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Execution Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <displayFormat>EP-{0000}</displayFormat>
    <label>Execution Plan#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan_Final_Approval_PM__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan_Final_Approval_PM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Execution Plan Final Approval (PM)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan_Final_Approval_PMCheck__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan_Final_Approval_PMCheck__c</fullName>
    <description>it will become TRUE when all installations are approved</description>
    <formula>IF( AND(FS_of_Installations__c&gt;0,(FS_Installations_approved_by_PM__c + FS_of_Installations_Cancelled__c) = FS_of_Installations__c) ,true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>All Execution Plan Final Approval (PM)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_of_Installations__c.field-meta.xml
<CustomField>
    <fullName>FS_of_Installations__c</fullName>
    <label># of Installations</label>
    <summaryForeignKey>FS_Installation__c.FS_Execution_Plan__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_Davaco_SA_Status__c.field-meta.xml
<CustomField>
    <fullName>FS_Davaco_SA_Status__c</fullName>
    <formula>(If( ISPICKVAL( FS_Davaco_Requirements__c, &quot;SA Not Required - OSM approval required for local market&quot;) ,&quot;Complete&quot;, 
(If( ISPICKVAL( FS_Davaco_Requirements__c , &quot;New Construction SA - Proceed w/Scheduling&quot;) ,&quot;Complete&quot;, 
(If( FS_Execution_Plan__r.FS_Bypass_functions_Company_Locations__c,&quot;Complete&quot;, 

(If( AND(TEXT( FS_SA_Scheduled_On_Date__c )=&quot;&quot; , 
TEXT( FS_SA_Completed_Date__c )=&quot;&quot;),&quot;**Pending&quot;, 

(If( AND(TEXT(FS_SA_Scheduled_On_Date__c)&lt;&gt;&quot;&quot; , 
TEXT(FS_SA_Completed_Date__c)=&quot;&quot;),&quot;*Scheduled&quot;, 

(If( AND(TEXT(FS_SA_Scheduled_On_Date__c)&lt;&gt;&quot;&quot; , 
TEXT(FS_SA_Completed_Date__c)&lt;&gt;&quot;&quot;),&quot;Complete&quot;,&quot;**Pending&quot;))))))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SA Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlet Info Summary</relationshipLabel>
    <relationshipName>Outlet_Info_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan_Final_Approval_PM__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan_Final_Approval_PM__c</fullName>
    <description>Execution Plan Final Approval (PM)</description>
    <label>Execution Plan Final Approval (PM)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_OB_Info_Status__c.field-meta.xml
<CustomField>
    <fullName>FS_OB_Info_Status__c</fullName>
    <formula>IF( OR( AND(TEXT(FS_Trainer__c) &lt;&gt;&quot;&quot; , Outlet_Open_Time__c &lt;&gt;&quot;&quot; , FS_Training_Start_Time__c &lt;&gt;&quot;&quot;), 
CONTAINS(TEXT(FS_Trainer__c), &quot;Not Needed&quot;) 
), &quot;Complete&quot;,&quot;Not Complete&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Onboarding Info Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Scheduled_Install_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Scheduled_Install_Date__c</fullName>
    <description>This is the replacement of the install date formula field. Which contains latest reschedule date.</description>
    <label>Scheduled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/Overall_Status2__c.field-meta.xml
<CustomField>
    <fullName>Overall_Status2__c</fullName>
    <label>Transaction Status</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FSExecutionPlanStatusIndicatorExtension.cls
/*******************************************************************************
Name         : FSExecutionPlanStatusIndicatorExtension
Created By   : Sonal Shrivastava (Appiro JDC)
Created Date : 08-Nov-2013
Usage        : Extension for FSExecutionPlanStatusIndicator Page , which is used
for StatusIndicator on Execution Plan Page
*******************************************************************************/
public without sharing class FSExecutionPlanStatusIndicatorExtension {
    public static final String GRAY='gray';
    public static final String BLUE='blue';
    public static final String YELLOW='yellow';
    public static final String REDC='red';
    public static final String GREEN='green';
    public static final Integer TWENTY=20;
    public static final Integer ZERO=0;
    public static final String COMPLETE='Complete';
    public static final String FIVECOMPLETE=FSConstants.IPCOMPLETE ;
    public static final String XPENDING='**Pending';
    public static final String XSCHEDULED='*Scheduled';
    public FS_Execution_Plan__c execPlan {get; set;}
    public String colorSAPending {get; set;}
    public String colorSAScheduled {get; set;}
    public String colorSAComplete {get; set;}
    public String colorEPApproved {get; set;}
    public String colorScheduled {get; set;}
    public String colorInstallComplete {get; set;}
    public String colorOnboardingComplete {get; set;}
	public static Object nullVal() { return null; }    
    //---------------------------------------------------------------------------
    // Constructor
    //--------------------------------------------------------------------------- 
    public FSExecutionPlanStatusIndicatorExtension(final Apexpages.Standardcontroller standCont){
        final String execPlanId = standCont.getId();
        init();
        for(FS_Execution_Plan__c ep : [SELECT Id, FS_of_Installations__c,FS_Execution_Plan_Final_Approval_PMCheck__c, FS_Execution_Age__c, FS_Execution_Plan_Final_Approval_PM__c, 
                                       (SELECT Id, FS_Davaco_SA_Status__c, Overall_Status2__c, FS_OB_Info_Status__c, FS_Scheduled_Install_Date__c 
                                        FROM Outlet_Info_Summary__r)
                                       FROM FS_Execution_Plan__c 
                                       WHERE Id = :execPlanId]){
                                           execPlan = ep;
                                       }
        populateColors();
    }
    
    //---------------------------------------------------------------------------
    // Method to initialize public variables
    //---------------------------------------------------------------------------
    private void init(){
        execPlan = new FS_Execution_Plan__c();
        colorSAPending = GRAY;
        colorSAScheduled = GRAY;
        colorSAComplete = GRAY;
        colorEPApproved = GRAY;
        colorScheduled = GRAY;
        colorInstallComplete = GRAY;
        colorOnboardingComplete = GRAY;
    }
    
    //---------------------------------------------------------------------------
    // Method to populate all color variables
    //---------------------------------------------------------------------------
    private void populateColors(){
        if(execPlan.Id != nullVal()){
            
            Boolean allNotPending = true;
            Boolean allNotNotReadyPending = true;
            Boolean allScheduled = true;
            Boolean allComplete = true;            
            Boolean allInstallDateNotBlank = true;
            Boolean allOverallStatusNot5InstComp = true;
            Boolean allOverallStatus5InstComp = true;
            Boolean allOBInfoStatusNotComp = true;
            Boolean allOBInfoStatusComp = true;
            
            if(execPlan.FS_Execution_Age__c >= ZERO){
                colorSAPending = GREEN;
            }
            
            for(FS_Installation__c inst : execPlan.Outlet_Info_Summary__r ){
                
                if(inst.FS_Davaco_SA_Status__c == XPENDING){
                    allNotPending = false;
                }
                if(inst.FS_Davaco_SA_Status__c == '***Not Ready' || inst.FS_Davaco_SA_Status__c == XPENDING){
                    allNotNotReadyPending = false;
                }
                if(inst.FS_Davaco_SA_Status__c != XSCHEDULED){
                    allScheduled = false;
                }
                if(inst.FS_Davaco_SA_Status__c != COMPLETE){
                    allComplete = false;
                }
                if(inst.FS_Scheduled_Install_Date__c == nullVal()){
                    allInstallDateNotBlank = false;
                }
                if(inst.Overall_Status2__c == FIVECOMPLETE){
                    allOverallStatusNot5InstComp = FALSE;
                }
                if(inst.Overall_Status2__c != FIVECOMPLETE){
                    allOverallStatus5InstComp = false;
                }
                if(inst.FS_OB_Info_Status__c == COMPLETE){
                    allOBInfoStatusNotComp = false;
                }
                if(inst.FS_OB_Info_Status__c != COMPLETE){
                    allOBInfoStatusComp = false;
                }
            }
            findSAScheduledColor(allNotNotReadyPending);
            findSACompleteColor(allNotPending, allScheduled, allComplete);
            findEPApprovedColor(allComplete);
            findScheduledColor(allInstallDateNotBlank);
            findInstallCompleteColor(allOverallStatusNot5InstComp, allOverallStatus5InstComp, allInstallDateNotBlank);
            findOnboardingCompleteColor(allOBInfoStatusNotComp, allOBInfoStatusComp, allOverallStatus5InstComp);
        }
    }
    
    //---------------------------------------------------------------------------
    // Method to find SA Scheduled Color
    //---------------------------------------------------------------------------
    private void findSAScheduledColor(final Boolean allNotNotReadyPending){
        if(execPlan.FS_of_Installations__c < TWENTY ){
            if(!allNotNotReadyPending  && execPlan.FS_Execution_Age__c < 2){
                colorSAScheduled = BLUE;
            }
            else if(!allNotNotReadyPending  && execPlan.FS_Execution_Age__c >= 2 && execPlan.FS_Execution_Age__c <= 3){
                colorSAScheduled = YELLOW;
            }
            else if(!allNotNotReadyPending && execPlan.FS_Execution_Age__c > 3){
                colorSAScheduled = REDC;
            }
            else if(allNotNotReadyPending){
                colorSAScheduled = GREEN;
            }
        }
        else{
            if(!allNotNotReadyPending && execPlan.FS_Execution_Age__c < 3){
                colorSAScheduled = BLUE;
            }
            else if(!allNotNotReadyPending && execPlan.FS_Execution_Age__c >= 3 && execPlan.FS_Execution_Age__c <= 4){
                colorSAScheduled = YELLOW;
            }
            else if(!allNotNotReadyPending && execPlan.FS_Execution_Age__c > 4){
                colorSAScheduled = REDC;
            }
            else if(allNotNotReadyPending){
                colorSAScheduled = GREEN;
            }
        }
    }
    
    //----------------------------------------------------------------------------
    // Method to find SA Complete Color
    //---------------------------------------------------------------------------- 
    private void findSACompleteColor(final Boolean allNotPending,final  Boolean allScheduled,final  Boolean allComplete){   
        if(execPlan.FS_of_Installations__c < TWENTY ){
            if(execPlan.FS_Execution_Age__c < 4 && allNotPending && !allScheduled){
                colorSAComplete = GRAY;
            }
            else if(!allComplete && execPlan.FS_Execution_Age__c < 8 && allScheduled){
                colorSAComplete = BLUE;
            }
            else if(!allComplete && execPlan.FS_Execution_Age__c >= 8 && execPlan.FS_Execution_Age__c <= 10 && allScheduled ){
                colorSAComplete = YELLOW;
            }
            else if(!allComplete && execPlan.FS_Execution_Age__c > 10 && allScheduled){
                colorSAComplete = REDC;
            }
            else if(allComplete){
                colorSAComplete = GREEN;
            }
        } 
        else{
            if(execPlan.FS_Execution_Age__c < 5 && allNotPending){
                colorSAComplete = GRAY;
            }
            else if(!allComplete && execPlan.FS_Execution_Age__c < 17){
                colorSAComplete = BLUE;
            }
            else if(!allComplete && execPlan.FS_Execution_Age__c >= 17 && execPlan.FS_Execution_Age__c <= 19 ){
                colorSAComplete = YELLOW;
            }
            else if(!allComplete && execPlan.FS_Execution_Age__c > 19 ){
                colorSAComplete = REDC;
            }
            else if(allComplete){
                colorSAComplete = GREEN;
            }
        }
    }
    
    //----------------------------------------------------------------------------
    // Method to find EP Approved Color
    //---------------------------------------------------------------------------- 
    private void findEPApprovedColor(final Boolean allComplete){   
        if(execPlan.FS_of_Installations__c < TWENTY ){
            if(execPlan.FS_Execution_Age__c < 11 && allComplete){
                colorEPApproved = GRAY;
            }
            else if(!execPlan.FS_Execution_Plan_Final_Approval_PMCheck__c && execPlan.FS_Execution_Age__c < 18 && allComplete){
                colorEPApproved = BLUE;
            }
            else if(!execPlan.FS_Execution_Plan_Final_Approval_PMCheck__c && execPlan.FS_Execution_Age__c >= 18 && execPlan.FS_Execution_Age__c <= TWENTY && allComplete){
                colorEPApproved = YELLOW;
            }
            else if(!execPlan.FS_Execution_Plan_Final_Approval_PMCheck__c && execPlan.FS_Execution_Age__c > TWENTY && allComplete){
                colorEPApproved = REDC;
            }
            else if(execPlan.FS_Execution_Plan_Final_Approval_PMCheck__c){
                colorEPApproved = GREEN;
            }
        } 
        else{
            if(execPlan.FS_Execution_Age__c < TWENTY && allComplete){
                colorEPApproved = GRAY;
            }
            else if(!execPlan.FS_Execution_Plan_Final_Approval_PMCheck__c && execPlan.FS_Execution_Age__c < 24 && allComplete){
                colorEPApproved = BLUE;
            }
            else if(!execPlan.FS_Execution_Plan_Final_Approval_PMCheck__c && execPlan.FS_Execution_Age__c >= 24 && execPlan.FS_Execution_Age__c <= 25 && allComplete){
                colorEPApproved = YELLOW;
            }
            else if(!execPlan.FS_Execution_Plan_Final_Approval_PMCheck__c && execPlan.FS_Execution_Age__c > 25 && allComplete){
                colorEPApproved = REDC;
            }
            else if(execPlan.FS_Execution_Plan_Final_Approval_PMCheck__c){
                colorEPApproved = GREEN;
            }
        }
    }
    
    //----------------------------------------------------------------------------
    // Method to find Scheduled Color
    //---------------------------------------------------------------------------- 
    private void findScheduledColor(final Boolean allInstallDateNotBlank){   
        if(execPlan.FS_of_Installations__c < TWENTY ){
            if(execPlan.FS_Execution_Age__c < 21 && execPlan.FS_Execution_Plan_Final_Approval_PMCheck__c){
                colorScheduled = GRAY;
            }
            else if(!allInstallDateNotBlank && execPlan.FS_Execution_Age__c < 23 && execPlan.FS_Execution_Plan_Final_Approval_PMCheck__c){
                colorScheduled = BLUE;
            }
            else if(!allInstallDateNotBlank && execPlan.FS_Execution_Age__c >= 23 && execPlan.FS_Execution_Age__c <= 24 && execPlan.FS_Execution_Plan_Final_Approval_PMCheck__c){
                colorScheduled = YELLOW;
            }
            else if(!allInstallDateNotBlank && execPlan.FS_Execution_Age__c > 24 && execPlan.FS_Execution_Plan_Final_Approval_PMCheck__c){
                colorScheduled = REDC;
            }
            else if(allInstallDateNotBlank){
                colorScheduled = GREEN;
            }
        } 
        else{
            if(execPlan.FS_Execution_Age__c < 26 && execPlan.FS_Execution_Plan_Final_Approval_PMCheck__c){
                colorScheduled = GRAY;
            }
            else if(!allInstallDateNotBlank  && execPlan.FS_Execution_Age__c < 28 && execPlan.FS_Execution_Plan_Final_Approval_PMCheck__c){
                colorScheduled = BLUE;
            }
            else if(!allInstallDateNotBlank  && execPlan.FS_Execution_Age__c >= 28 && execPlan.FS_Execution_Age__c <= 29 && execPlan.FS_Execution_Plan_Final_Approval_PMCheck__c){
                colorScheduled = YELLOW;
            }
            else if(!allInstallDateNotBlank  && execPlan.FS_Execution_Age__c > 29 && execPlan.FS_Execution_Plan_Final_Approval_PMCheck__c){
                colorScheduled = REDC;
            }
            else if(allInstallDateNotBlank){
                colorScheduled = GREEN;
            }
        }
    }
    
    //----------------------------------------------------------------------------
    // Method to find Install Complete Color
    //---------------------------------------------------------------------------- 
    private void findInstallCompleteColor(final Boolean allOverallStatusNot5InstComp,final  Boolean allOverallStatus5InstComp,final  Boolean allInstallDateNotBlank){   
        if(execPlan.FS_of_Installations__c < TWENTY ){
            if(execPlan.FS_Execution_Age__c < 25 && allInstallDateNotBlank){
                colorInstallComplete = GRAY;
            }
            else if(!allOverallStatus5InstComp && execPlan.FS_Execution_Age__c < 37 && allInstallDateNotBlank){
                colorInstallComplete = BLUE;
            }
            else if(!allOverallStatus5InstComp && execPlan.FS_Execution_Age__c >= 37 && execPlan.FS_Execution_Age__c <= 40 && allInstallDateNotBlank){
                colorInstallComplete = YELLOW;
            }
            else if(!allOverallStatus5InstComp && execPlan.FS_Execution_Age__c > 40 && allInstallDateNotBlank){
                colorInstallComplete = REDC;
            }
            else if(allOverallStatus5InstComp){
                colorInstallComplete = GREEN;
            }
        } 
        else{
            if(execPlan.FS_Execution_Age__c < 30 && allInstallDateNotBlank){
                colorInstallComplete = GRAY;
            }
            else if(allOverallStatusNot5InstComp && execPlan.FS_Execution_Age__c < 42 && allInstallDateNotBlank){
                colorInstallComplete = BLUE;
            }
            else if(allOverallStatusNot5InstComp && execPlan.FS_Execution_Age__c >= 43 && execPlan.FS_Execution_Age__c <= 45 && allInstallDateNotBlank){
                colorInstallComplete = YELLOW;
            }
            else if(allOverallStatusNot5InstComp && execPlan.FS_Execution_Age__c > 45 && allInstallDateNotBlank){
                colorInstallComplete = REDC;
            }
            else if(allOverallStatus5InstComp){
                colorInstallComplete = GREEN;
            }
        }
    }
    
    //----------------------------------------------------------------------------
    // Method to find Onboarding Complete Color
    //---------------------------------------------------------------------------- 
    private void findOnboardingCompleteColor(final Boolean allOBInfoStatusNotComp,final  Boolean allOBInfoStatusComp,final  Boolean allOverallStatus5InstComp){   
        if(execPlan.FS_of_Installations__c < TWENTY ){
            if(execPlan.FS_Execution_Age__c < 41 && allOverallStatus5InstComp){
                colorOnboardingComplete = GRAY;
            }
            else if(allOBInfoStatusNotComp && execPlan.FS_Execution_Age__c == 41 && allOverallStatus5InstComp){
                colorOnboardingComplete = BLUE;
            }
            else if(allOBInfoStatusNotComp && execPlan.FS_Execution_Age__c > 41 && allOverallStatus5InstComp){
                colorOnboardingComplete = REDC;
            }
            else if(allOBInfoStatusComp){
                colorOnboardingComplete = GREEN;
            }
        } 
        else{
            if(execPlan.FS_Execution_Age__c < 46 && allOverallStatus5InstComp){
                colorOnboardingComplete = GRAY;
            }
            else if(allOBInfoStatusNotComp && execPlan.FS_Execution_Age__c == 46 && allOverallStatus5InstComp){
                colorOnboardingComplete = BLUE;
            }
            else if(allOBInfoStatusNotComp && execPlan.FS_Execution_Age__c > 46 && allOverallStatus5InstComp){
                colorOnboardingComplete = REDC;
            }
            else if(allOBInfoStatusComp){
                colorOnboardingComplete = GREEN;
            }
        }
    }
    
}