force-app/main/default/objects/CaseToOutletdispenser__c/CaseToOutletdispenser__c.object-meta.xml
<CustomObject>
    <description>This is a junction object between case object and outlet dispenser object</description>
    <label>Case To OD</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case To Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseToOutletdispenser__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <description>Parent case</description>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Case To Outlet Dispensers</relationshipLabel>
    <relationshipName>CaseToOutletdispensers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CaseToOutletdispenser__c/fields/FS_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>FS_Serial_Number__c</fullName>
    <formula>Outlet_Dispenser__r.FS_Serial_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Serial Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseToOutletdispenser__c/fields/Outlet_Dispenser__c.field-meta.xml
<CustomField>
    <fullName>Outlet_Dispenser__c</fullName>
    <label>Outlet Dispenser</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Customer__c</field>
            <operation>equals</operation>
            <valueField>FS_Outlet_Dispenser__c.FS_Outlet__c</valueField>
        </filterItems>
        <filterItems>
            <field>FS_Outlet_Dispenser__c.FS_IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipName>CaseToOutletdispensers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_IsActive__c.field-meta.xml
<CustomField>
    <fullName>FS_IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>active or inactive</description>
    <label>Active (A) / Inactive (I)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Other_PIA_Installation__c.field-meta.xml
<CustomField>
    <fullName>FS_Other_PIA_Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RO4W/Removal/Replacement Transaction</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Outlet Dispensers (Other PIA Installation)</relationshipLabel>
    <relationshipName>Outlet_Dispensers2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <description>Outlet field.</description>
    <label>Outlet</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 3) OR (2 AND 4 AND (5 OR 7)) OR (2 AND 4 AND 6)</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for Outlet.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Outlet</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Outlet</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>7000, 8000, 9000, CCNA Dispenser</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Dispenser</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value>No, Yes</value>
        </filterItems>
        <filterItems>
            <field>Account.Is_Default_FET_International_Outlet__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlet Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>FS_Serial_Number__c</fullName>
    <formula>FS_Serial_Number2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Serial Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Status__c.field-meta.xml
<CustomField>
    <fullName>FS_Status__c</fullName>
    <description>Status.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Enroll</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Hibernate</fullName>
            </value>
            <value>
                <fullName>Wakeup</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Booking Complete</fullName>
            </value>
            <value>
                <fullName>Dispenser Pickup</fullName>
            </value>
            <value>
                <fullName>Dispenser Delivered</fullName>
            </value>
            <value>
                <fullName>In Inventory</fullName>
            </value>
            <value>
                <fullName>Assigned to Outlet</fullName>
            </value>
            <value>
                <fullName>Winterized</fullName>
            </value>
            <value>
                <fullName>Rough Stock</fullName>
            </value>
            <value>
                <fullName>Remaned</fullName>
            </value>
            <value>
                <fullName>To be scrapped by Bottler</fullName>
            </value>
            <value>
                <fullName>To be scrapped by CM</fullName>
            </value>
            <value>
                <fullName>Confirmed Scrapped</fullName>
            </value>
            <value>
                <fullName>Sold to Bottler</fullName>
            </value>
            <value>
                <fullName>Purchased from Bottler</fullName>
            </value>
            <value>
                <fullName>To be Remanufactured</fullName>
            </value>
            <value>
                <fullName>Unenrolled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FS_ODAndCaseCommentsDetails.cls
/*
* Date         : 20/06/2019
* Developer    : Infosys
* Purpose      : Controller class for VF Component's CaseCommentsOutletDispensers and FS_CaseDetailsForAMS to get 
				 OD details and casecomments.
*=================================================================================================================
*                                 Upate History
*                                 ---------------
*   Date        Developer       Tag   Description
*============+================+=====+=============================================================================
* 20/06/2019 | Infosys |     | Initial Version                                         
*===========+=================+=====+=============================================================================
*/
public without sharing class FS_ODAndCaseCommentsDetails {
    public Id caseRecId {get; set;}
    public Id recId {get; set;}
    public List<FS_Outlet_Dispenser__c> odList {get;set;}
    
    /*****************************************************************
    Method: getDispenserList
    Description: getDispenserList method is to get the Outlet Dispenser linked to Account.
    Added as part of FET 7.0, //Sprint 1 - FNF-459
    *******************************************************************/ 
    public List<FS_Outlet_Dispenser__c> getDispenserList(){
        if(recId != null)
        {   
            Set<Id> odIDSet = new Set<Id>();
            for(CaseToOutletdispenser__c caseOD: [select Case__c,Outlet_Dispenser__c,Outlet_Dispenser__r.FS_Outlet__c from CaseToOutletdispenser__c where Case__c=:caseRecId and Outlet_Dispenser__r.FS_Outlet__c=:recId]){
                odIDSet.add(caseOD.Outlet_Dispenser__c);              
            }
            odList = [select id,Name,FS_Outlet__r.name,FS_IsActive__c,FS_Serial_Number__c,FS_Status__c from FS_Outlet_Dispenser__c where Id IN: odIDSet]; 
        }
        return odList;
    }
    
    /*****************************************************************
    Method: getCaseComments
    Description: getCaseComments method is to get all the casecomments excluding 'Freestyle Administratore'created seprated with ';'.
    Added as part of FET 7.0, //Sprint 1 - FNF-459
    *******************************************************************/ 
    Public String getCaseComments(){
        String caseComments = '';
        List<CaseComment> ccList = new List<CaseComment>();
        ccList = [Select CommentBody from CaseComment where ParentId =: caseRecId and CreatedById !=: FSUtil.getFreeStyleUserId()];
        for(CaseComment ccCm : ccList){
            caseComments = caseComments + ccCm.CommentBody + ';';
        }
        return caseComments;
    }
    
    /*****************************************************************
    Method: getDispenserList
    Description: getDispenserList method is to get the Outlet Dispenser linked to RO4W..
    Added as part of FET 7.0, //Sprint 1 - FNF-459
    *******************************************************************/ 
     public List<FS_Outlet_Dispenser__c> getRO4WDispenserList(){
         if(recId != null)
         {   
             odList = [SELECT id,Name,FS_Outlet__r.name,FS_IsActive__c,FS_Serial_Number__c,FS_Status__c from FS_Outlet_Dispenser__c where FS_Other_PIA_Installation__c =: recId];                   
         }
         return odList;
    }
}