force-app/main/default/objects/Dummy_Execution_Plan_del__c/Dummy_Execution_Plan_del__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Dummy Execution Plan</label>
</CustomObject>

force-app/main/default/objects/Dummy_Execution_Plan_del__c/fields/ExecutionPlan_Name__c.field-meta.xml
<CustomField>
    <fullName>ExecutionPlan_Name__c</fullName>
    <label>ExecutionPlan Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <displayFormat>EP-{0000}</displayFormat>
    <label>Execution Plan#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/FSInstallationRelatedButtonsController.cls
public class FSInstallationRelatedButtonsController {
 
    @AuraEnabled
    public static id getEpId(){
        String EPName = Dummy_Execution_Plan_del__c.getInstance().ExecutionPlan_Name__c;
        FS_Execution_Plan__c eprec = [select id,name from FS_Execution_Plan__c where name like :('%' + EPName + '%') limit 1];
        return eprec.id;
    }
    @AuraEnabled
    public static boolean getProfileAccess(){
        boolean profileHasAccess=false;
        String usrProfileName = [select u.Profile.Name from User u where u.id = :Userinfo.getUserId()].Profile.Name;
        if(string.isNotBlank(usrProfileName) && (usrProfileName.contains('FS Admin PM_P') || usrProfileName.contains('FS AC_P') || usrProfileName.contains('FS PM_P') || usrProfileName.contains('System Administrator') || usrProfileName.contains('FET System Admin'))){
            profileHasAccess=true;
        }
        return profileHasAccess;
    }
}