force-app/main/default/objects/Apex_Error_Log__c/Apex_Error_Log__c.object-meta.xml
<CustomObject>
    <description>Custom Object used to store all the errors in exception blocks along with system.debug statements. Mostly useful in case of triggers, batch classes etc.</description>
    <label>Apex Error Log</label>
    <nameField>
        <label>Apex Error Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Errors Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Error_Log__c/fields/Application_Name__c.field-meta.xml
<CustomField>
    <fullName>Application_Name__c</fullName>
    <description>Name of the application</description>
    <label>Application Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Error_Log__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>Name of the Class or Component or File or Reference from where the error or exception reported.</description>
    <label>Class Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Error_Log__c/fields/Error_Severity__c.field-meta.xml
<CustomField>
    <fullName>Error_Severity__c</fullName>
    <description>Error Serverity</description>
    <label>Error Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>High</fullName>
                <default>true</default>
                <label>High</label>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Cosmetic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apex_Error_Log__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <description>Name of the Function or Method from where the error or exception reported.</description>
    <label>Method Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Error_Log__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>Name of the object associated with error reported.</description>
    <label>Object Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_Dispenser_QTY__c.field-meta.xml
<CustomField>
    <fullName>FS_Dispenser_QTY__c</fullName>
    <label>Dispenser QTY</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_DispOrder1__c.field-meta.xml
<CustomField>
    <fullName>FS_DispOrder1__c</fullName>
    <inlineHelpText>This reflects the quantity of dispensers specified on the related Equipment Package</inlineHelpText>
    <label>Dispensers QTY 1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_DispOrder2__c.field-meta.xml
<CustomField>
    <fullName>FS_DispOrder2__c</fullName>
    <inlineHelpText>This reflects the quantity of dispensers specified on the related Equipment Package</inlineHelpText>
    <label>Dispensers QTY 2</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_DispOrder3__c.field-meta.xml
<CustomField>
    <fullName>FS_DispOrder3__c</fullName>
    <inlineHelpText>This reflects the quantity of dispensers specified on the related Equipment Package</inlineHelpText>
    <label>Dispensers QTY 3</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Platform1__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform1__c</fullName>
    <label>Platform 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Platform2__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform2__c</fullName>
    <label>Platform 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Platform3__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform3__c</fullName>
    <label>Platform 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/Overall_Status2__c.field-meta.xml
<CustomField>
    <fullName>Overall_Status2__c</fullName>
    <label>Transaction Status</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/Type_of_Dispenser_Platform__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Dispenser_Platform__c</fullName>
    <description>multi select pick list</description>
    <label>Platform Type/s</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_IP_Equipment_Package__c/FS_IP_Equipment_Package__c.object-meta.xml
<CustomObject>
    <label>Equipment Package</label>
    <nameField>
        <displayFormat>IP_EQP-{0000}</displayFormat>
        <label>Equipment Package Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_IP_Equipment_Package__c/fields/FS_Dispenser_QTY__c.field-meta.xml
<CustomField>
    <fullName>FS_Dispenser_QTY__c</fullName>
    <label>Dispenser QTY</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FS_IP_Equipment_Package__c/fields/FS_Installation__c.field-meta.xml
<CustomField>
    <fullName>FS_Installation__c</fullName>
    <label>Installation</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Equipment Packages</relationshipLabel>
    <relationshipName>Equipment_Packages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_IP_Equipment_Package__c/fields/FS_Valid_Fill_Notification_Flag__c.field-meta.xml
<CustomField>
    <fullName>FS_Valid_Fill_Notification_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Valid Fill Notification Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Platform_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3100</fullName>
    </customValue>
    <customValue>
        <fullName>6000</fullName>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
    </customValue>
    <customValue>
        <fullName>7100</fullName>
    </customValue>
    <customValue>
        <fullName>8000</fullName>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
    </customValue>
    <masterLabel>Platform Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FS_EquipPakage_Install_TriggerHandler.cls
/**************************************
Name         : FS_EquipPakage_Install_TriggerHandler
Created By   : Infosys
Created Date : 19/01/2016
Usage        : This class holds the business logic of the Equipment Package Trigger
Modified: Venkat -- FET 5.0 US 7 and also code optimization 
****************************************/
public class FS_EquipPakage_Install_TriggerHandler{  
    
    public Static void isBeforeUpdate(final List<FS_IP_Equipment_Package__c> newList,final List<FS_IP_Equipment_Package__c> oldList,final Map<Id,FS_IP_Equipment_Package__c> newMap,final Map<Id,FS_IP_Equipment_Package__c> oldMap){
        validFillNotificationEQP(newList, oldMap);
    }   
    
    public Static void isAfterUpdate(final List<FS_IP_Equipment_Package__c> newList,final List<FS_IP_Equipment_Package__c> oldList,final Map<Id,FS_IP_Equipment_Package__c> newMap,final Map<Id,FS_IP_Equipment_Package__c> oldMap) {
        updateInstallQuantity (newList,oldList,newMap,oldMap);
    }
    
        /*****************************************************************
    Method: updateInstallQuantity
    Description: updateInstallQuantity method to update quantity and planned top mount fields on installation    
    New:Venkat as part of FET 5.0 US 7 copy quantity values from Equipment package to Installation
    *******************************************************************/ 
    
    public static void updateInstallQuantity(final List<FS_IP_Equipment_Package__c> newList,final List<FS_IP_Equipment_Package__c> oldList,final Map<Id,FS_IP_Equipment_Package__c> newMap,final Map<Id,FS_IP_Equipment_Package__c> oldMap) {
        //Map to store Equipment package reocrd with refrence to Install Id and Equipment package Platform
        final Map<String,FS_IP_Equipment_Package__c> equipPlatfromMap=new Map<String,FS_IP_Equipment_Package__c>();
        //Set to store Instalaltion Ids
        final Set<Id> installSet=new Set<Id>();
        //List to store installation records 
        final List<FS_Installation__c> installList=new List<FS_Installation__c>();
        //iterating new list to seperate equipment package records where Dispenser/IM adapter quantity fields been updated
        for(FS_IP_Equipment_Package__c equip:newList){
            if(equip.FS_Dispenser_QTY__c!=oldMap.get(equip.Id).FS_Dispenser_QTY__c){
                //set to store Installation Ids
                installSet.add(equip.FS_Installation__c);
                //Map to store Equipment package records based on Installation Id and Equipment Platform
                equipPlatfromMap.put(equip.FS_Installation__c+equip.FS_Platform_Type__c, equip);
            }
        }
        //Iterating Installation records
        for(FS_Installation__c install:[select id,name,Overall_Status2__c,Type_of_Dispenser_Platform__c,FS_Platform1__c,
                                        FS_Platform2__c,FS_Platform3__c,FS_DispOrder1__c,FS_DispOrder2__c,FS_DispOrder3__c,recordtypeId                     					
                                        from FS_Installation__c where Id IN:installSet and (recordtypeId=:FSInstallationValidateAndSet.ipNewRecType or recordtypeId=:FSInstallationValidateAndSet.ipRecTypeReplacement)]){
            //verifying the map with platform 1 field, to assign quantity fields from Equipment package to Installation                               
        	if(equipPlatfromMap.containsKey(install.Id+install.FS_Platform1__c)){                 
                install.FS_DispOrder1__c=equipPlatfromMap.get(install.Id+install.FS_Platform1__c).FS_Dispenser_QTY__c;                
            }
            //verifying the map with platform 2 field, to assign quantity fields from Equipment package to Installation  
            if(equipPlatfromMap.containsKey(install.Id+install.FS_Platform2__c)){                 
                install.FS_DispOrder2__c=equipPlatfromMap.get(install.Id+install.FS_Platform2__c).FS_Dispenser_QTY__c;               
            }
            //verifying the map with platform 3 field, to assign quantity fields from Equipment package to Installation 
            if(equipPlatfromMap.containsKey(install.Id+install.FS_Platform3__c)){                
                install.FS_DispOrder3__c=equipPlatfromMap.get(install.Id+install.FS_Platform3__c).FS_Dispenser_QTY__c;               
            }                                
            installList.add(install);
        } 
        
        if(!installList.isEmpty()){
            //Creating Apex error logger instance
            final Apex_Error_Log__c apexError=new Apex_Error_Log__c(Application_Name__c=FSConstants.FET,Class_Name__c='FSCopyEPEPToInstallationsSearchExtension',
                                                           Method_Name__c='updateQuantity',Object_Name__c=FSConstants.INSTALLATIONOBJECTNAME,
                                                           Error_Severity__c=FSConstants.MediumPriority);
            FSUtil.dmlProcessorUpdate(installList,true,apexError);
        }        
    }  
    
    /*****************************************************************
    Method: validFillNotificationEQP
    Description: validFillNotificationEQP method to find to valid fill quantity been changed and is > 0	
    New:Added this method as part of FET 2.0
    Modified:Venkat as part of FET 5.0 to optimize the code 
    *******************************************************************/  
    
    private Static void validFillNotificationEQP(final List<FS_IP_Equipment_Package__c> newList,final Map<Id,FS_IP_Equipment_Package__c> oldMap){
        //iterating the Equipment Package list
        for(FS_IP_Equipment_Package__c equipPack:newList){
            //Checking Valid Fill qty value been changed and quantity is > 0
            if(oldMap.get(equipPack.id).FS_Valid_Fill_QTY__c!=equipPack.FS_Valid_Fill_QTY__c && equipPack.FS_Valid_Fill_QTY__c>0){
                //assigning Valid Fill Notification flag value opposite to old value 
                if(oldMap.get(equipPack.id).FS_Valid_Fill_Notification_Flag__c){
                    equipPack.FS_Valid_Fill_Notification_Flag__c=false;
                }else{
                    equipPack.FS_Valid_Fill_Notification_Flag__c=true;
                }                
            }
        }       
    }    
}