force-app/main/default/objects/Apex_Error_Log__c/Apex_Error_Log__c.object-meta.xml
<CustomObject>
    <description>Custom Object used to store all the errors in exception blocks along with system.debug statements. Mostly useful in case of triggers, batch classes etc.</description>
    <label>Apex Error Log</label>
    <nameField>
        <label>Apex Error Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Errors Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Error_Log__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>Name of the Class or Component or File or Reference from where the error or exception reported.</description>
    <label>Class Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Error_Log__c/fields/Error_Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Error_Line_Number__c</fullName>
    <description>Line Number from where the exception was thrown.</description>
    <label>Error Line Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Apex_Error_Log__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Error_Log__c/fields/Error_Severity__c.field-meta.xml
<CustomField>
    <fullName>Error_Severity__c</fullName>
    <description>Error Serverity</description>
    <label>Error Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>High</fullName>
                <default>true</default>
                <label>High</label>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Cosmetic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apex_Error_Log__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <description>Name of the Function or Method from where the error or exception reported.</description>
    <label>Method Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Error_Log__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>Name of the object associated with error reported.</description>
    <label>Object Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Error_Log__c/fields/Unique_Error__c.field-meta.xml
<CustomField>
    <fullName>Unique_Error__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Unique Error</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/AELDupCheckBatchTest.cls
@isTest
public class AELDupCheckBatchTest {
    static testmethod void createApexLogger(){
        Apex_Error_Log__c aEL1 = new Apex_Error_Log__c ();
        aEL1.Method_Name__c ='Test Method';
        aEL1.Error_Line_Number__c = 3.0;
        aEL1.Error_Message__c = 'Test Message';
        aEL1.Error_Severity__c = 'Critical';
        aEL1.Object_Name__c = 'Test Object';
        aEL1.Unique_Error__c = true;
        Insert aEL1;
        
        Apex_Error_Log__c aEL2 = new Apex_Error_Log__c ();
        aEL2.Class_Name__c='Test Class';
        aEL2.Method_Name__c='Test Method';
        aEL2.Error_Line_Number__c = 3.0;
        ael2.Error_Message__c= 'Test Message';
        ael2.Error_Severity__c = 'Critical';
        ael2.Object_Name__c = 'Test Object';
        Insert aEL2;
        
        Test.startTest();
    		Database.executeBatch(new AELDupCheckBatch());
  		Test.stopTest();
	}
}