force-app/main/default/objects/Apex_Error_Log__c/Apex_Error_Log__c.object-meta.xml
<CustomObject>
    <description>Custom Object used to store all the errors in exception blocks along with system.debug statements. Mostly useful in case of triggers, batch classes etc.</description>
    <label>Apex Error Log</label>
    <nameField>
        <label>Apex Error Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Errors Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Error_Log__c/fields/Application_Name__c.field-meta.xml
<CustomField>
    <fullName>Application_Name__c</fullName>
    <description>Name of the application</description>
    <label>Application Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Error_Log__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>Name of the Class or Component or File or Reference from where the error or exception reported.</description>
    <label>Class Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Error_Log__c/fields/Error_Severity__c.field-meta.xml
<CustomField>
    <fullName>Error_Severity__c</fullName>
    <description>Error Serverity</description>
    <label>Error Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>High</fullName>
                <default>true</default>
                <label>High</label>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Cosmetic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apex_Error_Log__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <description>Name of the Function or Method from where the error or exception reported.</description>
    <label>Method Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Error_Log__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>Name of the object associated with error reported.</description>
    <label>Object Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Flavor_Change_Head__c/FS_Flavor_Change_Head__c.object-meta.xml
<CustomObject>
    <label>Flavor Change Header</label>
    <nameField>
        <displayFormat>FCP-{0000}</displayFormat>
        <label>Flavor Change Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flavor Change</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Flavor_Change_Head__c/fields/FS_Approved__c.field-meta.xml
<CustomField>
    <fullName>FS_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Confirmed Commercially Approved ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Flavor_Change_Head__c/fields/FS_CDM_Setup_Complete__c.field-meta.xml
<CustomField>
    <fullName>FS_CDM_Setup_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CDM Setup Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Flavor_Change_Head__c/fields/FS_Delivery_method__c.field-meta.xml
<CustomField>
    <fullName>FS_Delivery_method__c</fullName>
    <formula>FS_HQ_Chain__r.FS_Final_Delivery_Method__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Delivery method</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Flavor_Change_Head__c/fields/FS_isBatch__c.field-meta.xml
<CustomField>
    <fullName>FS_isBatch__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox is internally used to differentiate the records created by batch process and manual. We have certain workflows to uncheck the checkbox once the batch operation is complete.</description>
    <label>FS isBatch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Flavor_Change_Head__c/fields/FS_NDO_Approval__c.field-meta.xml
<CustomField>
    <fullName>FS_NDO_Approval__c</fullName>
    <label>NDO Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Changed to Direct Ship</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Flavor_Change_Head__c/fields/FS_Order_method__c.field-meta.xml
<CustomField>
    <fullName>FS_Order_method__c</fullName>
    <formula>FS_HQ_Chain__r.FS_Final_Order_Method__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order method</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Flavor_Change_Head__c/fields/FS_POM_Action_Complete__c.field-meta.xml
<CustomField>
    <fullName>FS_POM_Action_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>POM Action Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Flavor_Change_Head__c/fields/isWaterDasani__c.field-meta.xml
<CustomField>
    <fullName>isWaterDasani__c</fullName>
    <label>isWaterDasani</label>
    <summaryFilterItems>
        <field>FS_Flavor_Change_New__c.FS_Only_Water_Dasani__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>FS_Flavor_Change_New__c.FS_FC_Head__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/FSFlavorChangeHeaderQueueClass.cls
/***************************************************************************
 Name         : FSFlavorChangeHeaderQueueClass
 Created By   : Infosys Limited
 Description  : FSFlavorChangeHeaderQueueClass updates fields asynchronosly. This class mehtods are called from FSmassupdateflavorchanagebatchhelper
 Created Date : 23-JAN-2017
**********************************  ******************************************/
public without sharing class FSFlavorChangeHeaderQueueClass implements Queueable{
    public Set<Id> recordids;
    public List<FS_Flavor_Change_Head__c> flavorRecords;
    public static final String DISTRIBUTOR='distributor';
    public static final String BOTTLER='bottler';
      /*****************************************************************
      Method: FSFlavorChangeHeaderQueueClass
      Description: Constructor
      *******************************************************************/
    public FSFlavorChangeHeaderQueueClass(Set<Id> recordIds) {
        this.recordIds = recordIds;
        this.flavorRecords=[SELECT Id,FS_Order_method__c,FS_Delivery_method__c,FS_CDM_setup_complete__c,FS_NDO_Approval__c,
                            FS_POM_Action_Complete__c,FS_Approved__c,FS_isBatch__c,isWaterDasani__c
                            from FS_Flavor_Change_Head__c where Id IN :recordIds];
    }
      /*****************************************************************
      Method: execute
      Description: Execute method of the queue class
      *******************************************************************/
    public void execute(QueueableContext context) {
        final List<FS_Flavor_Change_Head__c> fcHeadList=new List<FS_Flavor_Change_Head__c>(); 
        String orderMethod='';
        String deliveryMethod='';
        //provide the approvals as per the flow description.
        //For file upload, making NDO Approval to "Approved"
        //For only water/dasani, escaping the below NDO approval update.
        for(FS_Flavor_Change_Head__c fcHeadId : flavorRecords){            
            FS_Flavor_Change_Head__c fcHead=new FS_Flavor_Change_Head__c();
            fcHead=fcHeadId;
            orderMethod=fcHead.FS_Order_method__c;
            deliveryMethod=fcHead.FS_Delivery_method__c;
            if(string.isNotBlank(deliveryMethod) && string.isNotBlank(orderMethod)  && fcHeadId.isWaterDasani__c==FSConstants.ZERO){
                if(deliveryMethod.containsIgnoreCase('direct') ){
                    fcHead.FS_CDM_setup_complete__c=true;
                    fcHead.FS_POM_Action_Complete__c=true;
            	}
                if((deliveryMethod.containsIgnoreCase(DISTRIBUTOR) && orderMethod.containsIgnoreCase(DISTRIBUTOR)) 
                   ||(deliveryMethod.containsIgnoreCase(BOTTLER) && orderMethod.containsIgnoreCase(BOTTLER))){
                        fcHead.FS_NDO_Approval__c='Approved';
                }
                if(deliveryMethod.containsIgnoreCase(DISTRIBUTOR) && !orderMethod.containsIgnoreCase(DISTRIBUTOR) ){
                    fcHead.FS_POM_Action_Complete__c=true;
                    fcHead.FS_NDO_Approval__c='Approved';
                    fcHead.FS_CDM_setup_complete__c=true;
                }
            }
            else if(fcHeadId.isWaterDasani__c==FSConstants.ZERO){
                fcHead.FS_POM_Action_Complete__c=true;
                fcHead.FS_NDO_Approval__c='Approved';
                fcHead.FS_CDM_setup_complete__c=true;
            }
           
            fcHead.FS_Approved__c=true;
            fcHead.FS_isBatch__c=true;
            fcHeadList.add(fcHead);
            
    	}
    	final Apex_Error_Log__c apexError=new Apex_Error_Log__c(Application_Name__c=FSConstants.FET,Class_Name__c='FSFlavorChangeHeaderQueueClass',
                                                           Method_Name__c='execute',Object_Name__c='FS_Flavor_Change_Head__c',
                                                           Error_Severity__c=FSConstants.MediumPriority);
    	FSUtil.dmlProcessorUpdate(fcHeadList,true,apexError);
    }
}