force-app/main/default/objects/Apex_Error_Log__c/Apex_Error_Log__c.object-meta.xml
<CustomObject>
    <description>Custom Object used to store all the errors in exception blocks along with system.debug statements. Mostly useful in case of triggers, batch classes etc.</description>
    <label>Apex Error Log</label>
    <nameField>
        <label>Apex Error Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Errors Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Error_Log__c/fields/Application_Name__c.field-meta.xml
<CustomField>
    <fullName>Application_Name__c</fullName>
    <description>Name of the application</description>
    <label>Application Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Error_Log__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>Name of the Class or Component or File or Reference from where the error or exception reported.</description>
    <label>Class Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Error_Log__c/fields/Error_Severity__c.field-meta.xml
<CustomField>
    <fullName>Error_Severity__c</fullName>
    <description>Error Serverity</description>
    <label>Error Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>High</fullName>
                <default>true</default>
                <label>High</label>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Cosmetic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apex_Error_Log__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <description>Name of the Function or Method from where the error or exception reported.</description>
    <label>Method Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Error_Log__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>Name of the object associated with error reported.</description>
    <label>Object Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Brandsets_Cartridges__c/FS_Brandsets_Cartridges__c.object-meta.xml
<CustomObject>
    <label>Brandset-Cartridges</label>
    <nameField>
        <displayFormat>BC-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brandset-Cartridges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/FSBrandsetCartridgeTriggerDispatcher.cls
/***************************************************************************
 Name         : FSBrandsetCartridgeTriggerDispatcher 
 Created By   : Infosys Limited
 Description  : Dispatcher for FSBrandsetCartridgeTrigger to set context variables and send trigger context variables 
                and a collection variable to hold all sobjects to be update in the same context
                to methods based on type of trigger event
 Created Date : 15-FEB-2017
****************************************************************************/
public class FSBrandsetCartridgeTriggerDispatcher extends TriggerClass{

  public static Boolean isBeforeInsertProcessing = false; 
  public static Map<Id,Sobject> sObjectsToUpdate= new Map<Id,Sobject>(); 
  
  /*****************************************************************
  Method: fSBrandsetCartridgeTriggerDispatcher
  Description: Constructor
  *******************************************************************/
  public fSBrandsetCartridgeTriggerDispatcher (final sObject obj, final Boolean isBefore, final Boolean isDelete, final Boolean isAfter,
    final Boolean isInsert, final Boolean isUpdate, final Boolean isExecuting,
    final List<sObject> newList, final Map<ID,sObject> newmap, final List<sObject>
    oldList, final Map<ID,sObject> oldmap){
        super(obj, isBefore, isDelete, isAfter, isInsert, isUpdate, isExecuting,
        newList, newmap, oldList, oldmap);
        this.MainEntry();
   }
    
    /*****************************************************************
  	Method: MainEntry
  	Description: overriding the mainentry method of superclass
	*******************************************************************/
    public override void MainEntry(){
       super.MainEntry(); // set appropriate execution context
             
          if(isBefore && isInsert && !isBeforeInsertProcessing){
            isBeforeInsertProcessing = true;
              
            FSBrandsetCartridgeTriggerHandler.beforeInsertProcess((List<FS_Brandsets_Cartridges__c>)newList,
                                                                 (List<FS_Brandsets_Cartridges__c>)oldList,
                                                                 (Map<Id,FS_Brandsets_Cartridges__c>)newMap,
                                                                 (Map<Id,FS_Brandsets_Cartridges__c>)oldMap,
                                                                 IsInsert,IsUpdate,System.isBatch(),sObjectsToUpdate);
            isBeforeInsertProcessing = false;                                                     
          }
       //As of now, this functionality is put on hold-need further confirmation to enable this
      /* if(IsAfter){
          if(IsInsert && !isAfterInsertProcessing){
            isAfterInsertProcessing=true;
            FSBrandsetCartridgeTriggerHandler.afterInsertProcess((List<FS_Brandsets_Cartridges__c>)newList,
                                                                 (List<FS_Brandsets_Cartridges__c>)oldList,
                                                                 (Map<Id,FS_Brandsets_Cartridges__c>)newMap,
                                                                 (Map<Id,FS_Brandsets_Cartridges__c>)oldMap,
                                                                 IsInsert,IsUpdate,System.isBatch(),sObjectsToUpdate);                                       
            isAfterInsertProcessing=false;
          }
       }*/
         /* if(IsUpdate && !isAfterUpdateProcessing){
             isAfterUpdateProcessing=true;
             //Call Handler FSBrandsetCartridgeTriggerHandler
             isAfterUpdateProcessing=false;                                                    
          }
       }*/
       
       
       updateSobjects();
    }
    

    /*****************************************************************
  	Method: updateSobjects
  	Description:Method to update all records that are to be update as a part of business logic in the trigger context.
    			It is placed in this class so that the update happens after all functionality are executed for the trigger object 
    			and avoid new trigger context inside current trigger context.
	*******************************************************************/
    public void updateSobjects(){    
       if(!sObjectsToUpdate.isEmpty()){
           final Apex_Error_Log__c apexError=new Apex_Error_Log__c(Application_Name__c=FSConstants.FET,Class_Name__c='FSBrandsetCartridgeTriggerDispatcher',Method_Name__c='updateSobjects',Object_Name__c='FS_Brandsets_Cartridges__c',Error_Severity__c='High');
          FSUtil.dmlProcessorUpdate(sObjectsToUpdate.values(),true,apexError);
       }
    }
    
}