force-app/main/default/objects/Apex_Error_Log__c/Apex_Error_Log__c.object-meta.xml
<CustomObject>
    <description>Custom Object used to store all the errors in exception blocks along with system.debug statements. Mostly useful in case of triggers, batch classes etc.</description>
    <label>Apex Error Log</label>
    <nameField>
        <label>Apex Error Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Errors Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Error_Log__c/fields/Application_Name__c.field-meta.xml
<CustomField>
    <fullName>Application_Name__c</fullName>
    <description>Name of the application</description>
    <label>Application Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Error_Log__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>Name of the Class or Component or File or Reference from where the error or exception reported.</description>
    <label>Class Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Error_Log__c/fields/Error_Severity__c.field-meta.xml
<CustomField>
    <fullName>Error_Severity__c</fullName>
    <description>Error Serverity</description>
    <label>Error Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>High</fullName>
                <default>true</default>
                <label>High</label>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Cosmetic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apex_Error_Log__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <description>Name of the Function or Method from where the error or exception reported.</description>
    <label>Method Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Error_Log__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>Name of the object associated with error reported.</description>
    <label>Object Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Brandset__c/FS_Brandset__c.object-meta.xml
<CustomObject>
    <description>FS_Brandset</description>
    <label>Brandset</label>
    <nameField>
        <label>Brandset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brandsets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Brandset__c/fields/FS_Available_for_commercial_use__c.field-meta.xml
<CustomField>
    <fullName>FS_Available_for_commercial_use__c</fullName>
    <formula>FS_Effective_Start_Date__c &lt;= today() &amp;&amp;(ISNULL(FS_Effective_End_Date__c )|| FS_Effective_End_Date__c &gt;today())</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Available for commercial use</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Brandset__c/fields/FS_Country__c.field-meta.xml
<CustomField>
    <fullName>FS_Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AD</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AG</fullName>
            </value>
            <value>
                <fullName>AI</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AN</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AQ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>AX</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BJ</fullName>
            </value>
            <value>
                <fullName>BL</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BN</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Brandset__c/fields/FS_Platform__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform__c</fullName>
    <description>Platform</description>
    <label>Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Brandsets_Cartridges__c/FS_Brandsets_Cartridges__c.object-meta.xml
<CustomObject>
    <label>Brandset-Cartridges</label>
    <nameField>
        <displayFormat>BC-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brandset-Cartridges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Brandsets_Cartridges__c/fields/FS_Brandset__c.field-meta.xml
<CustomField>
    <fullName>FS_Brandset__c</fullName>
    <label>Brandset</label>
    <referenceTo>FS_Brandset__c</referenceTo>
    <relationshipLabel>Cartridges</relationshipLabel>
    <relationshipName>Cartridge_Brandsets_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Brandsets_Cartridges__c/fields/FS_Cartridge__c.field-meta.xml
<CustomField>
    <fullName>FS_Cartridge__c</fullName>
    <label>Cartridge</label>
    <referenceTo>FS_Cartridge__c</referenceTo>
    <relationshipLabel>Brandsets</relationshipLabel>
    <relationshipName>Cartridge_Brandsets_Associations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Cartridge__c/FS_Cartridge__c.object-meta.xml
<CustomObject>
    <label>Cartridge</label>
    <nameField>
        <label>Cartridge Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cartridges</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Cartridge__c/fields/FS_Available_for_commercial_use__c.field-meta.xml
<CustomField>
    <fullName>FS_Available_for_commercial_use__c</fullName>
    <formula>FS_Effective_Date__c &lt;= today() &amp;&amp; (ISNULL(FS_Effective_End_Date__c )|| FS_Effective_End_Date__c &gt;today())</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Depends on Start and End Dates</inlineHelpText>
    <label>Available for Commercial Use</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Cartridge__c/fields/FS_Brand__c.field-meta.xml
<CustomField>
    <fullName>FS_Brand__c</fullName>
    <label>Brand</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Cartridge__c/fields/FS_Cartridge_type__c.field-meta.xml
<CustomField>
    <fullName>FS_Cartridge_type__c</fullName>
    <label>Cartridge type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>Speciality</fullName>
            </value>
            <value>
                <fullName>Flex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Cartridge__c/fields/FS_Country__c.field-meta.xml
<CustomField>
    <fullName>FS_Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AD</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AG</fullName>
            </value>
            <value>
                <fullName>AI</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AN</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AQ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>AX</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BJ</fullName>
            </value>
            <value>
                <fullName>BL</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BN</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Cartridge__c/fields/FS_Flavor__c.field-meta.xml
<CustomField>
    <fullName>FS_Flavor__c</fullName>
    <label>Flavor</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Cartridge__c/fields/FS_Platform__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform__c</fullName>
    <description>Platform</description>
    <label>Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2000</fullName>
            </value>
            <value>
                <fullName>3000</fullName>
            </value>
            <value>
                <fullName>7000</fullName>
            </value>
            <value>
                <fullName>8000</fullName>
            </value>
            <value>
                <fullName>9000</fullName>
            </value>
            <value>
                <fullName>9100</fullName>
            </value>
            <value>
                <fullName>3100</fullName>
            </value>
            <value>
                <fullName>6000</fullName>
            </value>
            <value>
                <fullName>7100</fullName>
            </value>
            <value>
                <fullName>6050</fullName>
                <isActive>false</isActive>
                <label>6050</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Cartridge__c/fields/FS_RFID__c.field-meta.xml
<CustomField>
    <fullName>FS_RFID__c</fullName>
    <label>RFID</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Cartridge__c/fields/FS_RFID_and_Version__c.field-meta.xml
<CustomField>
    <fullName>FS_RFID_and_Version__c</fullName>
    <externalId>true</externalId>
    <label>RFID and Version #</label>
    <length>12</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/globalValueSets/Platform_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3100</fullName>
    </customValue>
    <customValue>
        <fullName>6000</fullName>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
    </customValue>
    <customValue>
        <fullName>7100</fullName>
    </customValue>
    <customValue>
        <fullName>8000</fullName>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
    </customValue>
    <masterLabel>Platform Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FSAddCartridgeToBrandsetController.cls
/*********************************************************************************************************
Name         : FSAddCartridgeToBrandsetController 
Created By   : Infosys Limited 
Created Date : 7-Feb-2017
Usage        : Extension for FSAddCartridgeToBrandset, which is used to add cartridge records to Brandset

***********************************************************************************************************/
public without sharing class FSAddCartridgeToBrandsetController {
    
    private final static Object NULLOBJ = null;
    public static final Integer pageSize=30;
    public static final Boolean IsTrue=true;
    @TestVisible //Collection variable that holds all selected cartridge records
    private Map<Id,FS_Cartridge__c> selectedCartridgeMap;
    @TestVisible //Collection variable that holds all selected cartridge records to be removed
    private Map<Id,FS_Cartridge__c> selectedCartridgeRemoveMap;
    
    @TestVisible //Collection variable that holds all existing catridge records
    private Map<Id,FS_Cartridge__c> existingCartridgesMap;
    //Search literals of Cartridge Fields
    public String searchCartridgeName{set;get;}
    public String searchCartridgeBrand{set;get;}
    public String searchCartridgeFlavor{set;get;}
    public String searchCartridgeType{set;get;}
    public String[] searchCartridgePlatform{set;get;}
    public String searchCartridgeCountry{set;get;}
    
    
    //Collection variable that holds all available cartridge search result
    public List<CartridgeWrapper> cartridgeRecords{get;set;}
    
    //Collection variable that holds all selected cartridge search result
    public List<CartridgeWrapper> selectedCartridgeRecords{get;set;}  
   
    
    
    
    
    
    public ApexPages.StandardController standardController{get;set;}
    
    
    /****Pagination Variables Start****************************/
    
     //paginator reference for selected cartridge records
     public FSDynamicWrapperPaginator paginatorSelected {get;set;}
     
     //Collection variable(used for pagination) that holds selected cartridge search result
     public List<CartridgeWrapper> selectedCartridgesList{get;set;}
     
     //paginator reference for available cartridge records
     public FSDynamicWrapperPaginator paginatorAvailable {get;set;}
     
     //Collection variable (used for pagination) that holds available cartridge search result
     public List<CartridgeWrapper> availableCartridgesList{get;set;}
     
    /****Pagination Variables End****************************/
    
    public FSAddCartridgeToBrandsetController(ApexPages.StandardController controller) {
        
        //reference for Standard controller
        standardController=controller;
        
        //load current Brandset record details
        FS_Brandset__c thisRecord=(FS_Brandset__c )standardController.getRecord();
        
        //default platform type for the brandset record
        searchCartridgePlatform=new List<String>();
        if(String.isNotBlank(thisRecord.FS_Platform__c)){
          searchCartridgePlatform.addAll(thisRecord.FS_Platform__c.split(';'));
        }
        
        searchCartridgeCountry=thisRecord.FS_Country__c;
        
        selectedCartridgeMap=new Map<Id,FS_Cartridge__c>(); 
        selectedCartridgeRemoveMap=new Map<Id,FS_Cartridge__c>(); 
        
        existingCartridgesMap=new Map<Id,FS_Cartridge__c>();  
        
        selectedCartridgeRecords=new List<CartridgeWrapper>();  
        
        fetchExistingBrandsetCartridge();
        
        initializePaginator();
    }
    
    public void fetchExistingBrandsetCartridge(){
      //load already added cartridge records
        Set<Id> existingCartridgesIds=new Set<Id>();
        for(FS_Brandsets_Cartridges__c brandsetCartridge : retrieveAlreadyAddedCartridgeRecords()){
           existingCartridgesIds.add(brandsetCartridge.FS_Cartridge__c);
        }
        
        if(!existingCartridgesIds.isEmpty()){
           for(FS_Cartridge__c cartridge :  [SELECT Id,Name,FS_RFID_and_Version__c from FS_Cartridge__c where Id IN: existingCartridgesIds]){
               existingCartridgesMap.put(cartridge.Id,cartridge);
               selectedCartridgeRecords.add(new CartridgeWrapper(cartridge,false));
           }            
        }
    }
    
    
    public void initializePaginator(){
        this.paginatorAvailable = new FSDynamicWrapperPaginator(getCartridgeRecords());
        this.paginatorAvailable.pageNum =pageSize;
        updateAvailableData();
        
        this.paginatorSelected = new FSDynamicWrapperPaginator(selectedCartridgeRecords);
        this.paginatorSelected.pageNum =pageSize ;
        updateSelectedData();
    }
    
    /*****************************************************************
  	Method: search
  	Description: Method called by Search cartridge to update VF's view state
	*******************************************************************/
    public PageReference search(){
     getCartridgeRecords();
     return null;
    }
    
    public PageReference backToDetailPage(){
     return new PageReference('/'+standardController.getId());
    }
    
    public Pagereference  addSelectedCartridges(){
     
     getSelectedCartridges();
     
     //add existing cartridge records
     for(FS_Cartridge__c cartridge :  existingCartridgesMap.values()){
         selectedCartridgeRecords.add(new CartridgeWrapper(cartridge,false));
     }
     //add selected cartridge records
     for(FS_Cartridge__c cartridge :  selectedCartridgeMap.values()){
         selectedCartridgeRecords.add(new CartridgeWrapper(cartridge,false));
     }
     
     /*** Filter duplicate cartridge Start*********************************/
     Set<FS_Cartridge__c> uniqueCartridges = new Set<FS_Cartridge__c>();
     List<FS_Cartridge__c> result = new List<FS_Cartridge__c>();
     for(CartridgeWrapper wrpItem : selectedCartridgeRecords){
       uniqueCartridges.add(wrpItem.cartridge);
     }
     
     if(!uniqueCartridges.isEmpty()){
        selectedCartridgeRecords.clear();
        for(FS_Cartridge__c cartridge : uniqueCartridges){
           selectedCartridgeRecords.add(new CartridgeWrapper(cartridge,false));
        }
     }
     /*** Filter duplicate cartridge End*********************************/
     
     paginatorSelected = new FSDynamicWrapperPaginator(selectedCartridgeRecords);
     paginatorSelected.pageNum =pageSize ;
     updateSelectedData();
     
     getCartridgeRecords();
     
     return null;
    }
  
    /*****************************************************************
  	Method: saveCartridgesToBrandset
  	Description: Method call by add cartridges method
	*******************************************************************/
    public Pagereference saveCartridgesToBrandset(){
      
      List<FS_Brandsets_Cartridges__c> existingBrandsetCartridges= retrieveAlreadyAddedCartridgeRecords();
      
      List<FS_Brandsets_Cartridges__c > brandsetCartridgeTobeCreated= new List<FS_Brandsets_Cartridges__c >(); 
      
      for(CartridgeWrapper wrpItem :  selectedCartridgeRecords){
             FS_Brandsets_Cartridges__c brandsetCartridge=new FS_Brandsets_Cartridges__c();
               brandsetCartridge.FS_Brandset__c=standardController.getId();
               brandsetCartridge.FS_Cartridge__c=wrpItem.cartridge.Id;
               brandsetCartridgeTobeCreated.add(brandsetCartridge);
      }
      
      //Deleting already existing brandset cartridges        
      if(!existingBrandsetCartridges.isEmpty()){
          final Apex_Error_Log__c apexError=new Apex_Error_Log__c(Application_Name__c=FSConstants.FET,Class_Name__c='FSAddCartridgeToBrandsetController',
                                                           Method_Name__c='addCartridgesToBrandset',Object_Name__c='FS_Brandsets_Cartridges__c',
                                                           Error_Severity__c=FSConstants.MediumPriority);
           FSUtil.dmlProcessorDelete(existingBrandsetCartridges,true,apexError);
      }
      
      if(!brandsetCartridgeTobeCreated.isEmpty()){
          final Apex_Error_Log__c apexError=new Apex_Error_Log__c(Application_Name__c='FET',Class_Name__c='FSAddCartridgeToBrandsetController',
                                                           Method_Name__c='addCartridgesToBrandset',Object_Name__c='FS_Brandsets_Cartridges__c',
                                                           Error_Severity__c='High');
           FSUtil.dmlProcessorInsert(brandsetCartridgeTobeCreated,true,apexError);
      }   
      
       return standardController.view();
    }
    
    public void getSelectedCartridgesToRemove(){
        if(selectedCartridgeRecords!=NULLOBJ){
            for(CartridgeWrapper wrpItem : selectedCartridgeRecords){
                if(wrpItem.selected){
                  selectedCartridgeRemoveMap.put(wrpItem.cartridge.Id,wrpItem.cartridge); 
                  existingCartridgesMap.remove(wrpItem.cartridge.Id);
                }
                else{
                   selectedCartridgeRemoveMap.remove(wrpItem.cartridge.Id);
                }
            }
        }
    }
    
    /*****************************************************************
  	Method: removeCartridges
  	Description: Method call to remove brandset Cartridge records from the brandset 
	*******************************************************************/
    public Pagereference removeCartridges(){
      getSelectedCartridgesToRemove();
      
      List<CartridgeWrapper> addedCartridges=new List<CartridgeWrapper>();
      for(CartridgeWrapper wrpItem : selectedCartridgeRecords){
         if(!selectedCartridgeRemoveMap.containsKey(wrpItem.cartridge.Id)){
           addedCartridges.add(new CartridgeWrapper(wrpItem.cartridge,false));
         }
      }
      
      selectedCartridgeRecords.clear();
      selectedCartridgeRecords.addAll(addedCartridges);
      
      paginatorSelected = new FSDynamicWrapperPaginator(selectedCartridgeRecords);
      paginatorSelected.pageNum =pageSize ;
      updateSelectedData();
      
      selectedCartridgeMap = new Map<Id,FS_Cartridge__c>();  //loose view state for cartridge selected records
      getCartridgeRecords();
      
      return null;
    }
   
    /*****************************************************************
  	Method: getCartridgeRecords
  	Description: cartridge search result
	*******************************************************************/
    public List<CartridgeWrapper> getCartridgeRecords(){
    
        getSelectedCartridges();
        
        cartridgeRecords=new List<CartridgeWrapper>();
        
        //Collection to hold records that are displayed in selected cartridge section
        Map<Id,FS_Cartridge__c>  displayedSelectedCartridgeMap=new Map<Id,FS_Cartridge__c>();
        
        for(CartridgeWrapper wrpItem : selectedCartridgeRecords){
          displayedSelectedCartridgeMap.put(wrpItem.cartridge.Id,wrpItem.cartridge);
        }
        
        for(FS_Cartridge__c cartridge : fetchCartridgesSOQL()){
             if(!selectedCartridgeMap.containsKey(cartridge.Id)){
                if(!displayedSelectedCartridgeMap.containsKey(cartridge.Id)){
                   cartridgeRecords.add(new CartridgeWrapper(cartridge,false));
                }
             }
             else{
                if(!displayedSelectedCartridgeMap.containsKey(cartridge.Id)){
                   cartridgeRecords.add(new CartridgeWrapper(cartridge,true));
                }
             }
        }
        
        paginatorAvailable = new FSDynamicWrapperPaginator(cartridgeRecords);
        paginatorAvailable.pageNum =pageSize;
        updateAvailableData();
        
        return cartridgeRecords;
      
    }
    
    /*****************************************************************
  	Method: getSelectedCartridges
  	Description: populate collection to hold selected cartridge from search result
	*******************************************************************/
    public void getSelectedCartridges(){
        if(cartridgeRecords!=NULLOBJ){
            for(CartridgeWrapper wrpItem : cartridgeRecords){
                if(wrpItem.selected){
                  selectedCartridgeMap.put(wrpItem.cartridge.Id,wrpItem.cartridge); 
                }
                else{
                   selectedCartridgeMap.remove(wrpItem.cartridge.Id);
                }
            }
        }
    }
    
    /*****************************************************************
  	Method: fetchCartridgesSOQL
  	Description: Search Cartridge records Based on User Input
	*******************************************************************/
    public List<FS_Cartridge__c> fetchCartridgesSOQL(){ 
     
     //search literals
     String cartridgePlatform;
     String cartridgeCountry;
     List<String> cartridgeCountries=new List<String>();
     List<String> cartridgePlatforms=new List<String>();
     
     if(!searchCartridgePlatform.isEmpty()){
          cartridgePlatform='';
           for(String platform : searchCartridgePlatform){
              cartridgePlatform+= '\''+platform+ '\''+',';
           } 
           
           if(cartridgePlatform.lastIndexOf(',')!=-1){
             cartridgePlatform=cartridgePlatform.removeEnd(',');
           }
           
     }
     
     if(String.isNotBlank(searchCartridgeCountry)){
        if(searchCartridgeCountry.contains(';')){
           cartridgeCountries.addAll(searchCartridgeCountry.split(';'));
           cartridgeCountry='';
           for(String country : cartridgeCountries){
              cartridgeCountry+= '\''+country+ '\''+',';
           }
           cartridgeCountry=cartridgeCountry.removeEnd(',');
        }
        else{
          cartridgeCountry='\''+searchCartridgeCountry+ '\'';
        }
       
     }
     
     
     Date todaysDate=Date.today();
     
     String searchquery= 'Select Id,Name,FS_Platform__c,FS_Country__c,FS_Brand__c,FS_Flavor__c,FS_RFID__c,'
                        +'FS_RFID_and_Version__c,FS_Cartridge_type__c,FS_Available_for_commercial_use__c from FS_Cartridge__c WHERE FS_Available_for_commercial_use__c  = :isTrue ';
     
    
     if(String.isNotBlank(searchCartridgeName)){
       searchquery += ' AND Name LIKE \''+searchCartridgeName+'%\' ';
     }
     if(String.isNotBlank(searchCartridgeBrand)){
       searchquery += ' AND FS_Brand__c LIKE \''+searchCartridgeBrand+'%\' ';
     }  
     if(String.isNotBlank(searchCartridgeFlavor)){
       searchquery += ' AND FS_Flavor__c LIKE \''+searchCartridgeFlavor+'%\' ';
     }
     if(String.isNotBlank(cartridgePlatform)){
       searchquery += ' AND FS_Platform__c includes ('+cartridgePlatform+') ';
     }
     if(String.isNotBlank(cartridgeCountry)){
       searchquery += ' AND FS_Country__c includes ('+cartridgeCountry+') '; 
     } 
     if(String.isNotBlank(searchCartridgeType)){
       searchquery += ' AND FS_Cartridge_type__c LIKE \''+searchCartridgeType+'%\' ';
     }         
     searchquery +=' ORDER BY Name LIMIT 2000 ';  
     
     List<SObject> searchList=Database.query(searchquery);
     return (List<FS_Cartridge__c>)searchList;
     
    }

    /*****************************************************************
  	Method: retrieveAlreadyAddedCartridgeRecords
  	Description: brandset cartridge records for the brandset
	*******************************************************************/
    public List<FS_Brandsets_Cartridges__c> retrieveAlreadyAddedCartridgeRecords(){
     
     return [SELECT ID,Name,FS_Brandset__c,FS_Cartridge__c FROM FS_Brandsets_Cartridges__c 
             WHERE FS_Brandset__c =:standardController.getId() ORDER BY CreatedDate DESC];
    }
    
    
    public List<SelectOption> getCartridgeTypes(){ 
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('','--None--'));   
        
        // Adding picklist values to the select list
        for(Schema.PicklistEntry entry : FSUtil.getFieldPicklistValues(FS_Cartridge__c.SObjectType,'FS_Cartridge_type__c')){
               options.add(new SelectOption(entry.getValue(), entry.getLabel()));
        }
        
        return options; 
    }
    
    
    /**************Pagination Module Start***********************************/
    
    public PageReference updateAvailableData(){
        availableCartridgesList=new List<CartridgeWrapper>();
        for(Object obj: paginatorAvailable.populateResults()){
          this.availableCartridgesList.add((CartridgeWrapper) obj);
        }
        
        return null;
    }
    public PageReference availableFirst() {
      
      paginatorAvailable.First();
      updateAvailableData();
      return null;
    }
         
    public PageReference availablePrevious() { 
      
      paginatorAvailable.Previous();
      updateAvailableData();
      return null;
    }
         
    public PageReference availableNext() { 
      
      paginatorAvailable.Next();
      updateAvailableData();
      return null;
    }
         
    public PageReference availableEnd(){
       
      paginatorAvailable.Last();
      updateAvailableData();
      return null;
    }
         
    public Boolean getAvailableDisablePrevious() {
      return paginatorAvailable.getDisablePrevious();
    }
     
    public Boolean getAvailableDisableNext() {
      return paginatorAvailable.getDisableNext();
    }
    
    
    /*********************************************/
    
    public PageReference updateSelectedData(){
        selectedCartridgesList =new List<CartridgeWrapper>();
        for(Object obj: paginatorSelected.populateResults()){
          this.selectedCartridgesList.add((CartridgeWrapper) obj);
        }
        
        return null;
    }
    public PageReference selectedFirst() {
      paginatorSelected.First();
      updateSelectedData();
      return null;
    }
         
    public PageReference selectedPrevious() { 
      paginatorSelected.Previous();
      updateSelectedData();
      return null;
    }
         
    public PageReference selectedNext() { 
      paginatorSelected.Next();
      updateSelectedData();
      return null;
    }
         
    public PageReference selectedEnd(){ 
      paginatorSelected.Last();
      updateSelectedData();
      return null;
    }
         
    public Boolean getSelectedDisablePrevious() { 
      return paginatorSelected.getDisablePrevious();
    }
     
    public Boolean getSelectedDisableNext() { 
      return paginatorSelected.getDisableNext();
    }
    
           
    /**************Pagination Module End***********************************/ 
    
    /*****************************************************************
  	Method: CartridgeWrapper
  	Description: Wrapper Class to facilitate Cartridge Selection 
	*******************************************************************/
    public class CartridgeWrapper{
        public Boolean selected{set;get;}
        public FS_Cartridge__c cartridge {set;get;}
        public CartridgeWrapper(FS_Cartridge__c cartridgeIntance,Boolean selectCheck){
            selected=selectCheck;
            cartridge =cartridgeIntance;            
        }
        
    }
     
}