force-app/main/default/objects/Disable_Trigger__c/Disable_Trigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is only used in case there is a need to deactivate a trigger during data migration. The triggers must be kept activated at all times...</description>
    <label>Disable Trigger</label>
</CustomObject>

force-app/main/default/objects/Shipping_Form__c/Shipping_Form__c.object-meta.xml
<CustomObject>
    <label>Shipping Form</label>
    <nameField>
        <label>Shipping Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipping Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Form__c/fields/IC_Code__c.field-meta.xml
<CustomField>
    <fullName>IC_Code__c</fullName>
    <label>IC Code</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1795457</fullName>
            </value>
            <value>
                <fullName>1795458</fullName>
            </value>
            <value>
                <fullName>1795459</fullName>
            </value>
            <value>
                <fullName>1795460</fullName>
            </value>
            <value>
                <fullName>1700710</fullName>
            </value>
            <value>
                <fullName>1700711</fullName>
            </value>
            <value>
                <fullName>1700712</fullName>
            </value>
            <value>
                <fullName>1700713</fullName>
            </value>
            <value>
                <fullName>1700714</fullName>
            </value>
            <value>
                <fullName>1700715</fullName>
            </value>
            <value>
                <fullName>1700716</fullName>
            </value>
            <value>
                <fullName>1700717</fullName>
            </value>
            <value>
                <fullName>1700718</fullName>
            </value>
            <value>
                <fullName>1700719</fullName>
            </value>
            <value>
                <fullName>1700720</fullName>
            </value>
            <value>
                <fullName>1700721</fullName>
            </value>
            <value>
                <fullName>1702648</fullName>
            </value>
            <value>
                <fullName>46100</fullName>
            </value>
            <value>
                <fullName>46101</fullName>
            </value>
            <value>
                <fullName>46099</fullName>
            </value>
            <value>
                <fullName>46127</fullName>
            </value>
            <value>
                <fullName>46128</fullName>
            </value>
            <value>
                <fullName>46126</fullName>
            </value>
            <value>
                <fullName>46102</fullName>
            </value>
            <value>
                <fullName>46129</fullName>
            </value>
            <value>
                <fullName>46401</fullName>
            </value>
            <value>
                <fullName>46379</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/IC_Code__c.field-meta.xml
<CustomField>
    <fullName>IC_Code__c</fullName>
    <label>IC Code</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1795457</fullName>
            </value>
            <value>
                <fullName>1795458</fullName>
            </value>
            <value>
                <fullName>1795459</fullName>
            </value>
            <value>
                <fullName>1795460</fullName>
            </value>
            <value>
                <fullName>1700710</fullName>
            </value>
            <value>
                <fullName>1700711</fullName>
            </value>
            <value>
                <fullName>1700712</fullName>
            </value>
            <value>
                <fullName>1700713</fullName>
            </value>
            <value>
                <fullName>1700714</fullName>
            </value>
            <value>
                <fullName>1700715</fullName>
            </value>
            <value>
                <fullName>1700716</fullName>
            </value>
            <value>
                <fullName>1700717</fullName>
            </value>
            <value>
                <fullName>1700718</fullName>
            </value>
            <value>
                <fullName>1700719</fullName>
            </value>
            <value>
                <fullName>1700720</fullName>
            </value>
            <value>
                <fullName>1700721</fullName>
            </value>
            <value>
                <fullName>1702648</fullName>
            </value>
            <value>
                <fullName>46100</fullName>
            </value>
            <value>
                <fullName>46101</fullName>
            </value>
            <value>
                <fullName>46099</fullName>
            </value>
            <value>
                <fullName>46127</fullName>
            </value>
            <value>
                <fullName>46128</fullName>
            </value>
            <value>
                <fullName>46126</fullName>
            </value>
            <value>
                <fullName>46102</fullName>
            </value>
            <value>
                <fullName>46129</fullName>
            </value>
            <value>
                <fullName>46401</fullName>
            </value>
            <value>
                <fullName>46379</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ShippingFormTriggerHandlerTest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class ShippingFormTriggerHandlerTest {
    static Shipping_Form__c shippingForm1,shippingForm2;
    static User user1;
    static User user2;
    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        user1 =FSTestUtil.createUser(null,1,FSConstants.dispenserManufacturerProfile,true);
   
        system.runAs(user1){
            shippingForm1 = FSTestUtil.createShippingForm(true);
            user1.IC_Code__c = '1234;5463';
            update user1;
        }    
    }
    
 @testSetup  
     static void mytestSetup() {
       Disable_Trigger__c disableTriggerSetting = new Disable_Trigger__c();
       
       disableTriggerSetting.name='ShippingFormTriggerHandler';
       disableTriggerSetting.IsActive__c=true;
       disableTriggerSetting.Trigger_Name__c='ShippingFormTrigger' ; 
       insert disableTriggerSetting;   
      }    
}