force-app/main/default/objects/Account/fields/BOE_Migrated_Outlet__c.field-meta.xml
<CustomField>
    <fullName>BOE_Migrated_Outlet__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Migrated Outlet</description>
    <label>Migrated Outlet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Bottlers_Name__c.field-meta.xml
<CustomField>
    <fullName>Bottlers_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Bottlers  Associated with Contacts.</inlineHelpText>
    <label>Bottlers Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>FS Bottler</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Bottlers Name)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Chain__c.field-meta.xml
<CustomField>
    <fullName>FS_Chain__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chain</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for Chain.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Chain</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Headquarters/Outlets</relationshipLabel>
    <relationshipName>Chains</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Shipping_City_Int__c.field-meta.xml
<CustomField>
    <fullName>FS_Shipping_City_Int__c</fullName>
    <label>Outlet City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Shipping_Country_Int__c.field-meta.xml
<CustomField>
    <fullName>FS_Shipping_Country_Int__c</fullName>
    <label>Outlet Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>GR</fullName>
            </value>
            <value>
                <fullName>IE</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>JP</fullName>
            </value>
            <value>
                <fullName>LU</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NL</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TR</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Shipping_State_Province_INT__c.field-meta.xml
<CustomField>
    <fullName>FS_Shipping_State_Province_INT__c</fullName>
    <label>Outlet State/Province</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Shipping_Street_Int__c.field-meta.xml
<CustomField>
    <fullName>FS_Shipping_Street_Int__c</fullName>
    <label>Outlet Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Shipping_Zip_Postal_Code_Int__c.field-meta.xml
<CustomField>
    <fullName>FS_Shipping_Zip_Postal_Code_Int__c</fullName>
    <label>Outlet Zip/Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Google_Messages__c/Google_Messages__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of messages used in Address Validation.</description>
    <label>Google Validation Messages</label>
</CustomObject>

force-app/main/default/objects/Google_Messages__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>Description of the Error message.</description>
    <label>Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Google_Messages__c/fields/Error_type__c.field-meta.xml
<CustomField>
    <fullName>Error_type__c</fullName>
    <description>Used to define the error types</description>
    <label>Error type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FSOutletAddressValidationBatchTest.cls
@isTest
public class FSOutletAddressValidationBatchTest {
    private static Account accchain,accHQ,bottler;
    @testSetup 
    private static void testFSOutletAddressValidationBatch (){
        Test.startTest();
        final List<Account> accounts = new List<Account>();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        final Map<String,Schema.RecordTypeInfo> rtMapByName = Schema.SObjectType.Account.getRecordTypeInfosByName();
        final Schema.RecordTypeInfo rtByName =  rtMapByName.get(Label.INTERNATIONAL_OUTLET_RECORD_TYPE);
        final string outletRecordId = rtByName.getRecordTypeId();
        
        bottler=FSTestUtil.createTestAccount('Test Bottler 1',FSConstants.RECORD_TYPE_BOTLLER,true);
        accchain = FSTestUtil.createTestAccount('Test Chain 1',FSConstants.RECORD_TYPE_CHAIN,true);   
        
        // Create Headquarters
        accHQ = FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,false);
        accHQ.FS_Chain__c = accchain.Id;
        insert accHQ;
        
        final Google_Messages__c googleMsg = new Google_Messages__c();
        googleMsg.Error_Message__c='The Outlet Address  has no matches, a minimum of City and Country is required.';
        googleMsg.Error_type__c='ZERO_RESULTS';
        googleMsg.Name='ZERO_RESULTS';
        insert googleMsg;
        
        for (integer i=0; i<50;i++){
            final Account acc = new Account();
            acc.Name='testName'+i;
            acc.FS_Shipping_City_Int__c='city';
            acc.FS_Shipping_Street_Int__c='street';
            acc.FS_Shipping_State_Province_INT__c='state';
            acc.FS_Shipping_Country_Int__c='AU';
            acc.FS_Shipping_Zip_Postal_Code_Int__c='110017';            
            acc.RecordTypeId=outletRecordId;
            acc.Bottlers_Name__c=bottler.Id;
            acc.BOE_Migrated_Outlet__c = true;
            accounts.add(acc);
        }
        
        insert accounts;
        
        
        Test.stopTest();
    }
    private static testmethod void exceptionRecords()
    {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator1());
        
        final FSOutletAddressValidationBatch batchObj = new FSOutletAddressValidationBatch();
        Database.executeBatch(batchObj);
        
        Test.stopTest();
    }
    private static testmethod void validRecords()
    {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        
        final FSOutletAddressValidationBatch batchObj = new FSOutletAddressValidationBatch();
        Database.executeBatch(batchObj);
        
        Test.stopTest();
    }
    private static testmethod void exception()
    {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator2());
        
        final FSOutletAddressValidationBatch batchObj = new FSOutletAddressValidationBatch();
        Database.executeBatch(batchObj);
        
        Test.stopTest();
    }
}