force-app/main/default/objects/Account/fields/Bottlers_Name__c.field-meta.xml
<CustomField>
    <fullName>Bottlers_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Bottlers  Associated with Contacts.</inlineHelpText>
    <label>Bottlers Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>FS Bottler</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Bottlers Name)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Warehouse_Country__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Country__c</fullName>
    <description>2 Letter Country code</description>
    <label>Warehouse Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>IE</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>JP</fullName>
            </value>
            <value>
                <fullName>LU</fullName>
            </value>
            <value>
                <fullName>NL</fullName>
            </value>
            <value>
                <fullName>- Not Applicable -</fullName>
                <default>true</default>
                <label>- Not Applicable -</label>
            </value>
            <value>
                <fullName>NZ</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TR</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Equip_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Equip_Type__c</fullName>
    <description>equip type</description>
    <inlineHelpText>This is the JDE Equipment Type value</inlineHelpText>
    <label>Equipment Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <description>Outlet field.</description>
    <label>Outlet</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 3) OR (2 AND 4 AND (5 OR 7)) OR (2 AND 4 AND 6)</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for Outlet.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Outlet</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Outlet</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>7000, 8000, 9000, CCNA Dispenser</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Dispenser</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value>No, Yes</value>
        </filterItems>
        <filterItems>
            <field>Account.Is_Default_FET_International_Outlet__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlet Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Serial_Number2__c.field-meta.xml
<CustomField>
    <fullName>FS_Serial_Number2__c</fullName>
    <description>Serial Number/Asset Tag.</description>
    <label>JDE Serial Number/Asset Tag</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/isDefaultOutlet__c.field-meta.xml
<CustomField>
    <fullName>isDefaultOutlet__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isDefaultOutlet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Outlet_Country__c.field-meta.xml
<CustomField>
    <fullName>Outlet_Country__c</fullName>
    <formula>FS_Outlet__r.ShippingCountry</formula>
    <label>Outlet Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Outlet_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Outlet_Zip_Code__c</fullName>
    <formula>FS_Outlet__r.ShippingPostalCode</formula>
    <label>Outlet Zip Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Warehouse_Country__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Country__c</fullName>
    <label>â€‹Warehouse Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Luxembourg</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
            <value>
                <fullName>Philippines</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Switzerland</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Warehouse_Country_formula__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Country_formula__c</fullName>
    <formula>TEXT(Warehouse_Details__r.Warehouse_Country__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Warehouse Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Warehouse_Country_New__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Country_New__c</fullName>
    <label>Warehouse Country.</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Luxembourg</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
            <value>
                <fullName>Philippines</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Switzerland</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Warehouse_Name_formula__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Name_formula__c</fullName>
    <formula>Warehouse_Details__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Warehouse Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EmailTriggerHelper.cls
/******************************
Name         : EmailTriggerHelper
Created By   : Lavanya & Team
Description  : Email Helper class
Created Date : July 19, 2016

******************************/

public with sharing class EmailTriggerHelper{
    public static void sendEmailContact(List<Id> oDId){
        try{
                String response='';
                                
                //Find od
                 List<FS_Outlet_Dispenser__c> oDList = [Select isDefaultOutlet__c, Outlet_Zip_Code__c,Outlet_Country__c, Warehouse_Name_formula__c,
                                                        Warehouse_Country_formula__c,FS_Outlet__r.ShippingPostalCode, FS_Serial_Number2__c,
                                                        FS_Outlet__r.shippingCountry, FS_Outlet__r.Bottlers_Name__c ,FS_Equip_Type__c,
                                                        Warehouse_Country_New__c From FS_Outlet_Dispenser__c
                                                        WHERE ID =: oDId];
                                                        
                system.debug('In email trigger helper');  
                          
                Set<String> botAccount = new Set<String>(); 
                Set<String> outCountry = new Set<String>(); 
                for(FS_Outlet_Dispenser__c temp : oDList){
                    botAccount.add( temp.FS_Outlet__r.bottlers_name__c);
                    outCountry.add(temp.Outlet_Country__c);
                }
                //getting contact of bottler
                List<Contact> contactList= [Select id,Email,MailingCountry,Warehouse_Country__c,MailingPostalCode ,account.name from Contact where accountid in :botAccount];
                List<String> sendTo = new List<String>();
                String[] ccEmail;
                String equipmentType;                
                for(FS_Outlet_Dispenser__c od:oDList){
                                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                                equipmentType=od.FS_Equip_Type__c;
                        for(Contact c:contactList){
                            if(c.Warehouse_Country__c==od.FS_Outlet__r.shippingCountry){
                                sendTo.add(c.Email);
                                ccEmail=new String[]{UserInfo.getUserEmail()};
                             }
                       }        
                                //Recipients
                                mail.setToAddresses(sendTo);
                                mail.setCcAddresses(ccEmail);
                                mail.setSenderDisplayName('Coca-Cola');
                                //Subject
                                mail.setSubject('FET International Dispenser Delivered' );
                                //Body
                                //system.debug('In for loop'+c.email);
                                String body= Label.Email_Subject;
                                       body=body+'<br>Dispenser with serial number '+od.FS_Serial_Number2__c;
                                       body=body+' a Series '+equipmentType
                                            +' dispenser has been delivered to '+ od.Warehouse_Name_formula__c
                                            +' in '+od.Warehouse_Country_formula__c
                                            +'<br><br><b>This dispenser is available for Assignment to an Outlet. </b><br>';      
                                mail.setHtmlBody(body);                               

                                    Messaging.SendEmailResult[] resultMail = Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
                                    if(resultMail[0].isSuccess()){ response = 'email sent successfully';  }
                                    else{response = resultMail[0].getErrors().get(0).getMessage();}
                                
                           }
                      
             } catch(exception e){
                System.debug('Exception in last try catch(): ' + e.getMessage());
                ApexErrorLogger.addApexErrorLog('FET','EmailTriggerHelper','sendEmailContact','NA','Medium',e,'NA');
             }
      }
}