force-app/main/default/objects/Account/fields/Bottlers_Name__c.field-meta.xml
<CustomField>
    <fullName>Bottlers_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Bottlers  Associated with Contacts.</inlineHelpText>
    <label>Bottlers Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>FS Bottler</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts (Bottlers Name)</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_ACN__c.field-meta.xml
<CustomField>
    <fullName>FS_ACN__c</fullName>
    <description>SAP Legacy Customer #</description>
    <inlineHelpText>ACN is an auto generated field for International Outlets.</inlineHelpText>
    <label>ACN</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Is_Address_Validated__c.field-meta.xml
<CustomField>
    <fullName>FS_Is_Address_Validated__c</fullName>
    <inlineHelpText>Checked when the Address field is validated</inlineHelpText>
    <label>Is Address Validated?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Default_FET_International_Outlet__c.field-meta.xml
<CustomField>
    <fullName>Is_Default_FET_International_Outlet__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Default INT outlet used to assign the ODs when OD not assigned to actual outlet.</inlineHelpText>
    <label>Is Default FET International Outlet?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Brand_Set__c.field-meta.xml
<CustomField>
    <fullName>Brand_Set__c</fullName>
    <label>Brand Set</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Warehouse_Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>CAN Default Collection</fullName>
            </value>
            <value>
                <fullName>CAN McDonalds Collection</fullName>
            </value>
            <value>
                <fullName>GER Default Collection</fullName>
            </value>
            <value>
                <fullName>FRA Default Collection</fullName>
            </value>
            <value>
                <fullName>NZ Default Collection</fullName>
            </value>
            <value>
                <fullName>SGP Default Collection</fullName>
            </value>
            <value>
                <fullName>Gandalf GER Collection</fullName>
            </value>
            <value>
                <fullName>Gandalf JAPAN Collection</fullName>
            </value>
            <value>
                <fullName>Bluebird CAN Default</fullName>
            </value>
            <value>
                <fullName>GB Default Collection</fullName>
            </value>
            <value>
                <fullName>LUX Default Collection</fullName>
            </value>
            <value>
                <fullName>BE Default Collection</fullName>
            </value>
            <value>
                <fullName>Ireland Default Collection</fullName>
            </value>
            <value>
                <fullName>TUK Default Collection</fullName>
            </value>
            <value>
                <fullName>Spain Default Collection</fullName>
            </value>
            <value>
                <fullName>Denmark Default Collection</fullName>
            </value>
            <value>
                <fullName>Sweden Default Collection</fullName>
            </value>
            <value>
                <fullName>Netherlands Default Collection</fullName>
            </value>
            <value>
                <fullName>Japan Default Collection</fullName>
            </value>
            <value>
                <fullName>Thailand Default Collection</fullName>
            </value>
            <value>
                <fullName>Philippines Default Collection</fullName>
            </value>
            <value>
                <fullName>Australia Default Collection</fullName>
            </value>
            <value>
                <fullName>Switzerland Default Collection</fullName>
            </value>
            <value>
                <fullName>MA Default Collection</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Serial_Number2__c.field-meta.xml
<CustomField>
    <fullName>FS_Serial_Number2__c</fullName>
    <description>Serial Number/Asset Tag.</description>
    <label>JDE Serial Number/Asset Tag</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FSInt_Dispenser_Type__c.field-meta.xml
<CustomField>
    <fullName>FSInt_Dispenser_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dispenser Model</label>
    <referenceTo>Dispenser_Model__c</referenceTo>
    <relationshipLabel>Outlet Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Shipping_Form__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Form</label>
    <referenceTo>Shipping_Form__c</referenceTo>
    <relationshipLabel>Outlet Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Warehouse_Country__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Country__c</fullName>
    <label>â€‹Warehouse Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Luxembourg</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
            <value>
                <fullName>Philippines</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Switzerland</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Warehouse_Details__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse Details</label>
    <referenceTo>Warehouse_Details__c</referenceTo>
    <relationshipLabel>Outlet Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Warehouse_Details__c/Warehouse_Details__c.object-meta.xml
<CustomObject>
    <description>To store Warehouse Name, Warehouse Country &amp; Brandset values</description>
    <label>Warehouse Details</label>
    <nameField>
        <label>Warehouse Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouse Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Warehouse_Details__c/fields/Brand_Set__c.field-meta.xml
<CustomField>
    <fullName>Brand_Set__c</fullName>
    <label>Brand Set</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Warehouse_Details__c/fields/Warehouse_Country__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Country__c</fullName>
    <label>Warehouse Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CH</fullName>
            </value>
            <value>
                <fullName>CL</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DK</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>GR</fullName>
            </value>
            <value>
                <fullName>IE</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>JP</fullName>
            </value>
            <value>
                <fullName>LU</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MY</fullName>
            </value>
            <value>
                <fullName>NL</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>TR</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FET_OutletAssignmentCtrlTest.cls
/**
* This class contains unit tests for validating the behavior of Apex classes
* and triggers.
*
* Unit tests are class methods that verify whether a particular piece
* of code is working properly. Unit test methods take no arguments,
* commit no data to the database, and are flagged with the testMethod
* keyword in the method definition.
*
* All test methods in an organization are executed whenever Apex code is deployed
* to a production organization to confirm correctness, ensure code
* coverage, and prevent regressions. All Apex classes are
* required to have at least 75% code coverage in order to be deployed
* to a production organization. In addition, all triggers must have some code coverage.
* 
* The @isTest class annotation indicates this class only contains test
* methods. Classes defined with the @isTest annotation do not count against
* the organization size limit for all Apex scripts.
*
* See the Apex Language Reference for more information about Testing and Code Coverage.
*/
/**************************************************************************************
Apex Class Name     : FET_OutletAssignmentCtrlTest
Version             : 1.0
Function            : This test class is for FET_OutletAssignmentCtrl Class code coverage. 
Modification Log    : 
* Developer         :    Date              Description
* ----------------------------------------------------------------------------                 
* Infosys             			          Original Version 
*					  05/29/2018		  Removed usage of OutboundServiceDetails__c customSetting as part of FOT project
*************************************************************************************/
@isTest
private class FET_OutletAssignmentCtrlTest {
    public static Shipping_Form__c shippingForm;
    public static Dispenser_Model__c dispenserModel;
    public static User coordinatorUser;
    public static FS_Outlet_Dispenser__c dispenser;
    public static Account headquartersAcc,normalAcc,bottler,bottlerAcc,chainAccount,outlet2;
    public static FET_OutletAssignmentCtrl outletAssgnmntCtrl1;
    public static FS_Outlet_Dispenser__c outletDispenserInt1;
    public static ApexPages.StandardController stdCont1;
    public static Warehouse_Details__c war1;
    public static final string IDS='id';
    public static final string ACN='7687687678';
    private static Profile fetSysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_FETADMIN);
    
    private static void createTestData(){
        
        headquartersAcc = FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,true);
        chainAccount = FSTestUtil.createTestAccount('Test Chain 1',FSConstants.RECORD_TYPE_CHAIN,false);
        chainAccount.FS_ACN__c = '76876876ICH';
        insert chainAccount; 
        normalAcc = FSTestUtil.createAccountOutlet('Test Outlet International',FSConstants.RECORD_TYPE_OUTLET,headquartersAcc.id, false);
        bottler=FSTestUtil.createTestAccount('Test Bottler 1',FSConstants.RECORD_TYPE_BOTLLER,true);
        normalAcc.Bottlers_Name__c = bottler.id;       
        normalAcc.RecordTypeId=FSConstants.RECORD_TYPE_OUTLET1;
        normalAcc.FS_Is_Address_Validated__c='Yes';
        normalAcc.Is_Default_FET_International_Outlet__c=true; 
        insert normalAcc;
        coordinatorUser = FSTestUtil.createUser(null,1,FSConstants.dispenserCoordinatorProfile,true);
        system.runAs(coordinatorUser){
            shippingForm = FSTestUtil.createShippingForm(true);
            dispenserModel = FSTestUtil.createDispenserModel(true, '2000');
        }
        war1 = new Warehouse_Details__c();
        war1.Brand_Set__c = 'sample1';
        war1.Name = 'sample2';
        war1.Warehouse_Country__c = 'CA';  
        insert war1;
        outletDispenserInt1 = FSTestUtil.createOutletDispenserAllTypes(FSConstants.OD_RECORD_TYPE_INT,null,normalAcc.id,null,false);
        
        outletDispenserInt1.Shipping_Form__c = shippingForm.id;
        outletDispenserInt1.FSInt_Dispenser_Type__c = dispenserModel.id;
        outletDispenserInt1.FS_Serial_Number2__c = 'TEST_7687';
        outletDispenserInt1.Warehouse_Country__c = 'New Zealand';
        outletDispenserInt1.Warehouse_Name__c = 'New Zealand #1';
        outletDispenserInt1.Brand_Set__c = 'NZ Default Collection';
        outletDispenserInt1.FS_IsActive__c = true;
        outletDispenserInt1.FS_Outlet__c = normalAcc.id;
        outletDispenserInt1.FS_Planned_Install_Date__c =system.now().date();
        outletDispenserInt1.Planned_Remove_Date__c =system.now().date()+1;
    }
    
    private static testMethod void myUnitTest() {
        FSTestUtil.insertPlatformTypeCustomSettings();     
        // TO DO: implement unit test
        Test.startTest();    
        
        createTestData(); 
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
        system.runAs(fetSysAdminUser){
            outletDispenserInt1.FS_Status__c = 'Enrolled';
            insert outletDispenserInt1; 
            
            ApexPages.currentPage().getParameters().put(IDS, outletDispenserInt1.id);
            stdCont1 = new ApexPages.StandardController(outletDispenserInt1);
            system.assertNotEquals(outletDispenserInt1.Id, null);
            outletAssgnmntCtrl1 = new FET_OutletAssignmentCtrl(stdCont1);
            outletAssgnmntCtrl1.save();
            outletAssgnmntCtrl1.redirectPopup();
            outletAssgnmntCtrl1.closePopup1();
            outletAssgnmntCtrl1.closePopup();
        }
        Test.stopTest();
    }
    
    
    private static testMethod void myUnitTest1() {
        FSTestUtil.insertPlatformTypeCustomSettings();
        // TO DO: implement unit test
        Test.startTest();
        
        createTestData();              
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
        system.runAs(fetSysAdminUser){
            outletDispenserInt1.FS_Status__c = 'Dispenser Delivered';
            outletDispenserInt1.Warehouse_Details__c = war1.Id;  
            insert outletDispenserInt1;            
            
            ApexPages.currentPage().getParameters().put(IDS, outletDispenserInt1.id);
            stdCont1 = new ApexPages.StandardController(outletDispenserInt1);
            system.assertNotEquals(outletDispenserInt1.Id, null);
            outletAssgnmntCtrl1 = new FET_OutletAssignmentCtrl(stdCont1);
            outletAssgnmntCtrl1.save();
            outletAssgnmntCtrl1.redirectPopup();
            outletAssgnmntCtrl1.closePopup1();
            outletAssgnmntCtrl1.closePopup();
        }
        Test.stopTest();
    }
    
    //test method assigned to outlet
    private static testMethod void myUnitTest3() {
        FSTestUtil.insertPlatformTypeCustomSettings();
        // TO DO: implement unit test            
        
        createTestData();            
        normalAcc.fs_Chain__C=chainAccount.id;
        normalAcc.FS_ACN__c = ACN;       
        update normalAcc;
        
        Test.startTest();
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
        system.runAs(fetSysAdminUser){
            
            outletDispenserInt1.FS_Status__c = 'Assigned to Outlet';       
            outletDispenserInt1.Warehouse_Details__c = war1.Id;
            insert outletDispenserInt1;         
            
            ApexPages.currentPage().getParameters().put(IDS, outletDispenserInt1.id);
            stdCont1 = new ApexPages.StandardController(outletDispenserInt1);
            system.assertNotEquals(outletDispenserInt1.Id, null);
            outletAssgnmntCtrl1 = new FET_OutletAssignmentCtrl(stdCont1);
            outletAssgnmntCtrl1.save();
            outletAssgnmntCtrl1.removeAssignToOutlet();
            outletAssgnmntCtrl1.redirectPopup();
            outletAssgnmntCtrl1.closePopup1();
            outletAssgnmntCtrl1.closePopup2();
            outletAssgnmntCtrl1.closePopup();
        }
        Test.stopTest(); 
    }
    
    //test method assigned to outlet
    private static testMethod void myUnitTest6() {
        FSTestUtil.insertPlatformTypeCustomSettings();
        // TO DO: implement unit test
       
        createTestData();
        normalAcc.fs_Chain__C=chainAccount.id;
        normalAcc.FS_ACN__c = ACN;        
        update normalAcc; 
        
        Test.startTest();
        outletDispenserInt1.FS_Status__c = 'Assigned to Outlet';       
        outletDispenserInt1.Warehouse_Details__c = war1.Id;
        insert outletDispenserInt1;        
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
        system.runAs(fetSysAdminUser){
            ApexPages.currentPage().getParameters().put(IDS, outletDispenserInt1.id);
            stdCont1 = new ApexPages.StandardController(outletDispenserInt1);
            system.assertNotEquals(outletDispenserInt1.Id, null);
            outletAssgnmntCtrl1 = new FET_OutletAssignmentCtrl(stdCont1);
            outletAssgnmntCtrl1.save();
            outletAssgnmntCtrl1.removeAssignToOutlet();
            outletAssgnmntCtrl1.redirectPopup();
            outletAssgnmntCtrl1.closePopup1();
            outletAssgnmntCtrl1.closePopup2();
            outletAssgnmntCtrl1.closePopup();
        }
        Test.stopTest();        
    }
    
    
    private static testMethod void testAssignNewOutletDispenser() {
        FSTestUtil.insertPlatformTypeCustomSettings();    
        // TO DO: implement unit test
             
        final List<Account> outletsToInsert = new List<Account>();       
        
        createTestData();
        normalAcc.fs_Chain__C=chainAccount.id;
        normalAcc.FS_ACN__c = ACN;     
        outletsToInsert.add(normalAcc) ;
        bottlerAcc=FSTestUtil.createTestAccount('Test Bottler 1',FSConstants.RECORD_TYPE_BOTLLER,true);
        outlet2 = FSTestUtil.createAccountOutlet('Test Outlet International',FSConstants.RECORD_TYPE_OUTLET,headquartersAcc.id, false);
        outlet2.fs_Chain__C=chainAccount.id;
        outlet2.FS_ACN__c = '7687687699';
        outlet2.ShippingStreet='test street';
        outlet2.ShippingPostalCode='654321';
        outlet2.Bottlers_Name__c = bottlerAcc.id;   
        outlet2.RecordTypeId=FSConstants.RECORD_TYPE_OUTLET1;
        outlet2.FS_Is_Address_Validated__c='Yes';
        outlet2.Is_Default_FET_International_Outlet__c=true; 
        outlet2.FS_SAP_ID__c='12334577';
        outletsToInsert.add(outlet2) ;            
        upsert outletsToInsert;
        
        outletDispenserInt1.FS_Status__c = 'New';       
        outletDispenserInt1.Warehouse_Details__c = war1.Id;
        insert outletDispenserInt1;            
        
        Test.startTest(); 
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
        system.runAs(fetSysAdminUser){
            ApexPages.currentPage().getParameters().put(IDS, outletDispenserInt1.id);
            stdCont1 = new ApexPages.StandardController(outletDispenserInt1);
            system.assertNotEquals(outletDispenserInt1.Id, null);
            outletAssgnmntCtrl1 = new FET_OutletAssignmentCtrl(stdCont1);
            outletAssgnmntCtrl1.outletRef.FS_Outlet__c=outlet2.id;
            outletAssgnmntCtrl1.save();
            outletAssgnmntCtrl1.removeAssignToOutlet();
        }
        Test.stopTest();        
    }    
    
    //test method for removed from outlet
    private static testMethod void myUnitTest4() {
        FSTestUtil.insertPlatformTypeCustomSettings();
        // TO DO: implement unit test
        Test.startTest();              
        
        createTestData();
        normalAcc.fs_Chain__C=chainAccount.id;
        normalAcc.FS_ACN__c = ACN;      
        update normalAcc;          
        
        outletDispenserInt1.FS_Status__c='Removed From Outlet';        
        insert outletDispenserInt1;
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
        system.runAs(fetSysAdminUser){
            ApexPages.currentPage().getParameters().put(IDS, outletDispenserInt1.id);
            stdCont1 = new ApexPages.StandardController(outletDispenserInt1);
            system.assertNotEquals(outletDispenserInt1.Id, null);
            outletAssgnmntCtrl1 = new FET_OutletAssignmentCtrl(stdCont1);
            outletAssgnmntCtrl1.save();
            outletAssgnmntCtrl1.redirectPopup1();
            outletAssgnmntCtrl1.closePopup1();
            outletAssgnmntCtrl1.closePopup2();
            outletAssgnmntCtrl1.closePopup3();
            outletAssgnmntCtrl1.closePopup();  
        }
        Test.stopTest();
    }
}