force-app/main/default/objects/Account/fields/CCR_ACN_RecordType_Id__c.field-meta.xml
<CustomField>
    <fullName>CCR_ACN_RecordType_Id__c</fullName>
    <description>This field is the combination of ACN and Record type ID and the field will get populated through the interface</description>
    <externalId>true</externalId>
    <label>ACN + RecordType Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/CCR_KO_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>CCR_KO_Record_Type__c</fullName>
    <description>This field holds the SAP record type value that corresponds to the SFDC record type</description>
    <label>KO Record Type</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_ACN__c.field-meta.xml
<CustomField>
    <fullName>FS_ACN__c</fullName>
    <description>SAP Legacy Customer #</description>
    <inlineHelpText>ACN is an auto generated field for International Outlets.</inlineHelpText>
    <label>ACN</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Chain__c.field-meta.xml
<CustomField>
    <fullName>FS_Chain__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chain</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for Chain.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Chain</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Headquarters/Outlets</relationshipLabel>
    <relationshipName>Chains</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_SAP_ID__c.field-meta.xml
<CustomField>
    <fullName>FS_SAP_ID__c</fullName>
    <inlineHelpText>SAP ID is an auto generated field for International Outlets.</inlineHelpText>
    <label>SAP ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FSCreateHeadquartersBatchTest.cls
/*************************************************************************************************** 
Name         : FSCreateHeadquartersBatch
Usage        : Unit test coverage of FSCreateHeadquartersBatch
***************************************************************************************************/
@isTest 
private class FSCreateHeadquartersBatchTest{ 
    
    static testMethod void  Type4OutletsTest(){
        
        Account accHQ=FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,false);
        accHQ.FS_ACN__c='1111111111';
        accHQ.CCR_ACN_RecordType_Id__c='1111111111'+FSConstants.RECORD_TYPE_HQ;
        accHQ.FS_SAP_ID__c='2222222222';
        
        insert accHQ;
        
        Account accOutlet=FSTestUtil.createAccountOutlet('Test Outlet 1',FSConstants.RECORD_TYPE_OUTLET,accHQ.Id,false);
        accOutlet.CCR_KO_Record_Type__c=55;
        accOutlet.FS_ACN__c='4444444444';
        accOutlet.FS_SAP_ID__c='5555555555';
        accOutlet.ShippingCountry = 'US';
        insert accOutlet;
        
        Test.startTest();
        Database.executeBatch(new FSCreateHeadquartersBatch());
        Test.stopTest();
    }
    
    static testMethod void  Type3OutletsTest(){
        Account accOutlet=FSTestUtil.createAccountOutlet('Test Outlet 1',FSConstants.RECORD_TYPE_OUTLET,null,false);
        accOutlet.CCR_KO_Record_Type__c=55;
        accOutlet.FS_ACN__c='4444444444';
        accOutlet.CCR_ACN_RecordType_Id__c='4444444444'+FSConstants.RECORD_TYPE_NAME_OUTLET;
        accOutlet.FS_SAP_ID__c='5555555555';
        accOutlet.ShippingCountry = 'US';
        insert accOutlet;
        
        Test.startTest();
        Database.executeBatch(new FSCreateHeadquartersBatch());
        Test.stopTest();
    }
    
    
    static testMethod void  Type2OutletsTest(){
        Account accChain=FSTestUtil.createTestAccount('Test Chain 1',FSConstants.RECORD_TYPE_CHAIN,false);
        accChain.FS_ACN__c='1111111111';
        accChain.CCR_ACN_RecordType_Id__c='1111111111'+FSConstants.RECORD_TYPE_CHAIN;
        accChain.FS_SAP_ID__c='2222222222';        
        insert accChain;
        
        Account accOutlet=FSTestUtil.createAccountOutlet('Test Outlet 1',FSConstants.RECORD_TYPE_OUTLET,null,false);
        accOutlet.CCR_KO_Record_Type__c=55;
        accOutlet.FS_Chain__c=accChain.Id;
        accOutlet.FS_ACN__c='4444444444';
        accOutlet.CCR_ACN_RecordType_Id__c='4444444444'+FSConstants.RECORD_TYPE_NAME_OUTLET;
        accOutlet.FS_SAP_ID__c='5555555555';
        accOutlet.ShippingCountry = 'US';
        insert accOutlet;
        
        Test.startTest();
        Database.executeBatch(new FSCreateHeadquartersBatch());
        Test.stopTest();
    }
    
    static testMethod void  Type1OutletsTest(){
        Account accHQ=FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,false);
        accHQ.FS_ACN__c='1111111111';
        accHQ.CCR_ACN_RecordType_Id__c='1111111111'+FSConstants.RECORD_TYPE_HQ;
        accHQ.FS_SAP_ID__c='2222222222';
        
        insert accHQ;  
        
        Account accChain=FSTestUtil.createTestAccount('Test Chain 1',FSConstants.RECORD_TYPE_CHAIN,false);
        accChain.FS_ACN__c='1111111111';
        accChain.CCR_ACN_RecordType_Id__c='1111111111'+FSConstants.RECORD_TYPE_CHAIN;
        accChain.FS_SAP_ID__c='2222222222';
        
        insert accChain;
        
        Account accOutlet=FSTestUtil.createAccountOutlet('Test Outlet 1',FSConstants.RECORD_TYPE_OUTLET,accHQ.Id,false);
        accOutlet.CCR_KO_Record_Type__c=55;
        accOutlet.FS_Chain__c=accChain.Id;    
        accOutlet.FS_ACN__c='4444444444';
        accOutlet.FS_SAP_ID__c='5555555555';
        accOutlet.ShippingCountry = 'US';
        insert accOutlet;
        
        Test.startTest();
        Database.executeBatch(new FSCreateHeadquartersBatch());
        Test.stopTest();
    }   
    
}