force-app/main/default/objects/Account/fields/Cokesmart_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Cokesmart_Payment_Method__c</fullName>
    <inlineHelpText>Cartridge Fee Payment Method</inlineHelpText>
    <label>Cartridge Fee Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Invoice_Customer__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Bank Draft</fullName>
            </value>
            <value>
                <fullName>Invoice (Payment Terms)</fullName>
            </value>
            <value>
                <fullName>Distributor billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FS_CS_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>FS_CS_Payment_Method__c</fullName>
    <formula>TEXT(FS_Headquarters__r.Cokesmart_Payment_Method__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cokesmart/Cartridge Payment Method</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_CS_Sub_Trade_Channel__c.field-meta.xml
<CustomField>
    <fullName>FS_CS_Sub_Trade_Channel__c</fullName>
    <label>Sub-Trade Channel</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>009 - Chain Discount Drug Store</fullName>
            </value>
            <value>
                <fullName>010 - Conventional Independent Drug Store</fullName>
            </value>
            <value>
                <fullName>013 - QSR-Hamburger</fullName>
            </value>
            <value>
                <fullName>014 - QSR-Pizza</fullName>
            </value>
            <value>
                <fullName>015 - QSR-Chicken</fullName>
            </value>
            <value>
                <fullName>016 - QSR-Mexican</fullName>
            </value>
            <value>
                <fullName>017 - QSR-Sandwich</fullName>
            </value>
            <value>
                <fullName>018 - Hotel/Motel/Resort/Inn</fullName>
            </value>
            <value>
                <fullName>019 - Military - U.S. - Commissary</fullName>
            </value>
            <value>
                <fullName>021 - Military - U.S. - Exchange</fullName>
            </value>
            <value>
                <fullName>022 - Military - U.S. - Other</fullName>
            </value>
            <value>
                <fullName>023 - Primary School</fullName>
            </value>
            <value>
                <fullName>024 - Middle School</fullName>
            </value>
            <value>
                <fullName>026 - Secondary/High School</fullName>
            </value>
            <value>
                <fullName>027 - Cinema/Movie</fullName>
            </value>
            <value>
                <fullName>028 - Chain Supermarket</fullName>
            </value>
            <value>
                <fullName>033 - Independent Supermarket</fullName>
            </value>
            <value>
                <fullName>101 - Other Supermarket</fullName>
            </value>
            <value>
                <fullName>102 - Chain Convenience Store</fullName>
            </value>
            <value>
                <fullName>103 - Independent Convenience Store</fullName>
            </value>
            <value>
                <fullName>104 - Other Convenience Store</fullName>
            </value>
            <value>
                <fullName>105 - Butcher Shop</fullName>
            </value>
            <value>
                <fullName>106 - Bakery</fullName>
            </value>
            <value>
                <fullName>107 - Delicatessen</fullName>
            </value>
            <value>
                <fullName>108 - Health Food Store</fullName>
            </value>
            <value>
                <fullName>109 - Produce Stand</fullName>
            </value>
            <value>
                <fullName>110 - Other Specialty Food Store</fullName>
            </value>
            <value>
                <fullName>111 - Box Store</fullName>
            </value>
            <value>
                <fullName>112 - Other Discount Grocery</fullName>
            </value>
            <value>
                <fullName>113 - Mom &amp; Pop</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Outlet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Outlet_Information__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_Information__c</fullName>
    <formula>&quot;ACN: &quot; &amp; FS_ACN__c &amp;&quot; | SAP ID: &quot; &amp; FS_SAP_ID__c &amp; BR() &amp; &quot;Store #: &quot;&amp; FS_Store_Number__c &amp; BR() &amp; 
&quot;Address: &quot; &amp; ShippingStreet &amp; BR() &amp; 
ShippingCity &amp;&quot;, &quot;&amp; ShippingState &amp;&quot; &quot; &amp; ShippingCountry &amp;&#39; &#39;&amp; ShippingPostalCode &amp; BR() &amp; 
&quot;Phone: &quot; &amp;Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Outlet Information</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Payment_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Payment_Type__c</fullName>
    <inlineHelpText>&quot;Payment Term&quot; Invoicing requires Finance Approval from S. Curtis Marshall &amp; Mark Westenfelder. 

Warning: When Payment Term eligibility is changed from â€œYesâ€� to â€œNoâ€�, existing â€œPayment Termâ€� methods will need to be updated.</inlineHelpText>
    <label>Approved for Program Fee Invoicing?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Requested_Delivery_Method__c.field-meta.xml
<CustomField>
    <fullName>FS_Requested_Delivery_Method__c</fullName>
    <label>Requested Delivery Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Direct Ship</fullName>
            </value>
            <value>
                <fullName>Bottler</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Requested_Order_Method__c.field-meta.xml
<CustomField>
    <fullName>FS_Requested_Order_Method__c</fullName>
    <label>Requested Order Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CokeSmart</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Bottler</fullName>
            </value>
            <value>
                <fullName>Manual Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FS_VMS_Customer__c.field-meta.xml
<CustomField>
    <fullName>FS_VMS_Customer__c</fullName>
    <label>Cartridge Ordering Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cokesmart</fullName>
            </value>
            <value>
                <fullName>Bottler</fullName>
            </value>
            <value>
                <fullName>Manual Order</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Invoice_Customer__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Customer__c</fullName>
    <inlineHelpText>&quot;Payment Term&quot; Invoicing requires Finance Approval from S. Curtis Marshall &amp; Mark Westenfelder. 

Warning: When Payment Term eligibility is changed from Ã¢â‚¬Å“YesÃ¢â‚¬ï¿½ to Ã¢â‚¬Å“NoÃ¢â‚¬ï¿½, existing Ã¢â‚¬Å“Payment TermÃ¢â‚¬ï¿½ methods will need to be updated.</inlineHelpText>
    <label>Approved for Cartridge Pymt Invoicing?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <displayFormat>EP-{0000}</displayFormat>
    <label>Execution Plan#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For Post Install</description>
    <label>Outlet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Outlet</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Post Install Activity</relationshipLabel>
    <relationshipName>Outlet_Post_Execution_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/Cokesmart_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Cokesmart_Payment_Method__c</fullName>
    <description>Cartridge Fee Payment Method picklist</description>
    <inlineHelpText>Ã¢â‚¬Å“&quot;Payment Term&quot; Invoicing requires Finance Approval from S. Curtis Marshall &amp; Mark Westenfelder.

Warning: When Payment Term eligibility is changed from Ã¢â‚¬Å“YesÃ¢â‚¬ï¿½ to Ã¢â‚¬Å“NoÃ¢â‚¬ï¿½, existing Ã¢â‚¬Å“Payment TermÃ¢â‚¬ï¿½ methods will need to be updated.Ã¢â‚¬ï¿½</inlineHelpText>
    <label>Cartridge Fee Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
                <default>true</default>
                <label>Credit Card</label>
            </value>
            <value>
                <fullName>Bank Draft</fullName>
            </value>
            <value>
                <fullName>Invoice (Payment Terms)</fullName>
            </value>
            <value>
                <fullName>Distributor billing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_CS_Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>FS_CS_Payment_Method__c</fullName>
    <label>8000 Series - Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Bank Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlet Info Summary</relationshipLabel>
    <relationshipName>Outlet_Info_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installations (Outlet)</relationshipLabel>
    <relationshipName>Installations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Outlet_Information__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_Information__c</fullName>
    <description>Outlet Information</description>
    <formula>FS_Outlet__r.FS_Outlet_Information__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Outlet Information</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Requested_Delivery_Method__c.field-meta.xml
<CustomField>
    <fullName>FS_Requested_Delivery_Method__c</fullName>
    <label>Requested Delivery Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Direct Ship</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Requested_Order_Method__c.field-meta.xml
<CustomField>
    <fullName>FS_Requested_Order_Method__c</fullName>
    <label>Requested Order Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CokeSmart</fullName>
            </value>
            <value>
                <fullName>Bottler</fullName>
            </value>
            <value>
                <fullName>Manual Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FSEnterEditViewCokeSmartInfoController.cls
/******************
Name         : FSEnterEditViewCokeSmartInfoController
Created By   : Pallavi Sharma (Appiro)
Created Date : 17 - Sep - 2013
Usage        : Controller for Enter/Edit/View CokeSmart Info Page, which is used to edit information about
Outlet Info related to Execution Plan
9th Jan,2019 Modified by: Sai Krishna. Added a new Cancel method for redirection to prev Execution plan record page. Reg: FET 6 Ref:(Jira FNF-115)
*********************/
public with sharing class FSEnterEditViewCokeSmartInfoController {
    public set<Id> setOutletIds;
    
    public static final string CREDITCARD= 'Credit Card';  
    public static final string BANKDRAFT= 'Bank Draft';  
    public static final string PAYMENTTERM= 'Invoice (Payment Terms)';  
    public static final string DISTRIBUTORBILL='Distributor billing';
    public static final string VMS= 'VMS'; 
    public integer valZero = 0;
    public static final string DELIVERY= 'Delivery';  
    public static final string CHANNEL= 'Channel';   
    public static final string PROGRAMPAYMENT= 'ProgramPaymentMethod'; 
    public static final string PROGRAMPAYMNT= 'PaymentMethod'; 
    public static final string CHANNELNAME= 'ChannelName';    
    public static final string BILLTOADDRESS= 'BillToAddress';
    public static final string BILLTOCOUNTRY= 'BillToCountry';
    public static final string BILLTOCITY= 'BillToCity';    
    public static final string BILLTOSTATE= 'BillToState';   
    public static final string BILLTOZIP= 'BillToZip';   
    public static final string REMOVINGALL= 'RemovingAll';  
    public static final string ALL= 'All';
    public static final string NONE='--None--';
    public static final string YESVALUE='Yes';
    public Map<Id,Account> accountMap;
    public Boolean displayPopup{get;set;}
    public List<Account> lstOutlet{get;set;}
    public Id executionPlan{get;set;}
    public string selectedFillDown{get;set;}
    public List<OutletDetails> listOutletDetails {get;set;}    
    
    public static  object valnull() { return null; }    
    
    public class OutletDetails {
        public Account outlet {get;set;}
        public List<SelectOption> cokesmartPaymentMethodValues{get;set;} 
        public List<SelectOption> programPaymentMethodValues{get;set;}         
        
        public OutletDetails(final Account inputOutlet) {
            this.outlet = inputOutlet;
            cokesmartPaymentMethodValues = new List<SelectOption>();
            if(outlet.Invoice_Customer__c != valnull()) {
                cokesmartPaymentMethodValues.add(new SelectOption(NONE,NONE));
                if(outlet.Invoice_Customer__c.equalsIgnoreCase(YESVALUE)) {
                    cokesmartPaymentMethodValues.add(new SelectOption(CREDITCARD,CREDITCARD));                    
                    cokesmartPaymentMethodValues.add(new SelectOption(BANKDRAFT,BANKDRAFT));
                    cokesmartPaymentMethodValues.add(new SelectOption(PAYMENTTERM,PAYMENTTERM));
                    cokesmartPaymentMethodValues.add(new SelectOption(DISTRIBUTORBILL,DISTRIBUTORBILL));                    
                } 
                else if(outlet.Invoice_Customer__c.equalsIgnoreCase('No')) {                   
                    cokesmartPaymentMethodValues.add(new SelectOption(CREDITCARD,CREDITCARD));
                    cokesmartPaymentMethodValues.add(new SelectOption(BANKDRAFT,BANKDRAFT));
                    cokesmartPaymentMethodValues.add(new SelectOption(DISTRIBUTORBILL,DISTRIBUTORBILL));                    
                }
            }
            programPaymentMethodValues = new List<SelectOption>();
            if(outlet.FS_Payment_Type__c != valnull()) {
                programPaymentMethodValues.add(new SelectOption(NONE,NONE));
                if(outlet.FS_Payment_Type__c.equalsIgnoreCase(YESVALUE)) {
                    programPaymentMethodValues.add(new SelectOption(CREDITCARD,CREDITCARD));
                    programPaymentMethodValues.add(new SelectOption(BANKDRAFT,BANKDRAFT));
                    programPaymentMethodValues.add(new SelectOption(PAYMENTTERM,PAYMENTTERM));                   
                } else if(outlet.FS_Payment_Type__c.equalsIgnoreCase('No')) {                   
                    programPaymentMethodValues.add(new SelectOption(CREDITCARD,CREDITCARD));
                    programPaymentMethodValues.add(new SelectOption(BANKDRAFT,BANKDRAFT));                    
                }
            }
        }            
    }    
   
     /*****************************************************************
  	Method: closePopup
  	Description: closePopup method is close the popup displayed to the user
				added as part of FET 4.0
	*******************************************************************/
    public void closePopup() {displayPopup = false;} 
    /*****************************************************************
  	Method: showPopup
  	Description: showPopup method is show the popup for the user with 
				related message 
				added as part of FET 4.0
	*******************************************************************/
    public void showPopup() {displayPopup = true;}  
    
    //Constructor
    public FSEnterEditViewCokeSmartInfoController (){
        executionPlan = Apexpages.currentPage().getParameters().get('executionplanid');
        accountMap=new Map<Id,Account>();
        if(executionPlan != valnull()){
            setOutletIds = new set<Id>();
            lstOutlet = new List<Account>();
            listOutletDetails = new List<OutletDetails>();
            //Get all outlets Id from installation which is related to Execution Plan
            for(FS_Installation__c installation : [Select FS_Outlet__c,FS_Execution_Plan__c From FS_Installation__c  Where FS_Execution_Plan__c =: executionPlan]){
                setOutletIds.add(installation.FS_Outlet__c);                                   
            }
            
            //Get outlets
            if(!setOutletIds.isEmpty()){
                lstOutlet = [Select FS_VMS_Customer__c,FS_Requested_Order_Method__c,Invoice_Customer__c, FS_CS_Payment_Method__c, 
                             Cokesmart_Payment_Method__c, FS_Outlet_Information__c, FS_CS_Sub_Trade_Channel__c,
                             FS_Payment_Type__c,FS_Requested_Delivery_Method__c,FS_Payment_Method__c,FS_CS_Status__c, 
                             FS_CS_State__c, FS_CS_Bill_To_Zip__c, FS_CS_Bill_To_City__c, FS_CS_Sub_Trade_Channel_Name__c, 
                             FS_CS_Bill_To_Address__c,FS_CS_Bill_To_Country__c, FS_CS_All_Ftn_Removed__c, FS_Headquarters__r.Cokesmart_Payment_Method__c,
                             FS_Headquarters__r.Invoice_Customer__c From Account Where Id IN : setOutletIds];
                
                for(Account outlet: lstOutlet) {
                    listOutletDetails.add(new OutletDetails(outlet));
                    accountMap.put(outlet.Id, outlet);
                }               
            }
        }
    }
    
    //Save Outlets Information
    public PageReference saveOutletInfo(){
        PageReference pageRef;   
        try{         
            //upserting the Outlets
            if(!lstOutlet.isEmpty()){ 
                for(Account acc:lstOutlet){
                    if(acc.Cokesmart_Payment_Method__c==NONE){ acc.Cokesmart_Payment_Method__c=FSConstants.STRING_NULL; }
                    if(acc.FS_Payment_Method__c==NONE){ acc.FS_Payment_Method__c=FSConstants.STRING_NULL; }
                }
                upsert lstOutlet;
            }           
            pageRef= new PageReference('/'+executionPlan);
        }
        //catching DML Exception
        catch(DMLException ex){
			apexpages.addMessages(ex);			          
            ApexErrorLogger.addApexErrorLog(FSConstants.FET,'FSEnterEditViewCokeSmartInfoController','saveOutletInfo','Account',FSConstants.MediumPriority,ex,ex.getMessage());            
        }        
        return pageRef;
    }
    //Fill Down Functionality conditions
    public void fillDown(){ 
        Boolean popupCheck=false;       
        FSConstants.BypassOrderDelivery =true;
        if (selectedFillDown == VMS){
            for (Account acc :lstOutlet){
                acc.FS_Requested_Order_Method__c= lstOutlet[0].FS_Requested_Order_Method__c ;
            }
        }
        else if (selectedFillDown == DELIVERY){
            for (Account acc :lstOutlet){
                acc.FS_Requested_Delivery_Method__c= lstOutlet[0].FS_Requested_Delivery_Method__c ;
            }
        }
        else if(selectedFillDown == CHANNEL){
            for (Account acc :lstOutlet){ 
                acc.FS_CS_Sub_Trade_Channel__c= lstOutlet[0].FS_CS_Sub_Trade_Channel__c ;
            }
        }        
        else if(selectedFillDown == PROGRAMPAYMNT){            
            //  //Prod-Fix Change in Fill Down
            for (Account acc :lstOutlet){
                if(lstOutlet[0].Cokesmart_Payment_Method__c!=PAYMENTTERM || acc.Cokesmart_Payment_Method__c==PAYMENTTERM){
					acc.Cokesmart_Payment_Method__c=lstOutlet[0].Cokesmart_Payment_Method__c;
				}               
				else if(accountMap.containsKey(acc.Id) && acc.Invoice_Customer__c.equalsIgnoreCase(YESVALUE)){
					acc.Cokesmart_Payment_Method__c=lstOutlet[0].Cokesmart_Payment_Method__c;					
				}
                
				else{ popupCheck=true;	}
                
                if(popupCheck){ showPopup(); }
            }
        }
        
        else if(selectedFillDown == PROGRAMPAYMENT){
            for (Account acc :lstOutlet){
                if(lstOutlet[0].FS_Payment_Method__c!=PAYMENTTERM || acc.FS_Payment_Method__c==PAYMENTTERM){
					acc.FS_Payment_Method__c=lstOutlet[0].FS_Payment_Method__c;
				}
                
				else if(accountMap.containsKey(acc.Id) && acc.FS_Payment_Type__c.equalsIgnoreCase(YESVALUE)){
					acc.FS_Payment_Method__c=lstOutlet[0].FS_Payment_Method__c;					
				}
                
				else{ popupCheck=true;	}
                
				if(popupCheck){ showPopup(); }
            }
        }
        else if(selectedFillDown ==BILLTOADDRESS){
            for (Account acc :lstOutlet){
                acc.FS_CS_Bill_To_Address__c= lstOutlet[0].FS_CS_Bill_To_Address__c ;
            }
        }
        else if(selectedFillDown == BILLTOCITY){
            for (Account acc :lstOutlet){
                acc.FS_CS_Bill_To_City__c= lstOutlet[0].FS_CS_Bill_To_City__c ;
            }
        }
        else if(selectedFillDown ==BILLTOSTATE){
            for (Account acc :lstOutlet){
                acc.FS_CS_State__c= lstOutlet[0].FS_CS_State__c ;
            }
        }
        else if(selectedFillDown == BILLTOZIP){
            for (Account acc :lstOutlet){
                acc.FS_CS_Bill_To_Zip__c= lstOutlet[0].FS_CS_Bill_To_Zip__c ;
            }
        }
        //OCR 4393
        else if(selectedFillDown ==BILLTOCOUNTRY){
            for (Account acc :lstOutlet){
                acc.FS_CS_Bill_To_Country__c= lstOutlet[0].FS_CS_Bill_To_Country__c ;
            }
        }
        else if(selectedFillDown == REMOVINGALL){
            for (Account acc :lstOutlet){
                acc.FS_CS_All_Ftn_Removed__c= lstOutlet[0].FS_CS_All_Ftn_Removed__c ;
            }
        }
        else if(selectedFillDown == ALL){
            
            for (Account acc :lstOutlet){
                
                acc.FS_Requested_Order_Method__c= lstOutlet[0].FS_Requested_Order_Method__c ;
                acc.FS_Requested_Delivery_Method__c=lstOutlet[0].FS_Requested_Delivery_Method__c ;
                acc.FS_CS_Sub_Trade_Channel__c= lstOutlet[0].FS_CS_Sub_Trade_Channel__c ;                                
                acc.FS_CS_Bill_To_Address__c= lstOutlet[0].FS_CS_Bill_To_Address__c ;
                acc.FS_CS_Bill_To_Country__c= lstOutlet[0].FS_CS_Bill_To_Country__c ; //OCR
                acc.FS_CS_Bill_To_City__c= lstOutlet[0].FS_CS_Bill_To_City__c ;
                acc.FS_CS_State__c= lstOutlet[0].FS_CS_State__c ;
                acc.FS_CS_Bill_To_Zip__c= lstOutlet[0].FS_CS_Bill_To_Zip__c ;
                acc.FS_CS_All_Ftn_Removed__c= lstOutlet[0].FS_CS_All_Ftn_Removed__c ;
                if(lstOutlet[0].Cokesmart_Payment_Method__c!=PAYMENTTERM || acc.Cokesmart_Payment_Method__c==PAYMENTTERM){
					acc.Cokesmart_Payment_Method__c=lstOutlet[0].Cokesmart_Payment_Method__c;
				}
                
				else if(accountMap.containsKey(acc.Id) && acc.Invoice_Customer__c.equalsIgnoreCase(YESVALUE)){
					acc.Cokesmart_Payment_Method__c=lstOutlet[0].Cokesmart_Payment_Method__c;					
				}
				else{	popupCheck=true; }
                
                if(lstOutlet[0].FS_Payment_Method__c!=PAYMENTTERM || acc.FS_Payment_Method__c==PAYMENTTERM){
					acc.FS_Payment_Method__c=lstOutlet[0].FS_Payment_Method__c;
				}		
                
				else if(accountMap.containsKey(acc.Id) && acc.FS_Payment_Type__c.equalsIgnoreCase(YESVALUE)){
					acc.FS_Payment_Method__c=lstOutlet[0].FS_Payment_Method__c;					
				}
                
				else{ popupCheck=true; }
                if(popupCheck){ showPopup(); }
            }           
        }
    }
    /*****************************************************************
  	Method: cancel
  	Description: cancel method helps the user return back to the execution plan record  
	*******************************************************************/
    public PageReference cancel(){
        PageReference pageRef;
        if(executionPlan!= Null){
            pageRef= new PageReference('/' + executionPlan);
        }
        return pageRef;        
    }
}