force-app/main/default/objects/Account/fields/FS_7000_Series_Agitated_Brands_Selection__c.field-meta.xml
<CustomField>
    <fullName>FS_7000_Series_Agitated_Brands_Selection__c</fullName>
    <label>7000 Series Agitated Brands Selections</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Barqs</fullName>
            </value>
            <value>
                <fullName>Pibb</fullName>
            </value>
            <value>
                <fullName>Dr Pepper</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FS_LTO__c.field-meta.xml
<CustomField>
    <fullName>FS_LTO__c</fullName>
    <label>FET Limited Time Offer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Valid_Fill__c.field-meta.xml
<CustomField>
    <fullName>FS_Valid_Fill__c</fullName>
    <label>Valid Fill</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FS_Outlet_Dispenser__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_Dispenser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>To find OD Reference, Click on Search Icon to find OD Record by Serial# or ACN#</inlineHelpText>
    <label>OD Reference (Customer ACN)</label>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_Valid_Fill__c.field-meta.xml
<CustomField>
    <fullName>FS_Valid_Fill__c</fullName>
    <formula>TEXT(FS_Outlet_Dispenser__r.FS_Valid_Fill__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valid Fill</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_7000_Series_Agitated_Brands_Selection__c.field-meta.xml
<CustomField>
    <fullName>FS_7000_Series_Agitated_Brands_Selection__c</fullName>
    <label>7000 Series Agitated Brands Selections</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Barqs</fullName>
            </value>
            <value>
                <fullName>Pibb</fullName>
            </value>
            <value>
                <fullName>Dr Pepper</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_7000_Series_Brands_Option_Selections__c.field-meta.xml
<CustomField>
    <fullName>FS_7000_Series_Brands_Option_Selections__c</fullName>
    <label>7000 Series Brands Option Selections</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2 Static/1 Agitated</fullName>
            </value>
            <value>
                <fullName>0 Static/2 Agitated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_7000_Series_Static_Brands_Selections__c.field-meta.xml
<CustomField>
    <fullName>FS_7000_Series_Static_Brands_Selections__c</fullName>
    <description>rename the existing fields like spicy cherry, still and agitaged fields to &quot;Spicy cherry airwatch attribute&quot; and so on
move these fields to the system info section or in a different section that can be collapsed</description>
    <label>7000 Series Static Brands AW Attribute</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>POWERade</fullName>
            </value>
            <value>
                <fullName>Raspberry</fullName>
            </value>
            <value>
                <fullName>Hi-C</fullName>
            </value>
            <value>
                <fullName>Fuze</fullName>
            </value>
            <value>
                <fullName>Vitamin Water</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Equip_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Equip_Type__c</fullName>
    <description>equip type</description>
    <inlineHelpText>This is the JDE Equipment Type value</inlineHelpText>
    <label>Equipment Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_IsActive__c.field-meta.xml
<CustomField>
    <fullName>FS_IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>active or inactive</description>
    <label>Active (A) / Inactive (I)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_LTO__c.field-meta.xml
<CustomField>
    <fullName>FS_LTO__c</fullName>
    <description>LTO</description>
    <label>FET Limited Time offer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Migration_to_AW_Required__c.field-meta.xml
<CustomField>
    <fullName>FS_Migration_to_AW_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Migration to AW Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Model__c.field-meta.xml
<CustomField>
    <fullName>FS_Model__c</fullName>
    <inlineHelpText>For International OD&#39;s Platform value is derived from Dispenser Model.</inlineHelpText>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2000</fullName>
            </value>
            <value>
                <fullName>7000</fullName>
            </value>
            <value>
                <fullName>8000</fullName>
            </value>
            <value>
                <fullName>9000</fullName>
            </value>
            <value>
                <fullName>3100</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <description>Outlet field.</description>
    <label>Outlet</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 3) OR (2 AND 4 AND (5 OR 7)) OR (2 AND 4 AND 6)</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for Outlet.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Outlet</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Outlet</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>7000, 8000, 9000, CCNA Dispenser</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Dispenser</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value>No, Yes</value>
        </filterItems>
        <filterItems>
            <field>Account.Is_Default_FET_International_Outlet__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlet Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Pending_Migration_to_AW__c.field-meta.xml
<CustomField>
    <fullName>FS_Pending_Migration_to_AW__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pending Migration to AW</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Serial_Number2__c.field-meta.xml
<CustomField>
    <fullName>FS_Serial_Number2__c</fullName>
    <description>Serial Number/Asset Tag.</description>
    <label>JDE Serial Number/Asset Tag</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Valid_Fill__c.field-meta.xml
<CustomField>
    <fullName>FS_Valid_Fill__c</fullName>
    <label>Valid Fill Required</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 OR 2) AND 4) OR 3 OR 5</booleanFilter>
        <errorMessage>The installation referenced by this dispenser is linked to a different outlet than the outlet on the dispenser.</errorMessage>
        <filterItems>
            <field>FS_Installation__c.FS_Outlet__c</field>
            <operation>equals</operation>
            <valueField>$Source.FS_Outlet__c</valueField>
        </filterItems>
        <filterItems>
            <field>FS_Installation__c.FS_New_Outlet__c</field>
            <operation>equals</operation>
            <valueField>$Source.FS_Outlet__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Dispenser</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>CCNA Dispenser, 7000, 8000, 9000</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Installed Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/FS_Valid_Fill__c.object-meta.xml
<CustomObject>
    <label>Valid Fill</label>
    <nameField>
        <displayFormat>VF-{0000}</displayFormat>
        <label>Valid Fill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Valid Fill</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Valid_Fill__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Post-Install Valid Fill</relationshipLabel>
    <relationshipName>Vailid_Fill</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/fields/FS_Outlet_Dispenser__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_Dispenser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet Dispenser</label>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipLabel>Post Install Valid Fill</relationshipLabel>
    <relationshipName>Valid_Fill</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FS_LM_CaseEditPageController_Test.cls
/**************************************************************************************
Apex Class Name     : FS_LM_CaseEditPageController_Test
Function            : This is a Test class for handling all Unit test methods for FS_LM_CaseEditPageController class.
Author              : Infosys
Modification Log    :
* Developer         : Date             Description
* ----------------------------------------------------------------------------                 
* Hari            	03/06/2018       	First version for handling unit test methods for all methods in FS_LM_CaseEditPageController class.
					05/29/2018		 	Removed usage of OutboundServiceDetails__c customSetting as part of FOT project
*************************************************************************************/
@isTest(SeeAllData=false)
public class FS_LM_CaseEditPageController_Test {
 
    static FS_Outlet_Dispenser__c outletDisp1;
    static FS_Outlet_Dispenser__c outletDisp2;
    public static Id fsaccountRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(FSConstants.OUTLET_RECORD_TYPE).getRecordTypeId();
    public static Id ODRecordTypeId = Schema.SObjectType.FS_Outlet_Dispenser__c.getRecordTypeInfosByName().get(FSConstants.RT_NAME_CCNA_OD).getRecordTypeId();
    public static Id caseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get(FSConstants.RECORD_TYPE_NAME_LMCASE).getRecordTypeId();
     
    @testSetup
    public static void dataSetup()
    {
         User userRecord = new User();
            userRecord.LastName='Testuser';
            userRecord.Alias='testuser';
            userRecord.Email='abc@def.com';
            userRecord.Username='hkrishna12@test.com';
            userRecord.TimeZoneSidKey='America/Los_Angeles';
            profile id1=[select id from profile where name='FS_FACT_BAST_P'];
            userRecord.ProfileId=id1.id;
            userRecord.LocaleSidKey='en_US';
            userRecord.EmailEncodingKey='ISO-8859-1';
            userRecord.LanguageLocaleKey='en_US';
            insert userRecord;
        
        	User adminUser = new User();
            adminUser.LastName='Administrator';
        	adminUser.FirstName='Freestyle';
            adminUser.Alias='fadmi';
            adminUser.Email='abc1@def.com';
            adminUser.Username='admin23@test.com';
            adminUser.TimeZoneSidKey='America/Los_Angeles';
            profile id2=[select id from profile where name='System Administrator'];
            adminUser.ProfileId=id2.id;
            adminUser.LocaleSidKey='en_US';
            adminUser.EmailEncodingKey='ISO-8859-1';
            adminUser.LanguageLocaleKey='en_US';
            insert adminUser;
        
        //FACT_TestFactory.loadOutboundServiceForOutletDispensers();
        Account fsaccount1 = new Account();
        fsaccount1.RecordTypeId=fsaccountRecordTypeId;
        fsaccount1.shippingCountry='US';
        fsaccount1.name='FS Outlet To Account';
        insert fsaccount1;
        
        Account fsaccount2 = new Account();
        fsaccount2.RecordTypeId=fsaccountRecordTypeId;
        fsaccount2.shippingCountry='US';
        fsaccount2.name='FS Outlet From Account';
        insert fsaccount2;
        
        FSTestUtil.insertPlatformTypeCustomSettings();
        
        Test.setMock(HttpCalloutMock.class, new FSFETNMSConnectorMock());
        
        OutletDisp1 =FSTestUtil.createOutletDispenserAllTypes(FSConstants.RT_NAME_CCNA_OD,null,fsaccount2.id,null,false);
        OutletDisp1.FS_Outlet__c = fsaccount2.Id;
        OutletDisp1.FS_Equip_Type__c  ='9000';
        OutletDisp1.FS_Serial_Number2__c = 'AHKJ1775';
        //OutletDisp1.Installation__c = installation.id;
        //OutletDisp1.FS_Color__c = 'Black1';
        OutletDisp1.FS_IsActive__c = true ;
        OutletDisp1.FS_LTO__c='LTO11';
        OutletDisp1.FS_Model__c='90001';
        OutletDisp1.FS_Pending_Migration_to_AW__c=false;
        OutletDisp1.FS_Migration_to_AW_Required__c=true;
        OutletDisp1.FS_Valid_Fill__c='No1';
        OutletDisp1.FS_7000_Series_Brands_Option_Selections__c  = FSconstants.twoStatic1Agitated;
        OutletDisp1.FS_7000_Series_Static_Brands_Selections__c='Powerade1;Hi-C/Vitamin Water1';
        OutletDisp1.FS_7000_Series_Agitated_Brands_Selection__c = 'Barqs1';
        OutletDisp1.Brand_Set__c='GER Default Collection';
        OutletDisp1.FS_Soft_Ice_Adjust_Flag__c='No1';
        OutletDisp1.FS_Outlet__c = fsaccount2.id;
        OutletDisp1.FS_IsActive__c =True;
        OutletDisp1.FS_Serial_Number2__c='AHKJ1775';
        
        insert OutletDisp1;
        
        OutletDisp2 =FSTestUtil.createOutletDispenserAllTypes(FSConstants.RT_NAME_CCNA_OD,null,fsaccount2.id,null,false);
        OutletDisp2.FS_Outlet__c = fsaccount1.Id;
        OutletDisp2.FS_Equip_Type__c  ='9000';
        OutletDisp2.FS_Serial_Number2__c = 'AKHJ1775';
        //OutletDisp1.Installation__c = installation.id;
        //OutletDisp2.FS_Color__c = 'Black1';
        OutletDisp2.FS_IsActive__c = true ;
        OutletDisp2.FS_LTO__c='LTO11';
        OutletDisp2.FS_Model__c='90001';
        OutletDisp2.FS_Pending_Migration_to_AW__c=false;
        OutletDisp2.FS_Migration_to_AW_Required__c=true;
        OutletDisp2.FS_Valid_Fill__c='No1';
        OutletDisp2.FS_7000_Series_Brands_Option_Selections__c  =FSconstants.twoStatic1Agitated;
        OutletDisp2.FS_7000_Series_Static_Brands_Selections__c='Powerade1;Hi-C/Vitamin Water1';
        OutletDisp2.FS_7000_Series_Agitated_Brands_Selection__c = 'Barqs1';
        OutletDisp2.Brand_Set__c='GER Default Collection';
        OutletDisp2.FS_Soft_Ice_Adjust_Flag__c='No1';
        OutletDisp2.FS_Outlet__c = fsaccount1.id;
        OutletDisp2.FS_IsActive__c =True;
        OutletDisp2.FS_Serial_Number2__c='AKHJ1775';
        insert OutletDisp2;
   
    
    }
 
    public static testMethod void LMcaseinsert()
    {
        Account toaccount = [select id from Account where name='FS Outlet To Account'];
        Account fromaccount = [select id from Account where name='FS Outlet From Account'];
    FS_Outlet_Dispenser__c Disp1 =[select id from FS_Outlet_Dispenser__c where FS_Serial_Number2__c='AHKJ1775'];
    
        User testuser = [select id from User where Email='abc@def.com'];
    try
        {   system.runAs(testuser){
            Case caseInstance = new Case();
            caseInstance.Status = 'New';
            caseInstance.recordtypeId = caseRecordTypeId;
            caseInstance.Issue_Name__c ='Sample_Test';
            caseInstance.type ='JDE Linkage Request';
            caseInstance.To_Account__c = toaccount.Id;
            caseInstance.From_Account__c = fromaccount.Id;
            insert caseInstance;
            test.startTest();
            ApexPages.currentPage().getParameters().put('id',caseInstance.Id);
            Apexpages.StandardController stdController = new Apexpages.StandardController(caseInstance);
            FS_LM_CaseEditPageController FSLMCaseEditPageController =new FS_LM_CaseEditPageController(stdController);
             
            FSLMCaseEditPageController.toACNODdetails();
            FSLMCaseEditPageController.fromACNODdetailswrpr();
            FSLMCaseEditPageController.getdetails();
            FS_LM_CaseEditPageController.ODwrpr ODwrapObj= new FS_LM_CaseEditPageController.ODwrpr(Disp1,true); 
      		FSLMCaseEditPageController.ODList.add(ODwrapObj);
      		FSLMCaseEditPageController.saveCase();
            FSLMCaseEditPageController.saveNew();
            FSLMCaseEditPageController.editCase();
            FSLMCaseEditPageController.dpcancel();
            caseComment testcomment= new caseComment();
            testcomment.CommentBody='test sample';
            testcomment.ParentId = caseInstance.id;
            insert testcomment;
            ApexPages.currentPage().getParameters().put('CommentId_d',testComment.Id);
            FSLMCaseEditPageController.NewComment();
            FSLMCaseEditPageController.deleteComment();
            FSLMCaseEditPageController.deleteCase();
            test.stopTest();
        }}
        catch(DmlException ex)
        {
            system.debug('DmlException : ' + ex.getMessage());
        }
       
        
    }
    
    public static testMethod void LMEsclateToSalesSupport()
    {
        Account toaccount = [select id from Account where name='FS Outlet To Account'];
        Account fromaccount = [select id from Account where name='FS Outlet From Account'];
        FS_Outlet_Dispenser__c Disp1 =[select id from FS_Outlet_Dispenser__c where FS_Serial_Number2__c='AHKJ1775'];
    
        User testuser = [select id from User where Email='abc@def.com'];
        try
        {   system.runAs(testuser){
            Case caseInstance = new Case();
            caseInstance.Status = 'New';
            caseInstance.recordtypeId = caseRecordTypeId;
            caseInstance.Issue_Name__c ='Sample_Test';
            caseInstance.type ='JDE Initiated AMOA';
            caseInstance.To_Account__c = toaccount.Id;
            caseInstance.From_Account__c = fromaccount.Id;
            insert caseInstance;
            test.startTest();
            ApexPages.currentPage().getParameters().put('id',caseInstance.Id);
            Apexpages.StandardController stdController = new Apexpages.StandardController(caseInstance);
            FS_LM_CaseEditPageController FSLMCaseEditPageController =new FS_LM_CaseEditPageController(stdController);
            FSLMCaseEditPageController.escalateToSalesSupport();
            System.AssertNotEquals(caseInstance.Status,FSConstants.STRING_NULL);
            test.stopTest();
        }}
        catch(DmlException ex)
        {
            system.debug('DmlException : ' + ex.getMessage());
        }
    } 
}