force-app/main/default/objects/Account/fields/FS_ACN__c.field-meta.xml
<CustomField>
    <fullName>FS_ACN__c</fullName>
    <description>SAP Legacy Customer #</description>
    <inlineHelpText>ACN is an auto generated field for International Outlets.</inlineHelpText>
    <label>ACN</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Approved_For_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Approved_For_Execution_Plan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Approved For Execution Plan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Outlet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Headquarters</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for HQ.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Headquarters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Davaco_Requirements__c.field-meta.xml
<CustomField>
    <fullName>FS_Davaco_Requirements__c</fullName>
    <label>Select Site Assessment Requirements</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Davaco: Site Assessment + GFE</fullName>
            </value>
            <value>
                <fullName>Davaco: Site Assessment + Detailed Scope Summary</fullName>
            </value>
            <value>
                <fullName>Davaco: Site Assessment Only</fullName>
            </value>
            <value>
                <fullName>Davaco: New Construction Site Assessment</fullName>
            </value>
            <value>
                <fullName>No Site Assessment Required</fullName>
            </value>
            <value>
                <fullName>Power House</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <displayFormat>EP-{0000}</displayFormat>
    <label>Execution Plan#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan_Final_Approval_PM__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan_Final_Approval_PM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Execution Plan Final Approval (PM)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <label>Headquarters</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Value does not exist or does not match filter criteria for HQ on EP.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Execution Plans (Headquarters)</relationshipLabel>
    <relationshipName>Execution_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_Davaco_Requirements__c.field-meta.xml
<CustomField>
    <fullName>FS_Davaco_Requirements__c</fullName>
    <label>What type of Site Assessment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Construction SA - Proceed w/Scheduling</fullName>
            </value>
            <value>
                <fullName>SA Not Required - OSM approval required for local market</fullName>
            </value>
            <value>
                <fullName>Site Assess + GFE bid proposal (traditional)</fullName>
            </value>
            <value>
                <fullName>Site Assessment Only (survey only)</fullName>
            </value>
            <value>
                <fullName>Rush â€“ New Construction SA â€“ Proceed w/Scheduling</fullName>
            </value>
            <value>
                <fullName>Rush - Site Assess + GFE Bid proposal (traditional)</fullName>
            </value>
            <value>
                <fullName>Rush - Site Assessment Only (Survey Only)</fullName>
            </value>
            <value>
                <fullName>No Site Assessment-Required</fullName>
            </value>
            <value>
                <fullName>SA Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlet Info Summary</relationshipLabel>
    <relationshipName>Outlet_Info_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan_Final_Approval_PM__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan_Final_Approval_PM__c</fullName>
    <description>Execution Plan Final Approval (PM)</description>
    <label>Execution Plan Final Approval (PM)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Original_Install_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Original_Install_Date__c</fullName>
    <label>Initially Scheduled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Rush_Install_Reason__c.field-meta.xml
<CustomField>
    <fullName>FS_Rush_Install_Reason__c</fullName>
    <label>Rush Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Store Opening</fullName>
            </value>
            <value>
                <fullName>Marketing/Media</fullName>
            </value>
            <value>
                <fullName>Remodel</fullName>
            </value>
            <value>
                <fullName>Legacy Equipment Failure</fullName>
            </value>
            <value>
                <fullName>Customer Request</fullName>
            </value>
            <value>
                <fullName>Rebuild</fullName>
            </value>
            <value>
                <fullName>Health Inspection</fullName>
            </value>
            <value>
                <fullName>Coordinator Error</fullName>
            </value>
            <value>
                <fullName>NRA</fullName>
            </value>
            <value>
                <fullName>SA Not Uploaded</fullName>
            </value>
            <value>
                <fullName>Customer Unable to Pour Product</fullName>
            </value>
            <value>
                <fullName>Limited Dispenser Accessibility</fullName>
            </value>
            <value>
                <fullName>External Process Failure</fullName>
            </value>
            <value>
                <fullName>Acts of God</fullName>
            </value>
            <value>
                <fullName>Trade Show</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_SA_Completed_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_SA_Completed_Date__c</fullName>
    <label>SA Completed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_SA_Scheduled_On_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_SA_Scheduled_On_Date__c</fullName>
    <label>Original SA Scheduled On Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/FSEPStatusIndicatorTest_TestData.cls
/******************************************** 
Name         : FSEPStatusIndicatorTest_TestData
Created By   : Infosys Limited
Created Date : Sep. 19, 2017
Usage        : Utility class for test data creation
			   for FSEPStatusIndicatorTest class
*************************************************/
 
@isTest
public class FSEPStatusIndicatorTest_TestData {
    public static final String APPROVED='Approved';
    public static final String STORE='Store Opening';
    public static final String BLUE='blue';
    public static final String GREEN='green';
    public static final String REDCOLR='red';
    public static final String YELLOW='yellow';
    public static final String GRAY='gray';
    public static List<Id> idsList;
    public static List<Id> accountId;
    public static List<FS_Installation__c> installList;
    
    public static List<Id> loadTestData(){
        idsList=new List<Id>();
        FSTestFactory.createTestDisableTriggerSetting(); 
        final Account accHQ = FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,true);
        idsList.add(accHQ.Id);
        
        final Account accOutlet = FSTestUtil.createAccountOutlet('Test Outlet 1',FSConstants.RECORD_TYPE_OUTLET,accHQ.Id, false); 
        accOutlet.FS_Approved_For_Execution_Plan__c = true;    	
        accOutlet.FS_Headquarters__c = accHQ.Id;
        accOutlet.FS_ACN__c = 'outletACN';
        insert accOutlet; 
        idsList.add(accOutlet.Id);
        
        return idsList;        
    }   
    
    public static List<FS_Installation__c> createInstOther(final List<id> idsList,final Integer count,final Integer valueCheck){
        installList=new List<FS_Installation__c>();
        final List<Integer> integerList=new List<Integer>{1,2,3,4};
            for(integer i=0;i<count;i++){
                final FS_Installation__c  installation = FSTestUtil.createInstallationAcc(FSConstants.NEWINSTALLATION,idsList[0],idsList[1], false);
                installation.FS_SA_Scheduled_On_Date__c = System.today().addDays(-20);
                if(valueCheck==integerList[0]){ installation.FS_SA_Completed_Date__c = System.today().addDays(-10); }
                if(valueCheck==integerList[1]){installation.FS_Davaco_Requirements__c='SA Not Required - OSM approval required for local market';}
                if(valueCheck==integerList[2]){installation.FS_Execution_Plan_Final_Approval_PM__c=APPROVED;}
                if(valueCheck==integerList[3]){
                    installation.FS_Original_Install_Date__c = System.today().addDays(-10);
                    installation.FS_Rush_Install_Reason__c=STORE;
                }
                installList.add(installation);
            } 
        return installList;        
    } 
      
    public static List<FS_Installation__c> createInst(final List<id> idsList,final Integer count){
        installList=new List<FS_Installation__c>();
        for(integer i=0;i<count;i++){
            final FS_Installation__c installation = FSTestUtil.createInstallationAcc(FSConstants.NEWINSTALLATION,idsList[0],idsList[1], false);
            installList.add(installation);
        }
        return installList;        
    }
     public static FSExecutionPlanStatusIndicatorExtension executeMethod(final FS_Execution_Plan__c exePlan){
       //final Profile adminProfile = FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
      //final User adminUser = FSTestFactory.createUser(adminProfile.id);
      //insert adminUser;
        FSExecutionPlanStatusIndicatorExtension obj;
      //system.runAs(adminUser){
            final Pagereference pageRef = Page.FSCreateExecutionPlan;
            Test.setCurrentPage(pageRef);        
            // Initialize Page paramteres
            pageRef.getParameters().put('id', exePlan.Id);
           final apexpages.Standardcontroller standCont = new apexpages.Standardcontroller(exePlan);        
            obj = new FSExecutionPlanStatusIndicatorExtension(standCont);        
            
       //}
        return obj;
        
    }
}