force-app/main/default/objects/Account/fields/FS_ACN__c.field-meta.xml
<CustomField>
    <fullName>FS_ACN__c</fullName>
    <description>SAP Legacy Customer #</description>
    <inlineHelpText>ACN is an auto generated field for International Outlets.</inlineHelpText>
    <label>ACN</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Address__c.field-meta.xml
<CustomField>
    <fullName>FS_Address__c</fullName>
    <label>Valid Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/Dispenser_serial_number__c.field-meta.xml
<CustomField>
    <fullName>Dispenser_serial_number__c</fullName>
    <inlineHelpText>8 character alpha-numeric dispenser serial number. Separate multiple dispensers by comma.</inlineHelpText>
    <label>Dispenser serial number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FACT_Case_Type__c.field-meta.xml
<CustomField>
    <fullName>FACT_Case_Type__c</fullName>
    <label>Case Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Connectivity Issue</fullName>
            </value>
            <value>
                <fullName>Enrollment Issue</fullName>
            </value>
            <value>
                <fullName>Consumption Issue</fullName>
            </value>
            <value>
                <fullName>Alignment Issue</fullName>
            </value>
            <value>
                <fullName>Brand Selection</fullName>
            </value>
            <value>
                <fullName>Relocation / AMOA</fullName>
            </value>
            <value>
                <fullName>Software / Content</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FS_ACN__c.field-meta.xml
<CustomField>
    <fullName>FS_ACN__c</fullName>
    <formula>FS_Outlet_Dispenser__r.FS_ACN_NBR__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ACN#</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_Address__c.field-meta.xml
<CustomField>
    <fullName>FS_Address__c</fullName>
    <formula>FS_Outlet_Dispenser__r.FS_Outlet__r.CCR_Address__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_Outlet_Dispenser__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_Dispenser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>To find OD Reference, Click on Search Icon to find OD Record by Serial# or ACN#</inlineHelpText>
    <label>OD Reference (Customer ACN)</label>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_Outlet_Name__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_Name__c</fullName>
    <formula>FS_Outlet_Dispenser__r.FS_Name1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Outlet Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_Resolution_Comments__c.field-meta.xml
<CustomField>
    <fullName>FS_Resolution_Comments__c</fullName>
    <label>Resolution Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_Resolution_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Resolution_Type__c</fullName>
    <description>Created for FACT Cases</description>
    <inlineHelpText>Select Resolution Type when Status is changed to Closed</inlineHelpText>
    <label>Resolution Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booster</fullName>
            </value>
            <value>
                <fullName>Dispenser Enrolled</fullName>
            </value>
            <value>
                <fullName>Enrolled to wrong ACN Number</fullName>
            </value>
            <value>
                <fullName>External Modem</fullName>
            </value>
            <value>
                <fullName>Flavor Change</fullName>
            </value>
            <value>
                <fullName>Hide/Show Water</fullName>
            </value>
            <value>
                <fullName>Manual Software Update</fullName>
            </value>
            <value>
                <fullName>No Signal-Needs Hardwire</fullName>
            </value>
            <value>
                <fullName>OTA Update Needed</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Re-linkage and Enrollment</fullName>
            </value>
            <value>
                <fullName>Reporting with Wrong SAP Number</fullName>
            </value>
            <value>
                <fullName>Serial Number Exception</fullName>
            </value>
            <value>
                <fullName>Custom USB</fullName>
                <isActive>false</isActive>
                <label>Custom USB</label>
            </value>
            <value>
                <fullName>Retrigger OTA Updates</fullName>
                <isActive>false</isActive>
                <label>Retrigger OTA Updates</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FS_SAP__c.field-meta.xml
<CustomField>
    <fullName>FS_SAP__c</fullName>
    <formula>FS_Outlet_Dispenser__r.FS_Outlet__r.FS_SAP_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SAP#</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>FS_Serial_Number__c</fullName>
    <formula>FS_Outlet_Dispenser__r.FS_Serial_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Serial Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Issue_Name__c.field-meta.xml
<CustomField>
    <fullName>Issue_Name__c</fullName>
    <inlineHelpText>Please give a brief descriptive name of the issue</inlineHelpText>
    <label>Issue Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <description>Outlet field.</description>
    <label>Outlet</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 3) OR (2 AND 4 AND (5 OR 7)) OR (2 AND 4 AND 6)</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for Outlet.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Outlet</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Outlet</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>7000, 8000, 9000, CCNA Dispenser</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Dispenser</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value>No, Yes</value>
        </filterItems>
        <filterItems>
            <field>Account.Is_Default_FET_International_Outlet__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlet Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Serial_Number2__c.field-meta.xml
<CustomField>
    <fullName>FS_Serial_Number2__c</fullName>
    <description>Serial Number/Asset Tag.</description>
    <label>JDE Serial Number/Asset Tag</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>FS_Serial_Number__c</fullName>
    <formula>FS_Serial_Number2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Serial Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OutboundServiceDetails__c/OutboundServiceDetails__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>OutboundServiceDetails</label>
</CustomObject>

force-app/main/default/classes/FS_SendEmail_HelperTest.cls
/**************************************************************************************
Apex Class Name     : FS_SendEmail_HelperTest
Function            : This is a Test class for handling all Unit test methods for FS_SendEmail_Helper class.
Author              : Infosys
Modification Log    :
* Developer         : Date             Description
* ----------------------------------------------------------------------------                 
* Sunil TD            07/26/2017       First version for handling unit test methods for all methods in 
                                       FS_SendEmail_Helper class.
*					  06/18/2018	   Removed usage of OutboundServiceDetails__c customSetting as part of FOT project
*************************************************************************************/

@isTest(SeeAllData=false)
public class FS_SendEmail_HelperTest {

    public static Id caseRecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Connectivity Solution').getRecordTypeId();
    public static Id outletRecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('FS Outlet').getRecordTypeId();
    public static Id outletDispenserRecordTypeId = Schema.SObjectType.FS_Outlet_Dispenser__c.getRecordTypeInfosByName().get(FSConstants.RT_NAME_CCNA_OD).getRecordTypeId();
    
    /*****************************************************************************************
        Method : dataSetup
        Description : Method for setting up the data required in this unit test class.
    ******************************************************************************************/
    @testSetup
    public static void dataSetup()
    {
        try
        {
            Account accRecord = insertoutletRecord();
            FS_Outlet_Dispenser__c odRecord = insertOutletDispenser();
            insertCaseRecord('Testissue',odRecord);
            insertCaseRecord('IssueTest',null);
        }
        catch(DmlException ex)
        {
            system.debug('DmlException : ' + ex.getMessage());
        }
    }
    
    /*****************************************************************************************
        Method : insertoutletRecord
        Description : Method for inserting Outlet records.
    ******************************************************************************************/
    public static Account insertoutletRecord()
    {
        Account accountRecord = new Account();
        try
        {
            accountRecord.Name = 'TestOutlet';
            accountRecord.RecordTypeId = outletRecordTypeId;
            insert accountRecord;
        }
        catch(DmlException ex)
        {
            system.debug('DmlException : ' + ex.getMessage());
        }
        
        return accountRecord;
    }
    
    /*****************************************************************************************
        Method : insertOutletDispenser
        Description : Method for inserting Outlet Dispenser records.
    ******************************************************************************************/
    public static FS_Outlet_Dispenser__c insertOutletDispenser()
    {
        //create platform type custom settings
         FSTestUtil.insertPlatformTypeCustomSettings();
        
         //set mock callout
         Test.setMock(HttpCalloutMock.class, new FSFETNMSConnectorMock());
        FS_Outlet_Dispenser__c odRecord = new FS_Outlet_Dispenser__c();
        try
        {
            system.debug('inside OD ###');
            Account accountRecord = [select Id from Account where Name = 'TestOutlet'];
            odRecord.RecordTypeId = outletDispenserRecordTypeId;
            odRecord.FS_Outlet__c = accountRecord.Id;
            odRecord.FS_Serial_Number2__c = 'ZPL123456';
            insert odRecord;
            system.debug('inside OD $$$$');
        }
        catch(DmlException ex)
        {
            system.debug('DmlException : ' + ex.getMessage());
        }
        return odRecord;
    }
    
    /*****************************************************************************************
        Method : insertCaseRecord
        Description : Method for inserting Case records.
    Updated Date: Feb 2018
    ******************************************************************************************/
    public static void insertCaseRecord(String issueName,FS_Outlet_Dispenser__c outletDispenser)
    {
        try
        {
            Case caseInstance = new Case();
            caseInstance.Status = 'New';
            //caseInstance.FACT_Select_Dispenser__c = null; //FACT R1 2018: Deleted Connectivity Summary object
            caseInstance.recordtypeId = caseRecordTypeId;
            caseInstance.Issue_Name__c = issueName;
            if(outletDispenser != null)
            {
                caseInstance.FS_Outlet_Dispenser__c = outletDispenser.id;
            }
            insert caseInstance; 
        }
        catch(DmlException ex)
        {
            system.debug('DmlException : ' + ex.getMessage());
        }
    }
    
    /*****************************************************************************************
        Method : insertTemplate
        Description : Method for inserting Email Template.
    ******************************************************************************************/
    public static EmailTemplate insertTemplate()
    {
        EmailTemplate validEmailTemplate = new EmailTemplate();
        try
        {
            validEmailTemplate.isActive = true;
            validEmailTemplate.Name = 'name';
            validEmailTemplate.DeveloperName = 'Test_Name';
            validEmailTemplate.TemplateType = 'text';
            validEmailTemplate.Subject = 'Test Subject';
            validEmailTemplate.Body = 'Test Body';
            validEmailTemplate.FolderId = UserInfo.getUserId();
            insert validEmailTemplate;
        }
        catch(DmlException ex)
        {
            system.debug('DmlException : ' + ex.getMessage());
        }
        return validEmailTemplate;
    }
    
    /*****************************************************************************************
        Method : emailTest
        Description : Method for testing replaceMergeFieldValues method in FS_SendEmail_Helper class.
    ******************************************************************************************/
    public static testMethod void emailTest()
    {
        Test.startTest();
        EmailTemplate validEmailTemplate = insertTemplate();
        Case caseRecord = [select Id,CaseNumber,FS_Serial_Number__c,Subject,FS_ACN__c,FS_SAP__c,FACT_Case_Type__c,Description,
                           FS_Outlet_Name__c,FS_Address__c,FS_Resolution_Type__c,FS_Resolution_Comments__c,
                           Dispenser_serial_number__c from Case where Issue_Name__c = 'Testissue'];
        FS_SendEmail_Helper.replaceMergeFieldValues('TestName','abc@def.com',validEmailTemplate,caseRecord,false,null,null,false);
        FS_SendEmail_Helper.replaceMergeFieldValues('TestName','abc@def.com',validEmailTemplate,caseRecord,true,'Test','Test',false);
        FS_SendEmail_Helper.replaceMergeFieldValues('TestName','abc@def.com',validEmailTemplate,caseRecord,false,null,null,true);
        Test.stopTest();
    }
    
    /*****************************************************************************************
        Method : exceptionTest
        Description : Method for covering exceptions in FS_SendEmail_Helper class.
    ******************************************************************************************/
    public static testMethod void exceptionTest()
    {
        Test.startTest();
        EmailTemplate validEmailTemplate = new EmailTemplate();
        Case caseRecord = [select Id,CaseNumber,FS_Serial_Number__c,Subject,FS_ACN__c,FS_SAP__c,FACT_Case_Type__c,
                           FS_Outlet_Name__c,FS_Address__c,Dispenser_serial_number__c from Case 
                           where Issue_Name__c = 'IssueTest'];
        FS_SendEmail_Helper.replaceMergeFieldValues('TestName','abc@def.com',validEmailTemplate,caseRecord,false,null,null,false);
        FS_SendEmail_Helper.returnEmailObject(null,null,null,null,null);
        Test.stopTest();
    }
}