force-app/main/default/objects/Account/fields/FS_ACN__c.field-meta.xml
<CustomField>
    <fullName>FS_ACN__c</fullName>
    <description>SAP Legacy Customer #</description>
    <inlineHelpText>ACN is an auto generated field for International Outlets.</inlineHelpText>
    <label>ACN</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Outlet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_ACN__c.field-meta.xml
<CustomField>
    <fullName>FS_ACN__c</fullName>
    <formula>FS_Outlet_Dispenser__r.FS_ACN_NBR__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ACN#</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/FS_Dispenser_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Dispenser_Type__c</fullName>
    <description>FS Dispenser Type</description>
    <inlineHelpText>Please enter dispenser type</inlineHelpText>
    <label>FS Dispenser Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2000 Series</fullName>
            </value>
            <value>
                <fullName>3100 Series</fullName>
            </value>
            <value>
                <fullName>6000 Series</fullName>
            </value>
            <value>
                <fullName>7000 Series</fullName>
            </value>
            <value>
                <fullName>7100 Series</fullName>
            </value>
            <value>
                <fullName>8000 Series</fullName>
            </value>
            <value>
                <fullName>9000 Series</fullName>
            </value>
            <value>
                <fullName>9100 Series</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/FS_Outlet_Dispenser__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_Dispenser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>To find OD Reference, Click on Search Icon to find OD Record by Serial# or ACN#</inlineHelpText>
    <label>OD Reference (Customer ACN)</label>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Issue_Name__c.field-meta.xml
<CustomField>
    <fullName>Issue_Name__c</fullName>
    <inlineHelpText>Please give a brief descriptive name of the issue</inlineHelpText>
    <label>Issue Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseToOutletdispenser__c/CaseToOutletdispenser__c.object-meta.xml
<CustomObject>
    <description>This is a junction object between case object and outlet dispenser object</description>
    <label>Case To OD</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case To Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseToOutletdispenser__c/fields/FS_ACN__c.field-meta.xml
<CustomField>
    <fullName>FS_ACN__c</fullName>
    <formula>Outlet_Dispenser__r.FS_ACN_NBR__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ACN#</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseToOutletdispenser__c/fields/Outlet_Dispenser__c.field-meta.xml
<CustomField>
    <fullName>Outlet_Dispenser__c</fullName>
    <label>Outlet Dispenser</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.Customer__c</field>
            <operation>equals</operation>
            <valueField>FS_Outlet_Dispenser__c.FS_Outlet__c</valueField>
        </filterItems>
        <filterItems>
            <field>FS_Outlet_Dispenser__c.FS_IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipName>CaseToOutletdispensers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <displayFormat>EP-{0000}</displayFormat>
    <label>Execution Plan#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For Post Install</description>
    <label>Outlet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Outlet</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Post Install Activity</relationshipLabel>
    <relationshipName>Outlet_Post_Execution_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlet Info Summary</relationshipLabel>
    <relationshipName>Outlet_Info_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installations (Outlet)</relationshipLabel>
    <relationshipName>Installations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Date_Status__c.field-meta.xml
<CustomField>
    <fullName>FS_Date_Status__c</fullName>
    <label>MDM Registered Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Dispenser_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Dispenser_Type__c</fullName>
    <description>Dispenser Type</description>
    <formula>IF(RecordType.Name=&#39;BoE Dispenser&#39;, TEXT(FS_Model__c), FS_Equip_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dispenser Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Equip_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Equip_Type__c</fullName>
    <description>equip type</description>
    <inlineHelpText>This is the JDE Equipment Type value</inlineHelpText>
    <label>Equipment Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_IsActive__c.field-meta.xml
<CustomField>
    <fullName>FS_IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>active or inactive</description>
    <label>Active (A) / Inactive (I)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <description>Outlet field.</description>
    <label>Outlet</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 3) OR (2 AND 4 AND (5 OR 7)) OR (2 AND 4 AND 6)</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for Outlet.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Outlet</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Outlet</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>7000, 8000, 9000, CCNA Dispenser</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Dispenser</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value>No, Yes</value>
        </filterItems>
        <filterItems>
            <field>Account.Is_Default_FET_International_Outlet__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlet Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Serial_Number2__c.field-meta.xml
<CustomField>
    <fullName>FS_Serial_Number2__c</fullName>
    <description>Serial Number/Asset Tag.</description>
    <label>JDE Serial Number/Asset Tag</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Shipping_Form__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Form</label>
    <referenceTo>Shipping_Form__c</referenceTo>
    <relationshipLabel>Outlet Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FS_SEMultiDispensersControllerTest.cls
/*********************************************************************************************************
Apex Class Name     : FS_SEMultiDispensersControllerTest
Function            : This test class is created for class FS_SEMultiDispensersController
Author				: Infosys
Modification Log    :
* Developer         : Date             Description
* ----------------------------------------------------------------------------                 
* BhargavD	          09/10/2019       This class is a test class for FS_SEMultiDispensersController
									   
***********************************************************************************************************/

@isTest(SeeAllData=false)
private class FS_SEMultiDispensersControllerTest {
    
    static Account headQuarterAcc,outletAcc, defaultAccount, internationalOutlet, chainAccount,bottler;
    static FS_Execution_Plan__c executionPlan;
    static FS_Installation__c installation;
    static User apiUser, coordinatorUser;
    static FS_Outlet_Dispenser__c outletDispenser;
    static FS_Outlet_Dispenser__c outletDispenser1,outletDispenser2;
    static FS_Outlet_Dispenser__c outletDispenserInt,outletDispenserInt1;
    static final string SERIES_7K='7000 Series';
    static FS_Integration_NMS_User__c integrationUser;
    static FS_IP_Technician_Instructions__c  ipTechInstruction;
    static Shipping_Form__c shippingForm;
    static Dispenser_Model__c dispenserModel;
    static SEMultiDispensers testSEMultiDispensers;
    static case sampleCase;
    static PageReference pageRef;
    
/*****************************************************************************************
Method : createTestData
Description : Method for setting up the data required in this unit test class.
******************************************************************************************/
    static void createTestData(){
        try{

            User userRecord = new User();
            userRecord.LastName='Testuser';
            userRecord.Alias='testuser';
            userRecord.Email='abc@defq.com';
            userRecord.Username='hkrishna@test.com';
            userRecord.TimeZoneSidKey='America/Los_Angeles';
            profile id1=[select id from profile where name='FS_FACT_BAST_P'];
            userRecord.ProfileId=id1.id;
            userRecord.LocaleSidKey='en_US';
            userRecord.EmailEncodingKey='ISO-8859-1';
            userRecord.LanguageLocaleKey='en_US';
            insert userRecord; 
            User testuser = [select id from User where Email='abc@defq.com'];
            system.runAs(testuser)
            {  
            FSTestFactory.lstPlatform();
            Test.setMock(HttpCalloutMock.class, new FSFETNMSConnectorMock());
            apiUser=FSTestUtil.createUser(null,null,'API User',false);
            coordinatorUser = FSTestUtil.createUser(null,1,FSConstants.dispenserCoordinatorProfile,true);
            chainAccount = FSTestUtil.createTestAccount('Test Chain 1',FSConstants.RECORD_TYPE_CHAIN,false);        
            chainAccount.FS_ACN__c = '76876876';
            insert chainAccount;
            HeadQuarterAcc = FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,false); 
            HeadQuarterAcc.FS_ACN__c = '7658765876';
            insert HeadQuarterAcc;
            
            //Creates Outlet Accounts
            outletAcc = FSTestUtil.createAccountOutlet('Test Outlet 1',FSConstants.RECORD_TYPE_OUTLET,HeadQuarterAcc.Id, true);
            bottler=FSTestUtil.createTestAccount('Test Bottler 1',FSConstants.RECORD_TYPE_BOTLLER,true);
            defaultAccount = FSTestUtil.createAccountOutlet(FSConstants.defaultOutletName,FSConstants.RECORD_TYPE_OUTLET,HeadQuarterAcc.Id, false);
            internationalOutlet = FSTestUtil.createAccountOutlet('Test Outlet International',FSConstants.RECORD_TYPE_OUTLET_INT,HeadQuarterAcc.Id,false);
            system.runAs(coordinatorUser){
                shippingForm = FSTestUtil.createShippingForm(true);
            }
            dispenserModel = FSTestUtil.createDispenserModel(true, '7000');
            //Creates execution plan
            executionPlan = FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,HeadQuarterAcc.Id, true);
            //creates installation
            installation = FSTestUtil.createInstallationAcc(FSConstants.NEWINSTALLATION,executionPlan.Id,outletAcc.Id,true);                 
            
            ipTechInstruction=FSTestUtil.createTechnicianInstructions(FSConstants.TECHINSTRECTYPE,false);
            
            //creates initial order
            
            outletDispenser = FSTestUtil.createOutletDispenserAllTypes(FSConstants.RT_NAME_CCNA_OD,null,outletAcc.id,null,false);
            outletDispenser1 = FSTestUtil.createOutletDispenserAllTypes(FSConstants.RT_NAME_CCNA_OD,null,outletAcc.id,null,false);
            outletDispenser2= FSTestUtil.createOutletDispenserAllTypes(FSConstants.RT_NAME_CCNA_OD,null,outletAcc.id,null,false);        
            outletDispenserInt = FSTestUtil.createOutletDispenserAllTypes(FSConstants.RT_NAME_CCNA_OD,null,internationalOutlet.id,null,false);
            outletDispenserInt1 = FSTestUtil.createOutletDispenserAllTypes(FSConstants.RT_NAME_CCNA_OD,null,internationalOutlet.id,null,false);
            }
        }
        Catch(Exception ex)
        {
            system.debug('Exception : ' + ex.getMessage());
        }
    }
    
    /*****************************************************************************************
Method : getDispensersList
Description : Method for testing to get OD list.
******************************************************************************************/   
     
    static testmethod void getDispensersTest(){
        
        string dispenser;
        Id caseIn;
        createTestData();
        User testuser = [select id from User where Email='abc@defq.com'];
         system.runAs(testuser)
        {  
        createTestData();
        Test.startTest();
        outletDispenser1.FS_Outlet__c = outletAcc.Id;
        outletDispenser1.FS_Equip_Type__c  ='8000';
        outletDispenser1.FS_Serial_Number2__c='ZPL12345';
        outletDispenser1.FS_IsActive__c=true;
        outletDispenser1.FS_Date_Status__c=system.Date.today();
        insert outletDispenser1;
        FS_Outlet_Dispenser__c odRec = [Select Id,Name from FS_Outlet_Dispenser__c where FS_Serial_Number2__c='ZPL12345'];
        dispenser = odRec.Name; 
        system.debug('dispenserid : ' + dispenser);
        
        sampleCase=new case(Issue_Name__c='test case',Status='New',FS_Dispenser_Type__c=SERIES_7K,Categories__c='CDM',Dispenser_serial_number__c=outletDispenser1.FS_Serial_Number2__c);
        insert sampleCase;
        Case idCase = [Select Id,Issue_Name__c from Case where Issue_Name__c='test case'];
        CaseIn = IdCase.Id;
        system.debug('Casseid : ' + CaseIn);
        
        CaseToOutletdispenser__c cToOD = new CaseToOutletdispenser__c();
        cToOD.Case__c = IdCase.id;
        cToOD.Outlet_Dispenser__c = odRec.Id;
        insert cToOD;
       
       
        FS_SEMultiDispensersController.getDispensersList(dispenser,CaseIn);
        Test.stopTest(); 
        FS_Outlet_Dispenser__c dis = [SELECT FS_Outlet__c,FS_Serial_Number2__c FROM FS_Outlet_Dispenser__c WHERE name =:dispenser];
        system.assert(dis!=NULL);
        }
    }
    
        /*****************************************************************************************
Method : deleteJunctionRecords
Description : Method for testing to delete junction records.
******************************************************************************************/  
    
    static testmethod void deleteJunRecordsTest(){
        Id caseIn;
        createTestData();
        User testuser = [select id from User where Email='abc@defq.com'];
        system.runAs(testuser)
        {  
       
        Test.startTest();
        outletDispenser1.FS_Outlet__c = outletAcc.Id;
        outletDispenser1.FS_Equip_Type__c  ='8000';
        outletDispenser1.FS_Serial_Number2__c='ZPL12345';
        outletDispenser1.FS_IsActive__c=true;
        outletDispenser1.FS_Date_Status__c=system.Date.today();
        insert outletDispenser1;
        FS_Outlet_Dispenser__c odRec = [Select Id,Name from FS_Outlet_Dispenser__c where FS_Serial_Number2__c='ZPL12345'];
         
        sampleCase=new case(Issue_Name__c='test case',Status='New',FS_Dispenser_Type__c=SERIES_7K,Categories__c='CDM',Dispenser_serial_number__c=outletDispenser1.FS_Serial_Number2__c);
        insert sampleCase;
        Case idCase = [Select Id,Issue_Name__c from Case where Issue_Name__c='test case'];
        CaseIn = IdCase.Id;
       
        FS_SEMultiDispensersController.deleteJunctionRecords(CaseIn);
        Test.stopTest();
        case caseR;
        caseR=new case(Issue_Name__c='test case1',Status='New',FS_Dispenser_Type__c=SERIES_7K,Categories__c='CDM',Dispenser_serial_number__c=outletDispenser1.FS_Serial_Number2__c);
        insert caseR;
         system.assert(caseR!=NULL); 
        }
    }
    
 
           /*****************************************************************************************
Method : updateDispenserSerialNumber
Description : Method for testing to update DispenserSerialNumber.
******************************************************************************************/  
    
     static testmethod void updateODSerialNumTest(){
        Id caseIn;
        string serialNumber;
        createTestData();
        User testuser = [select id from User where Email='abc@defq.com'];
        system.runAs(testuser)
       {  
        
        Test.startTest();
        outletDispenser1.FS_Outlet__c = outletAcc.Id;
        outletDispenser1.FS_Equip_Type__c  ='8000';
        outletDispenser1.FS_Serial_Number2__c='ZPL12345';
        outletDispenser1.FS_IsActive__c=true;
        outletDispenser1.FS_Date_Status__c=system.Date.today();
        insert outletDispenser1;
        FS_Outlet_Dispenser__c odRec = [Select Id,Name from FS_Outlet_Dispenser__c where FS_Serial_Number2__c='ZPL12345'];
         
        sampleCase=new case(Issue_Name__c='test case',Status='New',FS_Dispenser_Type__c=SERIES_7K,Categories__c='CDM',Dispenser_serial_number__c=outletDispenser1.FS_Serial_Number2__c);
        insert sampleCase;
        Case idCase = [Select Id,Issue_Name__c from Case where Issue_Name__c='test case'];
        CaseIn = IdCase.Id;
        SerialNumber = 'ZPL12345,';
        FS_SEMultiDispensersController.updateDispenserSerialNumber(CaseIn,SerialNumber);
        Test.stopTest();
        case caseR=[select AccountId,Dispenser_serial_number__c from case where id=:CaseIn];
        system.assert(caseR!=NULL);
        
        }
    }
    
      /*****************************************************************************************
Method : setSerialNumber
Description : Method for testing to setSerialNumber.
******************************************************************************************/  
     static testmethod void setSerialNumTest(){
        Id caseIn;
        string serialNumber = 'ZPL12345,';
        string dispenser;
        createTestData();
        User testuser = [select id from User where Email='abc@defq.com'];
         system.runAs(testuser)
       {  
        Test.startTest();
        outletDispenser1.FS_Outlet__c = outletAcc.Id;
        outletDispenser1.FS_Equip_Type__c  ='8000';
        outletDispenser1.FS_Serial_Number2__c='ZPL12345';
        outletDispenser1.FS_IsActive__c=true;
        outletDispenser1.FS_Date_Status__c=system.Date.today();
        insert outletDispenser1;
        FS_Outlet_Dispenser__c odRec = [Select Id,Name from FS_Outlet_Dispenser__c where FS_Serial_Number2__c='ZPL12345'];
        dispenser = odRec.Name;
        sampleCase=new case(Issue_Name__c='test case',Status='New',FS_Dispenser_Type__c=SERIES_7K,Categories__c='CDM',Dispenser_serial_number__c=outletDispenser1.FS_Serial_Number2__c);
        insert sampleCase;
        Case idCase = [Select Id,Issue_Name__c from Case where Issue_Name__c='test case'];
        CaseIn = IdCase.Id;
        SerialNumber = 'ZPL12345,';
        FS_SEMultiDispensersController.setSerialNumber(CaseIn,SerialNumber,dispenser);
        Test.stopTest();
        case caseR = [Select Id,Issue_Name__c from Case where Issue_Name__c='test case'];
        system.assert(caseR!=NULL);
        }
    }
}