force-app/main/default/objects/Account/fields/FS_ACN__c.field-meta.xml
<CustomField>
    <fullName>FS_ACN__c</fullName>
    <description>SAP Legacy Customer #</description>
    <inlineHelpText>ACN is an auto generated field for International Outlets.</inlineHelpText>
    <label>ACN</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Approved_For_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Approved_For_Execution_Plan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Approved For Execution Plan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Chain__c.field-meta.xml
<CustomField>
    <fullName>FS_Chain__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chain</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for Chain.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Chain</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Headquarters/Outlets</relationshipLabel>
    <relationshipName>Chains</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Headquarters</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for HQ.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Headquarters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Market_ID__c.field-meta.xml
<CustomField>
    <fullName>FS_Market_ID__c</fullName>
    <label>Market ID</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Market_ID__c/FS_Market_ID__c.object-meta.xml
<CustomObject>
    <label>Market ID</label>
    <nameField>
        <displayFormat>MI-{0000}</displayFormat>
        <label>Market ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FSRealignOwnerAndTeamMembersBatchTest.cls
/*************************************************************************************************** 
Name         : FSRealignOwnerAndTeamMembersBatchTest
Created By   : Sunil(Appiro)
Created Date : Dec 17, 2013
Usage        : Unit test coverage of FSRealignOwnerAndTeamMembersBatch 
***************************************************************************************************/
@isTest 
private class FSRealignOwnerAndTeamMembersBatchTest{
  //------------------------------------------------------------------------------------------------
  // Unit Test Method 1
  //------------------------------------------------------------------------------------------------
  static testMethod void  testUnit(){
    // Create Chain Account
    Account accChain = FSTestUtil.createTestAccount('Test Chain 1',FSConstants.RECORD_TYPE_CHAIN,true);
    
    //Create Headquarter Account
    Account accHQ = FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,true);
    
    
    //Create Outlet Account
    Account accOutlet = FSTestUtil.createAccountOutlet('Test Outlet 1',FSConstants.RECORD_TYPE_OUTLET,accHQ.Id, false); 
    accOutlet.FS_Approved_For_Execution_Plan__c = true;
    accOutlet.FS_Chain__c = accChain.Id;
    accOutlet.FS_Headquarters__c = accHQ.Id;
    accOutlet.FS_ACN__c = 'outletACN';
    accOutlet.FS_Market_ID__c = 'test';
    insert accOutlet;
    
    AccountTeamMember teamMember = new AccountTeamMember();
    teamMember.UserId = UserInfo.getUserId(); 
    teamMember.AccountId = accChain.Id;
    teamMember.TeamMemberRole = 'Sales Leadership';
    insert teamMember;
    
    AccountTeamMember teamMember2 = new AccountTeamMember();
    teamMember2.UserId = UserInfo.getUserId(); 
    teamMember2.AccountId = accHQ.Id;
    teamMember2.TeamMemberRole = 'COM';
    insert teamMember2;
    
    AccountTeamMember teamMember3 = new AccountTeamMember();
    teamMember3.UserId = UserInfo.getUserId(); 
    teamMember3.AccountId = accOutlet.Id;
    teamMember3.TeamMemberRole = 'COM';
    insert teamMember3;
    
    Test.startTest();
    
    Id batchprocessid = Database.executeBatch(new FSRealignOwnerAndTeamMembersBatch(), 3);
    AsyncApexJob aaj;
    try{
      aaj = [SELECT Id, Status, JobItemsProcessed, TotalJobItems, NumberOfErrors FROM AsyncApexJob 
             WHERE ID =: batchprocessid];
    }
    catch(Exception e){
      // DO Nothing
    }
    
    // Verify the Job submission
    System.assert(aaj != null);             
    Test.stopTest();
    
  }
}