force-app/main/default/objects/Account/fields/FS_ACN__c.field-meta.xml
<CustomField>
    <fullName>FS_ACN__c</fullName>
    <description>SAP Legacy Customer #</description>
    <inlineHelpText>ACN is an auto generated field for International Outlets.</inlineHelpText>
    <label>ACN</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Outlet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Headquarters</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for HQ.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Headquarters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountTeamMember__c/AccountTeamMember__c.object-meta.xml
<CustomObject>
    <label>Account Team Member</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>AccountTeamMember Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountTeamMember__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>AccountId</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Team Members</relationshipLabel>
    <relationshipName>AccountTeamMembers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountTeamMember__c/fields/TeamMemberRole__c.field-meta.xml
<CustomField>
    <fullName>TeamMemberRole__c</fullName>
    <label>Team Member Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>COM</fullName>
            </value>
            <value>
                <fullName>COM Backup</fullName>
            </value>
            <value>
                <fullName>JCOM</fullName>
            </value>
            <value>
                <fullName>Sales Team Member</fullName>
            </value>
            <value>
                <fullName>PM</fullName>
            </value>
            <value>
                <fullName>PIC</fullName>
            </value>
            <value>
                <fullName>Sales Support</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>FDC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountTeamMember__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AccountTeamMembers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CIF_Header__c/CIF_Header__c.object-meta.xml
<CustomObject>
    <description>CIF Header</description>
    <label>CIF Header</label>
    <nameField>
        <label>CIF Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CIF Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CIF_Header__c/fields/FS_EP__c.field-meta.xml
<CustomField>
    <fullName>FS_EP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>EP</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipName>CIF_Head</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CIF_Header__c/fields/FS_HQ__c.field-meta.xml
<CustomField>
    <fullName>FS_HQ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HQ Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>CIF_Head</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CIF_Header__c/fields/FS_Sales_Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>FS_Sales_Rep_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AccountTeamMember__c.AccountId__r.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <filterItems>
            <field>AccountTeamMember__c.AccountId__c</field>
            <operation>equals</operation>
            <valueField>$Source.FS_HQ__c</valueField>
        </filterItems>
        <filterItems>
            <field>AccountTeamMember__c.TeamMemberRole__c</field>
            <operation>equals</operation>
            <value>Sales Team Member</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AccountTeamMember__c</referenceTo>
    <relationshipLabel>CIF Headers</relationshipLabel>
    <relationshipName>CIF_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CIF_Header__c/fields/FS_Status__c.field-meta.xml
<CustomField>
    <fullName>FS_Status__c</fullName>
    <inlineHelpText>In Progress Ã¢â‚¬â€œ CIF is still open or a site assessment is still opens
Closed Ã¢â‚¬â€œ Cancelled or Not Approved Ã¢â‚¬â€œ All outlets are either cancelled or not approved to move forward
Closed Ã¢â‚¬â€œ Converted to EP. The CIF has been converted to an EP and closed</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>SS Submitted</fullName>
            </value>
            <value>
                <fullName>SA Submitted</fullName>
            </value>
            <value>
                <fullName>EP Submitted</fullName>
            </value>
            <value>
                <fullName>SS Approved</fullName>
            </value>
            <value>
                <fullName>SA Approved</fullName>
            </value>
            <value>
                <fullName>EP Created</fullName>
            </value>
            <value>
                <fullName>Closed Ã¢â‚¬â€œ Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed Ã¢â‚¬â€œ Converted to EP</fullName>
            </value>
            <value>
                <fullName>Closed Ã¢â‚¬â€œ Cancelled or Not Approved</fullName>
            </value>
            <value>
                <fullName>Closed Ã¢â‚¬â€œNot Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CIF_Header__c/fields/FS_Version__c.field-meta.xml
<CustomField>
    <fullName>FS_Version__c</fullName>
    <label>Version</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Disable_Trigger__c/Disable_Trigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is only used in case there is a need to deactivate a trigger during data migration. The triggers must be kept activated at all times...</description>
    <label>Disable Trigger</label>
</CustomObject>

force-app/main/default/objects/FS_CIF__c/FS_CIF__c.object-meta.xml
<CustomObject>
    <label>CIF</label>
    <nameField>
        <label>CIF Outlet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CIF</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_CIF__c/fields/CIF_Head__c.field-meta.xml
<CustomField>
    <fullName>CIF_Head__c</fullName>
    <label>CIF Header Name</label>
    <referenceTo>CIF_Header__c</referenceTo>
    <relationshipLabel>CIF</relationshipLabel>
    <relationshipName>CIF</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_CIF__c/fields/FS_Account__c.field-meta.xml
<CustomField>
    <fullName>FS_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related CIF</relationshipLabel>
    <relationshipName>CIF9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_CIF__c/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Headquarters</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CIF</relationshipLabel>
    <relationshipName>CIF</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_CIF__c/fields/FS_Installation__c.field-meta.xml
<CustomField>
    <fullName>FS_Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>CIF</relationshipLabel>
    <relationshipName>CIF</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_CIF__c/fields/FS_Platform1__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform1__c</fullName>
    <label>Platform 1 for Install</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_CIF__c/fields/FS_Platform1_Qty__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform1_Qty__c</fullName>
    <label>Quantity 1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <displayFormat>EP-{0000}</displayFormat>
    <label>Execution Plan#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan_Status__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan_Status__c</fullName>
    <description>Execution Plan Status</description>
    <label>Execution Plan Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <default>true</default>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>On-Hold</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <label>Headquarters</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Value does not exist or does not match filter criteria for HQ on EP.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Execution Plans (Headquarters)</relationshipLabel>
    <relationshipName>Execution_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_CIF__c.field-meta.xml
<CustomField>
    <fullName>FS_CIF__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CIF</label>
    <referenceTo>FS_CIF__c</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlet Info Summary</relationshipLabel>
    <relationshipName>Outlet_Info_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Platform1__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform1__c</fullName>
    <label>Platform 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Platform_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3100</fullName>
    </customValue>
    <customValue>
        <fullName>6000</fullName>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
    </customValue>
    <customValue>
        <fullName>7100</fullName>
    </customValue>
    <customValue>
        <fullName>8000</fullName>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
    </customValue>
    <masterLabel>Platform Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FSCIFReparentingTest.cls
@isTest
public class FSCIFReparentingTest {
    
    private static final string FPS = 'FS PM_P';
    private static final string COM = 'COM';
    private static CIF_Header__c cifHead;
    private static CIF_Header__c updCifHead;
    private static final string ACCID = 'AccId';
    private static final string IDSTRING = 'id';
    private static final string PROG_STATUS='In Progress';
    private static final string CLOSED_STATUS='Closed – Converted to EP';
    private Static Id recTypeHQ=FSUtil.getObjectRecordTypeId(Account.sObjectType,'FS Headquarters');
    private static List<String> updAcntIdList=new List<String>();
    private static List<Account> updAcntList=new List<Account>();
    private static List<Account> updAcntList1=new List<Account>();
    private static List<Account> updAcntList2=new List<Account>();
    private static List<FS_CIF__c> cifList=new List<FS_CIF__c>();
    private static List<Account> hqList=new List<Account>();
    private static FS_Execution_Plan__c executionPlan;
    private static FS_Installation__c installation;
    private static Profile fetSysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_FETADMIN);
    
    @testSetup
    private static void loadTestData(){
        Integer count=0;
         List<Disable_Trigger__c> triggerList = new List<Disable_Trigger__c>();
        List<String> disTriggersRec = new List<String>{'FSAccountBusinessProcess','FSInstallationBusinessProcess','FSExecutionPlanTriggerHandler'};
            for(String str:disTriggersRec){
                triggerList.add(new Disable_Trigger__c(Name=str,IsActive__c=false));
            }
        insert triggerList;
        final List<Account> hqCustList= FSTestFactory.createTestAccount(true,4,FSUtil.getObjectRecordTypeId(Account.SObjectType,'FS Headquarters'));
        final List<User> userLst = new List<User>();
        final User sysAdmin = [Select id from User where id =: UserInfo.getUserId()];
        System.runAs(sysAdmin){
            final Profile comProf = FSTestFactory.getProfileId('FS COM_P');
            final User comUserID = FSTestFactory.createUser(comProf.id);
            userLst.add(comUserID);
            final Profile fpsProf = FSTestFactory.getProfileId(FPS);
            final User fpsUserID = FSTestFactory.createUser(fpsProf.id);
            userLst.add(fpsUserID);
        }
        insert userLst;
        //Create Account Team Member
        final List<AccountTeamMember__c> atmLst = new List<AccountTeamMember__c>();
        final AccountTeamMember__c atmCom=new AccountTeamMember__c();
        atmCom.AccountId__c=hqCustList[0].id;
        atmCom.TeamMemberRole__c =COM;
        atmCom.UserId__c =userLst[0].id;
        atmLst.add(atmCom);
        final AccountTeamMember__c atmSales=new AccountTeamMember__c();
        atmSales.AccountId__c=hqCustList[0].id;
        atmSales.TeamMemberRole__c ='Sales Team Member';
        atmSales.UserId__c =userLst[0].id;
        atmLst.add(atmSales);
        Insert atmLst;
        
        system.runAs(userLst[1])
        {
            //Create Contact
            final Contact cntct = FSTestUtil.createTestContact(hqCustList[0].id, 'New Contact', false);
            cntct.phone='9874563210';
            cntct.email='newcontact@mail.com';
            insert cntct;    
        }
        
        //Create Outlets
        final List<Account> outletCustList= FSTestFactory.createTestAccount(false,25,FSUtil.getObjectRecordTypeId(Account.SObjectType,'FS Outlet'));
        for(Account acc:outletCustList){
            acc.FS_Headquarters__c = hqCustList.get(0).id;
            acc.FS_ACN__c = '00001673'+count;
            count++;
        }
        Insert outletCustList;
        //Creating cifHead
        cifHead = new CIF_Header__c();
        cifHead.Name =hqCustList[0].name+' V.0';
        cifHead.FS_Version__c = 10.02;
        cifHead.FS_HQ__c=hqCustList[0].id;
        cifHead.FS_Status__c=PROG_STATUS;
        insert cifHead;
        //Creating CIF records
        final List<FS_CIF__c> cifLst = new  List<FS_CIF__c>();
        final FS_CIF__c cif = new FS_CIF__c();
        cif.CIF_Head__c = cifHead.id;
        cif.FS_Account__c = outletCustList[0].id;
        cif.FS_Headquarters__c =hqCustList[0].id; 
        cif.FS_Platform1__c='7000';
        cif.FS_Platform1_Qty__c = 15;
        cifLst.add(cif);
        
        final FS_CIF__c cif1 = new FS_CIF__c();
        cif1.CIF_Head__c = cifHead.id;
        //Edited 12 Dec - Assigned different account to cif
        cif1.FS_Account__c = outletCustList[1].id;
        cif1.FS_Headquarters__c =hqCustList[0].id; 
        cif.FS_Platform1__c='7000';
        cif.FS_Platform1_Qty__c = 12;
        cifLst.add(cif1);
        
        insert cifLst;
        //FSTestFactory.createTestDisableTriggerSetting();
    }
    
    
    private static testmethod void testNoReparent(){        
        final Account parentRecord= [SELECT Id,RecordTypeId FROM Account WHERE RecordTypeId=:recTypeHQ  limit 1];
        cifHead = [Select id,Name,FS_Version__c,FS_HQ__c from CIF_Header__c Limit 1];
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
        test.startTest();
        system.runAs(fetSysAdminUser){
            pageLoadUnderHQ(parentRecord.id,cifHead);
        }
        test.stopTest();
                System.assertNotEquals(fetSysAdminUser,null);
    }
    
    private static testmethod void testPartialReparentDiffHQs(){
        
        cifHead = [Select id,Name,FS_Version__c,FS_HQ__c from CIF_Header__c Limit 1];
        final Account parentRecord= [SELECT Id,RecordTypeId FROM Account WHERE RecordTypeId=:recTypeHQ  and id=:cifHead.FS_HQ__c];
        
        cifList=[select id, name,FS_Account__c from FS_CIF__c where CIF_Head__c=:cifHead.id];
        
        hqList=[select id, name from Account where RecordTypeId=:recTypeHQ and id!=:cifHead.FS_HQ__c];
        
        //updating outlet's HQ
        updAcntList1=[Select id, name, fs_headquarters__c from Account where id=:cifList.get(0).fs_account__c];
        updAcntList1[0].FS_Headquarters__c=hqList[0].id;
        
        
        updAcntList2=[Select id, name, fs_headquarters__c from Account where id=:cifList.get(1).fs_account__c];
        updAcntList2[0].FS_Headquarters__c=hqList[1].id;
        
        updAcntList.add(updAcntList1[0]);
        updAcntList.add(updAcntList2[0]);
        
        update updAcntList;
        test.startTest();
        update cifHead;
        
        final List<FS_CIF__c> cifListNew=[select id, name,FS_Account__r.fs_headquarters__c from FS_CIF__c where CIF_Head__c=:cifHead.id];
        system.assertNotEquals(cifHead.FS_HQ__c, cifListNew.get(0).FS_Account__r.fs_headquarters__c);
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
        system.runAs(fetSysAdminUser){
            pageLoadUnderHQ(parentRecord.id,cifHead);
        }  
        test.stopTest();
    }
    
    private static testmethod void testPartialReparent(){        
        
        cifHead = [Select id,Name,FS_Version__c,FS_HQ__c,FS_Status__c from CIF_Header__c Limit 1];
        
        final Account parentRecord= [SELECT Id,RecordTypeId FROM Account WHERE RecordTypeId=:recTypeHQ  and id=:cifHead.FS_HQ__c];
        
        cifList=[select id, name,FS_Account__c from FS_CIF__c where CIF_Head__c=:cifHead.id];
        
        hqList=[select id, name from Account where RecordTypeId=:recTypeHQ and id!=:cifHead.FS_HQ__c];
        
        //updating outlet's HQ
        updAcntList=[Select id, name, fs_headquarters__c from Account where id=:cifList.get(0).fs_account__c];
        updAcntList[0].FS_Headquarters__c=hqList[0].id;
        
        update updAcntList;
        test.startTest();
        final List<FS_CIF__c> cifListNew=[select id, name,FS_Account__r.fs_headquarters__c from FS_CIF__c where CIF_Head__c=:cifHead.id];
        system.assertNotEquals(cifHead.FS_HQ__c, cifListNew.get(0).FS_Account__r.fs_headquarters__c);
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
        system.runAs(fetSysAdminUser){
            pageLoadUnderHQ(parentRecord.id,cifHead);  
        }
       test.stopTest();
    }
    
    private static testmethod void testPartialReparentClosedCIF(){
        
        cifHead = [Select id,Name,FS_Version__c,FS_HQ__c,FS_Status__c,FS_EP__c from CIF_Header__c Limit 1];
        
        cifList=[select id, name,FS_Account__c from FS_CIF__c where CIF_Head__c=:cifHead.id];
        
        //creating execution plan record
        executionPlan=FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,cifhead.FS_HQ__c, false); 
        executionPlan.FS_Execution_Plan_Status__c=PROG_STATUS;
        insert executionPlan;
        
        cifhead.FS_Status__c=CLOSED_STATUS;
        cifhead.FS_EP__c=executionPlan.id;
        update cifhead;
      
        //creating installation record
        installation=FSTestUtil.createInstallationAcc(FSConstants.NEWINSTALLATION,executionPlan.id, cifList.get(0).fs_account__c, true);
                     
        cifList.get(0).FS_Installation__c=installation.id;
        update cifList;
        
        final Account parentRecord= [SELECT Id,RecordTypeId FROM Account WHERE RecordTypeId=:recTypeHQ  and id=:cifHead.FS_HQ__c];
        
        hqList=[select id, name from Account where RecordTypeId=:recTypeHQ and id!=:cifHead.FS_HQ__c];
        
        //updating outlet's HQ
        updAcntList=[Select id, name, fs_headquarters__c from Account where id=:cifList.get(0).fs_account__c];
        updAcntList[0].FS_Headquarters__c=hqList[0].id;
        test.startTest();
        update updAcntList;
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;    
       
        FSUpdateExecutionPlan.updateReparentedInst(cifhead.id);
        system.runAs(fetSysAdminUser){
            final List<FS_CIF__c> cifListNew=[select id, name,FS_Account__r.fs_headquarters__c from FS_CIF__c where CIF_Head__c=:cifHead.id];
            system.assertNotEquals(cifHead.FS_HQ__c, cifListNew.get(0).FS_Account__r.fs_headquarters__c);
            
            pageLoadUnderHQ(parentRecord.id,cifHead);   
        }
        
       test.stopTest();
    }
    
    private static testmethod void testAllReparent(){
        
       
        cifHead = [Select id,Name,FS_Version__c,FS_HQ__c from CIF_Header__c Limit 1];
        final Account parentRecord= [SELECT Id,RecordTypeId FROM Account WHERE RecordTypeId=:recTypeHQ  and id=:cifHead.FS_HQ__c];
        
        cifList=[select id, name,FS_Account__c from FS_CIF__c where CIF_Head__c=:cifHead.id];
        
        hqList=[select id, name from Account where RecordTypeId=:recTypeHQ and id!=:cifHead.FS_HQ__c];
        
        for(FS_CIF__c cif:cifList){
            updAcntIdList.add(cif.FS_Account__c);
        }
        updAcntList=[select id,name from Account where id IN:updAcntIdList];
        for(Account a:updAcntList){
            a.FS_Headquarters__c=hqList[0].id;
        }
        update updAcntList;
        
        cifHead.FS_HQ__c=hqList[0].id;
        update cifHead;
        test.startTest();
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
        system.runAs(fetSysAdminUser){
            
            final List<FS_CIF__c> cifListNew=[select id, name,FS_Account__r.fs_headquarters__c from FS_CIF__c where CIF_Head__c=:cifHead.id];
            system.assertEquals(cifHead.FS_HQ__c, cifListNew.get(0).FS_Account__r.fs_headquarters__c);
            
            pageLoadUnderHQ(parentRecord.id,cifHead); 
        } 
        test.stopTest();
    }
    
    private static void pageLoadUnderHQ(final Id parentRec,final CIF_Header__c cifHead){
        //Sets the current PageReference for the controller
        final PageReference pageRef = Page.FSCustomerInputForm;
        Test.setCurrentPage(pageRef);
        
        //Add parameters to page URL 
        ApexPages.currentPage().getParameters().put(ACCID, parentRec); 
        ApexPages.currentPage().getParameters().put(IDSTRING, cifHead.id);  
        
        
        final ApexPages.StandardController stdcon = new ApexPages.standardController(cifHead);
        final FSCIFReparenting controller=new FSCIFReparenting(stdcon);
        
        system.assertEquals(2,controller.CiFs.size());
        
        controller.processReparent();
        
        updCifHead = [Select id,Name,FS_Version__c,FS_HQ__c,FS_Sales_Rep_Name__c from CIF_Header__c Limit 1];
        
        if(!updAcntList.isEmpty()){
            system.assertEquals(null, updCifHead.FS_Sales_Rep_Name__c);
        }
    
    }
}