force-app/main/default/objects/Account/fields/FS_ACN__c.field-meta.xml
<CustomField>
    <fullName>FS_ACN__c</fullName>
    <description>SAP Legacy Customer #</description>
    <inlineHelpText>ACN is an auto generated field for International Outlets.</inlineHelpText>
    <label>ACN</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Chain__c.field-meta.xml
<CustomField>
    <fullName>FS_Chain__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chain</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for Chain.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Chain</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Headquarters/Outlets</relationshipLabel>
    <relationshipName>Chains</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CIF_Header__c/CIF_Header__c.object-meta.xml
<CustomObject>
    <description>CIF Header</description>
    <label>CIF Header</label>
    <nameField>
        <label>CIF Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CIF Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CIF_Header__c/fields/FS_HQ__c.field-meta.xml
<CustomField>
    <fullName>FS_HQ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HQ Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>CIF_Head</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CIF_Header__c/fields/FS_Version__c.field-meta.xml
<CustomField>
    <fullName>FS_Version__c</fullName>
    <label>Version</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Disable_Trigger__c/Disable_Trigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is only used in case there is a need to deactivate a trigger during data migration. The triggers must be kept activated at all times...</description>
    <label>Disable Trigger</label>
</CustomObject>

force-app/main/default/objects/FS_CIF__c/FS_CIF__c.object-meta.xml
<CustomObject>
    <label>CIF</label>
    <nameField>
        <label>CIF Outlet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CIF</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_CIF__c/fields/CIF_Head__c.field-meta.xml
<CustomField>
    <fullName>CIF_Head__c</fullName>
    <label>CIF Header Name</label>
    <referenceTo>CIF_Header__c</referenceTo>
    <relationshipLabel>CIF</relationshipLabel>
    <relationshipName>CIF</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_CIF__c/fields/FS_Account__c.field-meta.xml
<CustomField>
    <fullName>FS_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related CIF</relationshipLabel>
    <relationshipName>CIF9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_CIF__c/fields/FS_Customer_s_disposition_after_review__c.field-meta.xml
<CustomField>
    <fullName>FS_Customer_s_disposition_after_review__c</fullName>
    <description>Picklist values for CustomerÃ¢â‚¬â„¢s Disposition after review</description>
    <label>CustomerÃ¢â‚¬â„¢s disposition after review</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved by Customer</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Pending Site Survey</fullName>
                <default>true</default>
                <label>Pending Site Survey</label>
            </value>
            <value>
                <fullName>Second Site Survey Pending</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer Decision</fullName>
            </value>
            <value>
                <fullName>Ready for COM</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Reviewed Awaiting Customer Decision</fullName>
                <isActive>false</isActive>
                <label>Reviewed Awaiting Customer Decision</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_CIF__c/fields/FS_EP_Check__c.field-meta.xml
<CustomField>
    <fullName>FS_EP_Check__c</fullName>
    <defaultValue>false</defaultValue>
    <description>used to check which CIF ready for EP creation</description>
    <label>EP Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_CIF__c/fields/FS_Platform1__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform1__c</fullName>
    <label>Platform 1 for Install</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_CIF__c/fields/FS_Platform2__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform2__c</fullName>
    <label>Platform 2 for Install</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_CIF__c/fields/FS_Platform3__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform3__c</fullName>
    <label>Platform 3 for Install</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_CIF__c/fields/FS_Select_Site_assessment_contact__c.field-meta.xml
<CustomField>
    <fullName>FS_Select_Site_assessment_contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Used to select the Site assessment outlet contact name</description>
    <label>Site Assessment Contact Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Contact not found or incomplete.</errorMessage>
        <filterItems>
            <field>Contact.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.FS_Headquarters__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.FS_Contact_Info_Complete__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.Email</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>Contact.Phone</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CIF (Select Site assessment contact)</relationshipLabel>
    <relationshipName>CIFDUjK</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Platform_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3100</fullName>
    </customValue>
    <customValue>
        <fullName>6000</fullName>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
    </customValue>
    <customValue>
        <fullName>7100</fullName>
    </customValue>
    <customValue>
        <fullName>8000</fullName>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
    </customValue>
    <masterLabel>Platform Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FsCIFReParentTriggerHelperTest.cls
@isTest
public class FsCIFReParentTriggerHelperTest {
    public static CIF_Header__c cifHead;
    private static Account chainAcc,accHeadQtr,accOutlet1,accOutlet2,accOutlet3;
    public static  string valTest = 'test';
    public static final string NO9000 = '9000';
    public static final string NO8000 = '8000';
    public static final string NO7000 = '7000';
    public static final string CUSTAPPROVED = 'Approved by Customer'; 
    
    
    private static testmethod void cifCreation(){
        
        Disable_Trigger__c disableTriggerSetting = new Disable_Trigger__c();
        disableTriggerSetting.name='FSCOMNotifications';
        disableTriggerSetting.IsActive__c=true;
        disableTriggerSetting.Trigger_Name__c='FSCOMNotifications' ; 
        insert disableTriggerSetting;  
        
        Disable_Trigger__c disableTriggerSetting2 = new Disable_Trigger__c();
        disableTriggerSetting2.name='FSCIFHeaderTrigger';
        disableTriggerSetting2.IsActive__c=true;
        disableTriggerSetting2.Trigger_Name__c='FSCIFHeaderTrigger' ; 
        insert disableTriggerSetting2;  
        
        final List<Account> hqCustList= FSTestFactory.createTestAccount(true,2,FSUtil.getObjectRecordTypeId(Account.SObjectType,'FS Headquarters'));
        //Creating cifHead
        cifHead = new CIF_Header__c();
        cifHead.Name =hqCustList[0].name+' V.0';
        cifHead.FS_Version__c = 10.02;
        cifHead.FS_HQ__c=hqCustList[0].id;
        insert cifHead;
        
        chainAcc=FSTestUtil.createTestAccount('Test Chain 1',FSConstants.RECORD_TYPE_CHAIN,true);  
        accHeadQtr = FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,false);
        
        accHeadQtr.FS_Chain__c=chainAcc.Id;
        insert accHeadQtr;  
        //Create Outlet Account  
        accOutlet1 = FSTestUtil.createAccountOutlet(valTest,FSConstants.RECORD_TYPE_OUTLET,accHeadQtr.Id, false);
        accOutlet1.Name = valTest;
        accOutlet1.FS_ACN__c = 'test1';
        accOutlet1.ShippingCity = valTest;
        accOutlet1.ShippingState = valTest;
        accoutlet1.RecordTypeId=FSUtil.getObjectRecordTypeId(Account.sObjectType,'FS Outlet');
        insert accOutlet1;
        
        final FS_CIF__c cif1=new FS_CIF__c();
        cif1.FS_Account__c=accOutlet1.Id;
        cif1.CIF_Head__c=cifHead.Id;
        ID headID=cifHead.Id;
        //cif1.FS_Select_Site_assessment_contact__c=contact1.Id;
        cif1.FS_Platform1__c=NO9000;
        cif1.FS_Platform2__c=NO8000;
        cif1.FS_Platform3__c=NO7000;
        cif1.FS_EP_Check__c=true;
        cif1.FS_Customer_s_disposition_after_review__c=CUSTAPPROVED;
        insert cif1;
      
        cifHead.FS_HQ__c=hqCustList[1].id;
        update cifhead;
  
    }
    
}