force-app/main/default/objects/Account/fields/FS_ACN__c.field-meta.xml
<CustomField>
    <fullName>FS_ACN__c</fullName>
    <description>SAP Legacy Customer #</description>
    <inlineHelpText>ACN is an auto generated field for International Outlets.</inlineHelpText>
    <label>ACN</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Outlet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <displayFormat>EP-{0000}</displayFormat>
    <label>Execution Plan#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For Post Install</description>
    <label>Outlet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Outlet</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Post Install Activity</relationshipLabel>
    <relationshipName>Outlet_Post_Execution_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlet Info Summary</relationshipLabel>
    <relationshipName>Outlet_Info_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installations (Outlet)</relationshipLabel>
    <relationshipName>Installations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Valid_Fill_Approved__c.field-meta.xml
<CustomField>
    <fullName>FS_Valid_Fill_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Valid Fill Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/Overall_Status2__c.field-meta.xml
<CustomField>
    <fullName>Overall_Status2__c</fullName>
    <label>Transaction Status</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Equip_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Equip_Type__c</fullName>
    <description>equip type</description>
    <inlineHelpText>This is the JDE Equipment Type value</inlineHelpText>
    <label>Equipment Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <description>Outlet field.</description>
    <label>Outlet</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 3) OR (2 AND 4 AND (5 OR 7)) OR (2 AND 4 AND 6)</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for Outlet.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Outlet</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Outlet</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>7000, 8000, 9000, CCNA Dispenser</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Dispenser</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value>No, Yes</value>
        </filterItems>
        <filterItems>
            <field>Account.Is_Default_FET_International_Outlet__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlet Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Status__c.field-meta.xml
<CustomField>
    <fullName>FS_Status__c</fullName>
    <description>Status.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Enroll</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Hibernate</fullName>
            </value>
            <value>
                <fullName>Wakeup</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Booking Complete</fullName>
            </value>
            <value>
                <fullName>Dispenser Pickup</fullName>
            </value>
            <value>
                <fullName>Dispenser Delivered</fullName>
            </value>
            <value>
                <fullName>In Inventory</fullName>
            </value>
            <value>
                <fullName>Assigned to Outlet</fullName>
            </value>
            <value>
                <fullName>Winterized</fullName>
            </value>
            <value>
                <fullName>Rough Stock</fullName>
            </value>
            <value>
                <fullName>Remaned</fullName>
            </value>
            <value>
                <fullName>To be scrapped by Bottler</fullName>
            </value>
            <value>
                <fullName>To be scrapped by CM</fullName>
            </value>
            <value>
                <fullName>Confirmed Scrapped</fullName>
            </value>
            <value>
                <fullName>Sold to Bottler</fullName>
            </value>
            <value>
                <fullName>Purchased from Bottler</fullName>
            </value>
            <value>
                <fullName>To be Remanufactured</fullName>
            </value>
            <value>
                <fullName>Unenrolled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Re_Manufactured__c.field-meta.xml
<CustomField>
    <fullName>Re_Manufactured__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Re-Manufactured</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/WebServiceHelperTest.cls
@isTest
public class WebServiceHelperTest {
    
    public static Account hQAcc,outletAcc,chainAcc,chainInt,hqInt,bottler;
    public static FS_Outlet_Dispenser__c outletDispenser;   
    private static final string SERIES_7K='7000';
    private static Contact cont;    
    private static FS_Execution_Plan__c executionPlan;
    public static FS_Installation__c installation;
    public static Profile fetSysAdmin;
    
    private static void createTestData(){   
        fetSysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_FETADMIN);
        final List<Account> listAcc = new LIst<Account>();
        //Chain Account
        chainAcc = FSTestUtil.createTestAccount('Test Chain 1',FSConstants.RECORD_TYPE_CHAIN,false);
        chainAcc.FS_ACN__c = '76876876';
        listAcc.add(chainAcc);
        
        //HQ Account
        hQAcc = FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,false);
        hQAcc.FS_ACN__c = '7658765876';
        listAcc.add(hQAcc);
        
        //Creates Outlet Accounts 
        outletAcc = FSTestUtil.createAccountOutlet('Test Outlet 1',FSConstants.RECORD_TYPE_OUTLET,hQAcc.Id, false);
        outletAcc.FS_ACN__c='9874562100';
        listAcc.add(outletAcc);
        //Bottler for international
        bottler=FSTestUtil.createTestAccount('Test Bottler 1',FSConstants.RECORD_TYPE_BOTLLER,false);
        listAcc.add(bottler);
        insert listAcc;
        
        //Creates execution plan
        executionPlan = FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,hQAcc.Id, true);
        
        //creates installation
        installation = FSTestUtil.createInstallationAcc(FSConstants.NEWINSTALLATION,executionPlan.Id,outletAcc.Id,false);
        installation.Overall_Status2__c=FSConstants.x4InstallSchedule;
        installation.FS_Valid_Fill_Approved__c=false;     
        insert installation;
        FSTestFactory.createTestDisableTriggerSetting();
        
        //Platform typpes custom settings
        FSTestFactory.lstPlatform();
        //creates OD  
        outletDispenser = FSTestUtil.createOutletDispenserAllTypes(FSConstants.RT_NAME_CCNA_OD,null,outletAcc.id,null,false);        
    } 
    
    private static testmethod void testreAssignDispenser(){
        createTestData();
        
        outletDispenser.FS_Equip_Type__c = SERIES_7K;
        outletDispenser.FS_Outlet__c=outletAcc.id;
        outletDispenser.Re_Manufactured__c=true;
        insert outletDispenser;
        Test.startTest();
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
        system.runAs(fetSysAdminUser){
            WebServiceHelper.reAssignDispenser(outletDispenser.id);
        }
        Test.stopTest();
        system.assertEquals('Assigned to Outlet', [select id,FS_Status__c from  FS_Outlet_Dispenser__c where id=:outletDispenser.id].FS_Status__c);
    }
    
    
    private static testmethod void testSformNotification(){
        createTestData();
        Test.startTest();
        outletDispenser.FS_Equip_Type__c = SERIES_7K;
        outletDispenser.FS_Outlet__c=outletAcc.id;        
        String returnValue;
        insert outletDispenser;        
        
        cont=FSTestUtil.createTestContact(outletAcc.id, 'TestContact', false);
        cont.Email='test@contact.com';
        insert cont;
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
        system.runAs(fetSysAdminUser){
            returnValue=WebServiceHelper.shippingFormGenerationNotification(outletDispenser.id);
        }
        Test.stopTest();
        system.assertEquals('Success', returnValue);
    }
}