force-app/main/default/objects/Account/fields/FS_Chain__c.field-meta.xml
<CustomField>
    <fullName>FS_Chain__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chain</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for Chain.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Chain</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Headquarters/Outlets</relationshipLabel>
    <relationshipName>Chains</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Outlet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Headquarters</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for HQ.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Headquarters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Equipment_Placement_Questionnaire__c/FS_Equipment_Placement_Questionnaire__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Equipment Placement Questionnaire</label>
</CustomObject>

force-app/main/default/objects/FS_Equipment_Placement_Questionnaire__c/fields/Field_API_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Mapping__c</fullName>
    <label>Field API Mapping</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <displayFormat>EP-{0000}</displayFormat>
    <label>Execution Plan#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <label>Headquarters</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Value does not exist or does not match filter criteria for HQ on EP.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Execution Plans (Headquarters)</relationshipLabel>
    <relationshipName>Execution_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_What_type_of_beverage_station_is_this__c.field-meta.xml
<CustomField>
    <fullName>FS_What_type_of_beverage_station_is_this__c</fullName>
    <label>What type of beverage station is this?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>-None-</fullName>
                <default>true</default>
                <label>-None-</label>
            </value>
            <value>
                <fullName>Self-Serve</fullName>
            </value>
            <value>
                <fullName>Crew Serve</fullName>
            </value>
            <value>
                <fullName>Both Self &amp; Crew Serve (multiple units)</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_What_type_of_install_is_this__c.field-meta.xml
<CustomField>
    <fullName>FS_What_type_of_install_is_this__c</fullName>
    <label>What type of install is this?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>-None-</fullName>
                <default>true</default>
                <label>-None-</label>
            </value>
            <value>
                <fullName>Existing outlet - Dispenser swap-out</fullName>
            </value>
            <value>
                <fullName>New construction - New Install</fullName>
            </value>
            <value>
                <fullName>Remodel â€“ Reinstall</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FSEquipmentPlacementQuestionsTest.cls
@isTest
public  class FSEquipmentPlacementQuestionsTest {
    static Account accchain,accHQ,accOutlet;
    static FS_Execution_Plan__c executionPlan;
    static String recTypeEP=Schema.SObjectType.FS_Execution_Plan__c.getRecordTypeInfosByName().get(FSConstants.EXECUTIONPLAN).getRecordTypeId() ;
    Static void createtestData(){
        
        accchain = FSTestUtil.createTestAccount('Test Chain 1',FSConstants.RECORD_TYPE_CHAIN,true);
        
        accHQ = FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,false);     
        accHQ.FS_Chain__c = accchain.Id;
        insert accHQ;
        accOutlet = FSTestUtil.createAccountOutlet('Test Outlet 1',FSConstants.RECORD_TYPE_OUTLET,accHQ.Id,true);
        
    }
    Static testMethod void fsEquipmentPlacementQuestionsTest(){
        createtestData();
        
        executionPlan=new FS_Execution_Plan__c();
        executionPlan.FS_Headquarters__c= accHQ.Id;
        executionPlan.recordtypeid=recTypeEP;
        Test.startTest();
        insert executionPlan;
        
        FS_Equipment_Placement_Questionnaire__c equipmentCustomSetting=new FS_Equipment_Placement_Questionnaire__c();
        equipmentCustomSetting.name='1';
        equipmentCustomSetting.Field_API_Mapping__c='FS_What_type_of_install_is_this__c';
        equipmentCustomSetting.Question_Label__c='What type of install is this?';
        insert equipmentCustomSetting;
        FS_Equipment_Placement_Questionnaire__c equipmentCustomSetting2=new FS_Equipment_Placement_Questionnaire__c();
        equipmentCustomSetting2.name='2';
        equipmentCustomSetting2.Field_API_Mapping__c='FS_What_type_of_beverage_station_is_this__c';
        equipmentCustomSetting2.Question_Label__c='What type of beverage station is this?';
        insert equipmentCustomSetting2;
        
        ApexPages.StandardController controller=new ApexPages.StandardController(executionPlan);
        FSEquipmentPlacementQuestionsCTRL fsEqipQues= new FSEquipmentPlacementQuestionsCTRL(controller);
        fsEqipQues.Save();
        fsEqipQues.Edit();
        fsEqipQues.cancel();
        fsEqipQues.setAllNotApplicable();
        Test.stopTest();
    }
    
    Static testMethod void fsEquipmentPlacementQuestionsTestNegative(){
        createtestData();
        
        executionPlan=new FS_Execution_Plan__c();
        executionPlan.FS_Headquarters__c= accHQ.Id;
        executionPlan.recordtypeid=recTypeEP;
        Test.startTest();
        insert executionPlan;
        
        FS_Equipment_Placement_Questionnaire__c equipmentCustomSetting=new FS_Equipment_Placement_Questionnaire__c();
        equipmentCustomSetting.name='1';
        equipmentCustomSetting.Field_API_Mapping__c='FS_What_type_of_install_is_this__c';
        equipmentCustomSetting.Question_Label__c='What type of install is this?';
        insert equipmentCustomSetting;
        FS_Equipment_Placement_Questionnaire__c equipmentCustomSetting2=new FS_Equipment_Placement_Questionnaire__c();
        equipmentCustomSetting2.name='2';
        equipmentCustomSetting2.Field_API_Mapping__c='FS_What_type_of_beverage_station_is_this__c';
        equipmentCustomSetting2.Question_Label__c='What type of beverage station is this?';
        insert equipmentCustomSetting2;
        system.debug('aaaa'+FS_Equipment_Placement_Questionnaire__c.getall().values());
        
        ApexPages.StandardController controller=new ApexPages.StandardController(executionPlan);
        FSEquipmentPlacementQuestionsCTRL fsEqipQues= new FSEquipmentPlacementQuestionsCTRL(controller);
        fsEqipQues.isSetAllNotApplicable=true;
        fsEqipQues.setAllNotApplicable();
        Test.stopTest();
    }
    Static testMethod void fsEquipmentPlacementQuestionsTestNegative2(){
        createtestData();
        executionPlan=new FS_Execution_Plan__c();
        executionPlan.FS_Headquarters__c= accHQ.Id;
        executionPlan.recordtypeid=recTypeEP;
        
        Test.startTest();
        insert executionPlan;
        
        Pagereference pg = Page.FSEquipmentPlacementQuestions;
        Test.setCurrentPage(pg);
        pg.getParameters().put('displaySaveandClose','true');
        FS_Equipment_Placement_Questionnaire__c equipmentCustomSetting=new FS_Equipment_Placement_Questionnaire__c();
        equipmentCustomSetting.name='1';
        equipmentCustomSetting.Field_API_Mapping__c='FS_What_type_of_install_is_this__c';
        equipmentCustomSetting.Question_Label__c='What type of install is this?';
        insert equipmentCustomSetting;
        FS_Equipment_Placement_Questionnaire__c equipmentCustomSetting2=new FS_Equipment_Placement_Questionnaire__c();
        equipmentCustomSetting2.name='2';
        equipmentCustomSetting2.Field_API_Mapping__c='FS_What_type_of_beverage_station_is_this__c';
        equipmentCustomSetting2.Question_Label__c='What type of beverage station is this?';
        insert equipmentCustomSetting2;
        system.debug('aaaa'+FS_Equipment_Placement_Questionnaire__c.getall().values());
        
        ApexPages.StandardController controller=new ApexPages.StandardController(executionPlan);
        FSEquipmentPlacementQuestionsCTRL fsEqipQues= new FSEquipmentPlacementQuestionsCTRL(controller);
        
        fsEqipQues.Edit();
        Test.stopTest();
    }
}