force-app/main/default/objects/Account/fields/FS_CE_Enabled__c.field-meta.xml
<CustomField>
    <fullName>FS_CE_Enabled__c</fullName>
    <label>FET Enable Consumer Engagement</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FS_LTO__c.field-meta.xml
<CustomField>
    <fullName>FS_LTO__c</fullName>
    <label>FET Limited Time Offer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Promo_Enabled__c.field-meta.xml
<CustomField>
    <fullName>FS_Promo_Enabled__c</fullName>
    <label>FET Promotion Enabled</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Post_Install_Marketing__c/FS_Post_Install_Marketing__c.object-meta.xml
<CustomObject>
    <label>Post Install Marketing</label>
    <nameField>
        <displayFormat>PIM-{0000}</displayFormat>
        <label>Post Install Marketing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Post Install Marketing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Post_Install_Marketing__c/fields/FS_Account__c.field-meta.xml
<CustomField>
    <fullName>FS_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Post Install Marketing</relationshipLabel>
    <relationshipName>Post_Install_Marketing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Post_Install_Marketing__c/fields/FS_Cncl_Post_Install_Marketting_fields__c.field-meta.xml
<CustomField>
    <fullName>FS_Cncl_Post_Install_Marketting_fields__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Cancelled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Post_Install_Marketing__c/fields/FS_Enable_CE_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Enable_CE_Effective_Date__c</fullName>
    <label>FET Enable CE Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Post_Install_Marketing__c/fields/FS_Enable_Consumer_Engagement__c.field-meta.xml
<CustomField>
    <fullName>FS_Enable_Consumer_Engagement__c</fullName>
    <label>FET Enable Consumer Engagement</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Post_Install_Marketing__c/fields/FS_LTO__c.field-meta.xml
<CustomField>
    <fullName>FS_LTO__c</fullName>
    <inlineHelpText>Select &quot;No&quot; in case an existing Limited Time Offer on the dispenser needs to be removed</inlineHelpText>
    <label>FET Limited Time Offer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Post_Install_Marketing__c/fields/FS_LTO_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_LTO_Effective_Date__c</fullName>
    <label>FET Limited Time Offer Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Post_Install_Marketing__c/fields/FS_Promo_Enabled__c.field-meta.xml
<CustomField>
    <fullName>FS_Promo_Enabled__c</fullName>
    <label>FET Promotion Enabled</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Post_Install_Marketing__c/fields/FS_Promo_Enabled_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Promo_Enabled_Effective_Date__c</fullName>
    <label>FET Promotion Enabled Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/FSMarketingFieldCopyToAccountBatch.cls
global class FSMarketingFieldCopyToAccountBatch implements Database.batchable <sobject> {
    public Date today;
    
    public FSMarketingFieldCopyToAccountBatch(final Date today){
        this.today=today;
    }
    
    global Database.QueryLocator start(final Database.BatchableContext batchCon){
        
        return Database.getQueryLocator('select id,FS_Cncl_Post_Install_Marketting_fields__c,FS_Enable_Consumer_Engagement__c,FS_Enable_CE_Effective_Date__c,FS_LTO__c,FS_LTO_Effective_Date__c,FS_Promo_Enabled__c,FS_Promo_Enabled_Effective_Date__c,FS_Account__r.id,FS_Account__r.FS_CE_Enabled__c,FS_Account__r.FS_LTO__c,FS_Account__r.FS_Promo_Enabled__c from FS_Post_Install_Marketing__c where FS_Enable_CE_Effective_Date__c=:today or FS_LTO_Effective_Date__c=:today or FS_Promo_Enabled_Effective_Date__c=:today'  );       
        
    }
    
    global void execute(final Database.BatchableContext batchCon, final List<sObject> scope){
        List<Account> updateAccountList =new List<Account>();
        Map<id,Account> accMaptoUpdate=new Map<id,account>();
        List<FS_Post_Install_Marketing__c> allPIM = (List<FS_Post_Install_Marketing__c>)scope;
        Account relatedAcc;
        
        for(FS_Post_Install_Marketing__c pim:allPIM){
            if(pim.FS_Account__r.id!=null && !pim.FS_Cncl_Post_Install_Marketting_fields__c){
                Boolean check1=false;
                
                relatedAcc = new Account(id=pim.FS_Account__r.id,FS_CE_Enabled__c=pim.FS_Account__r.FS_CE_Enabled__c,FS_LTO__c=pim.FS_Account__r.FS_LTO__c,FS_Promo_Enabled__c=pim.FS_Account__r.FS_Promo_Enabled__c);
                
                if(accMaptoUpdate.containskey(relatedAcc.id)){
                    relatedAcc=accMaptoUpdate.get(relatedAcc.id);
                }
                
                
                if(pim.FS_Enable_CE_Effective_Date__c == today && pim.FS_Enable_Consumer_Engagement__c!=relatedAcc.FS_CE_Enabled__c){
                    relatedAcc.FS_CE_Enabled__c=pim.FS_Enable_Consumer_Engagement__c;
                    check1=true;
                }
                if(pim.FS_LTO_Effective_Date__c == today && pim.FS_LTO__c!=relatedAcc.FS_LTO__c){
                    relatedAcc.FS_LTO__c=pim.FS_LTO__c;
                    check1=true;
                }
                if(pim.FS_Promo_Enabled_Effective_Date__c == today && pim.FS_Promo_Enabled__c!=relatedAcc.FS_Promo_Enabled__c){
                    relatedAcc.FS_Promo_Enabled__c=pim.FS_Promo_Enabled__c;
                    check1=true;
                }
                
                if(check1==true){
                    accMaptoUpdate.put(relatedAcc.id,relatedAcc);
                }
                
            }
        }
        //Update Account
        if(!accMaptoUpdate.isEmpty()){
            Database.update(accMaptoUpdate.values(),false);
        }
    }
    
    
    global void finish(final Database.BatchableContext info){   
        system.debug('info'+info);
    }
    
    
}