force-app/main/default/objects/Account/fields/FS_Chain__c.field-meta.xml
<CustomField>
    <fullName>FS_Chain__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chain</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for Chain.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Chain</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Headquarters/Outlets</relationshipLabel>
    <relationshipName>Chains</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Outlet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Disable_Trigger__c/Disable_Trigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is only used in case there is a need to deactivate a trigger during data migration. The triggers must be kept activated at all times...</description>
    <label>Disable Trigger</label>
</CustomObject>

force-app/main/default/objects/Error_Message_Resend_Counter__c/Error_Message_Resend_Counter__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Error Message Resend Counter</label>
</CustomObject>

force-app/main/default/objects/Error_Message_Resend_Counter__c/fields/Resend_Number__c.field-meta.xml
<CustomField>
    <fullName>Resend_Number__c</fullName>
    <label>Resend Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <displayFormat>EP-{0000}</displayFormat>
    <label>Execution Plan#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlet Info Summary</relationshipLabel>
    <relationshipName>Outlet_Info_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Serial_Number2__c.field-meta.xml
<CustomField>
    <fullName>FS_Serial_Number2__c</fullName>
    <description>Serial Number/Asset Tag.</description>
    <label>JDE Serial Number/Asset Tag</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HttpStatusCodes__c/HttpStatusCodes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Stores HTTP status code to that are to be retried for Outlet Dispenser callout</description>
    <label>HttpStatusCodes</label>
</CustomObject>

force-app/main/default/objects/OutboundServiceDetails__c/OutboundServiceDetails__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>OutboundServiceDetails</label>
</CustomObject>

force-app/main/default/objects/Service_Message_Error_Log__c/Service_Message_Error_Log__c.object-meta.xml
<CustomObject>
    <label>Service Message Error Log</label>
    <nameField>
        <displayFormat>ERR-{00000}</displayFormat>
        <label>Service Message Error Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Message Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Message_Error_Log__c/fields/Error_Code__c.field-meta.xml
<CustomField>
    <fullName>Error_Code__c</fullName>
    <label>Error Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Message_Error_Log__c/fields/FS_Serial_Number_Asset_Tag__c.field-meta.xml
<CustomField>
    <fullName>FS_Serial_Number_Asset_Tag__c</fullName>
    <description>This is the serial number of the Outlet Dispenser</description>
    <inlineHelpText>This is the serial number of the Outlet Dispenser</inlineHelpText>
    <label>Serial Number/Asset Tag</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Message_Error_Log__c/fields/Outlet_Dispenser__c.field-meta.xml
<CustomField>
    <fullName>Outlet_Dispenser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet Dispenser</label>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipLabel>Service Message Error Logs</relationshipLabel>
    <relationshipName>Service_Message_Error_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Message_Error_Log__c/fields/Request_Message__c.field-meta.xml
<CustomField>
    <fullName>Request_Message__c</fullName>
    <label>Request Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Service_Message_Error_Log__c/fields/ServiceName__c.field-meta.xml
<CustomField>
    <fullName>ServiceName__c</fullName>
    <label>ServiceName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FSServiceMessageErrorLogSchedulerTest.cls
/**************************************************************************************
Apex Class Name     : FSServiceMessageErrorLogSchedulerTest
Version             : 1.0
Function            : This test class is for FSServiceMessageErrorLogScheduler Class code coverage. 
Modification Log    : 
* Developer         :    Date              Description
*-------------------------------------------------------------------------------------                 
* Infosys             09/09/              Original Version 
*					  05/29/2018		  Removed usage of OutboundServiceDetails__c customSetting as part of FOT project
**************************************************************************************/
//Created on 9th Sep. FSServiceMessageErrorLogScheduler never had a test class until now
@isTest
public class FSServiceMessageErrorLogSchedulerTest {
    @testSetup
    static void createTestData() {
        
        //create platform type custom settings
        FSTestUtil.insertPlatformTypeCustomSettings();
        
        //Custom Setting Values
        List<HttpStatusCodes__c> statusCodeList=new List<HttpStatusCodes__c>();
        
        HttpStatusCodes__c sc2=new HttpStatusCodes__c(Name='204');
        statusCodeList.add(sc2);
        HttpStatusCodes__c sc3=new HttpStatusCodes__c(Name='400');
        statusCodeList.add(sc3);
        HttpStatusCodes__c sc4=new HttpStatusCodes__c(Name='401');
        statusCodeList.add(sc4);
        HttpStatusCodes__c sc5=new HttpStatusCodes__c(Name='500');
        statusCodeList.add(sc5);
        HttpStatusCodes__c sc6=new HttpStatusCodes__c(Name='502');
        statusCodeList.add(sc6);
        HttpStatusCodes__c sc7=new HttpStatusCodes__c(Name='503');
        statusCodeList.add(sc7);
        HttpStatusCodes__c sc8=new HttpStatusCodes__c(Name='504');
        statusCodeList.add(sc8);
        
        insert statusCodeList;
        
        List<Error_Message_Resend_Counter__c> errormessageResendCounterList=new List<Error_Message_Resend_Counter__c>();
        Error_Message_Resend_Counter__c resendCounterInstance1= new Error_Message_Resend_Counter__c ();
        resendCounterInstance1.Name='FSServiceMessageErrorBatchSize';
        resendCounterInstance1.Resend_Number__c=1;
        errormessageResendCounterList.add(resendCounterInstance1);
        
        Error_Message_Resend_Counter__c resendCounterInstance2= new Error_Message_Resend_Counter__c ();
        resendCounterInstance2.Name='Service Message Error';
        resendCounterInstance2.Resend_Number__c=1;
        errormessageResendCounterList.add(resendCounterInstance2);
        insert errormessageResendCounterList;
    }
    
    static testMethod void testScheduler(){
        
        List<Disable_Trigger__c> triggerList = new List<Disable_Trigger__c>();
        List<String> disTriggersRec = new List<String>{'FSAccountBusinessProcess','FSInstallationBusinessProcess','FSExecutionPlanTriggerHandler'};
            for(String str:disTriggersRec){
                triggerList.add(new Disable_Trigger__c(Name=str,IsActive__c=false));
            }
        insert triggerList;
        //set mock callout
        Test.setMock(HttpCalloutMock.class, new FSFETNMSConnectorMock());
        
        //Create Chain
        Account accChain=FSTestUtil.createTestAccount('Test Chain 1',FSConstants.RECORD_TYPE_CHAIN,true);
        Account accHQ=FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,false);
        accHQ.FS_Chain__c=accChain.Id;
        insert accHQ;
        
        Account accOutlet=FSTestUtil.createAccountOutlet('Test Outlet 1',FSConstants.RECORD_TYPE_OUTLET,accHQ.Id,false);
        accOutlet.FS_Chain__c=accChain.Id;
        insert accOutlet;
        //EP of 8k type
        FS_Execution_Plan__c executionPlan8k=FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,accHQ.Id,true);
        //IP of 8k type
        FS_Installation__c  installation8k=FSTestUtil.createInstallationAcc(FSConstants.NEWINSTALLATION,executionPlan8k.Id,accOutlet.Id,true);      
        
        //for 200 Recods
        //Od recordType:8000
        Id od8kRecType=Schema.SObjectType.FS_Outlet_Dispenser__c.getRecordTypeInfosByName().get(FSConstants.RT_NAME_CCNA_OD).getRecordTypeId();
        List<FS_Outlet_Dispenser__c > outletDispenserList=new List<FS_Outlet_Dispenser__c>();
        outletDispenserList=FSTestFactory.createTestOutletDispenser(installation8k.Id,accOutlet.Id,od8kRecType,true,1,null);        
        
        //Insert Service error log records
        List<Service_Message_Error_Log__c > serviceErrorLogs=new List<Service_Message_Error_Log__c >();
        for(FS_Outlet_Dispenser__c od : outletDispenserList){
            Service_Message_Error_Log__c errorLog=new Service_Message_Error_Log__c ();
            errorLog.Outlet_Dispenser__c=od.Id;
            errorLog.FS_Serial_Number_Asset_Tag__c=od.FS_Serial_Number2__c;
            errorLog.ServiceName__c='MasterDataCreate';
            errorLog.Resend__c=true;
            errorLog.Error_Code__c='400';
            errorLog.Request_Message__c='no body';
            serviceErrorLogs.add(errorLog);
        }
        insert serviceErrorLogs;
        
        
        Test.startTest();
        try{
            String cronExp = '0 0 23 * * ?';
            FSServiceMessageErrorLogScheduler scheObj = new FSServiceMessageErrorLogScheduler();
            String jobId = system.schedule('Test Scheduler Job', cronExp, scheObj);
            CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
            System.assertEquals(cronExp,ct.CronExpression);
            System.assertEquals(0, ct.TimesTriggered);

        }catch(exception e) {}
        Test.stopTest();
        
    }
    
    static testMethod void testSchedulerfailure(){
         List<Disable_Trigger__c> triggerList = new List<Disable_Trigger__c>();
        List<String> disTriggersRec = new List<String>{'FSAccountBusinessProcess','FSInstallationBusinessProcess','FSExecutionPlanTriggerHandler'};
            for(String str:disTriggersRec){
                triggerList.add(new Disable_Trigger__c(Name=str,IsActive__c=false));
            }
        insert triggerList;
        //set mock callout
        Test.setMock(HttpCalloutMock.class, new FSFETNMSConnectorMockFailure());
        
        //Create Chain
        Account accChain=FSTestUtil.createTestAccount('Test Chain 1',FSConstants.RECORD_TYPE_CHAIN,true);
        Account accHQ=FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,false);
        accHQ.FS_Chain__c=accChain.Id;
        insert accHQ;
        
        Account accOutlet=FSTestUtil.createAccountOutlet('Test Outlet 1',FSConstants.RECORD_TYPE_OUTLET,accHQ.Id,false);
        accOutlet.FS_Chain__c=accChain.Id;
        insert accOutlet;
        //EP of 8k type
        FS_Execution_Plan__c executionPlan8k=FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,accHQ.Id,true);
        //IP of 8k type
        FS_Installation__c  installation8k=FSTestUtil.createInstallationAcc(FSConstants.NEWINSTALLATION,executionPlan8k.Id,accOutlet.Id,true);      
        
        //for 200 Recods
        //Od recordType:8000
        Id od8kRecType=Schema.SObjectType.FS_Outlet_Dispenser__c.getRecordTypeInfosByName().get(FSConstants.RT_NAME_CCNA_OD).getRecordTypeId();
        List<FS_Outlet_Dispenser__c > outletDispenserList=new List<FS_Outlet_Dispenser__c>();
        outletDispenserList=FSTestFactory.createTestOutletDispenser(installation8k.Id,accOutlet.Id,od8kRecType,true,1,null);        
        
        //Insert Service error log records
        List<Service_Message_Error_Log__c > serviceErrorLogs=new List<Service_Message_Error_Log__c >();
        for(FS_Outlet_Dispenser__c od : outletDispenserList){
            Service_Message_Error_Log__c errorLog=new Service_Message_Error_Log__c ();
            errorLog.Outlet_Dispenser__c=od.Id;
            errorLog.FS_Serial_Number_Asset_Tag__c=od.FS_Serial_Number2__c;
            errorLog.ServiceName__c='MasterDataCreate';
            errorLog.Resend__c=true;
            errorLog.Error_Code__c='400';
            errorLog.Request_Message__c='no body';
            serviceErrorLogs.add(errorLog);
        }
        insert serviceErrorLogs;
        
        
        Test.startTest();
        try{
            
            Id jobId = DataBase.executeBatch(new BatchForErrorHandling(),200);
            system.assert(jobId != null);
        }catch(exception e) {}
        Test.stopTest();
    }
    
}