force-app/main/default/objects/Account/fields/FS_Chain__c.field-meta.xml
<CustomField>
    <fullName>FS_Chain__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chain</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for Chain.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Chain</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Headquarters/Outlets</relationshipLabel>
    <relationshipName>Chains</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Valid_Fill__c.field-meta.xml
<CustomField>
    <fullName>FS_Valid_Fill__c</fullName>
    <label>Valid Fill</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Flavor_Change__c/Flavor_Change__c.object-meta.xml
<CustomObject>
    <label>Flavor Change</label>
    <nameField>
        <displayFormat>FC-{0000}</displayFormat>
        <label>Flavor Change Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flavor Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flavor_Change__c/fields/FS_Outlet_HQ_Chain__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_HQ_Chain__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet/Headquarters/Chain</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Flavor Changes</relationshipLabel>
    <relationshipName>Flavor_Changes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Post_Install_Marketing__c/FS_Post_Install_Marketing__c.object-meta.xml
<CustomObject>
    <label>Post Install Marketing</label>
    <nameField>
        <displayFormat>PIM-{0000}</displayFormat>
        <label>Post Install Marketing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Post Install Marketing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Post_Install_Marketing__c/fields/FS_Account__c.field-meta.xml
<CustomField>
    <fullName>FS_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Post Install Marketing</relationshipLabel>
    <relationshipName>Post_Install_Marketing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Post_Install_Marketing__c/fields/FS_RcdIDForCncl__c.field-meta.xml
<CustomField>
    <fullName>FS_RcdIDForCncl__c</fullName>
    <label>Record ID For Cancel</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/FS_Valid_Fill__c.object-meta.xml
<CustomObject>
    <label>Valid Fill</label>
    <nameField>
        <displayFormat>VF-{0000}</displayFormat>
        <label>Valid Fill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Valid Fill</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Valid_Fill__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Post-Install Valid Fill</relationshipLabel>
    <relationshipName>Vailid_Fill</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/fields/FS_RcdIDForCncl__c.field-meta.xml
<CustomField>
    <fullName>FS_RcdIDForCncl__c</fullName>
    <label>Record ID For Cancel</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FSBatchCopyChaintoHq.cls
/*
Copying flavor changes the copy to low levels from Chain to HQ
Author: Srinivas B
Date:05/04/2015
*/
global class FSBatchCopyChaintoHq implements  Database.Batchable<sObject>, Database.Stateful{

   public String recId;
   public Flavor_Change__c fc;
   public FS_Post_Install_Marketing__c PM;
   public FS_Valid_Fill__c VF;
     //Create a Set for  HQ to store outlets having installations  and Outlet Dispensers records 
    Set<Id> HQIdSet=new Set<Id>();     
     
 
   //Constructor
   public FSBatchCopyChaintoHq (String recId,Flavor_Change__c fc,FS_Post_Install_Marketing__c PM,FS_Valid_Fill__c VF) {
     this.recId = recId;
     this.fc=fc;
     this.PM=PM;
     this.VF=VF;
    
   }

   /****************************************************************************
    //Start the batch and query
    /***************************************************************************/
    global Database.QueryLocator start(Database.BatchableContext BC){
         
        return Database.getQueryLocator([Select Id From Account where FS_Chain__c =: recId And RecordType.Name = :FSConstants.RECORD_TYPE_NAME_HQ ]); 

    }

    /****************************************************************************
    //Process a batch
    /***************************************************************************/
    global void execute(Database.BatchableContext BC, List<sObject> Hqlist){
          //List of new FC to be inserted into HQ related list
    List<Flavor_Change__c> lstClonedFCHQ= new List<Flavor_Change__c>();
    
    //List of new FC to be inserted into HQ related list
    List<FS_Post_Install_Marketing__c> lstClonedMarketingHQ= new List<FS_Post_Install_Marketing__c>();
    
    //List of new VF to be inserted into HQ
    List<FS_Valid_Fill__c> lstClonedValidFillHQ = new List<FS_Valid_Fill__c>();
         
        for(Account acc : (List<Account>)Hqlist){
          if(fc!=null){  
          Flavor_Change__c newFC =  fc.clone();
          newFC.FS_Outlet_HQ_Chain__c = acc.Id;          
          newFC.FS_RcdIDForCncl__c=fc.id;
          lstClonedFCHQ.add(newFC);
          HQIdSet.add(acc.id);
          } 
         if(PM!=null){  
          FS_Post_Install_Marketing__c newPIM =  PM.clone();
          newPIM.FS_Account__c = acc.Id;
          newPIM.FS_RcdIDForCncl__c=PM.Id;
          lstClonedMarketingHQ.add(newPIM);
          HQIdSet.add(acc.id);
          } 
         if(VF!=null){  
         FS_Valid_Fill__c newVF =  VF.clone();
          newVF.FS_Outlet__c  = acc.Id;
          lstClonedValidFillHQ.add(newVF);
          HQIdSet.add(acc.id);
          } 
          
        }
         try{
         insert lstClonedFCHQ;
         insert lstClonedMarketingHQ;
         insert lstClonedValidFillHQ;
         }
         Catch(Exception ex)
         {      
         }
 
    }

     /****************************************************************************
    //finish the batch
    /***************************************************************************/
    global void finish(Database.BatchableContext BC){
   
    if(!HQIdSet.isEmpty()){
    if(FC!=null)
        Database.Executebatch(new FSBatchCopyHqtoOutlet(null,fc,null,null,HQIdSet),200 );
    if(PM!=null)
        Database.Executebatch(new FSBatchCopyHqtoOutlet(null,null,PM,null,HQIdSet),200 );
    if(VF!=null)
        Database.Executebatch(new FSBatchCopyHqtoOutlet(null,null,null,VF,HQIdSet),200 );
     }
     

    }

}