force-app/main/default/objects/Account/fields/FS_CE_Enabled__c.field-meta.xml
<CustomField>
    <fullName>FS_CE_Enabled__c</fullName>
    <label>FET Enable Consumer Engagement</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FS_LTO__c.field-meta.xml
<CustomField>
    <fullName>FS_LTO__c</fullName>
    <label>FET Limited Time Offer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Promo_Enabled__c.field-meta.xml
<CustomField>
    <fullName>FS_Promo_Enabled__c</fullName>
    <label>FET Promotion Enabled</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Post_Install_Marketing__c/FS_Post_Install_Marketing__c.object-meta.xml
<CustomObject>
    <label>Post Install Marketing</label>
    <nameField>
        <displayFormat>PIM-{0000}</displayFormat>
        <label>Post Install Marketing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Post Install Marketing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Post_Install_Marketing__c/fields/FS_Account__c.field-meta.xml
<CustomField>
    <fullName>FS_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Post Install Marketing</relationshipLabel>
    <relationshipName>Post_Install_Marketing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Post_Install_Marketing__c/fields/FS_Enable_CE_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Enable_CE_Effective_Date__c</fullName>
    <label>FET Enable CE Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Post_Install_Marketing__c/fields/FS_Enable_Consumer_Engagement__c.field-meta.xml
<CustomField>
    <fullName>FS_Enable_Consumer_Engagement__c</fullName>
    <label>FET Enable Consumer Engagement</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Post_Install_Marketing__c/fields/FS_LTO__c.field-meta.xml
<CustomField>
    <fullName>FS_LTO__c</fullName>
    <inlineHelpText>Select &quot;No&quot; in case an existing Limited Time Offer on the dispenser needs to be removed</inlineHelpText>
    <label>FET Limited Time Offer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Post_Install_Marketing__c/fields/FS_LTO_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_LTO_Effective_Date__c</fullName>
    <label>FET Limited Time Offer Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Post_Install_Marketing__c/fields/FS_Promo_Enabled__c.field-meta.xml
<CustomField>
    <fullName>FS_Promo_Enabled__c</fullName>
    <label>FET Promotion Enabled</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Post_Install_Marketing__c/fields/FS_Promo_Enabled_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Promo_Enabled_Effective_Date__c</fullName>
    <label>FET Promotion Enabled Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/FSPostInstallMarketingHelper.cls
public with Sharing class FSPostInstallMarketingHelper {
    
    public static void updateAccountonToday(){
        Map<id,Account> accToUpdate = new Map<id,Account>();
        Set<id> accIDSet=new Set<id>();
        
        for(FS_Post_Install_Marketing__c pim:(List<FS_Post_Install_Marketing__c>)Trigger.New){
            if(pim.FS_Account__c!=null && (pim.FS_Enable_CE_Effective_Date__c==System.today() || pim.FS_LTO_Effective_Date__c==system.today() || pim.FS_Promo_Enabled_Effective_Date__c==system.today())){
                   accIDSet.add(pim.FS_Account__c);             
            }
        }
        
        Map<id,Account>  relatedAccountsMap=new Map<id,Account>([select id,FS_CE_Enabled__c,FS_LTO__c,FS_Promo_Enabled__c from Account where id IN :accIDSet]);
        system.debug('Related ACc'+ relatedAccountsMap);
        Account relatedAcc;
        for(FS_Post_Install_Marketing__c pim:(List<FS_Post_Install_Marketing__c>)Trigger.New){
            Boolean check1=false;
            if(pim.FS_Account__c!=null && relatedAccountsMap.containsKey(pim.FS_Account__c)){
               	
                relatedAcc = relatedAccountsMap.get(pim.FS_Account__c);
                
                if(accToUpdate.containskey(relatedAcc.id)){
                    relatedAcc=accToUpdate.get(relatedAcc.id);
                }
                
                if(pim.FS_Enable_CE_Effective_Date__c == system.today() && pim.FS_Enable_Consumer_Engagement__c!=relatedAcc.FS_CE_Enabled__c){
                    relatedAcc.FS_CE_Enabled__c=pim.FS_Enable_Consumer_Engagement__c;
                    check1=true;
                }
                
                if(pim.FS_LTO_Effective_Date__c == system.today() && pim.FS_LTO__c!=relatedAcc.FS_LTO__c){
                    relatedAcc.FS_LTO__c=pim.FS_LTO__c;
                    check1=true;
                }
                
                if(pim.FS_Promo_Enabled_Effective_Date__c == system.today() && pim.FS_Promo_Enabled__c!=relatedAcc.FS_Promo_Enabled__c){
                    relatedAcc.FS_Promo_Enabled__c=pim.FS_Promo_Enabled__c;
                    check1=true;
                }
                
                if(check1=true){
                    
                    accToUpdate.put(relatedAcc.id,relatedAcc);
                    
                }
            }
        }
        
        update(accToUpdate.Values());
        
    }
    
}