force-app/main/default/objects/Account/fields/FS_Chain__c.field-meta.xml
<CustomField>
    <fullName>FS_Chain__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chain</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for Chain.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Chain</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Headquarters/Outlets</relationshipLabel>
    <relationshipName>Chains</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Outlet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Headquarters</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for HQ.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Headquarters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Survey_Install_Cancelled__c.field-meta.xml
<CustomField>
    <fullName>FS_Survey_Install_Cancelled__c</fullName>
    <label>Survey/Install Cancelled</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Disable_Trigger__c/Disable_Trigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is only used in case there is a need to deactivate a trigger during data migration. The triggers must be kept activated at all times...</description>
    <label>Disable Trigger</label>
</CustomObject>

force-app/main/default/objects/FS_EP_Technician_Instructions__c/FS_EP_Technician_Instructions__c.object-meta.xml
<CustomObject>
    <label>Technician Instructions</label>
    <nameField>
        <displayFormat>EPTI-{0000}</displayFormat>
        <label>EP Technician Instructions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Technician Instructions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_EP_Technician_Instructions__c/fields/Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>Execution_Plan__c</fullName>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Technician Instructions</relationshipLabel>
    <relationshipName>Technician_Instructions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Back_up_COM__c.field-meta.xml
<CustomField>
    <fullName>FS_Back_up_COM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>FS_Back_up_COM</description>
    <label>COM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Execution_Plans1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Davaco_Requirements__c.field-meta.xml
<CustomField>
    <fullName>FS_Davaco_Requirements__c</fullName>
    <label>Select Site Assessment Requirements</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Davaco: Site Assessment + GFE</fullName>
            </value>
            <value>
                <fullName>Davaco: Site Assessment + Detailed Scope Summary</fullName>
            </value>
            <value>
                <fullName>Davaco: Site Assessment Only</fullName>
            </value>
            <value>
                <fullName>Davaco: New Construction Site Assessment</fullName>
            </value>
            <value>
                <fullName>No Site Assessment Required</fullName>
            </value>
            <value>
                <fullName>Power House</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <displayFormat>EP-{0000}</displayFormat>
    <label>Execution Plan#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan_Status__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan_Status__c</fullName>
    <description>Execution Plan Status</description>
    <label>Execution Plan Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <default>true</default>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>On-Hold</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <label>Headquarters</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Value does not exist or does not match filter criteria for HQ on EP.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Execution Plans (Headquarters)</relationshipLabel>
    <relationshipName>Execution_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For Post Install</description>
    <label>Outlet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Outlet</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Post Install Activity</relationshipLabel>
    <relationshipName>Outlet_Post_Execution_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Platform_change_approved__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform_change_approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Platform change approved?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Platform_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform_Type__c</fullName>
    <description>multi select picklist</description>
    <label>Platform Type/s</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_Davaco_Requirements__c.field-meta.xml
<CustomField>
    <fullName>FS_Davaco_Requirements__c</fullName>
    <label>What type of Site Assessment</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Construction SA - Proceed w/Scheduling</fullName>
            </value>
            <value>
                <fullName>SA Not Required - OSM approval required for local market</fullName>
            </value>
            <value>
                <fullName>Site Assess + GFE bid proposal (traditional)</fullName>
            </value>
            <value>
                <fullName>Site Assessment Only (survey only)</fullName>
            </value>
            <value>
                <fullName>Rush â€“ New Construction SA â€“ Proceed w/Scheduling</fullName>
            </value>
            <value>
                <fullName>Rush - Site Assess + GFE Bid proposal (traditional)</fullName>
            </value>
            <value>
                <fullName>Rush - Site Assessment Only (Survey Only)</fullName>
            </value>
            <value>
                <fullName>No Site Assessment-Required</fullName>
            </value>
            <value>
                <fullName>SA Not Required</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlet Info Summary</relationshipLabel>
    <relationshipName>Outlet_Info_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Install_Complete__c.field-meta.xml
<CustomField>
    <fullName>FS_Install_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Install Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Original_Install_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Original_Install_Date__c</fullName>
    <label>Initially Scheduled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installations (Outlet)</relationshipLabel>
    <relationshipName>Installations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Overall_Status__c.field-meta.xml
<CustomField>
    <fullName>FS_Overall_Status__c</fullName>
    <description>FS Overall Status</description>
    <formula>Overall_Status2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FS Overall Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Rush_Install_Reason__c.field-meta.xml
<CustomField>
    <fullName>FS_Rush_Install_Reason__c</fullName>
    <label>Rush Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Store Opening</fullName>
            </value>
            <value>
                <fullName>Marketing/Media</fullName>
            </value>
            <value>
                <fullName>Remodel</fullName>
            </value>
            <value>
                <fullName>Legacy Equipment Failure</fullName>
            </value>
            <value>
                <fullName>Customer Request</fullName>
            </value>
            <value>
                <fullName>Rebuild</fullName>
            </value>
            <value>
                <fullName>Health Inspection</fullName>
            </value>
            <value>
                <fullName>Coordinator Error</fullName>
            </value>
            <value>
                <fullName>NRA</fullName>
            </value>
            <value>
                <fullName>SA Not Uploaded</fullName>
            </value>
            <value>
                <fullName>Customer Unable to Pour Product</fullName>
            </value>
            <value>
                <fullName>Limited Dispenser Accessibility</fullName>
            </value>
            <value>
                <fullName>External Process Failure</fullName>
            </value>
            <value>
                <fullName>Acts of God</fullName>
            </value>
            <value>
                <fullName>Trade Show</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Survey_Install_Cancelled__c.field-meta.xml
<CustomField>
    <fullName>FS_Survey_Install_Cancelled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Survey/Install - Cancelled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Survey_Install_On_Hold__c.field-meta.xml
<CustomField>
    <fullName>FS_Survey_Install_On_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Survey/Install - On Hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Platform_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3100</fullName>
    </customValue>
    <customValue>
        <fullName>6000</fullName>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
    </customValue>
    <customValue>
        <fullName>7100</fullName>
    </customValue>
    <customValue>
        <fullName>8000</fullName>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
    </customValue>
    <masterLabel>Platform Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FSExecutionPlanTriggerHandlerTest.cls
/**************************************************************************************
Apex Class Name     : FSExecutionPlanTriggerHandlerTest
Version             : 1.0
Function            : This is a test class for FSExecutionPlanTriggerHandler & FSExecutionPlanValidateAndSet classes
Modification Log    :
* Developer         :    Date              Description
* ----------------------------------------------------------------------------                 
* Mohit Parnami         Nov 11, 2013         Original Version
*Venkata				01/12/2017 			Updated for FET 4.0 code coverage
*************************************************************************************/

@isTest
private class FSExecutionPlanTriggerHandlerTest{
    public static Account accchain,accHQ,accOutlet;
    public static FS_Execution_Plan__c executionPlan;
    public static String recTypeNewIP=Schema.SObjectType.FS_Installation__c.getRecordTypeInfosByName().get(Label.IP_New_Install_Rec_Type).getRecordTypeId() ;
    public static String recTypeExePlan=Schema.SObjectType.FS_Execution_Plan__c.getRecordTypeInfosByName().get('Execution Plan').getRecordTypeId() ;
    
    public static void createtestData(){
        FSTestFactory.createTestDisableTriggerSetting();
        accchain = FSTestUtil.createTestAccount('Test Chain 1',FSConstants.RECORD_TYPE_CHAIN,true);        
        accHQ = FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,false);    
        accHQ.FS_Chain__c = accchain.Id;
        insert accHQ;
        accOutlet = FSTestUtil.createAccountOutlet('Test Outlet 1',FSConstants.RECORD_TYPE_OUTLET,accHQ.Id,true);   
    }
    
    public static testmethod void testcreateTechInstruction(){
        final Profile adminProfile = FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
        final User adminUser = FSTestFactory.createUser(adminProfile.id);
        insert adminUser;
        system.runAs(adminUser){
            createtestData();   
            final Profile fetCOM=FSTestFactory.getProfileId(FSConstants.USER_POFILE_COM);
        	final User fetCOMUser=FSTestFactory.createUser(fetCOM.id);
        	insert fetCOMUser;
            final List<FS_Execution_Plan__c> epList=new List<FS_Execution_Plan__c>();
            final List<FS_Installation__c > ipList=new List<FS_Installation__c >();
            epList.add(new FS_Execution_Plan__c(FS_Headquarters__c= accHQ.Id,recordtypeid=recTypeExePlan,FS_Platform_Type__c='7000;8000',FS_Back_up_COM__c=fetCOMUser.Id));
            insert epList;
            ipList.add(new FS_Installation__c (FS_Execution_Plan__c=epList[0].id,FS_Outlet__c=accOutlet.Id,RecordTypeId=recTypeNewIP));
            insert ipList;
			system.debug('testcreateTechInstruction q#queries '+ Limits.getQueries());
            Test.startTest(); 
            final FS_Execution_Plan__c epUpdate=new FS_Execution_Plan__c(Id=epList[0].id,FS_Platform_Type__c='7000;9000',FS_Platform_change_approved__c=true );
            update epUpdate;
            system.debug('testcreateTechInstruction q#queries '+ Limits.getQueries());
            Test.stopTest();
            
            final List<FS_EP_Technician_Instructions__c> epTiList=[select id from FS_EP_Technician_Instructions__c where Execution_Plan__c=:epList[0].id];
            system.assertEquals(2,epTiList.size());
        }
    }  
    
    public static testmethod void testupdateInstallation(){
        final Profile adminProfile = FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
        final User adminUser = FSTestFactory.createUser(adminProfile.id);
        insert adminUser;
        system.runAs(adminUser){
            createtestData();       
            final List<FS_Execution_Plan__c> epList=new List<FS_Execution_Plan__c>();
            final List<FS_Installation__c > ipList=new List<FS_Installation__c >();
            epList.add(new FS_Execution_Plan__c(FS_Headquarters__c= accHQ.Id,recordtypeid=recTypeExePlan,FS_Platform_Type__c='7000;8000'));     
            insert epList;
            
            system.debug('testupdateInstallation q#queries '+ Limits.getQueries());
            Test.startTest(); 
            
            ipList.add(new FS_Installation__c (FS_Execution_Plan__c=epList[0].id,FS_Outlet__c=accOutlet.Id,RecordTypeId=recTypeNewIP));
            insert ipList;
            
            Test.stopTest();
            final List<FS_EP_Technician_Instructions__c> eqpList=[select id from FS_EP_Technician_Instructions__c where Execution_Plan__c=:epList[0].Id];
            system.assert(!eqpList.isEmpty());
        }
    }  
    
    public static testmethod void testupdateExecutionPlanStatusOnHold(){
        final Profile adminProfile = FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
        final User adminUser = FSTestFactory.createUser(adminProfile.id);
        insert adminUser;
        system.runAs(adminUser){
            createtestData();     
            final List<FS_Execution_Plan__c> epList=new List<FS_Execution_Plan__c>();
            final List<FS_Installation__c > ipList=new List<FS_Installation__c >();
            final List<FS_Installation__c > ipListtoUpdate=new List<FS_Installation__c >();
            
            
            epList.add(new FS_Execution_Plan__c(FS_Headquarters__c= accHQ.Id,recordtypeid=recTypeExePlan));     
            insert epList;
            
            ipList.add(new FS_Installation__c (FS_Execution_Plan__c=epList[0].id,FS_Outlet__c=accOutlet.Id,RecordTypeId=recTypeNewIP));
            insert ipList;
            
            system.debug('testupdateExecutionPlanStatusOnHold q#queries '+ Limits.getQueries());
            Test.startTest();
            ipListtoUpdate.add(new FS_Installation__c (Id=ipList[0].id,FS_Survey_Install_On_Hold__c=true));     
            update ipListtoUpdate;   
            system.debug('testupdateExecutionPlanStatusOnHold q#queries test '+ Limits.getQueries());
            Test.stopTest();
            final  String value=[select FS_Overall_Status__c from FS_Installation__c where Id=:ipList[0].id].FS_Overall_Status__c;
            system.assertEquals(FSConstants.onHolds ,value);
        }
    } 
    
    public static testmethod void testupdateExecutionPlanStatusCancelled(){
        final Profile adminProfile = FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
        final User adminUser = FSTestFactory.createUser(adminProfile.id);
        insert adminUser;
        system.runAs(adminUser){
            createtestData();
            final List<FS_Execution_Plan__c> epList=new List<FS_Execution_Plan__c>();
            final List<FS_Installation__c > ipList=new List<FS_Installation__c >();
            final List<FS_Installation__c > ipListtoUpdate=new List<FS_Installation__c >();
            
            epList.add(new FS_Execution_Plan__c(FS_Headquarters__c= accHQ.Id,recordtypeid=recTypeExePlan));     
            insert epList;
            
            ipList.add(new FS_Installation__c (FS_Execution_Plan__c=epList[0].id,FS_Outlet__c=accOutlet.Id,RecordTypeId=recTypeNewIP));
            insert ipList;
            system.debug('testupdateExecutionPlanStatusCancelled q#queries '+ Limits.getQueries());
            Test.startTest();
            ipListtoUpdate.add(new FS_Installation__c (Id=ipList[0].id,FS_Survey_Install_Cancelled__c=true));     
            update ipListtoUpdate;   
            system.debug('testupdateExecutionPlanStatusCancelled q#queries test '+ Limits.getQueries());
            Test.stopTest();
            system.assertEquals('Cancelled',[select FS_Execution_Plan_Status__c from FS_Execution_Plan__c where Id=:epList[0].id].FS_Execution_Plan_Status__c );
        }
    }  
    public static testmethod void testupdateExecutionPlanStatusInprogress(){
        final Profile adminProfile = FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
        final User adminUser = FSTestFactory.createUser(adminProfile.id);
        insert adminUser;
        system.runAs(adminUser){
            createtestData();

            final Account accOutlet1=FSTestUtil.createAccountOutlet('Test Outlet 1',FSConstants.RECORD_TYPE_OUTLET,accHQ.Id,true);
            final List<FS_Execution_Plan__c> epList=new List<FS_Execution_Plan__c>();
            final List<FS_Installation__c > ipList=new List<FS_Installation__c >();
            final List<FS_Installation__c > ipListtoUpdate=new List<FS_Installation__c >();
            
            Test.startTest();
            
            epList.add(new FS_Execution_Plan__c(FS_Headquarters__c= accHQ.Id,recordtypeid=recTypeExePlan));     
            insert epList;
            
            ipList.add(new FS_Installation__c (FS_Execution_Plan__c=epList[0].id,FS_Outlet__c=accOutlet.Id,RecordTypeId=recTypeNewIP));
            ipList.add(new FS_Installation__c (FS_Execution_Plan__c=epList[0].id,FS_Outlet__c=accOutlet1.Id,RecordTypeId=recTypeNewIP));
            insert ipList;
            
            Test.stopTest();
            
            ipListtoUpdate.add(new FS_Installation__c (Id=ipList[0].id,FS_Davaco_Requirements__c='SA Not Required - OSM approval required for local market',FS_Install_Complete__c=true,FS_Original_Install_Date__c=Date.today(),FS_Rush_Install_Reason__c='NRA'));
            ipListtoUpdate.add(new FS_Installation__c (Id=ipList[1].id,FS_Survey_Install_Cancelled__c=true));     
            update ipListtoUpdate;   
            
            system.assertEquals('In Progress',[select FS_Execution_Plan_Status__c from FS_Execution_Plan__c where Id=:epList[0].id].FS_Execution_Plan_Status__c );
        }
    } 
    
    @testSetup  
    public static void mytestSetup() {
        final Disable_Trigger__c disTrigrSetting = new Disable_Trigger__c();       
        disTrigrSetting.name='FSExecutionPlanTriggerHandler';
        disTrigrSetting.IsActive__c=true;
        disTrigrSetting.Trigger_Name__c='FSExecutionPlanTrigger' ; 
        insert disTrigrSetting; 
        system.assertEquals(true,disTrigrSetting.IsActive__c);  
    }
    
}