force-app/main/default/objects/Account/fields/FS_Chain__c.field-meta.xml
<CustomField>
    <fullName>FS_Chain__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chain</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for Chain.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Chain</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Headquarters/Outlets</relationshipLabel>
    <relationshipName>Chains</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Outlet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Valid_Fill__c.field-meta.xml
<CustomField>
    <fullName>FS_Valid_Fill__c</fullName>
    <label>Valid Fill</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <displayFormat>EP-{0000}</displayFormat>
    <label>Execution Plan#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For Post Install</description>
    <label>Outlet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Outlet</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Post Install Activity</relationshipLabel>
    <relationshipName>Outlet_Post_Execution_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Valid_Fill__c.field-meta.xml
<CustomField>
    <fullName>FS_Valid_Fill__c</fullName>
    <label>Valid Fill</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>46245 : Valid Fill Conversion Kit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlet Info Summary</relationshipLabel>
    <relationshipName>Outlet_Info_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installations (Outlet)</relationshipLabel>
    <relationshipName>Installations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Valid_Fill__c.field-meta.xml
<CustomField>
    <fullName>FS_Valid_Fill__c</fullName>
    <label>Valid Fill</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>46245 : Valid Fill Conversion Kit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_7000_Series_Agitated_Selections_New__c.field-meta.xml
<CustomField>
    <fullName>FS_7000_Series_Agitated_Selections_New__c</fullName>
    <label>7000 Series Agitated Brands Selections.</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Barqs</fullName>
            </value>
            <value>
                <fullName>Pibb</fullName>
            </value>
            <value>
                <fullName>Dr Pepper</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Equip_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Equip_Type__c</fullName>
    <description>equip type</description>
    <inlineHelpText>This is the JDE Equipment Type value</inlineHelpText>
    <label>Equipment Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <description>Outlet field.</description>
    <label>Outlet</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 3) OR (2 AND 4 AND (5 OR 7)) OR (2 AND 4 AND 6)</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for Outlet.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Outlet</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Outlet</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>7000, 8000, 9000, CCNA Dispenser</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Dispenser</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value>No, Yes</value>
        </filterItems>
        <filterItems>
            <field>Account.Is_Default_FET_International_Outlet__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlet Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Serial_Number2__c.field-meta.xml
<CustomField>
    <fullName>FS_Serial_Number2__c</fullName>
    <description>Serial Number/Asset Tag.</description>
    <label>JDE Serial Number/Asset Tag</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Valid_Fill__c.field-meta.xml
<CustomField>
    <fullName>FS_Valid_Fill__c</fullName>
    <label>Valid Fill Required</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 OR 2) AND 4) OR 3 OR 5</booleanFilter>
        <errorMessage>The installation referenced by this dispenser is linked to a different outlet than the outlet on the dispenser.</errorMessage>
        <filterItems>
            <field>FS_Installation__c.FS_Outlet__c</field>
            <operation>equals</operation>
            <valueField>$Source.FS_Outlet__c</valueField>
        </filterItems>
        <filterItems>
            <field>FS_Installation__c.FS_New_Outlet__c</field>
            <operation>equals</operation>
            <valueField>$Source.FS_Outlet__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Dispenser</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>CCNA Dispenser, 7000, 8000, 9000</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Installed Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Post_Install_Marketing__c/FS_Post_Install_Marketing__c.object-meta.xml
<CustomObject>
    <label>Post Install Marketing</label>
    <nameField>
        <displayFormat>PIM-{0000}</displayFormat>
        <label>Post Install Marketing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Post Install Marketing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Post_Install_Marketing__c/fields/FS_Enable_Consumer_Engagement__c.field-meta.xml
<CustomField>
    <fullName>FS_Enable_Consumer_Engagement__c</fullName>
    <label>FET Enable Consumer Engagement</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Post_Install_Marketing__c/fields/FS_Installation__c.field-meta.xml
<CustomField>
    <fullName>FS_Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Post Install Marketing</relationshipLabel>
    <relationshipName>Post_Install_Marketing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Post_Install_Marketing__c/fields/FS_Outlet_Dispenser__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_Dispenser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet Dispenser</label>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipLabel>Post Install Marketing</relationshipLabel>
    <relationshipName>Post_Install_Marketing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/FS_Valid_Fill__c.object-meta.xml
<CustomObject>
    <label>Valid Fill</label>
    <nameField>
        <displayFormat>VF-{0000}</displayFormat>
        <label>Valid Fill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Valid Fill</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Valid_Fill__c/fields/FS_Installation__c.field-meta.xml
<CustomField>
    <fullName>FS_Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Post Install Valid Fill</relationshipLabel>
    <relationshipName>Valid_Fill</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Post-Install Valid Fill</relationshipLabel>
    <relationshipName>Vailid_Fill</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/fields/FS_Outlet_Dispenser__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_Dispenser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet Dispenser</label>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipLabel>Post Install Valid Fill</relationshipLabel>
    <relationshipName>Valid_Fill</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FSCancelPostInstallActivity_Test.cls
/**************************************************************************************
Apex Class Name     : FSCancelPostInstallActivity_Test
Version             : 1.0
Function            : This test class is for FSCancelPostInstallActivity Class code coverage. 
Modification Log    : 
* Developer         :    Date              Description
* ----------------------------------------------------------------------------                 
* Infosys             			          Original Version 
*					  05/29/2018		  Removed usage of OutboundServiceDetails__c customSetting as part of FOT project
*************************************************************************************/
@isTest 
public Class FSCancelPostInstallActivity_Test {
    public static Account accchain,accHQ,accOutlet;
    public static FS_Execution_Plan__c executionPlan;
    public static FS_Installation__c installtion;
    public Static FS_outlet_dispenser__c outletDispenser;   
    private static Profile fetSysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_FETADMIN);
    
    private Static testMethod void createtestData(){
        final List<Account> accList=new List<Account>();
        accchain = FSTestUtil.createTestAccount('Test Chain 1',FSConstants.RECORD_TYPE_CHAIN,false); 
        accList.add(accchain);
        accHQ = FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,false);
        accHQ.FS_Chain__c = accchain.Id;
        accList.add(accHQ);        
        accOutlet = FSTestUtil.createAccountOutlet('Test Outlet 1',FSConstants.RECORD_TYPE_OUTLET,accHQ.Id, false);        
        accList.add(accOutlet);
        insert accList;
        executionPlan = FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,accHQ.Id, true);
        system.debug('Execution Id'+executionPlan );
        
        installtion =FSTestUtil.createInstallationAcc(FSConstants.NEWINSTALLATION,executionPlan.Id,accOutlet.id , true);
        
        //Create custom setting data
        FSTestFactory.lstPlatform();
        Test.setMock(HttpCalloutMock.class, new FSFETNMSConnectorMock());
        
        outletDispenser= new FS_outlet_dispenser__c();
        
        outletDispenser.FS_Outlet__c = accOutlet.Id;
        outletDispenser.FS_Equip_Type__c  ='7000';
        outletDispenser.FS_Serial_Number2__c = 'AHK7785';
        outletDispenser.Installation__c = installtion.id;
        outletDispenser.FS_7000_Series_Agitated_Selections_New__c = 'N/A to 8000/9000 Series';
        insert outletDispenser;  
                system.assertNotEquals(outletDispenser, null);

    }
    
    
    
    private static testMethod void  testUnitFSCancelValidFill7000(){    
        
        Test.startTest();
        createtestData();
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
        system.runAs(fetSysAdminUser){
            FS_Valid_Fill__c validFill = new FS_Valid_Fill__c();
            validFill =FSTestUtil.createValidFill('7000',true);
            validFill.FS_Installation__c=installtion.id; 
            update validFill;
                 
            FSCancelPostInstallActivity.FSCancelValidFill(validFill.id);
        }
                        system.assertNotEquals(fetSysAdminUser, null);
        Test.stopTest();
    }
    
    private static testMethod void  testUnitFSCancelValidFill8000(){    
        
        Test.startTest();
        createtestData();
        outletDispenser.FS_Equip_Type__c  ='8000';
        update outletDispenser; 
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
        system.runAs(fetSysAdminUser){
            FS_Valid_Fill__c validFill = new FS_Valid_Fill__c();
            validFill =FSTestUtil.createValidFill('8000',true);
            validFill.FS_Installation__c=installtion.id; 
            update validFill;
                 
            FSCancelPostInstallActivity.FSCancelValidFill(validFill.id);
        }
                        system.assertNotEquals(fetSysAdminUser, null);
        Test.stopTest();
    }
    private static testMethod void  testUnitFSCancelValidFill9000(){    
        Test.startTest();
        createtestData();
        outletDispenser.FS_Equip_Type__c  ='9000';
        update outletDispenser; 
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
        system.runAs(fetSysAdminUser){
            FS_Valid_Fill__c validFill = new FS_Valid_Fill__c();
            validFill =FSTestUtil.createValidFill('9000',true);
            validFill.FS_Installation__c=installtion.id; 
            update validFill;
                
            FSCancelPostInstallActivity.FSCancelValidFill(validFill.id);
        }
                        system.assertNotEquals(fetSysAdminUser, null);
        Test.stopTest();
    }
    private static testMethod void  testUnitFSCancelValidFill8k9k(){    
        
        Test.startTest();
        createtestData();
        outletDispenser.FS_Equip_Type__c  ='9100';
        update outletDispenser; 
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
        system.runAs(fetSysAdminUser){
            FS_Valid_Fill__c validFill = new FS_Valid_Fill__c();
            validFill =FSTestUtil.createValidFill('9100',true);
            validFill.FS_Installation__c=installtion.id; 
            update validFill;
                  
            FSCancelPostInstallActivity.FSCancelValidFill(validFill.id);
        }
        system.assertNotEquals(fetSysAdminUser, null);
        Test.stopTest();
    }
    
    private static testMethod void  testUnitFSCancelPostInsMrkt(){
        createtestData();       
        
        FS_Post_Install_Marketing__c marketingField = new FS_Post_Install_Marketing__c();
        marketingField =FSTestUtil.createMarketingField(true);
        marketingField.FS_Installation__c=installtion.id;
        marketingField.FS_Enable_Consumer_Engagement__c='Yes';
        marketingField.FS_Enable_CE_Effective_Date__c=system.today();
		marketingField.FS_FAV_MIX__c='Yes';
        marketingField.FS_FAV_MIX_Effective_Date__c=system.today();
        marketingField.FS_LTO__c='LTO1';
        marketingField.FS_LTO_Effective_Date__c=system.today();
        marketingField.FS_Promo_Enabled__c='Yes';
        marketingField.FS_Promo_Enabled_Effective_Date__c=system.today();
        update marketingField;      
       
        Test.startTest();
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
        system.runAs(fetSysAdminUser){
            FSCancelPostInstallActivity.FSCancelPostInsMrkt(marketingField.id);
        }
        system.assertNotEquals(fetSysAdminUser, null);
        Test.stopTest();        
    }
    
}