force-app/main/default/objects/Account/fields/FS_Chain__c.field-meta.xml
<CustomField>
    <fullName>FS_Chain__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chain</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for Chain.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Chain</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Headquarters/Outlets</relationshipLabel>
    <relationshipName>Chains</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_FSM_Review__c.field-meta.xml
<CustomField>
    <fullName>FS_FSM_Review__c</fullName>
    <label>FSM Review</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Headquarters</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for HQ.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Headquarters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Site_Assessment_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>FS_Site_Assessment_Contact_Email__c</fullName>
    <label>Site Assessment Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Site_Assessment_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>FS_Site_Assessment_Contact_Name__c</fullName>
    <label>Site Assessment Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Site_Assessment_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>FS_Site_Assessment_Contact_Phone__c</fullName>
    <label>Site Assessment Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FS_Contact_Info_Complete__c.field-meta.xml
<CustomField>
    <fullName>FS_Contact_Info_Complete__c</fullName>
    <formula>IF(AND(Phone &lt;&gt; &quot;&quot;, Email &lt;&gt; &quot;&quot;),TRUE,FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Info Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FS_Execution_Plan_Role__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan_Role__c</fullName>
    <label>Contact Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary Contact</fullName>
            </value>
            <value>
                <fullName>Secondary Contact</fullName>
            </value>
            <value>
                <fullName>Accounts Payable Contact</fullName>
            </value>
            <value>
                <fullName>Site Assessment Contact</fullName>
            </value>
            <value>
                <fullName>Secondary Site Assessment Contact</fullName>
            </value>
            <value>
                <fullName>Contractor Contact</fullName>
            </value>
            <value>
                <fullName>On-Board Training Contact</fullName>
            </value>
            <value>
                <fullName>Installation Contact</fullName>
            </value>
            <value>
                <fullName>Coke Smart Admin User</fullName>
            </value>
            <value>
                <fullName>Coke Smart Standard User</fullName>
            </value>
            <value>
                <fullName>Order Confirmation Contact</fullName>
            </value>
            <value>
                <fullName>Shipment Confirmation Contact</fullName>
            </value>
            <value>
                <fullName>Credit Confirmation Contact</fullName>
            </value>
            <value>
                <fullName>Water Filter Contact</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_CI_Required_Fields_Region__c/FS_CI_Required_Fields_Region__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>FS CI Required Fields Region</label>
</CustomObject>

force-app/main/default/objects/FS_CI_Required_Fields_Region__c/fields/Field_API__c.field-meta.xml
<CustomField>
    <fullName>Field_API__c</fullName>
    <label>Field API</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_CI_Required_Fields_Region__c/fields/Field_Lable__c.field-meta.xml
<CustomField>
    <fullName>Field_Lable__c</fullName>
    <label>Field Label</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Customer_Input__c/FS_Customer_Input__c.object-meta.xml
<CustomObject>
    <label>Customer Input</label>
    <nameField>
        <label>Customer Input Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Inputs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Customer_Input__c/fields/FS_Account__c.field-meta.xml
<CustomField>
    <fullName>FS_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Inputs</relationshipLabel>
    <relationshipName>Customer_Inputs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Customer_Input__c/fields/FS_Number_crew_serve_unit__c.field-meta.xml
<CustomField>
    <fullName>FS_Number_crew_serve_unit__c</fullName>
    <label>#Planned 8000 Series Freestyle Dispenser</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Customer_Input__c/fields/FS_Number_self_serve_units__c.field-meta.xml
<CustomField>
    <fullName>FS_Number_self_serve_units__c</fullName>
    <label>#Planned 9000 Series Freestyle Dispenser</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Customer_Input__c/fields/FS_Self_Serve_Top_Mnt_Ice_Maker_Instld__c.field-meta.xml
<CustomField>
    <fullName>FS_Self_Serve_Top_Mnt_Ice_Maker_Instld__c</fullName>
    <inlineHelpText>9000 series</inlineHelpText>
    <label>#Planned Top-Mount Ice Maker</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <default>true</default>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Customer_Input__c/fields/FS_Site_Assessment_contact_email__c.field-meta.xml
<CustomField>
    <fullName>FS_Site_Assessment_contact_email__c</fullName>
    <label>Site Assessment contact email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/FS_Customer_Input__c/fields/FS_Site_Assessment_Contact_name__c.field-meta.xml
<CustomField>
    <fullName>FS_Site_Assessment_Contact_name__c</fullName>
    <label>Site Assessment Contact name</label>
    <length>128</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Customer_Input__c/fields/FS_Site_Assessment_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>FS_Site_Assessment_Contact_Phone__c</fullName>
    <label>Site Assessment Contact Phone-(primary)</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/FS_Customer_Input__c/fields/FS_Site_Assessment_Required__c.field-meta.xml
<CustomField>
    <fullName>FS_Site_Assessment_Required__c</fullName>
    <label>Select Site Assessment Requirements</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Davaco: Site Assessment + GFE</fullName>
            </value>
            <value>
                <fullName>Davaco: Site Assessment + Detailed Scope Summary</fullName>
            </value>
            <value>
                <fullName>Davaco: Site Assessment Only</fullName>
            </value>
            <value>
                <fullName>Davaco: New Construction Site Assessment</fullName>
            </value>
            <value>
                <fullName>No Site Assessment Required</fullName>
            </value>
            <value>
                <fullName>Power House</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Customer_Input__c/fields/HQ_CIF__c.field-meta.xml
<CustomField>
    <fullName>HQ_CIF__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HQ CIF</label>
    <referenceTo>FS_Customer_Input__c</referenceTo>
    <relationshipLabel>Customer Inputs</relationshipLabel>
    <relationshipName>Customer_Inputs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FSHQPageServices.cls
/********************************************************************************************************* 
Name         : FSHQPageServices
Created By   : Pallavi Sharma (Appiro)
Created Date : 23 - Sep - 2013
Usage        : Global Class for executing conditions CreateCustomerInput, InitiateExecutionPlan and CreateExecutionPlan button on HQ
***********************************************************************************************************/
global class FSHQPageServices {
  
  /*
  // Create Customer Input Changes for T-205448 
  webservice static String createCustomerInput(String hqId){
    List<Contact> lstCon = [Select Id 
                            From Contact 
                            Where FS_Execution_Plan_Role__c Includes ('Primary Contact') 
                             And FS_Contact_Info_Complete__c = true  
                             And AccountId = :hqId ];
    if(lstCon == null || lstCon.size() == 0){
        return 'You must first add Primary Contact';
    }
    
    List<Account> lstHQAcc = [Select Id, FS_HQ_Revenue_Center__c , FS_Chain__c ,FS_Chain__r.FS_FSM_Review__c 
                              From Account
                              Where Id =: hqId];
    Account accHQ = lstHQAcc.get(0);
    if(accHQ.FS_HQ_Revenue_Center__c != null && !accHQ.FS_HQ_Revenue_Center__c.contains('Region')){
        if(accHQ.FS_Chain__c != null && accHQ.FS_Chain__r.FS_FSM_Review__c == 'Reviewed'){
             return 'success';
        }
        else{
            return 'Headquarters needs to be related to Approved Chain';
        }
    }
    
    return 'success';
    
  }*/
  
  // Create Customer Input Changes for T-213757
  webservice static String createCustomerInput(String hqId){
    List<Contact> lstCon = [Select Id 
                            From Contact 
                            Where FS_Execution_Plan_Role__c Includes ('Primary Contact') 
                            And AccountId = :hqId ];
    if(lstCon == null || lstCon.size() == 0){
        return 'You must first add Primary Contact on HQ';
    }
    return 'success';
  }
  
  // Create Customer Input Changes for T-213757
  webservice static String initiateExecutionPlan(String hqId){
    Account account = [Select FS_FSM_Review__c, FS_Chain__r.FS_FSM_Review__c, FS_Chain__c From Account Where Id = : hqId];
    if(account.FS_Chain__c != null && account.FS_Chain__r.FS_FSM_Review__c == 'Reviewed'){
      return 'success';
    }
    else if(account.FS_FSM_Review__c == 'Reviewed' ){
      return 'success';
    }
    return 'Headquarters must be FSM approved before Intitating an Execution Plan'; 
  }
  
  
  webservice static String copyToOutlets(String hqId){
    List<FS_Customer_Input__c> lstCI = [Select FS_Site_Assessment_Required__c, FS_Site_Assessment_Contact_name__c From FS_Customer_Input__c Where FS_Account__c = : hqId  ];
    if(lstCI == null || lstCI.size() == 0 ){
        return 'There is no Customer Input associated with this HQ';
    }
    else{
      FS_Customer_Input__c cutomerInput =  lstCI.get(0);
      if(cutomerInput.FS_Site_Assessment_Required__c == 'No Site Assessment Required' || 
         cutomerInput.FS_Site_Assessment_Contact_name__c != null){
            
         }
        else{
            return 'Site Assessment Information Required';
        }
    }
    return 'success';
  }
  
  // Create Execution Plan Changes for T-205448
  webservice static String createExecutionPlan(String hqId){
    //Prepare Set for Outlets:
    Set<Id> outletIds = new Set<Id>();
    for(Account acc : [SELECT Id, (SELECT Id FROM Customer_Inputs__r)
                        FROM Account WHERE FS_Headquarters__c = :hqId  
                        AND RecordType.Name = 'FS Outlet']){
        
      if(acc.Customer_Inputs__r != null && acc.Customer_Inputs__r.size() > 0 ){
        outletIds.add(acc.Id);
      }  
    }    
    
    
    //Fetch Customer Input forms for all outlets and HQ as well.
    String qryCI = getCIQuery(getRequiredFieldMap()) + ' Where FS_Account__c IN: outletIds OR FS_Account__c = :hqId';
    
    FS_Customer_Input__c hqCI;
    List<FS_Customer_Input__c> lstOutletsCI = new List<FS_Customer_Input__c>();
    for(FS_Customer_Input__c CI :(List<FS_Customer_Input__c>)database.query(qryCI)){
      if(CI.FS_Account__c == hqId){
        hqCI = Ci;
      }
      else{
        lstOutletsCI.add(CI);
      } 
    }
    
    
    if(hqCI == null ){
      return 'There is no Customer Input associated with this HQ';
    }
    
    Boolean flagNoSA = true;
    for(FS_Customer_Input__c CI :lstOutletsCI){
      if(CI.FS_Site_Assessment_Required__c != 'No Site Assessment Required'){
        flagNoSA = false;   
      }
    }
    
    // If No site assessment required we don't need to check other things.
    if(flagNoSA == true){
      return 'success';
    }
    
    for(FS_Customer_Input__c CI :lstOutletsCI){
        if(checkPlannedDispensersIsNotNull(CI) == false){
        return 'You must enter planned dispensers and Top Mount Ice Makers before creating an Execution Plan';   
      }
    }
    
    if(checkStandaredConactHasRole_SA(hqId) == true){
        return 'success';
    }
    
    for(FS_Customer_Input__c CI :lstOutletsCI){
      if(checkSAContactInformationIsNotNull(CI) == false && CI.FS_Site_Assessment_Required__c != 'No Site Assessment Required'){
        return 'You must first Enter or Select a Site Assessment Contact before creating Execution Plan';   
      }
    }
    return 'success';
  }
  
  
  private static Boolean checkPlannedDispensersIsNotNull(FS_Customer_Input__c ci){
    if(String.isBlank(ci.FS_Number_self_serve_units__c) ||
       (String.isBlank(ci.FS_Number_crew_serve_unit__c)) ||
       (String.isBlank(ci.FS_Self_Serve_Top_Mnt_Ice_Maker_Instld__c))){
      return false;
    }
    return true;
  }
  
  private static Boolean checkSAContactInformationIsNotNull(FS_Customer_Input__c ci){
    if(String.isBlank(ci.FS_Site_Assessment_Contact_name__c) ||
       (String.isBlank(ci.FS_Site_Assessment_Contact_Phone__c)) ||
       (String.isBlank(ci.FS_Site_Assessment_contact_email__c))){
      return false;
    }
    return true;
  }
  
  private static Boolean checkStandaredConactHasRole_SA(Id hqId){
     List<Contact> lstCon = [SELECT Id FROM Contact WHERE FS_Execution_Plan_Role__c Includes ('Site Assessment Contact') 
                             AND FS_Contact_Info_Complete__c = TRUE  
                             AND AccountId = :hqId ];
    if(lstCon != null && lstCon.size() > 0){
        return true;
    }
    return false;
  }
  
  
  
  
  
  
  private static String checkRequiredFields(FS_Customer_Input__c cutomerInput, Map<String,String> requiredFields){
    for(String reqFields : requiredFields.keySet()){
        if(cutomerInput.get(reqFields) == null ){
            return 'Required Field Missing - ' + requiredFields.get(reqFields);
        }
    }
    return 'success';
  }
  
  private static Map<String,String> getRequiredFieldMap(){
    Map<String,String> requiredFields = new Map<String,String>();  
    List<FS_CI_Required_Fields_Region__c> lstRequireFields = FS_CI_Required_Fields_Region__c.getall().values();
    
    for(FS_CI_Required_Fields_Region__c reqF : lstRequireFields){
        requiredFields.put(reqF.Field_API__c, reqF.Field_Lable__c);
    }   
    return requiredFields;
  }
  
  private static String getCIQuery(Map<String,String> requiredFields){
    String csv = ' ';
    for(String reqFields : requiredFields.keySet()){
      csv += reqFields + ',';
    }
    csv = csv.substring(0, csv.lastIndexOf(','));
    return 'Select ' + csv + ' , FS_Account__c From FS_Customer_Input__c  ';
  }
  
}