force-app/main/default/objects/Account/fields/FS_Chain__c.field-meta.xml
<CustomField>
    <fullName>FS_Chain__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chain</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for Chain.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Chain</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Headquarters/Outlets</relationshipLabel>
    <relationshipName>Chains</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountTeamMember__c/AccountTeamMember__c.object-meta.xml
<CustomObject>
    <label>Account Team Member</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>AccountTeamMember Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountTeamMember__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>AccountId</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Team Members</relationshipLabel>
    <relationshipName>AccountTeamMembers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountTeamMember__c/fields/TeamMemberRole__c.field-meta.xml
<CustomField>
    <fullName>TeamMemberRole__c</fullName>
    <label>Team Member Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>COM</fullName>
            </value>
            <value>
                <fullName>COM Backup</fullName>
            </value>
            <value>
                <fullName>JCOM</fullName>
            </value>
            <value>
                <fullName>Sales Team Member</fullName>
            </value>
            <value>
                <fullName>PM</fullName>
            </value>
            <value>
                <fullName>PIC</fullName>
            </value>
            <value>
                <fullName>Sales Support</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>FDC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountTeamMember__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AccountTeamMembers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FSAccountTeamMemberOutletsBatchTest.cls
/***************************************************************************
 Name         : FSAccountTeamMemberOutletsBatchTest
 Created By   : Infosys
 Description  : Test class for FSAccountTeamMemberOutletsBatch
 Created Date : May 24, 2017 
****************************************************************************/

@isTest
public class FSAccountTeamMemberOutletsBatchTest {
    private static Account accChain, accHeadQtr1, accOutlet1;
    private static User user;
    
    private static void createTestData(){
        FSTestFactory.createTestDisableTriggerSetting();
        final List<Account> lstHQAccToInsert = new List<Account>();
        final List<Account> lstOAccToInsert = new List<Account>();
        
        user = FSTestUtil.createUser(null,0,FSConstants.systemAdmin, true);
        
        //Create Chain Account
        accChain = FSTestUtil.createTestAccount('Test Chain 1',FSConstants.RECORD_TYPE_CHAIN,true);
        
        //Create Headquarter Account
        accHeadQtr1 = FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,false);
        accHeadQtr1.FS_Chain__c = accChain.Id;
        lstHQAccToInsert.add(accHeadQtr1);
        
        insert lstHQAccToInsert;
        
        //Create Outlet Account
        accOutlet1 = FSTestUtil.createAccountOutlet('Test Outlet 1',FSConstants.RECORD_TYPE_OUTLET,accHeadQtr1.Id, false);
        lstOAccToInsert.add(accOutlet1);        
        
        insert lstOAccToInsert;      
    }
    //Test Method
    private static testMethod void  copyAccountMembersOnOutletLookupsTest(){
        createTestData();
        final Profile adminProfile = FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
        final User adminUser = FSTestFactory.createUser(adminProfile.id);
        insert adminUser;
        system.runAs(adminUser){
            Test.startTest(); 
            //To Test on HQ Account Team member
            final AccountTeamMember__c hqATM = new AccountTeamMember__c(AccountId__c = accHeadQtr1.Id, UserId__c = user.Id, TeamMemberRole__c = 'COM');
            insert hqATM;
            final List<AccountTeamMember__c> listteam = new List<AccountTeamMember__c>();
            listteam.add(hqATM);
            final ID jobId = Database.executeBatch(new FSAccountTeamMemberOutletsBatch(listteam), 2000); 
            
            test.stopTest();
            final List<AccountTeamMember__c> teamMembers = [SELECT Id from AccountTeamMember__c];
            System.assert(teamMembers.size()>1);
        }
    }
    
}