force-app/main/default/objects/Account/fields/FS_CE_Enabled__c.field-meta.xml
<CustomField>
    <fullName>FS_CE_Enabled__c</fullName>
    <label>FET Enable Consumer Engagement</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FS_FAV_MIX__c.field-meta.xml
<CustomField>
    <fullName>FS_FAV_MIX__c</fullName>
    <label>Favorite Mix</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>FS_CE_Enabled__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Promo_Enabled__c.field-meta.xml
<CustomField>
    <fullName>FS_Promo_Enabled__c</fullName>
    <label>FET Promotion Enabled</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_CE_Enabled__c.field-meta.xml
<CustomField>
    <fullName>FS_CE_Enabled__c</fullName>
    <description>Enable Consumer Engageme</description>
    <label>Enable Consumer Engagement</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_FAV_MIX__c.field-meta.xml
<CustomField>
    <fullName>FS_FAV_MIX__c</fullName>
    <description>Favoritemix</description>
    <label>Favorite Mix</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Overall_Status__c.field-meta.xml
<CustomField>
    <fullName>FS_Overall_Status__c</fullName>
    <description>FS Overall Status</description>
    <formula>Overall_Status2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FS Overall Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Promo_Enabled__c.field-meta.xml
<CustomField>
    <fullName>FS_Promo_Enabled__c</fullName>
    <description>Promotion Enabled</description>
    <label>Promotion Enabled</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_CE_Enabled__c.field-meta.xml
<CustomField>
    <fullName>FS_CE_Enabled__c</fullName>
    <description>CE enabled</description>
    <label>FET Enable Consumer Engagement</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_FAV_MIX__c.field-meta.xml
<CustomField>
    <fullName>FS_FAV_MIX__c</fullName>
    <label>FET Favorite Mix</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_IsActive__c.field-meta.xml
<CustomField>
    <fullName>FS_IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>active or inactive</description>
    <label>Active (A) / Inactive (I)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Migration_to_AW_Complete__c.field-meta.xml
<CustomField>
    <fullName>FS_Migration_to_AW_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Migration to AW Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Migration_to_AW_Required__c.field-meta.xml
<CustomField>
    <fullName>FS_Migration_to_AW_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Migration to AW Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Pending_Migration_to_AW__c.field-meta.xml
<CustomField>
    <fullName>FS_Pending_Migration_to_AW__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pending Migration to AW</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Promo_Enabled__c.field-meta.xml
<CustomField>
    <fullName>FS_Promo_Enabled__c</fullName>
    <description>.</description>
    <label>FET Promotion Enabled</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FSCEAttributesUpdates.cls
/** Class used to update Enable Consumer Engagement,Favorite Mix,Promotion Enabled to YES
*  TASK0882385 --CCSN request
*  Created By: FET Support
*/
global without sharing class FSCEAttributesUpdates implements Database.Batchable<sObject>, Database.AllowsCallouts{
    
    public Static Id recTypeChain=getObjectRecordTypeId(Account.sObjectType,'FS Chain');
    public Static Id recTypeHQ=getObjectRecordTypeId(Account.sObjectType,'FS Headquarters');
    public Static Id recTypeOutlet=getObjectRecordTypeId(Account.sObjectType,'FS Outlet');
    
    public String ObjectType;
    
    global FSCEAttributesUpdates(String ObjectType){
        
        this.ObjectType=ObjectType;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        if(ObjectType=='Account') 
            return Database.getQueryLocator([SELECT Id,Name,FS_CE_Enabled__c,FS_FAV_MIX__c,FS_Promo_Enabled__c FROM Account WHERE (RecordTypeId=:recTypeChain OR RecordTypeId=:recTypeHQ OR RecordTypeId=:recTypeOutlet) AND (FS_CE_Enabled__c!='Yes' OR FS_FAV_MIX__c!='Yes' OR FS_Promo_Enabled__c!='Yes')]);
        
        if(ObjectType=='FS_Installation__c')  //To Be done for all Open Installation
            return Database.getQueryLocator([SELECT Id,Name,FS_CE_Enabled__c,FS_FAV_MIX__c,FS_Promo_Enabled__c FROM FS_Installation__c WHERE (FS_Overall_Status__c!='' AND FS_Overall_Status__c!=:FSConstants.IPCOMPLETE AND FS_Overall_Status__c!=:FSConstants.IPCANCELLED )]);
        
        if(ObjectType=='FS_Outlet_Dispenser__c')  
            //return Database.getQueryLocator([SELECT Id, Name, FS_CE_Enabled__c, FS_FAV_MIX__c, FS_Promo_Enabled__c FROM FS_Outlet_Dispenser__c WHERE FS_IsActive__c=TRUE AND (FS_CE_Enabled__c!='Yes' OR FS_FAV_MIX__c!='Yes' OR FS_Promo_Enabled__c!='Yes')]);
            return Database.getQueryLocator([SELECT Id, Name,FS_CE_Enabled__c,FS_FAV_MIX__c,FS_Promo_Enabled__c, FS_Migration_to_AW_Required__c , FS_Pending_Migration_to_AW__c, FS_Migration_to_AW_Complete__c FROM FS_Outlet_Dispenser__c WHERE FS_IsActive__c=TRUE]);
        return null;
    }
    
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
        
        
        Schema.SObjectType sObjectType = Schema.getGlobalDescribe().get(ObjectType);
        List<Sobject> sObjectsToUpdate=new List<Sobject>();
        
        if(ObjectType=='FS_Outlet_Dispenser__c'){
            for(SObject obj : scope){
                
                SObject record= sObjectType.newSObject(obj.Id);
                record.put('FS_CE_Enabled__c','Yes');
                //record.put('FS_FAV_MIX__c','Yes');
                record.put('FS_Promo_Enabled__c','Yes');
                record.put('FS_Migration_to_AW_Required__c',TRUE );
                record.put('FS_Pending_Migration_to_AW__c',TRUE );
                record.put('FS_Migration_to_AW_Complete__c',FALSE);
                sObjectsToUpdate.add(record);
            }
        }
        
        Database.update(sObjectsToUpdate,false);
        
        system.debug('Records In Batch'+sObjectsToUpdate);
    }
    
    global void finish(Database.BatchableContext BC){
        Database.executeBatch(new FS_Data_Migration_8k_9k(),1);
    }
    
    public static Id getObjectRecordTypeId(SObjectType sObjectType, String recordTypeName){
        //Generate a map of tokens for all the Record Types for the desired object
        Map<String,Schema.RecordTypeInfo> rtMapByName = sObjectType.getDescribe().getRecordTypeInfosByName();
        //Retrieve the record type id by name
        return rtMapByName.get(recordTypeName).getRecordTypeId();
    }
}