force-app/main/default/objects/Account/fields/FS_Chain__c.field-meta.xml
<CustomField>
    <fullName>FS_Chain__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chain</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for Chain.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Chain</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Headquarters/Outlets</relationshipLabel>
    <relationshipName>Chains</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Outlet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Disable_Trigger__c/Disable_Trigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is only used in case there is a need to deactivate a trigger during data migration. The triggers must be kept activated at all times...</description>
    <label>Disable Trigger</label>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <displayFormat>EP-{0000}</displayFormat>
    <label>Execution Plan#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlet Info Summary</relationshipLabel>
    <relationshipName>Outlet_Info_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Install_Reconnect_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Install_Reconnect_Date__c</fullName>
    <label>Initially Install/Reconnect Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Rush_Install_Reason__c.field-meta.xml
<CustomField>
    <fullName>FS_Rush_Install_Reason__c</fullName>
    <label>Rush Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Store Opening</fullName>
            </value>
            <value>
                <fullName>Marketing/Media</fullName>
            </value>
            <value>
                <fullName>Remodel</fullName>
            </value>
            <value>
                <fullName>Legacy Equipment Failure</fullName>
            </value>
            <value>
                <fullName>Customer Request</fullName>
            </value>
            <value>
                <fullName>Rebuild</fullName>
            </value>
            <value>
                <fullName>Health Inspection</fullName>
            </value>
            <value>
                <fullName>Coordinator Error</fullName>
            </value>
            <value>
                <fullName>NRA</fullName>
            </value>
            <value>
                <fullName>SA Not Uploaded</fullName>
            </value>
            <value>
                <fullName>Customer Unable to Pour Product</fullName>
            </value>
            <value>
                <fullName>Limited Dispenser Accessibility</fullName>
            </value>
            <value>
                <fullName>External Process Failure</fullName>
            </value>
            <value>
                <fullName>Acts of God</fullName>
            </value>
            <value>
                <fullName>Trade Show</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/Type_of_Dispenser_Platform__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Dispenser_Platform__c</fullName>
    <description>multi select pick list</description>
    <label>Platform Type/s</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/recordTypes/Relocation.recordType-meta.xml
<RecordType>
    <fullName>Relocation</fullName>
    <active>true</active>
    <description>Relocation (I4W) Record Type..</description>
    <label>Relocation (I4W)</label>
</RecordType>

force-app/main/default/objects/FS_Installation__c/recordTypes/Replacement.recordType-meta.xml
<RecordType>
    <fullName>Replacement</fullName>
    <active>true</active>
    <description>Replacement Record Type...</description>
    <label>Replacement</label>
</RecordType>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Equip_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Equip_Type__c</fullName>
    <description>equip type</description>
    <inlineHelpText>This is the JDE Equipment Type value</inlineHelpText>
    <label>Equipment Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Other_PIA_Installation__c.field-meta.xml
<CustomField>
    <fullName>FS_Other_PIA_Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RO4W/Removal/Replacement Transaction</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Outlet Dispensers (Other PIA Installation)</relationshipLabel>
    <relationshipName>Outlet_Dispensers2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Serial_Number2__c.field-meta.xml
<CustomField>
    <fullName>FS_Serial_Number2__c</fullName>
    <description>Serial Number/Asset Tag.</description>
    <label>JDE Serial Number/Asset Tag</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Relocated_Installation__c.field-meta.xml
<CustomField>
    <fullName>Relocated_Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Installation Lookup only for RI4W Type</description>
    <label>Relocated Installation</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Outlet Dispensers (Relocated Installation)</relationshipLabel>
    <relationshipName>Outlet_Dispensers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Platform_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3100</fullName>
    </customValue>
    <customValue>
        <fullName>6000</fullName>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
    </customValue>
    <customValue>
        <fullName>7100</fullName>
    </customValue>
    <customValue>
        <fullName>8000</fullName>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
    </customValue>
    <masterLabel>Platform Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FSSPPlannerEmailHelperControllerTest.cls
/**************************************************************************************
Apex Class Name     : FSSPPlannerEmailHelperControllerTest
Version             : 1.0
Function            : Test class for  FSSPPlannerEmailHelperController Class. 
Modification Log    : 
* Developer         :    Date              Description
* ----------------------------------------------------------------------------                 
* Infosys             28/06/2019          Original Version 
*					  
*************************************************************************************/

@isTest
public class FSSPPlannerEmailHelperControllerTest {
    
    public static Account accchain,accHQ,accOutlet;    
    public static FS_Execution_Plan__c executionPlan;
    public static FS_Installation__c installtion,replacementInstall,relocationInstall;
    public static FS_Outlet_Dispenser__c  odRec;
    private static Profile fetSysAdmin;    
    private static String recTypeRelocation=Schema.SObjectType.FS_Installation__c.getRecordTypeInfosByName().get(Label.IP_Relocation_I4W_Rec_Type).getRecordTypeId() ;
    private static String recTypeReplace=Schema.SObjectType.FS_Installation__c.getRecordTypeInfosByName().get(Label.IP_Replacement_Rec_Type).getRecordTypeId();
    private static final String REMODEL ='Remodel';
    
    private static void createtestData(){
        List<Disable_Trigger__c> triggerList = new List<Disable_Trigger__c>();
        List<String> disTriggersRec = new List<String>{'FSAccountBusinessProcess','FSExecutionPlanTriggerHandler'};
            for(String str:disTriggersRec){
                triggerList.add(new Disable_Trigger__c(Name=str,IsActive__c=false));
            }
        insert triggerList;
        Test.setMock(HttpCalloutMock.class, new FSFETNMSConnectorMock());
        FSTestUtil.insertPlatformTypeCustomSettings();      
        
        accchain = new Account();
        accchain = FSTestUtil.createTestAccount('Test Chain 1',FSConstants.RECORD_TYPE_CHAIN,true);
        
        accHQ    = new Account();
        accHQ = FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,false);     
        accHQ.FS_Chain__c = accchain.Id;
        insert accHQ;
        
        accOutlet = new Account();
        accOutlet = FSTestUtil.createAccountOutlet('Test Outlet 1',FSConstants.RECORD_TYPE_OUTLET,accHQ.Id,true);
        
        executionPlan = new FS_Execution_Plan__c();
        executionPlan =FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,accHQ.Id,true);
        fetSysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_FETADMIN);
        installtion = new FS_Installation__c();
        installtion =FSTestUtil.createInstallationAcc(FSConstants.NEWINSTALLATION,executionPlan.id,accOutlet.id,true);       
        odRec = FSTestUtil.createOutletDispenserAllTypes(FSConstants.RT_NAME_CCNA_OD,null,accOutlet.id,installtion.id,true);
        
        //Create Relocation and Replacement Instalaltion
        List<FS_Installation__c> listInstall=new List<FS_Installation__c>();
        replacementInstall=new FS_Installation__c();
        replacementInstall.Type_of_Dispenser_Platform__c='7000;8000;9000';
        replacementInstall.FS_Execution_Plan__c=executionPlan.id;
        replacementInstall.RecordTypeId=recTypeReplace;
        replacementInstall.FS_Install_Reconnect_Date__c=system.today();
        replacementInstall.FS_Rush_Install_Reason__c=REMODEL;
        listInstall.add(replacementInstall) ;
        
        relocationInstall=new FS_Installation__c();
        relocationInstall.Type_of_Dispenser_Platform__c='7000;8000;9000';
        relocationInstall.FS_Execution_Plan__c=executionPlan.id;
        relocationInstall.RecordTypeId=recTypeRelocation;
        relocationInstall.FS_Install_Reconnect_Date__c=system.today();
        relocationInstall.FS_Rush_Install_Reason__c=REMODEL;
        listInstall.add(relocationInstall);
        
        insert listInstall;
        
    }
    
    //OD record with Replacement Record
    private static testmethod void testODwithReplacementPIA(){
        createTestData();
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
        
        final Disable_Trigger__c disableABTrigger = new Disable_Trigger__c(Name='FSODBusinessProcess',IsActive__c=false,Trigger_Name__c='FSODBusinessProcess');
        insert disableABTrigger;
        test.startTest();
        system.runAs(fetSysAdminUser){ 
            
            //Link OD record with PIA and Update platform and Serial No to check later
            odRec.FS_Other_PIA_Installation__c=replacementInstall.id;
            odRec.FS_Serial_Number2__c='ZPL1234567';
            odRec.FS_Equip_Type__c='7000';
            update odRec;
            
            //Call Controller
            FSSPPlannerEmailHelperController spPlannerController =new FSSPPlannerEmailHelperController();
            spPlannerController.platform='7000';
            spPlannerController.installationId=replacementInstall.id;
            String strSerialNo=spPlannerController.getODSerialNo();
            
            //Check OD serial No and return string from COntroller are same
            system.assertEquals(strSerialNo,odRec.FS_Serial_Number2__c);
        }
        test.stopTest();
    }
    
    //OD record with Relocation I4W
    private static testmethod void testODWithRelocationI4WPIA(){
        createTestData();
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
        test.startTest();
        final Disable_Trigger__c disableABTrigger = new Disable_Trigger__c(Name='FSODBusinessProcess',IsActive__c=false,Trigger_Name__c='FSODBusinessProcess');
        insert disableABTrigger;
        system.runAs(fetSysAdminUser){
            
            //Link OD record with PIA and Update platform and Serial No to check later
            odRec.Relocated_Installation__c=relocationInstall.id;
            odRec.FS_Serial_Number2__c='ZPL1234567';
            odRec.FS_Equip_Type__c='7000';
            update odRec;
            
            //Call Controller
            FSSPPlannerEmailHelperController spPlannerController =new FSSPPlannerEmailHelperController();
            spPlannerController.recordType= Label.IP_Relocation_I4W_Rec_Type;
            spPlannerController.platform='7000';
            spPlannerController.installationId=relocationInstall.id;
            String strSerialNo=spPlannerController.getODSerialNo();
            
            //Check OD serial No and return string from COntroller are same
            system.assertEquals(strSerialNo,odRec.FS_Serial_Number2__c);
        }
        test.stopTest();
    }
}