force-app/main/default/objects/Account/fields/FS_Chain__c.field-meta.xml
<CustomField>
    <fullName>FS_Chain__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chain</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for Chain.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Chain</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Headquarters/Outlets</relationshipLabel>
    <relationshipName>Chains</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_OD_Settings__c/FS_OD_Settings__c.object-meta.xml
<CustomObject>
    <description>OD Settings</description>
    <label>OD Settings</label>
    <nameField>
        <displayFormat>ODS-{0000000}</displayFormat>
        <label>OD Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OD Settings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_OD_Settings__c/fields/FS_OD_RecId__c.field-meta.xml
<CustomField>
    <fullName>FS_OD_RecId__c</fullName>
    <description>OD Record ID</description>
    <label>OD RecID</label>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipLabel>OD Settings</relationshipLabel>
    <relationshipName>Settings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_OD_SettingsReadOnly__c/FS_OD_SettingsReadOnly__c.object-meta.xml
<CustomObject>
    <description>OD SettingsReadOnly</description>
    <label>OD SettingsReadOnly</label>
    <nameField>
        <displayFormat>ODSR-{0000000}</displayFormat>
        <label>OD SettingsReadOnly Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OD SettingsReadOnly</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_OD_SettingsReadOnly__c/fields/FS_OD_RecId__c.field-meta.xml
<CustomField>
    <fullName>FS_OD_RecId__c</fullName>
    <description>OD Record ID</description>
    <label>OD RecID</label>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipName>OD_Editable_Settings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/FOT_ODSettingsController_Test.cls
@isTest
public class FOT_ODSettingsController_Test {
	private static Account accchain,bottler,outlet,accHQ;
    @TestSetUp
    Static void RecordCreate(){
        
        FSTestFactory.lstPlatform(); 
        accchain = FSTestUtil.createTestAccount('Test Chain 1',FSConstants.RECORD_TYPE_CHAIN,true);
        //Create Headquarters
        accHQ = FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,false);
        accHQ.FS_Chain__c = accchain.Id;
        insert accHQ;
        outlet = FSTestUtil.createAccountOutlet('Test Outlet',FSConstants.RECORD_TYPE_OUTLET,accHQ.id, true);
        FS_Outlet_Dispenser__c outletDispenser1 = FSTestUtil.createOutletDispenserAllTypes(FSConstants.RT_NAME_CCNA_OD,null,outlet.id,null,true);
        
        List<FS_OD_Settings__c> lstODSetting = New List<FS_OD_Settings__c> ();
        FS_OD_Settings__c ODSet1 = New FS_OD_Settings__c();
        
        ODSet1.FS_OD_RecId__c=outletDispenser1.id;
        lstODSetting.add(ODSet1);
        
        List<FS_OD_SettingsReadOnly__c> lstODsetReadOnly = New List<FS_OD_SettingsReadOnly__c> ();
        FS_OD_SettingsReadOnly__c setReadOnly = New FS_OD_SettingsReadOnly__c();
        setReadOnly.FS_OD_RecId__c =outletDispenser1.id;
        lstODsetReadOnly.add(setReadOnly);
        
    }
    
     @istest
    static void testMethod1()
    {
        
        FS_Outlet_Dispenser__c Od = [Select Id FROM FS_Outlet_Dispenser__c];
        //final Profile fotOPAmin=FSTestFactory.getProfileId(FSConstants.USER_PROFILE_OP_ADMIN);
        //final User fotOPAminUser=FSTestFactory.createUser(fotOPAmin.id);
        //insert fotOPAminUser;
        String proName;
         //system.runAs(fotOPAminUser){ 
         test.startTest();
        FOT_ODSettingsController.ODSettingsRecordDetails(Od.Id);
        FOT_ODSettingsController.ODEDitableSettingsRecordDetails(Od.Id);
        proName = FOT_ODSettingsController.userProfileAccess();
        //system.assertEquals('Ops Admin', proName);
        system.assertEquals('System Administrator', proName);
        test.stopTest();
         //}
    }
}