force-app/main/default/objects/Account/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Outlet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <displayFormat>EP-{0000}</displayFormat>
    <label>Execution Plan#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Initial_Order__c/FS_Initial_Order__c.object-meta.xml
<CustomObject>
    <label>Initial Order</label>
    <nameField>
        <label>Initial Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Initial Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Initial_Order__c/fields/FS_CPO_Notes__c.field-meta.xml
<CustomField>
    <fullName>FS_CPO_Notes__c</fullName>
    <label>Customer Support Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FS_Initial_Order__c/fields/FS_Installation__c.field-meta.xml
<CustomField>
    <fullName>FS_Installation__c</fullName>
    <label>Installation</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Initial Orders</relationshipLabel>
    <relationshipName>Initial_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Initial_Order__c/fields/FS_Order_Processed__c.field-meta.xml
<CustomField>
    <fullName>FS_Order_Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Order Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Initial_Order__c/fields/FS_Order_Processed_by__c.field-meta.xml
<CustomField>
    <fullName>FS_Order_Processed_by__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Processed by</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Initial_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Initial_Order__c/fields/FS_Order_Processed_DataTime__c.field-meta.xml
<CustomField>
    <fullName>FS_Order_Processed_DataTime__c</fullName>
    <label>Order Processed/Modified Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_CPO_Notes__c.field-meta.xml
<CustomField>
    <fullName>FS_CPO_Notes__c</fullName>
    <label>Customer Support Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlet Info Summary</relationshipLabel>
    <relationshipName>Outlet_Info_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Order_Processed_By__c.field-meta.xml
<CustomField>
    <fullName>FS_Order_Processed_By__c</fullName>
    <label>Order Processed By</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Order_Processed_Data_Time__c.field-meta.xml
<CustomField>
    <fullName>FS_Order_Processed_Data_Time__c</fullName>
    <label>Order Processed Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/FS_InitialOrderCorrectionTest.cls
@istest
private class FS_InitialOrderCorrectionTest{
    
    static testmethod void testBatchProcess(){
        Profile fetSysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_FETADMIN);
        Account headQuarterAcc = FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,true);
        Account  outlet=FSTestUtil.createAccountOutlet('Test Outlet 1',FSConstants.RECORD_TYPE_OUTLET,headQuarterAcc.Id,true);
        FS_Execution_Plan__c executionPlan = FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,headQuarterAcc.Id, true);
        FS_Installation__c installation = FSTestUtil.createInstallationAcc(FSConstants.NEWINSTALLATION,executionPlan.Id, outlet.id, true);   
        
        Test.startTest(); //FET 7.0 FNF-823
        FS_Initial_Order__c ioRec = new FS_Initial_Order__c();
        ioRec.FS_Installation__c =installation.id ;
        ioRec.name = 'testIo';        
        ioRec.FS_Order_Processed__c=true;        
        ioRec.recordtypeid= Schema.SObjectType.FS_Initial_Order__c.getRecordTypeInfosByName().get(FSConstants.NEWINITIALORDER).getRecordTypeId();
        insert ioRec;
        installation.FS_CPO_Notes__c='testing1';
        installation.FS_Order_Processed_By__c=null;
        installation.FS_Order_Processed_Data_Time__c=null;
        update installation;
        String query='select FS_Installation__c,FS_CPO_Notes__c,FS_Order_Processed_by__c,FS_Order_Processed_DataTime__c'+ 
            ' from FS_Initial_Order__c WHERE FS_Order_Processed__c=true and LastModifiedDate  = THIS_WEEK'; 
        system.debug('The SOQL is '+query );
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
        system.runAs(fetSysAdminUser){
            FS_InitialOrderCorrection  c = new FS_InitialOrderCorrection(query);
            Database.executeBatch(c);
        }
          Test.stopTest(); //FET 7.0 FNF-823
        system.assert([select id,FS_Order_Processed_By__c from FS_Installation__c where id=:installation.id].FS_Order_Processed_By__c != null);
        system.assertEquals([select id,FS_CPO_Notes__c from FS_Installation__c where id=:installation.id].FS_CPO_Notes__c,Null);
      
    }
}