force-app/main/default/objects/Account/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Outlet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Headquarters</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for HQ.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Headquarters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/FS_Association_Brandset__c.object-meta.xml
<CustomObject>
    <label>Default Brandset</label>
    <nameField>
        <displayFormat>AB-{00000}</displayFormat>
        <label>Account Brandset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Brandsets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Brandset__c.field-meta.xml
<CustomField>
    <fullName>FS_Brandset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brandset</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Selected Brandset is not available for commercial use</errorMessage>
        <filterItems>
            <field>FS_Brandset__c.FS_Platform_Applicable__c</field>
            <operation>contains</operation>
            <valueField>$Source.FS_Platform__c</valueField>
        </filterItems>
        <filterItems>
            <field>FS_Brandset__c.Available_for_Selection__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FS_Brandset__c</referenceTo>
    <relationshipLabel>Default Brandsets</relationshipLabel>
    <relationshipName>Brandsets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Headquarters</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Default Brandset</relationshipLabel>
    <relationshipName>FSHeadquarters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Installation__c.field-meta.xml
<CustomField>
    <fullName>FS_Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation Plan</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Selected Brandsets</relationshipLabel>
    <relationshipName>Account_Brandsets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Outlet_Dispenser__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_Dispenser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet Dispenser</label>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipLabel>Brandset Details (Current)</relationshipLabel>
    <relationshipName>OutletDispensers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <displayFormat>EP-{0000}</displayFormat>
    <label>Execution Plan#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <label>Headquarters</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Value does not exist or does not match filter criteria for HQ on EP.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Execution Plans (Headquarters)</relationshipLabel>
    <relationshipName>Execution_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Platform_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform_Type__c</fullName>
    <description>multi select picklist</description>
    <label>Platform Type/s</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_Brandset__c.field-meta.xml
<CustomField>
    <fullName>FS_Brandset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brandset 7000</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>FS_Brandset__c.FS_Platform_Applicable__c</field>
            <operation>contains</operation>
            <value>7000</value>
        </filterItems>
        <filterItems>
            <field>FS_Brandset__c.Available_for_Selection__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FS_Brandset__c</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlet Info Summary</relationshipLabel>
    <relationshipName>Outlet_Info_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/Type_of_Dispenser_Platform__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Dispenser_Platform__c</fullName>
    <description>multi select pick list</description>
    <label>Platform Type/s</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Brandset__c.field-meta.xml
<CustomField>
    <fullName>FS_Brandset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Brandset Associated to Outlet Dispenser</description>
    <label>Brandset</label>
    <referenceTo>FS_Brandset__c</referenceTo>
    <relationshipLabel>Outlet Dispensers (Brandset)</relationshipLabel>
    <relationshipName>CurrentBrandset</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 OR 2) AND 4) OR 3 OR 5</booleanFilter>
        <errorMessage>The installation referenced by this dispenser is linked to a different outlet than the outlet on the dispenser.</errorMessage>
        <filterItems>
            <field>FS_Installation__c.FS_Outlet__c</field>
            <operation>equals</operation>
            <valueField>$Source.FS_Outlet__c</valueField>
        </filterItems>
        <filterItems>
            <field>FS_Installation__c.FS_New_Outlet__c</field>
            <operation>equals</operation>
            <valueField>$Source.FS_Outlet__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Dispenser</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>CCNA Dispenser, 7000, 8000, 9000</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Installed Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/FS_Valid_Fill__c.object-meta.xml
<CustomObject>
    <label>Valid Fill</label>
    <nameField>
        <displayFormat>VF-{0000}</displayFormat>
        <label>Valid Fill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Valid Fill</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Valid_Fill__c/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <formula>FS_Outlet__r.FS_Headquarters__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Headquarters</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/fields/FS_Installation__c.field-meta.xml
<CustomField>
    <fullName>FS_Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Post Install Valid Fill</relationshipLabel>
    <relationshipName>Valid_Fill</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/fields/FS_Outlet_Dispenser__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_Dispenser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet Dispenser</label>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipLabel>Post Install Valid Fill</relationshipLabel>
    <relationshipName>Valid_Fill</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Platform_Type_ctrl__c/Platform_Type_ctrl__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>PlatformType Ctrl</description>
    <label>PlatformType Ctrl</label>
</CustomObject>

force-app/main/default/objects/Platform_Type_ctrl__c/fields/Platforms__c.field-meta.xml
<CustomField>
    <fullName>Platforms__c</fullName>
    <description>Platforms</description>
    <label>Platforms</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Platform_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3100</fullName>
    </customValue>
    <customValue>
        <fullName>6000</fullName>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
    </customValue>
    <customValue>
        <fullName>7100</fullName>
    </customValue>
    <customValue>
        <fullName>8000</fullName>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
    </customValue>
    <masterLabel>Platform Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FSEnterEditViewFlavorChangeWiredSolTest.cls
/*********************************************************************************************************
Name         : FSEnterEditViewFlavorChangeWiredSolTest
Created By   : Pallavi Sharma (Appiro)
Created Date : 18 - Sep - 2013
Usage        : Unit test coverage of FSEnterEditViewFlavorChangeWiredSolCtrl
Modified By : Venkata 13-02-2017	reg FET 4.0 Project for covering the new code
***********************************************************************************************************/
/**************************************************************************************
Apex Class Name     : FSEnterEditViewFlavorChangeWiredSolTest
Version             : 1.0
Function            : This test class is for  FSEnterEditViewFlavorChangeWiredSolctrl Class code coverage. 
Modification Log    : 
* Developer         :    Date              Description
* ----------------------------------------------------------------------------                 
* Infosys             			          Original Version 
*					  05/29/2018		  Removed usage of OutboundServiceDetails__c customSetting as part of FOT project
*************************************************************************************/
@isTest
private class FSEnterEditViewFlavorChangeWiredSolTest {
    
    public static string emptyVal = '';  
    public static string fName1 = 'fName1';     
    public static string lName1 = 'lName1';   
    public static string barqs = 'Barqs';
    public static final string PLAT7K='7000';
    public static string excutionPlanParam = 'executionplanid';
    public static Id executionPlanId;
    public static List<FS_Brandset__c> brandsets;
    public static FS_Installation__c installation;
    public static Platform_Type_ctrl__c platformTypes,platformTypes1,platformTypes2,platformTypes3,platformTypes4,platformTypes5; 
    //Create Test Data
    private static void createTestData(){
        FSTestFactory.createTestDisableTriggerSetting();        
        
        //Create Single HeadQuarter
        final List<Account> headQuarterCustomerList= FSTestFactory.createTestAccount(true,1,
                                                                                     FSUtil.getObjectRecordTypeId(Account.SObjectType,'FS Headquarters'));
        //Create Single Outlet
        final List<Account> outletCustomerList=new List<Account>();
        for(Account acc : FSTestFactory.createTestAccount(false,1,FSUtil.getObjectRecordTypeId(Account.SObjectType,'FS Outlet'))){
            acc.FS_Headquarters__c=headQuarterCustomerList.get(0).Id;
            outletCustomerList.add(acc);
        }
        insert outletCustomerList;
        
        //Create Execution Plan
        final Id epRecordTypeId=FSUtil.getObjectRecordTypeId(FS_Execution_Plan__c.SObjectType,FSConstants.EXECUTIONPLAN);                    
        FS_Execution_Plan__c executionPlan = FSTestFactory.createTestExecutionPlan(headQuarterCustomerList.get(0).Id,false,1,epRecordTypeId)[0];
        executionPlan.FS_Platform_Type__c=PLAT7K;
        insert executionPlan;    
        
        //Create Installation         
        final Id intallationRecordTypeId = FSUtil.getObjectRecordTypeId(FS_Installation__c.SObjectType,FSConstants.NEWINSTALLATION); 
        final List<FS_Installation__c > installList =FSTestFactory.createTestInstallationPlan(executionPlan.id,outletCustomerList.get(0).Id,false,1,intallationRecordTypeId);
        installList[0].Type_of_Dispenser_Platform__c=PLAT7K;
        insert installList;

        brandsets=FSTestFactory.createTestBrandset();
        executionPlan=[select id from FS_Execution_Plan__c limit 1];
        
        executionPlanId=executionPlan.id;
        final List<Platform_Type_ctrl__c> listplatform = new List<Platform_Type_ctrl__c>();
        platformTypes=new Platform_Type_ctrl__c(Name='updateBrands',Platforms__c=PLAT7K);
        listplatform.add(platformTypes);
        platformTypes1=new Platform_Type_ctrl__c(Name='EquipmentTypeCheckForNMSUpdateCall',Platforms__c='7000,8000,9000');       
        listplatform.add(platformTypes1);
        platformTypes2=new Platform_Type_ctrl__c(Name='WaterHideCheck',Platforms__c='8000,9000');        
        listplatform.add(platformTypes2);
        platformTypes3=new Platform_Type_ctrl__c(Name='all_Platform',Platforms__c='7000,8000,9000');        
        listplatform.add(platformTypes3);
        platformTypes4=new Platform_Type_ctrl__c(Name='updatecrewServeDasani',Platforms__c='8000');
        listplatform.add(platformTypes4);
        platformTypes5=new Platform_Type_ctrl__c(Name='updateSelfServeDasani',Platforms__c='9000');        
        listplatform.add(platformTypes5);
        insert listplatform; 
        
        Test.setMock(HttpCalloutMock.class, new FSFETNMSConnectorMock());
        final Disable_Trigger__c disableODTrigger = new Disable_Trigger__c(Name='FSODBusinessProcess',IsActive__c=false,Trigger_Name__c='Fs_OD_Trigger');
        insert disableODTrigger;
        final FS_Outlet_Dispenser__c outletDispenser=new FS_Outlet_Dispenser__c(FS_Outlet__c=outletCustomerList.get(0).Id,FS_Serial_Number2__c='SNO001',FS_Dispenser_Location__c='Location',
                                                   FS_User_Defined_Location__c='Location2',FS_Valid_Fill__c='No', 
                                                   FS_Equip_Type__c=PLAT7K,FS_IsActive__c=true,Installation__c =  installList[0].Id );        
       
        insert outletDispenser;
    }   
    
    private static testMethod void testUpdateAB(){
        final Profile adminProfile = FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
        final User adminUser = FSTestFactory.createUser(adminProfile.id);
        insert adminUser;
        system.runAs(adminUser){
            createTestData(); 
            system.debug('-----------------Queries after createTestData----'+Limits.getQueries());
            
            Test.startTest();
            
            final Pagereference pgRefer = Page.FSEnterEditView_Flavor_ChangeWired_Sol;
            Test.setCurrentPage(pgRefer);
            //Initialize Page paramteres
            pgRefer.getParameters().put(excutionPlanParam, executionPlanId);
            //Initialize controller
            final FSEnterEditViewFlavorChangeWiredSolCtrl flavorChange = new FSEnterEditViewFlavorChangeWiredSolCtrl();
            
            for (FS_Installation__c ip : flavorChange.lstInstallation){
                system.debug(ip.Account_Brandsets__r);
                for (FS_Association_Brandset__c assBrand : ip.Account_Brandsets__r) {
                    system.debug(ip.Account_Brandsets__r);
                    assBrand.FS_Brandset__c=brandsets[0].id;
                    assBrand.FS_NonBranded_Water__c='Show';
                }
            }            
            flavorChange.saveInstallation();            
             System.assertEquals(flavorChange.executionPlan, executionPlanId);
            Test.stopTest();
        }
    }
    
    private static testMethod void testErrorMessage(){
        final Profile adminProfile = FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
        final User adminUser = FSTestFactory.createUser(adminProfile.id);
        insert adminUser;
        system.runAs(adminUser){
            createTestData(); 
            system.debug('-----------------Queries after createTestData----'+Limits.getQueries());
            
            Test.startTest();
            
            final Pagereference pgRefer = Page.FSEnterEditView_Flavor_ChangeWired_Sol;
            Test.setCurrentPage(pgRefer);
            //Initialize Page paramteres
            pgRefer.getParameters().put(excutionPlanParam, executionPlanId);
            //Initialize controller
            final FSEnterEditViewFlavorChangeWiredSolCtrl flavorChange = new FSEnterEditViewFlavorChangeWiredSolCtrl();
            
            for (FS_Installation__c ip : flavorChange.lstInstallation){
                system.debug(ip.Account_Brandsets__r);
                for (FS_Association_Brandset__c assBrand : ip.Account_Brandsets__r) {
                    system.debug(ip.Account_Brandsets__r);
                    //assBrand.FS_Brandset__c=brandsets[0].id;
                    assBrand.FS_NonBranded_Water__c='Show';
                }
            }            
            flavorChange.saveInstallation();
            
            Test.stopTest();
        }
    }
    // Test method for Cancel
    private static testMethod void testCancelMethod(){
        final Profile adminProfile = FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
        final User adminUser = FSTestFactory.createUser(adminProfile.id);
        insert adminUser;
        system.runAs(adminUser){
            createTestData(); 
            system.debug('-----------------Queries after createTestData----'+Limits.getQueries());
            
            Test.startTest();
            
            final Pagereference pgRefer = Page.FSEnterEditView_Flavor_ChangeWired_Sol;
            Test.setCurrentPage(pgRefer);
            //Initialize Page paramteres
            pgRefer.getParameters().put(excutionPlanParam, executionPlanId);
            //Initialize controller
            final FSEnterEditViewFlavorChangeWiredSolCtrl flavorChange = new FSEnterEditViewFlavorChangeWiredSolCtrl();    
            //testing cancel method
            flavorChange.cancel();            
            System.assertEquals(flavorChange.executionPlan, executionPlanId);
            Test.stopTest();
        }
    }
}