force-app/main/default/objects/Account/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Outlet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apex_Error_Log__c/Apex_Error_Log__c.object-meta.xml
<CustomObject>
    <description>Custom Object used to store all the errors in exception blocks along with system.debug statements. Mostly useful in case of triggers, batch classes etc.</description>
    <label>Apex Error Log</label>
    <nameField>
        <label>Apex Error Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Errors Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Error_Log__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>Name of the Class or Component or File or Reference from where the error or exception reported.</description>
    <label>Class Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Disable_Trigger__c/Disable_Trigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is only used in case there is a need to deactivate a trigger during data migration. The triggers must be kept activated at all times...</description>
    <label>Disable Trigger</label>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <displayFormat>EP-{0000}</displayFormat>
    <label>Execution Plan#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For Post Install</description>
    <label>Outlet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Outlet</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Post Install Activity</relationshipLabel>
    <relationshipName>Outlet_Post_Execution_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/AutorabitExtId__c.field-meta.xml
<CustomField>
    <fullName>AutorabitExtId__c</fullName>
    <description>External Id created by AutoRABIT</description>
    <externalId>true</externalId>
    <label>AutorabitExtId__c</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlet Info Summary</relationshipLabel>
    <relationshipName>Outlet_Info_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Original_Install_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Original_Install_Date__c</fullName>
    <label>Initially Scheduled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installations (Outlet)</relationshipLabel>
    <relationshipName>Installations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/Overall_Status2__c.field-meta.xml
<CustomField>
    <fullName>Overall_Status2__c</fullName>
    <label>Transaction Status</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/Type_of_Dispenser_Platform__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Dispenser_Platform__c</fullName>
    <description>multi select pick list</description>
    <label>Platform Type/s</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Other_PIA_Installation__c.field-meta.xml
<CustomField>
    <fullName>FS_Other_PIA_Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RO4W/Removal/Replacement Transaction</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Outlet Dispensers (Other PIA Installation)</relationshipLabel>
    <relationshipName>Outlet_Dispensers2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <description>Outlet field.</description>
    <label>Outlet</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 3) OR (2 AND 4 AND (5 OR 7)) OR (2 AND 4 AND 6)</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for Outlet.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Outlet</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Outlet</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>7000, 8000, 9000, CCNA Dispenser</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Dispenser</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value>No, Yes</value>
        </filterItems>
        <filterItems>
            <field>Account.Is_Default_FET_International_Outlet__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlet Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Platform_Type_ctrl__c/Platform_Type_ctrl__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>PlatformType Ctrl</description>
    <label>PlatformType Ctrl</label>
</CustomObject>

force-app/main/default/objects/Platform_Type_ctrl__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>Class Name</description>
    <label>Class Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Type_ctrl__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>This field contains the method name where this Custom Setting is being used</description>
    <label>MethodName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Type_ctrl__c/fields/Platforms__c.field-meta.xml
<CustomField>
    <fullName>Platforms__c</fullName>
    <description>Platforms</description>
    <label>Platforms</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/AutorabitExtId__c.field-meta.xml
<CustomField>
    <fullName>AutorabitExtId__c</fullName>
    <description>External Id created by AutoRABIT</description>
    <externalId>true</externalId>
    <label>AutorabitExtId__c</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Platform_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3100</fullName>
    </customValue>
    <customValue>
        <fullName>6000</fullName>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
    </customValue>
    <customValue>
        <fullName>7100</fullName>
    </customValue>
    <customValue>
        <fullName>8000</fullName>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
    </customValue>
    <masterLabel>Platform Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FSInstallRescheduleAuraControllerTest.cls
@isTest
public class FSInstallRescheduleAuraControllerTest {
    private static Profile fetSysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_FETADMIN);
    private static Account headquartersAcc,outletAcc,outletAccHavingNoDispensers;
    private static FS_Execution_Plan__c executionPlan;
    private static FS_Installation__c installation;
    private static String recTypeNewInstall=Schema.SObjectType.FS_Installation__c.getRecordTypeInfosByName().get(FSConstants.NEWINSTALLATION).getRecordTypeId() ;
    private static String recTypeRemoval=Schema.SObjectType.FS_Installation__c.getRecordTypeInfosByName().get(Label.IP_Removal_Rec_Type).getRecordTypeId() ;
    
    private static void createTestData(){
        headquartersAcc = FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,true);
        outletAcc= FSTestUtil.createAccountOutlet('Test Outlet 1',FSConstants.RECORD_TYPE_OUTLET,null,true);
        outletAccHavingNoDispensers= FSTestUtil.createAccountOutlet('Test Outlet 2',FSConstants.RECORD_TYPE_OUTLET,null,true);
        executionPlan = FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,headquartersAcc.Id, true);
        List<Platform_Type_ctrl__c> pTypes = new List<Platform_Type_ctrl__c>();
        Platform_Type_ctrl__c platType1= new Platform_Type_ctrl__c(Name='all_Platform',Platforms__c='6000,6050,7000,8000,9000,9100',Method__c='OD trigger handler',AutorabitExtId__c= 'a141g0000008fLhAAI');
        pTypes.add(platType1);
        Platform_Type_ctrl__c platType2= new Platform_Type_ctrl__c(Name='updateBrands',Platforms__c='7000',Method__c='OD trigger handler',AutorabitExtId__c= 'a141g0000008fLfAAI');
        pTypes.add(platType2);
        Platform_Type_ctrl__c platType3= new Platform_Type_ctrl__c(Name='updatecrewServeDasani',Platforms__c='8000',Method__c='OD trigger handler',AutorabitExtId__c= 'a141g0000008fLeAAI');
        pTypes.add(platType3);
        Platform_Type_ctrl__c platType4= new Platform_Type_ctrl__c(Name='updateSelfServeDasani',Platforms__c='9000',Method__c='OD trigger handler',AutorabitExtId__c= 'a141g0000008fLeAAI');
        pTypes.add(platType4);
        Platform_Type_ctrl__c platType5= new Platform_Type_ctrl__c(Name='WaterHideCheck',Platforms__c='7000',Method__c='airWatchSynchronousCall',AutorabitExtId__c= 'a141g0000008fLjAAI',Class_Name__c = 'FS FET NMS CONNECTOR');
        pTypes.add(platType5);
        Platform_Type_ctrl__c platType6= new Platform_Type_ctrl__c(Name='EquipmentTypeCheckForNMSUpdateCall',Platforms__c='6000,6050,7000,8000,9000,9100',Method__c='airWatchSynchronousCall',AutorabitExtId__c= 'a141g0000008fLiAAI',Class_Name__c = 'FS FET NMS CONNECTOR');
        pTypes.add(platType6);
        insert pTypes;
        
    }
    
    @isTest
    private static void disableAccessCheckTest(){ 
        //Insert User
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
		test.startTest();
        system.runAs(fetSysAdminUser){
            boolean checkDisableAccess=FSInstallRescheduleAuraController.disableAccessCheck();
            system.assertEquals(false, checkDisableAccess);
        }
		test.stopTest();        
    }
    
    
    @isTest
    private static void installScheduleCheckTest(){      
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
        Disable_Trigger__c installCustomSetRec = new Disable_Trigger__c(Name='FSInstallationBusinessProcess',ISACTIVE__C=false);
        insert installCustomSetRec;
		createTestData();
        List<FS_Installation__c> installList = new List<FS_Installation__c>();
        installList.add(new FS_Installation__c(recordtypeid=recTypeNewInstall,Type_of_Dispenser_Platform__c='7000',FS_Execution_plan__c=executionPlan.id,FS_outlet__c=outletAcc.Id,FS_Original_Install_Date__c=system.today()));
        installList.add(new FS_Installation__c(recordtypeid=recTypeRemoval,Type_of_Dispenser_Platform__c='8000;9000',FS_Execution_plan__c=executionPlan.id,FS_outlet__c=outletAcc.Id));
        insert installList;
        test.startTest();
        FS_Installation__c ipRec = new FS_Installation__c(recordtypeid=recTypeNewInstall,Type_of_Dispenser_Platform__c='7000',FS_Execution_plan__c=executionPlan.id,FS_outlet__c=outletAcc.Id,FS_Original_Install_Date__c=system.today()); 
        
        system.runAs(fetSysAdminUser){
            FSInstallRescheduleAuraController.installScheduleDateCheck(ipRec.Id);
            system.assert([select id from Apex_Error_Log__c limit 10].size()>0);
            FSInstallRescheduleAuraController ipScheduleValidCheck=FSInstallRescheduleAuraController.installScheduleDateCheck(installList[0].Id);
            system.assertEquals(false, ipScheduleValidCheck.ipScheduleCheck);
            FSInstallRescheduleAuraController ipScheduleInValidCheck=FSInstallRescheduleAuraController.installScheduleDateCheck(installList[1].Id);
            system.assertEquals(true, ipScheduleInValidCheck.ipScheduleCheck);     
        }
		test.stopTest();        
    }
   /* Checking for No dispenser selected error, empty dispenser section, platform mismatch error 
        and Checking if the Platform Types that are selected under IP contains the OD selected of that Platform Type.
   as part of FNF-747*/
    @isTest
    private static void installReScheduleCheck(){   
        List<FS_Installation__c> ins = new List<FS_Installation__c>();
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
        Disable_Trigger__c installCustomSetRec = new Disable_Trigger__c(Name='FSInstallationBusinessProcess',ISACTIVE__C=false);
        insert installCustomSetRec;
		createTestData();

        test.startTest();
        FS_Installation__c ipRec = new FS_Installation__c(recordtypeid=recTypeRemoval,Type_of_Dispenser_Platform__c='8000',FS_Execution_plan__c=executionPlan.id,FS_outlet__c=outletAcc.Id,Overall_Status2__c='Scheduled'); 
        ins.add(ipRec);
        FS_Installation__c noDispenserInstallation = new FS_Installation__c(recordtypeid=recTypeRemoval,Type_of_Dispenser_Platform__c='8000',FS_Execution_plan__c=executionPlan.id,FS_outlet__c=outletAccHavingNoDispensers.Id,Overall_Status2__c='Scheduled'); 
         ins.add(noDispenserInstallation);
        FS_Installation__c platformMismatchIns = new FS_Installation__c(recordtypeid=recTypeRemoval,Type_of_Dispenser_Platform__c='8000',FS_Execution_plan__c=executionPlan.id,FS_outlet__c=outletAccHavingNoDispensers.Id,Overall_Status2__c='Scheduled'); 
        ins.add(platformMismatchIns);
        FS_Installation__c platformMismatchIns1 = new FS_Installation__c(recordtypeid=recTypeRemoval,Type_of_Dispenser_Platform__c='8000;9000',FS_Execution_plan__c=executionPlan.id,FS_outlet__c=outletAccHavingNoDispensers.Id,Overall_Status2__c='Scheduled'); 
        ins.add(platformMismatchIns1);
        if(ins.size()>0){
            insert ins;
        }
        FS_Outlet_Dispenser__c outDisp = FSTestUtil.createOutletDispenserAllTypes('BoE Dispenser','7000',outletAcc.id,null,true);
        outDisp.FS_Other_PIA_Installation__c = ins[2].id;
        update outDisp;
        FS_Outlet_Dispenser__c outDisp1 = FSTestUtil.createOutletDispenserAllTypes('BoE Dispenser','8000',outletAcc.id,null,true);
        outDisp1.FS_Other_PIA_Installation__c = ins[3].id;
        update outDisp1;
        
        system.runAs(fetSysAdminUser){
            FSInstallRescheduleAuraController noDispSelected=FSInstallRescheduleAuraController.installScheduleDateCheck(ins[0].id);
            system.assertEquals(true, noDispSelected.outletDispensersNotSelectedError);  
             FSInstallRescheduleAuraController emptyDispSection=FSInstallRescheduleAuraController.installScheduleDateCheck(ins[1].id);
            system.assertEquals(true, emptyDispSection.dispenserSectionEmptyError); 
            FSInstallRescheduleAuraController platFormMisMatch=FSInstallRescheduleAuraController.installScheduleDateCheck(ins[2].id);
            system.assertEquals(true, platFormMisMatch.plattformMismatchError); 
             FSInstallRescheduleAuraController platFormMisMatch1=FSInstallRescheduleAuraController.installScheduleDateCheck(ins[3].id);
            system.assertEquals(true, platFormMisMatch1.plattformMismatchError); 
        }
		test.stopTest();        
    }

}