force-app/main/default/objects/Account/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Outlet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Valid_Fill__c.field-meta.xml
<CustomField>
    <fullName>FS_Valid_Fill__c</fullName>
    <label>Valid Fill</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <displayFormat>EP-{0000}</displayFormat>
    <label>Execution Plan#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For Post Install</description>
    <label>Outlet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Outlet</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Post Install Activity</relationshipLabel>
    <relationshipName>Outlet_Post_Execution_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Valid_Fill__c.field-meta.xml
<CustomField>
    <fullName>FS_Valid_Fill__c</fullName>
    <label>Valid Fill</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>46245 : Valid Fill Conversion Kit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlet Info Summary</relationshipLabel>
    <relationshipName>Outlet_Info_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installations (Outlet)</relationshipLabel>
    <relationshipName>Installations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Valid_Fill__c.field-meta.xml
<CustomField>
    <fullName>FS_Valid_Fill__c</fullName>
    <label>Valid Fill</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>46245 : Valid Fill Conversion Kit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <description>Outlet field.</description>
    <label>Outlet</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 3) OR (2 AND 4 AND (5 OR 7)) OR (2 AND 4 AND 6)</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for Outlet.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Outlet</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Outlet</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>7000, 8000, 9000, CCNA Dispenser</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Dispenser</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value>No, Yes</value>
        </filterItems>
        <filterItems>
            <field>Account.Is_Default_FET_International_Outlet__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlet Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Valid_Fill__c.field-meta.xml
<CustomField>
    <fullName>FS_Valid_Fill__c</fullName>
    <label>Valid Fill Required</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/FS_Valid_Fill__c.object-meta.xml
<CustomObject>
    <label>Valid Fill</label>
    <nameField>
        <displayFormat>VF-{0000}</displayFormat>
        <label>Valid Fill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Valid Fill</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Valid_Fill__c/fields/FS_Installation__c.field-meta.xml
<CustomField>
    <fullName>FS_Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Post Install Valid Fill</relationshipLabel>
    <relationshipName>Valid_Fill</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Post-Install Valid Fill</relationshipLabel>
    <relationshipName>Vailid_Fill</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/fields/FS_Outlet_Dispenser__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_Dispenser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet Dispenser</label>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipLabel>Post Install Valid Fill</relationshipLabel>
    <relationshipName>Valid_Fill</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/fields/FS_RcdIDForCncl__c.field-meta.xml
<CustomField>
    <fullName>FS_RcdIDForCncl__c</fullName>
    <label>Record ID For Cancel</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OutboundServiceDetails__c/OutboundServiceDetails__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>OutboundServiceDetails</label>
</CustomObject>

force-app/main/default/classes/FSBatchCancelValidFillTest.cls
/**************************************************************************************
Apex Class Name     : FSBatchCancelValidFillTest
Version             : 1.0
Function            : This test class is for FSBatchCancelValidFill Class code coverage. 
Modification Log    : 
* Developer         :    Date              Description
* ----------------------------------------------------------------------------                 
* Infosys             			          Original Version 
*					  05/29/2018		  Removed usage of OutboundServiceDetails__c customSetting as part of FOT project
*************************************************************************************/
@isTest
private class FSBatchCancelValidFillTest{
    public static Account headquartersAcc,outletAcc;
    public static FS_Execution_Plan__c executionPlan;
    public static FS_Installation__c installation;
    public static FS_Outlet_Dispenser__c oDispenser7k,oDispenser8k,oDispenser9k;
    public static FS_Valid_Fill__c validFill7k,validFill8k,validFill9k;
    
    private static void createTestData(){
        
        Test.setMock(HttpCalloutMock.class, new FSFETNMSConnectorMock());
        FSTestUtil.insertPlatformTypeCustomSettings();

        headquartersAcc = FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,true);
        outletAcc=FSTestUtil.createAccountOutlet('Test Outlet 1',FSConstants.RECORD_TYPE_OUTLET,headquartersAcc.id,true);        
        executionPlan=FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,headquartersAcc.Id, false);    
        final List<FS_Execution_Plan__c> epList=new List<FS_Execution_Plan__c>();
        epList.add(executionPlan);        
        insert epList;
        
        installation= FSTestUtil.createInstallationAcc(FSConstants.NEWINSTALLATION,executionPlan.Id,outletAcc.id , false);
        
        final List<FS_Installation__c> ipList=new List<FS_Installation__c>();
        ipList.add(installation);      
        
        insert ipList;
    }
    
    private static testmethod void cancelValidFill(){
        createTestData();
        oDispenser7k=FSTestUtil.createOutletDispenserAllTypes('CCNA Dispenser','7000',outletAcc.id,installation.id,true);
        
        validFill7k=FSTestUtil.createValidFill('7000',false);
        validFill7k.FS_Outlet__c=outletAcc.id;
        insert validFill7k;
        Test.startTest();
        validFill7k.FS_RcdIDForCncl__c=validFill7k.id;
        update validFill7k;
        final Profile fetSysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_FETADMIN);
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
        system.runAs(fetSysAdminUser){
            final FSBatchCancelValidFill batchInstance=new FSBatchCancelValidFill(validFill7k.id);
            Database.executeBatch(batchInstance);
        }
        Test.stopTest();        
    }
    
    private static testmethod void cancelValidFill8000(){
        createTestData();
        oDispenser7k=FSTestUtil.createOutletDispenserAllTypes('CCNA Dispenser','8000',outletAcc.id,installation.id,true);
        
        validFill8k=FSTestUtil.createValidFill('8000',false);
        validFill8k.FS_Outlet__c=outletAcc.id;
        insert validFill8k;
        Test.startTest();
        validFill8k.FS_RcdIDForCncl__c=validFill8k.id;
        update validFill8k;
        final Profile fetSysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_FETADMIN);
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
        system.runAs(fetSysAdminUser){
            final FSBatchCancelValidFill batchInstance=new FSBatchCancelValidFill(validFill8k.id);
            Database.executeBatch(batchInstance);
        }
        Test.stopTest();        
    }
    
    private static testmethod void cancelValidFill9000(){
        createTestData();
        oDispenser7k=FSTestUtil.createOutletDispenserAllTypes('CCNA Dispenser','9000',outletAcc.id,installation.id,true);
        
        validFill8k=FSTestUtil.createValidFill('9000',false);
        validFill8k.FS_Outlet__c=outletAcc.id;
        insert validFill8k;
        Test.startTest();
        validFill8k.FS_RcdIDForCncl__c=validFill8k.id;
        update validFill8k;
        final Profile fetSysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_FETADMIN);
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
        system.runAs(fetSysAdminUser){
            final FSBatchCancelValidFill batchInstance=new FSBatchCancelValidFill(validFill8k.id);
            Database.executeBatch(batchInstance);
        }
        Test.stopTest();        
    }
    
     private static testmethod void cancelValidFill9100(){
        createTestData();
        oDispenser7k=FSTestUtil.createOutletDispenserAllTypes('CCNA Dispenser','9100',outletAcc.id,installation.id,true);
        
        validFill8k=FSTestUtil.createValidFill('9100',false);
        validFill8k.FS_Outlet__c=outletAcc.id;
        insert validFill8k;
        Test.startTest();
        validFill8k.FS_RcdIDForCncl__c=validFill8k.id;
        update validFill8k;
        final Profile fetSysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_FETADMIN);
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
        system.runAs(fetSysAdminUser){
            final FSBatchCancelValidFill batchInstance=new FSBatchCancelValidFill(validFill8k.id);
            Database.executeBatch(batchInstance);
        }
        Test.stopTest();        
    }
}