force-app/main/default/objects/Account/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Outlet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Headquarters</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for HQ.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Headquarters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/FS_Association_Brandset__c.object-meta.xml
<CustomObject>
    <label>Default Brandset</label>
    <nameField>
        <displayFormat>AB-{00000}</displayFormat>
        <label>Account Brandset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Brandsets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Brandset__c.field-meta.xml
<CustomField>
    <fullName>FS_Brandset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brandset</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Selected Brandset is not available for commercial use</errorMessage>
        <filterItems>
            <field>FS_Brandset__c.FS_Platform_Applicable__c</field>
            <operation>contains</operation>
            <valueField>$Source.FS_Platform__c</valueField>
        </filterItems>
        <filterItems>
            <field>FS_Brandset__c.Available_for_Selection__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FS_Brandset__c</referenceTo>
    <relationshipLabel>Default Brandsets</relationshipLabel>
    <relationshipName>Brandsets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Headquarters</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Default Brandset</relationshipLabel>
    <relationshipName>FSHeadquarters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Installation__c.field-meta.xml
<CustomField>
    <fullName>FS_Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation Plan</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Selected Brandsets</relationshipLabel>
    <relationshipName>Account_Brandsets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Outlet_Dispenser__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_Dispenser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet Dispenser</label>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipLabel>Brandset Details (Current)</relationshipLabel>
    <relationshipName>OutletDispensers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Brandset__c/FS_Brandset__c.object-meta.xml
<CustomObject>
    <description>FS_Brandset</description>
    <label>Brandset</label>
    <nameField>
        <label>Brandset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brandsets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Brandset__c/fields/FS_Platform__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform__c</fullName>
    <description>Platform</description>
    <label>Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <displayFormat>EP-{0000}</displayFormat>
    <label>Execution Plan#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <label>Headquarters</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Value does not exist or does not match filter criteria for HQ on EP.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Execution Plans (Headquarters)</relationshipLabel>
    <relationshipName>Execution_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For Post Install</description>
    <label>Outlet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Outlet</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Post Install Activity</relationshipLabel>
    <relationshipName>Outlet_Post_Execution_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_Brandset__c.field-meta.xml
<CustomField>
    <fullName>FS_Brandset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brandset 7000</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>FS_Brandset__c.FS_Platform_Applicable__c</field>
            <operation>contains</operation>
            <value>7000</value>
        </filterItems>
        <filterItems>
            <field>FS_Brandset__c.Available_for_Selection__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FS_Brandset__c</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlet Info Summary</relationshipLabel>
    <relationshipName>Outlet_Info_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installations (Outlet)</relationshipLabel>
    <relationshipName>Installations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/Type_of_Dispenser_Platform__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Dispenser_Platform__c</fullName>
    <description>multi select pick list</description>
    <label>Platform Type/s</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Brandset__c.field-meta.xml
<CustomField>
    <fullName>FS_Brandset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Brandset Associated to Outlet Dispenser</description>
    <label>Brandset</label>
    <referenceTo>FS_Brandset__c</referenceTo>
    <relationshipLabel>Outlet Dispensers (Brandset)</relationshipLabel>
    <relationshipName>CurrentBrandset</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Equip_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Equip_Type__c</fullName>
    <description>equip type</description>
    <inlineHelpText>This is the JDE Equipment Type value</inlineHelpText>
    <label>Equipment Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <description>Outlet field.</description>
    <label>Outlet</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 3) OR (2 AND 4 AND (5 OR 7)) OR (2 AND 4 AND 6)</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for Outlet.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Outlet</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Outlet</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>7000, 8000, 9000, CCNA Dispenser</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Dispenser</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value>No, Yes</value>
        </filterItems>
        <filterItems>
            <field>Account.Is_Default_FET_International_Outlet__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlet Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/globalValueSets/Platform_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3100</fullName>
    </customValue>
    <customValue>
        <fullName>6000</fullName>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
    </customValue>
    <customValue>
        <fullName>7100</fullName>
    </customValue>
    <customValue>
        <fullName>8000</fullName>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
    </customValue>
    <masterLabel>Platform Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FSCopyTodaysBrandsetsDispenserTest.cls
/**************************************************************************************
Apex Class Name     : FSCopyTodaysBrandsetsDispenserTest
Version             : 1.0
Function            : This test class is for  FSCopyTodaysBrandsetsDispenser Class code coverage. 
Modification Log    : 
* Developer         :    Date              Description
* ----------------------------------------------------------------------------                 
* Infosys             04/24/2017          Original Version 
*                     05/29/2018          Removed usage of OutboundServiceDetails__c customSetting as part of FOT project
*************************************************************************************/
@isTest
private  class FSCopyTodaysBrandsetsDispenserTest{
    private static final String SERIES7000 ='7000 Series';   
    private static final String SERIES8000 ='8000 Series'; 

    private static final String SERIES8000N9000 ='8000 & 9000 Series';
    
    private static final String NUM7000 ='7000'; 
    private static final String NUM8000 ='8000';
    private static final String NUM9000 ='9000'; 
    private static final String CUSTOMFIELDEQUIPTYPE='FS_Equip_Type__c';
    private static final String CUSTOMFIELDPLATFORM ='FS_Platform__c';
    private static List<FS_Brandset__c> brandset7000List;
    private static List<FS_Brandset__c> brandset8000List;
    private static List<FS_Brandset__c> brandset9000List;
    private static List<FS_Outlet_Dispenser__c> dispenserToUpdate;
    
    
    @testSetup
    public static void loadTestData(){              
        //create Brandset records
        FSTestFactory.createTestBrandset();
        
         /** @desc this method creates 1 chain,1 HQ, 1 Outlet,1 Execution Pan(Execution Plan),
      * 4 Installation('7000 Series','8000 & 9000 Series','8000 Series','9000 Series')*/
       //Create Single HeadQuarter
        final List<Account> headQuarterCustomerList= FSTestFactory.createTestAccount(true,1,
                                                                                     FSUtil.getObjectRecordTypeId(Account.SObjectType,'FS Headquarters'));
        
        //Create Single Outlet
        final List<Account> outletCustomerList=new List<Account>();
        for(Account acc : FSTestFactory.createTestAccount(false,1,FSUtil.getObjectRecordTypeId(Account.SObjectType,'FS Outlet'))){
            acc.FS_Headquarters__c=headQuarterCustomerList.get(0).Id;
            outletCustomerList.add(acc);
        }
        insert outletCustomerList;
        
        //Create Execution Plan
        //Collection to hold all recordtype names of Execution plan                                                                       
        final Set<String> executionPlanRecordTypesSet=new Set<String>{fsconstants.EXECUTIONPLAN};
            //Collection to hold all recordtype values of Execution plan
            final Map<Id,String> executionPlanRecordTypesMap=new Map<Id,String>();
        
        final List<FS_Execution_Plan__c> executionPlanList=new List<FS_Execution_Plan__c>();
        //Create One executionPlan records for each record type
        for(String epRecType : executionPlanRecordTypesSet){            
            final Id epRecordTypeId=FSUtil.getObjectRecordTypeId(FS_Execution_Plan__c.SObjectType,epRecType);            
            executionPlanRecordTypesMap.put(epRecordTypeId,epRecType);            
            final List<FS_Execution_Plan__c> epList=FSTestFactory.createTestExecutionPlan(headQuarterCustomerList.get(0).Id,false,1,epRecordTypeId);
            executionPlanList.addAll(epList);                                                                     
        }                       
        insert executionPlanList;       
        //Create Installation
        final Set<String> installationPlanRecordTypesSet=new Set<String>{fsconstants.NEWINSTALLATION}; 
            final List<FS_Installation__c > installationPlanList=new List<FS_Installation__c >();         
        //Create Installation for each Execution Plan according to recordtype        
        for(String  installationRecordType : installationPlanRecordTypesSet){
            final Id intallationRecordTypeId = FSUtil.getObjectRecordTypeId(FS_Installation__c.SObjectType,installationRecordType); 
            final List<FS_Installation__c > installList =FSTestFactory.createTestInstallationPlan(executionPlanList.get(0).Id,outletCustomerList.get(0).Id,false,1,intallationRecordTypeId);
            installationPlanList.addAll(installList);
        }         
        insert installationPlanList;  
        //Create custom setting data
        List<Platform_Type_ctrl__c> listplatform = FSTestFactory.lstPlatform();
        List<ProfileListFromCustomSettings__c>  lstOfProfiles = FSTestFactory.lstProfiles();
        Test.setMock(HttpCalloutMock.class, new FSFETNMSConnectorMock());
        final Map<Id,String> installationRecordTypeIdAndName=FSUtil.getObjectRecordTypeIdAndNAme(FS_Installation__c.SObjectType);
        
        
        final List<FS_Outlet_Dispenser__c> outletDispenserList=new List<FS_Outlet_Dispenser__c>();
        
        //Create Outlet Dispensers 
        for(FS_Installation__c installPlan : [SELECT Id,RecordTypeId,FS_Outlet__c,Type_of_Dispenser_Platform__c FROM FS_Installation__c  limit 100]){
            List<FS_Outlet_Dispenser__c> odList=new List<FS_Outlet_Dispenser__c>();
            Id outletDispenserRecordTypeId =FSUtil.getObjectRecordTypeId(FS_Outlet_Dispenser__c.SObjectType,FsConstants.RT_NAME_CCNA_OD);
            
            if(installPlan.Type_of_Dispenser_Platform__c.contains(SERIES7000) ){
                
                odList=FSTestFactory.createTestOutletDispenser(installPlan.Id,installPlan.FS_Outlet__c,outletDispenserRecordTypeId,false,1,'');
                odList[0].put(CUSTOMFIELDEQUIPTYPE, SERIES7000);
            }
            
            if(installPlan.Type_of_Dispenser_Platform__c.contains(NUM8000) ){
                
                odList=FSTestFactory.createTestOutletDispenser(installPlan.Id,installPlan.FS_Outlet__c,outletDispenserRecordTypeId,false,1,'');
                odList[0].put(CUSTOMFIELDEQUIPTYPE, NUM8000);
                
            }
            if(installPlan.Type_of_Dispenser_Platform__c.contains(NUM9000) ){
                
                odList=FSTestFactory.createTestOutletDispenser(installPlan.Id,installPlan.FS_Outlet__c,outletDispenserRecordTypeId,false,1,'');
                odList[0].put(CUSTOMFIELDEQUIPTYPE, NUM9000);
            }
            outletDispenserList.addAll(odList);
            
        }
        //create trigger switch --custom setting
        FSTestFactory.createTestDisableTriggerSetting();
        test.startTest();
        insert outletDispenserList;
        test.stopTest();
    }
    
    private static testMethod void testDispenserWithoutAssociationBrandset(){
        //create HTTP mock to handle runtime HTTP request from FETNMS Connector
        try{
            Test.setMock(HttpCalloutMock.class, new FSFETNMSConnectorMock());
            //FSFETNMSConnector.airWatchSynchronousCall(lstOutletDispensersID,NULL);
        }catch(Exception ex){
            System.debug('Exception- '+ex);
        }
        FSFETNMSConnectorMock http = new FSFETNMSConnectorMock();
        
        //Separate Brandset based on platform 
        final List<FS_Brandset__c> brandset7000List=new List<FS_Brandset__c>();
        brandset8000List=new List<FS_Brandset__c>();
        brandset9000List=new List<FS_Brandset__c>();
        
        for(FS_Brandset__c brandset: [SELECT Id,FS_Platform__c FROM FS_Brandset__c LIMIT 100]){
            if(brandset.FS_Platform__c.contains(NUM7000)){
                brandset7000List.add(brandset);
            } 
            if(brandset.FS_Platform__c.contains(NUM8000)){
                brandset8000List.add(brandset);
            } 
            if(brandset.FS_Platform__c.contains(NUM9000)) {
                brandset9000List.add(brandset);
            }
            
        }

        dispenserToUpdate=[SELECT Id,Name,FS_Equip_Type__c,FS_Brandset_New__c,FS_Brandset_Effective_Date__c FROM FS_Outlet_Dispenser__c LIMIT 200];

        for(FS_Outlet_Dispenser__c dispenser : dispenserToUpdate){
            if(dispenser.FS_Equip_Type__c==NUM7000){

                dispenser.FS_Brandset_New__c=brandset7000List.get(0).Id;
                dispenser.FS_Brandset_Effective_Date__c =System.today();
            }
            if(dispenser.FS_Equip_Type__c==NUM8000){

                dispenser.FS_Brandset_New__c=brandset8000List.get(0).Id;
                dispenser.FS_Brandset_Effective_Date__c =System.today();
            }
            if(dispenser.FS_Equip_Type__c==NUM9000){
                dispenser.FS_Brandset_New__c=brandset9000List.get(0).Id;
                dispenser.FS_Brandset_Effective_Date__c =System.today();
            }
        }
        Test.startTest();
        UPDATE dispenserToUpdate;
        
        Test.stopTest();
        
        //verify values were copied
        for(FS_Outlet_Dispenser__c dispenser :  [SELECT Id,FS_Brandset_New__c,FS_Brandset_Effective_Date__c  FROM FS_Outlet_Dispenser__c  LIMIT 200]){
            system.assert(dispenser.FS_Brandset_New__c!=NULL);
            system.assert(dispenser.FS_Brandset_Effective_Date__c !=NULL);
        }
    }
    
    private static testMethod void testDispenserWithAssociationBrandset(){
        //Separate Brandset based on platform 
        brandset7000List=new List<FS_Brandset__c>();
        brandset8000List=new List<FS_Brandset__c>();
        brandset9000List=new List<FS_Brandset__c>();
        
        for(FS_Brandset__c brandset: [SELECT Id,FS_Platform__c FROM FS_Brandset__c LIMIT 100]){
            if(brandset.FS_Platform__c.contains(NUM7000)){
                brandset7000List.add(brandset);
            } 
            if(brandset.FS_Platform__c.contains(NUM8000)){
                brandset8000List.add(brandset);
            } 
            if(brandset.FS_Platform__c.contains(NUM9000)) {
                brandset9000List.add(brandset);
            }
        }
        
        dispenserToUpdate=[SELECT Id,Name,FS_Equip_Type__c,FS_Brandset_New__c,FS_Brandset_Effective_Date__c FROM FS_Outlet_Dispenser__c LIMIT 200];
        final List<FS_Association_Brandset__c > associationBrandsetList =new List<FS_Association_Brandset__c >();
        
        for(FS_Outlet_Dispenser__c dispenser : dispenserToUpdate){
            List<FS_Association_Brandset__c > associationList=new List<FS_Association_Brandset__c >();
            if(dispenser.FS_Equip_Type__c==NUM7000){
                final List<FS_Brandset__c > bransetOtherthanAssociatedToDispenser=new List<FS_Brandset__c>{brandset7000List[1]};
                associationList=FSTestFactory.createTestAssociationBrandset(false,bransetOtherthanAssociatedToDispenser,'FS_Outlet_Dispenser__c',dispenser.Id,1);
                associationList[0].put(CUSTOMFIELDPLATFORM , NUM7000);
                associationBrandsetList.addAll(associationList);
                
                dispenser.FS_Brandset_New__c=brandset7000List.get(0).Id;
                dispenser.FS_Brandset_Effective_Date__c =System.today();
            }
            if(dispenser.FS_Equip_Type__c==NUM8000){
                final List<FS_Brandset__c > bransetOtherthanAssociatedToDispenser=new List<FS_Brandset__c>{brandset8000List[1]};
                    associationList=FSTestFactory.createTestAssociationBrandset(false,bransetOtherthanAssociatedToDispenser,'FS_Outlet_Dispenser__c',dispenser.Id,1);
                associationList[0].put(CUSTOMFIELDPLATFORM , NUM8000);
                associationBrandsetList.addAll(associationList);
                
                dispenser.FS_Brandset_New__c=brandset8000List.get(0).Id;
                dispenser.FS_Brandset_Effective_Date__c =System.today();
            }
            if(dispenser.FS_Equip_Type__c==NUM9000){
                final List<FS_Brandset__c > bransetOtherthanAssociatedToDispenser=new List<FS_Brandset__c>{brandset9000List[1]};
                    associationList=FSTestFactory.createTestAssociationBrandset(false,bransetOtherthanAssociatedToDispenser,'FS_Outlet_Dispenser__c',dispenser.Id,1);
                associationList[0].put(CUSTOMFIELDPLATFORM, NUM9000);
                associationBrandsetList.addAll(associationList);
                
                dispenser.FS_Brandset_New__c=brandset9000List.get(0).Id;
                dispenser.FS_Brandset_Effective_Date__c =System.today();
            }
        }
        
        INSERT associationBrandsetList;
        system.assert([select id from FS_Association_Brandset__c]!=null);
        final User sysAdminUser=FSTestUtil.createUser(null,1,FSConstants.USER_POFILE_SYSADMIN,true);
        system.runAs(sysAdminUser){
            Test.startTest();
            Test.setMock(HttpCalloutMock.class, new FSFETNMSConnectorMock());
            UPDATE dispenserToUpdate;
            
            Test.stopTest();
            for(FS_Outlet_Dispenser__c dispenser :  [SELECT Id,FS_Brandset_New__c,FS_Brandset_Effective_Date__c  FROM FS_Outlet_Dispenser__c  LIMIT 200]){
            system.assert(dispenser.FS_Brandset_New__c!=NULL);
            system.assert(dispenser.FS_Brandset_Effective_Date__c !=NULL);
        }
        }
    } 
}