force-app/main/default/objects/Account/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Outlet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Outlet_Information__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_Information__c</fullName>
    <formula>&quot;ACN: &quot; &amp; FS_ACN__c &amp;&quot; | SAP ID: &quot; &amp; FS_SAP_ID__c &amp; BR() &amp; &quot;Store #: &quot;&amp; FS_Store_Number__c &amp; BR() &amp; 
&quot;Address: &quot; &amp; ShippingStreet &amp; BR() &amp; 
ShippingCity &amp;&quot;, &quot;&amp; ShippingState &amp;&quot; &quot; &amp; ShippingCountry &amp;&#39; &#39;&amp; ShippingPostalCode &amp; BR() &amp; 
&quot;Phone: &quot; &amp;Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Outlet Information</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Vendor_Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>FS_Vendor_Primary_Contact__c</fullName>
    <label>Vendor Primary Contact</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Vendor_Primary_Email__c.field-meta.xml
<CustomField>
    <fullName>FS_Vendor_Primary_Email__c</fullName>
    <label>Vendor Primary Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Vendor_Primary_Phone__c.field-meta.xml
<CustomField>
    <fullName>FS_Vendor_Primary_Phone__c</fullName>
    <label>Vendor Primary Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Vendor_Secondary_Contact__c.field-meta.xml
<CustomField>
    <fullName>FS_Vendor_Secondary_Contact__c</fullName>
    <label>Vendor Secondary Contact</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Vendor_Secondary_Email__c.field-meta.xml
<CustomField>
    <fullName>FS_Vendor_Secondary_Email__c</fullName>
    <label>Vendor Secondary Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Vendor_Secondary_Phone__c.field-meta.xml
<CustomField>
    <fullName>FS_Vendor_Secondary_Phone__c</fullName>
    <label>Vendor Secondary Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Vendor_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Vendor_Type__c</fullName>
    <label>Vendor Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>*Davaco</fullName>
            </value>
            <value>
                <fullName>Counter</fullName>
            </value>
            <value>
                <fullName>Electrician</fullName>
            </value>
            <value>
                <fullName>General Contractor</fullName>
            </value>
            <value>
                <fullName>Ice Maker</fullName>
            </value>
            <value>
                <fullName>Plumber</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <displayFormat>EP-{0000}</displayFormat>
    <label>Execution Plan#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For Post Install</description>
    <label>Outlet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Outlet</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Post Install Activity</relationshipLabel>
    <relationshipName>Outlet_Post_Execution_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlet Info Summary</relationshipLabel>
    <relationshipName>Outlet_Info_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_GC_Coordination_to_be_done_by__c.field-meta.xml
<CustomField>
    <fullName>FS_GC_Coordination_to_be_done_by__c</fullName>
    <label>GC - Coordination to be done by?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Sales Support</fullName>
            </value>
            <value>
                <fullName>COM</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installations (Outlet)</relationshipLabel>
    <relationshipName>Installations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Outlet_Information__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_Information__c</fullName>
    <description>Outlet Information</description>
    <formula>FS_Outlet__r.FS_Outlet_Information__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Outlet Information</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Related_Vendor__c.field-meta.xml
<CustomField>
    <fullName>FS_Related_Vendor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Related Vendor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>please select a valid vendor.</errorMessage>
        <filterItems>
            <field>Account.FS_Vendor_Type__c</field>
            <operation>equals</operation>
            <value>General Contractor</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Vendor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installations (Related Vendor)</relationshipLabel>
    <relationshipName>Installations3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FSGeneralContractorCtrl.cls
//**************************************************
//Name         : FSGeneralContractorCtrl
//Created By   : Mohit Parnami (Appiro)
//Created Date : 1 - oct - 2013
//Usage        : Controller class of FSGeneralContractor
//Modification Log: venkata as part of FET 4.0
//9th Jan,2019 Modified by: Sai Krishna. Added a new Cancel method for redirection to prev Execution plan record page. Reg: FET 6 Ref:(Jira FNF-115)
// **************************************************
public with sharing class FSGeneralContractorCtrl {
    public static final string ALL='All';
    public static final string COORDINATION='Coordination';
    public static final string RELATEDVENDOR='RelatedVendor';
    public FS_Execution_Plan__c executionPlan {get;set;}    
    public List<FS_Installation__c> lstInstallations{get;set;}
    public string selectedFillDown{get;set;}  
    
    public static object nullValue() { return null; }
    //constructor method to fetch the execution plan record
    public FSGeneralContractorCtrl(final ApexPages.StandardController stdController){
        //getting the execution plan record
        executionPlan = (FS_Execution_Plan__c)stdController.getRecord();        
        init();
    }   
    
        /*****************************************************************
  	Method: init
  	Description: init method is used to get all the installation under the execution plan		
	*******************************************************************/
    public  void init(){
        lstInstallations = new List<FS_Installation__c>();
        //fetching all the installations under the execution plan
        for(FS_Installation__c inst : [select id,Name,FS_Outlet__r.FS_Outlet_Information__c, FS_Related_Vendor__c, FS_GC_Coordination_to_be_done_by__c,
                                       FS_Related_Vendor__r.FS_Vendor_Type__c, FS_Related_Vendor__r.Name, FS_Related_Vendor__r.FS_Vendor_Primary_Contact__c,
                                       FS_Related_Vendor__r.FS_Vendor_Primary_Phone__c, FS_Related_Vendor__r.FS_Vendor_Primary_Email__c,
                                       FS_Related_Vendor__r.FS_Vendor_Secondary_Contact__c, FS_Related_Vendor__r.FS_Vendor_Secondary_Phone__c,
                                       FS_Related_Vendor__r.FS_Vendor_Secondary_Email__c From FS_Installation__c
                                       Where FS_Execution_Plan__c =: executionPlan.Id]){
                                           lstInstallations.add(inst); 
                                       }      
    }
    
     /*****************************************************************
  	Method: saveOutletInfo
  	Description: saveOutletInfo method is to save the outlets and the respective Installation records		
	*******************************************************************/
    public PageReference saveOutletInfo(){ 
        PageReference page;       
        SavePoint savePosition;   //Save Point Variable        
        final List<Account> lstAccountToUpdate = new List<Account>();
        final set<Account> setAccountToUpdate=new Set<Account>();
        
        for(FS_Installation__c ins :lstInstallations){           
            if(ins.FS_Outlet__r != nullValue()){
                setAccountToUpdate.add(ins.FS_Outlet__r);                
            }
        }
        lstAccountToUpdate.addAll(setAccountToUpdate);
        
        //OCR1 Req to bypass Bottler by srini
        FSConstants.BypassOrderDelivery =true;
        try{
            savePosition = Database.setSavePoint();
            //update the account details
            if(!lstAccountToUpdate.isEmpty()){
                update lstAccountToUpdate;             
            }
            //update the installation records
            if(!lstInstallations.isEmpty()){
                update lstInstallations;               
            }     
            page=new PageReference('/' + executionPlan.Id);
        }
        //catching DML Exceptions and rolling back the changes to savepoint state
        catch(DMLException ex){
            apexpages.addMessages(ex);
            Database.rollback(savePosition);			           
            ApexErrorLogger.addApexErrorLog(FSConstants.FET,'FSGeneralContractorCtrl','saveOutletInfo',FSConstants.INSTALLATIONOBJECTNAME,FSConstants.MediumPriority,ex,ex.getMessage());            
        }                     
        return page;
    }
    /*****************************************************************
  	Method: fillDown
  	Description: fillDown method is to fill the same value of the first record to the respective following records		
	*******************************************************************/
   
    public void fillDown(){       
        if (selectedFillDown == ALL){
            for (FS_Installation__c inst :lstInstallations){       
                inst.FS_GC_Coordination_to_be_done_by__c= lstInstallations[0].FS_GC_Coordination_to_be_done_by__c ;
                inst.FS_Related_Vendor__c= lstInstallations[0].FS_Related_Vendor__c ;
            }
        }
        else if (selectedFillDown == COORDINATION){
            for (FS_Installation__c inst :lstInstallations){       
                inst.FS_GC_Coordination_to_be_done_by__c= lstInstallations[0].FS_GC_Coordination_to_be_done_by__c ;
            }
        }
        else if (selectedFillDown == RELATEDVENDOR){
            for (FS_Installation__c inst :lstInstallations){       
                inst.FS_Related_Vendor__c= lstInstallations[0].FS_Related_Vendor__c ;
            }
        }     
    }
    /*****************************************************************
  	Method: cancel
  	Description: cancel method helps the user return back to the execution plan record  
	*******************************************************************/
    public PageReference cancel(){
        PageReference pageRef;
        if(executionPlan.Id!= Null){
            pageRef= new PageReference('/' + executionPlan.Id);
        }
        return pageRef;        
    } 
}