force-app/main/default/objects/Account/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Outlet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Headquarters</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for HQ.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Headquarters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_SP_Aligned_Zip__c.field-meta.xml
<CustomField>
    <fullName>FS_SP_Aligned_Zip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SP Aligned Zip</label>
    <referenceTo>FS_SP_Aligned_Zip__c</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/FS_Association_Brandset__c.object-meta.xml
<CustomObject>
    <label>Default Brandset</label>
    <nameField>
        <displayFormat>AB-{00000}</displayFormat>
        <label>Account Brandset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Brandsets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Brandset__c.field-meta.xml
<CustomField>
    <fullName>FS_Brandset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brandset</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Selected Brandset is not available for commercial use</errorMessage>
        <filterItems>
            <field>FS_Brandset__c.FS_Platform_Applicable__c</field>
            <operation>contains</operation>
            <valueField>$Source.FS_Platform__c</valueField>
        </filterItems>
        <filterItems>
            <field>FS_Brandset__c.Available_for_Selection__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FS_Brandset__c</referenceTo>
    <relationshipLabel>Default Brandsets</relationshipLabel>
    <relationshipName>Brandsets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Headquarters</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Default Brandset</relationshipLabel>
    <relationshipName>FSHeadquarters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Installation__c.field-meta.xml
<CustomField>
    <fullName>FS_Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation Plan</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Selected Brandsets</relationshipLabel>
    <relationshipName>Account_Brandsets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Brandset__c/FS_Brandset__c.object-meta.xml
<CustomObject>
    <description>FS_Brandset</description>
    <label>Brandset</label>
    <nameField>
        <label>Brandset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brandsets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Brandset__c/fields/FS_Platform__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform__c</fullName>
    <description>Platform</description>
    <label>Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <displayFormat>EP-{0000}</displayFormat>
    <label>Execution Plan#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <label>Headquarters</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Value does not exist or does not match filter criteria for HQ on EP.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Execution Plans (Headquarters)</relationshipLabel>
    <relationshipName>Execution_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For Post Install</description>
    <label>Outlet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Outlet</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Post Install Activity</relationshipLabel>
    <relationshipName>Outlet_Post_Execution_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Platform_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform_Type__c</fullName>
    <description>multi select picklist</description>
    <label>Platform Type/s</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_Brandset__c.field-meta.xml
<CustomField>
    <fullName>FS_Brandset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brandset 7000</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>FS_Brandset__c.FS_Platform_Applicable__c</field>
            <operation>contains</operation>
            <value>7000</value>
        </filterItems>
        <filterItems>
            <field>FS_Brandset__c.Available_for_Selection__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FS_Brandset__c</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlet Info Summary</relationshipLabel>
    <relationshipName>Outlet_Info_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Original_Install_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Original_Install_Date__c</fullName>
    <label>Initially Scheduled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installations (Outlet)</relationshipLabel>
    <relationshipName>Installations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/Type_of_Dispenser_Platform__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Dispenser_Platform__c</fullName>
    <description>multi select pick list</description>
    <label>Platform Type/s</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation_Reschedule__c/FS_Installation_Reschedule__c.object-meta.xml
<CustomObject>
    <description>This object stores the reschedule information and is created as part of FET 5.0 release..</description>
    <label>Reschedule</label>
    <nameField>
        <displayFormat>RS-{0000000}</displayFormat>
        <label>Reschedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reschedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation_Reschedule__c/fields/FS_Installation__c.field-meta.xml
<CustomField>
    <fullName>FS_Installation__c</fullName>
    <label>Installation Name</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Transaction Reschedule/s</relationshipLabel>
    <relationshipName>Installation_Reschedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_SP_Aligned_Zip__c/FS_SP_Aligned_Zip__c.object-meta.xml
<CustomObject>
    <description>Establishes the default Service Provider for a given Zip Code. Every record is a Zip Code (unique), and each one aligns to a Service Provider account via lookup.</description>
    <label>SP Aligned Zip</label>
    <nameField>
        <displayFormat>SPZ-{000000}</displayFormat>
        <label>SP Aligned Zip</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SP Aligned Zips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_SP_Aligned_Zip__c/fields/FS_Platform_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform_Type__c</fullName>
    <label>Platform Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_SP_Aligned_Zip__c/fields/FS_Selling_Activity_Market__c.field-meta.xml
<CustomField>
    <fullName>FS_Selling_Activity_Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Selling Activity Market</label>
    <referenceTo>Selling_Activity_Market__c</referenceTo>
    <relationshipLabel>SP Aligned Zips</relationshipLabel>
    <relationshipName>SP_Aligned_Zips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_SP_Aligned_Zip__c/fields/FS_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>FS_Zip_Code__c</fullName>
    <description>The 5-char Zip Code, including leading zeroes</description>
    <externalId>true</externalId>
    <inlineHelpText>Zip Code must be exactly 5 digits, include leading zeroes.</inlineHelpText>
    <label>Zip Code</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Selling_Activity_Market__c/Selling_Activity_Market__c.object-meta.xml
<CustomObject>
    <label>Selling Activity Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selling Activity Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Selling_Activity_Market__c/fields/Market_Activation_Date__c.field-meta.xml
<CustomField>
    <fullName>Market_Activation_Date__c</fullName>
    <label>Market Activation Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Platform_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3100</fullName>
    </customValue>
    <customValue>
        <fullName>6000</fullName>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
    </customValue>
    <customValue>
        <fullName>7100</fullName>
    </customValue>
    <customValue>
        <fullName>8000</fullName>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
    </customValue>
    <masterLabel>Platform Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FSInstallRescheduleTriggerTest.cls
/*****************************
Name         : FSInstallRescheduleTriggerTest
Created By   : Infosys
Created Date : 19/03/2018
Usage        : Test class for installation Reschedule object Trigger handler.
*****************************/
@isTest
private class FSInstallRescheduleTriggerTest {
    private static FS_Installation__c installationNew;
    private static FS_Installation__c RelocationIP;
    private static void createData(){     
        
        final List<Account> insertAccounts = new List<Account>();
        //create HQ record        
        final Account accHQ=new Account(Name = 'Test Headquarters',RecordTypeId = FSConstants.RECORD_TYPE_HQ);        
        insertAccounts.add(accHQ);
        //create Outlet record  
        final Account accOutlet=new Account(Name = 'Test Outlet',RecordTypeId = FSConstants.RECORD_TYPE_OUTLET,FS_Headquarters__c= accHQ.Id);        
        accOutlet.ShippingPostalCode='1234';
        insertAccounts.add(accOutlet);        
        insert insertAccounts;
        
        Selling_Activity_Market__c sellingMarket=new Selling_Activity_Market__c();
        sellingMarket.Name='testData';
        sellingMarket.Market_Activation_Date__c=System.today()-30;
        insert sellingMarket;
        
        final List<FS_SP_Aligned_Zip__c> spAlignedList=new List<FS_SP_Aligned_Zip__c>();
        spAlignedList.add(new FS_SP_Aligned_Zip__c(FS_Zip_Code__c=accOutlet.ShippingPostalCode,FS_Platform_Type__c='7000',FS_Selling_Activity_Market__c=sellingMarket.id));
        spAlignedList.add(new FS_SP_Aligned_Zip__c(FS_Zip_Code__c=accOutlet.ShippingPostalCode,FS_Platform_Type__c='8000',FS_Selling_Activity_Market__c=sellingMarket.id ));
        spAlignedList.add(new FS_SP_Aligned_Zip__c(FS_Zip_Code__c=accOutlet.ShippingPostalCode,FS_Platform_Type__c='9000',FS_Selling_Activity_Market__c=sellingMarket.id));
        spAlignedList.add(new FS_SP_Aligned_Zip__c(FS_Zip_Code__c=accOutlet.ShippingPostalCode,FS_Platform_Type__c='9100',FS_Selling_Activity_Market__c=sellingMarket.id));
        insert spAlignedList;
        
        //create Brandset records
        final List<FS_Brandset__c> brandsetRecordList=FSTestFactory.createTestBrandset();  
        //Separate Brandset based on platform 
        final List<FS_Brandset__c> branset7000List=new List<FS_Brandset__c>();
        final List<FS_Brandset__c> branset8000List=new List<FS_Brandset__c>();
        final List<FS_Brandset__c> branset9000List=new List<FS_Brandset__c>();
        
        for(FS_Brandset__c branset :brandsetRecordList){
            if(branset.FS_Platform__c.contains('7000')){
                branset7000List.add(branset);
            }
            if(branset.FS_Platform__c.contains('8000')){
                branset8000List.add(branset);
            }           
            if(branset.FS_Platform__c.contains('9000')) {
                branset9000List.add(branset);
            }
        }
        //create EP record  
        final FS_Execution_Plan__c executionPlan = new FS_Execution_Plan__c(FS_Headquarters__c = accHQ.Id,FS_Platform_Type__c='7000;8000');
        executionPlan.recordTypeId=Schema.SObjectType.FS_Execution_Plan__c.getRecordTypeInfosByName().get(FSConstants.EXECUTIONPLAN).getRecordTypeId();
        insert executionPlan;
        
        final List<FS_Installation__c> ipInsert = new List<FS_Installation__c>();
        
        FSTestFactory.createTestDisableTriggerSetting();
        //create New Install record
        installationNew = new FS_Installation__c(FS_Execution_Plan__c = executionPlan.Id,FS_Outlet__c = accOutlet.Id);        
        installationNew.recordtypeid=Schema.SObjectType.FS_Installation__c.getRecordTypeInfosByName().get(FSConstants.NEWINSTALLATION).getRecordTypeId();
        installationNew.Type_of_Dispenser_Platform__c='8000';
        installationNew.FS_Original_Install_Date__c=system.today()+30;
		installationNew.FS_Rush_Install_Reason__c='Remodel';      
        installationNew.FS_Pending_for_Reschedule__c=true;
        installationNew.FS_Scheduled_Install_Date__c=Date.today();
        installationNew.FS_SA_Scheduled_On_Date__c=Date.today();
        installationNew.FS_SA_Completed_Date__c=Date.today();
        ipInsert.add(installationNew);
        
        //create RI4W Installation
        RelocationIP = new FS_Installation__c(FS_Execution_Plan__c = executionPlan.Id,FS_Outlet__c = accOutlet.Id);        
        RelocationIP.recordtypeid=Schema.SObjectType.FS_Installation__c.getRecordTypeInfosByName().get(Label.IP_Relocation_I4W_Rec_Type).getRecordTypeId();
        RelocationIP.FS_Relocation_from_old_outlet_to_SP_is__c=FSConstants.BOOL_VAL;
        RelocationIP.FS_Disconnect_Final_Date__c=Date.today().addDays(1);
        RelocationIP.Type_of_Dispenser_Platform__c='8000';
        ipInsert.add(RelocationIP);
        
        insert ipInsert;

        final List<FS_Association_Brandset__c> abList=[select id,name,FS_Brandset__c,FS_Platform__c,FS_NonBranded_Water__c,FS_Installation__c from FS_Association_Brandset__c where FS_Installation__c=:installationNew.Id];
        for(FS_Association_Brandset__c abRec:abList){
            if(abRec.FS_Platform__c=='8000' &&  !branset8000List.isEmpty() ){
                abRec.FS_Brandset__c=branset8000List[0].Id;
            }
            abRec.FS_NonBranded_Water__c='Hide';
        }
        update abList;
    }
    
    private static testMethod void testInstallReschedule(){
        createData(); 
        final Profile adminProfile = FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
        final User adminUser = FSTestFactory.createUser(adminProfile.id);
        insert adminUser;
        Test.startTest();
        system.runAs(adminUser){
            
            final List<FS_Installation_Reschedule__c> installResch=new List<FS_Installation_Reschedule__c>();
            final FS_Installation_Reschedule__c installReschedule=new FS_Installation_Reschedule__c();
			installReschedule.FS_Reschedule_Install_Date__c=system.today();
            installReschedule.FS_Reason_for_Reschedule__c ='Construction Incomplete';
            installReschedule.FS_Rush_Install_Reason__c='Remodel';
            installReschedule.FS_Installation__c=installationNew.Id;
			installResch.add(installReschedule);
            
            final FS_Installation_Reschedule__c installReschedule1=new FS_Installation_Reschedule__c();
			installReschedule1.FS_Pending_for_Reschedule__c=true;
            installReschedule1.FS_Reason_for_Reschedule__c ='Construction Incomplete';            
            installReschedule1.FS_Installation__c=installationNew.Id;
            installResch.add(installReschedule1);
            
            insert installResch;
            
            final FS_Installation_Reschedule__c installReschedule2=new FS_Installation_Reschedule__c();
            installReschedule2.FS_Reschedule_Install_Date__c=system.today();
            installReschedule2.FS_Reason_for_Reschedule__c ='Construction Incomplete';            
            installReschedule2.FS_Installation__c=RelocationIP.Id;
            try{
                insert installReschedule2;
            }
            catch(Exception e){
                Boolean expectedExceptionThrown =  e.getMessage().contains('date later than the last Remove/Disconnect') ? true : false;
            	system.assertEquals(expectedExceptionThrown,true);      
            }
                        
        }
        Test.stopTest();
    }
    
}