force-app/main/default/objects/Account/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Outlet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dummy_Execution_Plan_del__c/Dummy_Execution_Plan_del__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Dummy Execution Plan</label>
</CustomObject>

force-app/main/default/objects/Dummy_Execution_Plan_del__c/fields/ExecutionPlan_Name__c.field-meta.xml
<CustomField>
    <fullName>ExecutionPlan_Name__c</fullName>
    <label>ExecutionPlan Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <displayFormat>EP-{0000}</displayFormat>
    <label>Execution Plan#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Platform_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform_Type__c</fullName>
    <description>multi select picklist</description>
    <label>Platform Type/s</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Platform_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3100</fullName>
    </customValue>
    <customValue>
        <fullName>6000</fullName>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
    </customValue>
    <customValue>
        <fullName>7100</fullName>
    </customValue>
    <customValue>
        <fullName>8000</fullName>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
    </customValue>
    <masterLabel>Platform Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FSInstallRelatedButtonsCntrlTest.cls
/******************************************************************************* 
Name         : FSInstallationRelatedButtonsController
Created By   : Infosys Limited
Created Date : Feb 05, 2019
Usage        : Unit test coverage of FSInstallationRelatedButtonsController
*******************************************************************************/

@isTest 
private class FSInstallRelatedButtonsCntrlTest{
    //--------------------------------------------------------------------------
    // Unit Test Method 
    //--------------------------------------------------------------------------
    static testMethod void  testUnit(){
          
        // Create Headquarter Account
        Account accHQ = FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,true);
        //Create Custom Setting
        Dummy_Execution_Plan_del__c expname=new Dummy_Execution_Plan_del__c();
        expname.ExecutionPlan_Name__c='abcd';
        insert expname;
        // Create Execution Plan
        FS_Execution_Plan__c excPlan =  FSTestUtil.createExecutionPlan('Execution Plan',accHQ.Id, false);
        excPlan.FS_Platform_Type__c='7000;8000';  
        excPlan.Name='abcd';     
        insert excPlan;
        Test.startTest();
        FSInstallationRelatedButtonsController.getEpId();
        System.assertEquals(expname.ExecutionPlan_Name__c, excPlan.Name);
        FSInstallationRelatedButtonsController.getProfileAccess();
        Test.stopTest();
    }
}