force-app/main/default/objects/Account/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Outlet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Headquarters</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for HQ.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Headquarters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_EP_Equipment_Package__c/FS_EP_Equipment_Package__c.object-meta.xml
<CustomObject>
    <label>Equipment Package</label>
    <nameField>
        <displayFormat>EP_EQP-{0000}</displayFormat>
        <label>Equipment Package Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipment Package</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_EP_Equipment_Package__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Equipment Package</relationshipLabel>
    <relationshipName>Equipment_Package</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <displayFormat>EP-{0000}</displayFormat>
    <label>Execution Plan#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan_Final_Approval_PM__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan_Final_Approval_PM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Execution Plan Final Approval (PM)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <label>Headquarters</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Value does not exist or does not match filter criteria for HQ on EP.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Execution Plans (Headquarters)</relationshipLabel>
    <relationshipName>Execution_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Platform_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform_Type__c</fullName>
    <description>multi select picklist</description>
    <label>Platform Type/s</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlet Info Summary</relationshipLabel>
    <relationshipName>Outlet_Info_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan_Final_Approval_PM__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan_Final_Approval_PM__c</fullName>
    <description>Execution Plan Final Approval (PM)</description>
    <label>Execution Plan Final Approval (PM)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/Type_of_Dispenser_Platform__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Dispenser_Platform__c</fullName>
    <description>multi select pick list</description>
    <label>Platform Type/s</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Platform_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3100</fullName>
    </customValue>
    <customValue>
        <fullName>6000</fullName>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
    </customValue>
    <customValue>
        <fullName>7100</fullName>
    </customValue>
    <customValue>
        <fullName>8000</fullName>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
    </customValue>
    <masterLabel>Platform Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FSCopyEPEPToInstallationsTest.cls
/*************************************************************************************
Apex Class Name     : FSCopyEPEPToInstallationsTest
Version             : 1.0
Function            : This test class is for FSCopyEPEPToInstallationsSearchExtension Class code coverage. 
Modification Log    :
* Developer         :    Date              Description
* ----------------------------------------------------------------------------                 
* Venkat    FET4.0        	11/23/2016          Original Version
* Venkat	FET5.0 			01/05/2018			Updated Version
************************************************************************************/

@isTest
private class FSCopyEPEPToInstallationsTest {    
    
    public static final string IDVAL = 'Id';
    public static final String PLATFORM='7000;8000;9000';
    public static final String APPROVED='Approved';
    public static User adminUser;
    @testSetup
    public  static void loadTestData(){        
        //Create HeadQuarters
        FSTestFactory.createTestDisableTriggerSetting();
        
        final List<Account> headQuarterList= FSTestFactory.createTestAccount(true,1,FSUtil.getObjectRecordTypeId(Account.SObjectType,FSConstants.RECORD_TYPE_NAME_HQ));
        
        //Creating Execution Plan
        final List<FS_Execution_Plan__c> executionPlanLst = FSTestFactory.createTestExecutionPlan(headQuarterList[0].id,false,5,FSUtil.getObjectRecordTypeId(FS_Execution_Plan__c.SObjectType,FSConstants.EXECUTIONPLAN));
        for(FS_Execution_Plan__c exePlan :executionPlanLst ){
            exePlan.FS_Platform_Type__c = PLATFORM;
        }
        insert executionPlanLst;
        //creating outlet
        final List<Account> outletLst = FSTestFactory.createTestAccount(false,1,FSUtil.getObjectRecordTypeId(Account.SObjectType,FSConstants.RECORD_TYPE_NAME_OUTLET));
        for(Account outlet : outletLst){
            outlet.FS_Headquarters__c =  headQuarterList[0].id;
        }
        insert outletLst;
                                                           
        //FET 5.0 regular Installation default record type "New Install"        
        //creating installation
        final List<FS_Installation__c> installList = FSTestFactory.createTestInstallationPlan(executionPlanLst[0].id,outletLst[0].id,false,1,FSUtil.getObjectRecordTypeId(FS_Installation__c.SObjectType,FSConstants.NEWINSTALLATION)); 
        for(FS_Installation__c install:installList){
            install.Type_of_Dispenser_Platform__c=PLATFORM;
        }      
        insert installList; 
        //FET 5.0 regular Installation default record type "New Install"
    } 
   
    
    private static testmethod void selectOutletTest() { 
        final Profile adminProfile = FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
        adminUser = FSTestFactory.createUser(adminProfile.id);
        insert adminUser;
        system.runAs(adminUser){            
            Test.startTest();
            final List<FS_EP_Equipment_Package__c> executionPkge = [Select id,FS_Platform_Type__c,FS_Execution_Plan__c from FS_EP_Equipment_Package__c Limit 1]; 
            final PageReference pageRef=Page.FSCopyEPEPToInstallationsSearch;
            //Sets the current PageReference for the controller
            Test.setCurrentPage(pageRef);
            //Add parameters to page URL
            pageRef.getParameters().put(IDVAL,executionPkge[0].id);
            final ApexPages.StandardController stdcon = new ApexPages.standardController(executionPkge[0]);            
            final FSCopyEPEPToInstallationsSearchExtension controller= new FSCopyEPEPToInstallationsSearchExtension(stdcon);
            controller.first();
            
            //Searching Outlet
            controller.searchOutletName = 'aaa';
            controller.searchOutlet();
            system.assertEquals(controller.wrapperRecordList.size(),0);
            Test.stopTest();          
        }
           
    }
    private static testmethod void createEPIPCopy() {        
        
        final Profile adminProfile = FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
        adminUser = FSTestFactory.createUser(adminProfile.id);
        insert adminUser;
        
        system.runAs(adminUser){
            Test.startTest();     
            final FS_EP_Equipment_Package__c executionPkge = [Select id,FS_Execution_Plan__c from FS_EP_Equipment_Package__c Limit 1];
            //Sets the current PageReference for the controller
            final PageReference pageRef=Page.FSCopyEPEPToInstallationsSearch;
            Test.setCurrentPage(pageRef);
            //Add parameters to page URL
            pageRef.getParameters().put(IDVAL,executionPkge.id);
            final ApexPages.StandardController stdcon = new ApexPages.standardController(executionPkge);        
            
            final FSCopyEPEPToInstallationsSearchExtension controller = new FSCopyEPEPToInstallationsSearchExtension(stdcon);
            
            controller.next();
            controller.previous();
            controller.first();
            controller.last();
            //Clicking Copy to Installation without selecting installations
            controller.createEPIP();
            
            //Selecting Installtion
            for(FSCopyEPEPToInstallationsSearchExtension.WrapperClass wrap: controller.wrapperRecordList) {
                wrap.isSelected = true;
                wrap.installation.FS_Execution_Plan_Final_Approval_PM__c =APPROVED;
            }
            
            controller.createEPIP();
            
            //Pagination
            final Integer pageNumber = controller.pageNumber;
            system.assertEquals(1,pageNumber);
            final Integer totalPages = controller.getTotalPages();
            system.assertEquals(1,totalPages);
            final Integer noOfRecords = controller.noOfRecords;
            system.assertEquals(1,noOfRecords);        
            final Boolean hasPrevious = controller.hasPrevious;
            system.assertEquals(false,hasPrevious);
            final Boolean hasNext = controller.hasNext;
            system.assertEquals(false,hasNext);
            final Integer pageSize = controller.pageSize;
            system.assertEquals(20,pageSize);       
            
            Test.stopTest();     
        }
    }    
    private static testmethod void cancelEPIPTest() {
        final Profile adminProfile = FSTestFactory.getProfileId(FSConstants.USER_POFILE_SYSADMIN);
        adminUser = FSTestFactory.createUser(adminProfile.id);
        insert adminUser;
        system.runAs(adminUser){
            Test.startTest();
            final FS_EP_Equipment_Package__c executionPkge = [Select id,FS_Execution_Plan__c from FS_EP_Equipment_Package__c Limit 1];
            //Sets the current PageReference for the controller
            final PageReference pageRef=Page.FSCopyEPEPToInstallationsSearch;
            Test.setCurrentPage(pageRef);
            //Add parameters to page URL
            pageRef.getParameters().put(IDVAL,executionPkge.id);
            final ApexPages.StandardController stdcon = new ApexPages.standardController(executionPkge);           
            
            final FSCopyEPEPToInstallationsSearchExtension controller = new FSCopyEPEPToInstallationsSearchExtension(stdcon);
            
            controller.first();
            controller.last(); 
            
            //Selecting Installtion
            for(FSCopyEPEPToInstallationsSearchExtension.WrapperClass wrap: controller.wrapperRecordList) {
                wrap.isSelected = true;
                wrap.installation.FS_Execution_Plan_Final_Approval_PM__c = APPROVED;
            }
            //Cancelling Copy to Installation
            controller.cancelEPIP(); 
            system.assertEquals(controller.wrapperRecordList.size(),1); 
            Test.stopTest();   
        }
    }
}