force-app/main/default/objects/Account/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Outlet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CIF_Header__c/CIF_Header__c.object-meta.xml
<CustomObject>
    <description>CIF Header</description>
    <label>CIF Header</label>
    <nameField>
        <label>CIF Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CIF Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <displayFormat>EP-{0000}</displayFormat>
    <label>Execution Plan#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For Post Install</description>
    <label>Outlet</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Outlet</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Post Install Activity</relationshipLabel>
    <relationshipName>Outlet_Post_Execution_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlet Info Summary</relationshipLabel>
    <relationshipName>Outlet_Info_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installations (Outlet)</relationshipLabel>
    <relationshipName>Installations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Reason_Code__c.field-meta.xml
<CustomField>
    <fullName>FS_Reason_Code__c</fullName>
    <label>Reason Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Removal - Commercial Terms</fullName>
            </value>
            <value>
                <fullName>Removal - Dispenser Issues</fullName>
            </value>
            <value>
                <fullName>Condemned by Sr. Tech</fullName>
            </value>
            <value>
                <fullName>Remodeling of Outlet</fullName>
            </value>
            <value>
                <fullName>Repair of Restaurant</fullName>
            </value>
            <value>
                <fullName>Repair of Beverage Area</fullName>
            </value>
            <value>
                <fullName>Customer Request</fullName>
            </value>
            <value>
                <fullName>Relocation Outside of 4 Walls</fullName>
            </value>
            <value>
                <fullName>Bridge 9000 To 9100</fullName>
            </value>
            <value>
                <fullName>Early Replacement 9000 To 9100</fullName>
            </value>
            <value>
                <fullName>Competitive</fullName>
            </value>
            <value>
                <fullName>Bottle Can</fullName>
            </value>
            <value>
                <fullName>Return to Legacy - Commercial Terms (Cost)</fullName>
            </value>
            <value>
                <fullName>Return to Legacy - Dispenser Issue</fullName>
            </value>
            <value>
                <fullName>OOB/Ownership Change</fullName>
            </value>
            <value>
                <fullName>Return to Legacy - End of Market Test</fullName>
            </value>
            <value>
                <fullName>Too many CCFS equipment placed initially</fullName>
            </value>
            <value>
                <fullName>Change of Color</fullName>
            </value>
            <value>
                <fullName>Customer Relationship</fullName>
            </value>
            <value>
                <fullName>Damaged at Arrival</fullName>
            </value>
            <value>
                <fullName>Platform Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Same_incoming_platform__c.field-meta.xml
<CustomField>
    <fullName>FS_Same_incoming_platform__c</fullName>
    <label>Same incoming platform?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/recordTypes/Replacement.recordType-meta.xml
<RecordType>
    <fullName>Replacement</fullName>
    <active>true</active>
    <description>Replacement Record Type...</description>
    <label>Replacement</label>
</RecordType>

force-app/main/default/classes/FS_ReplacementDMTest.cls
@isTest
public class FS_ReplacementDMTest {
	@testSetup
    static void setup() {
        Id outletId = [SELECT Id FROM RecordType WHERE Name = 'FS Outlet'].Id;
        Id newInstallId = [SELECT Id FROM RecordType WHERE Name = 'New Install' AND SObjectType = 'FS_Installation__c'].Id;
        Id epId = [SELECT Id FROM RecordType WHERE Name = 'Execution Plan'].Id;
        Account[] customer = FSTestFactory.createTestAccount(true, 1, outletId);
        FS_Execution_Plan__c[] eps = FSTestFactory.createTestExecutionPlan(customer[0].Id, true, 2, epId);
        FS_Installation__c[] replacements = FSTestFactory.createTestInstallationPlan(eps[0].Id, customer[0].Id, true, 5, FSInstallationValidateAndSet.ipRecTypeReplacement);
        CIF_Header__c cifHead = new CIF_Header__c();
        insert cifHead;
        FSTestFactory.createTestCif(customer, cifHead.Id, 1, true);
        
        List<String> reasonCodes = new List<String>{'Platform Change', 'Change of Color', 'Bridge 9000 to 9100', 'Early Replacement 9000 to 9100', 'Condemned by Sr. Tech'};
        for(Integer i = 0; i < reasonCodes.size(); i++) {
            replacements[i].FS_Reason_Code__c = reasonCodes[i];    
        }
        update replacements;
    }
    
    static testMethod void testBatchScript() {
        Test.startTest();
        Database.executeBatch(new FS_ReplacementDMBatchScript());
        Test.stopTest();
        Set<String> picklistVals = new Set<String>{'Bridge 9000 To 9100', 'Early Replacement 9000 To 9100', 'Platform Change'};
        FS_Installation__c[] replacements = [SELECT Id, FS_Reason_Code__c, FS_Same_incoming_platform__c
                                         FROM FS_Installation__c
                                         WHERE RecordType.Name = 'Replacement'
                                         AND FS_Reason_Code__c IN ('Bridge 9000 to 9100', 'Early Replacement 9000 to 9100', 'Platform Change')
                                         ORDER BY FS_Outlet__c];
        System.assertEquals(replacements.size(), 3);
        for(FS_Installation__c replacement : replacements) {
            System.assert(picklistVals.contains(replacement.FS_Reason_Code__c));
            System.assertEquals(replacement.FS_Same_incoming_platform__c, 'No');
        }
    }
    
    static testMethod void testBatchScriptAllOthers() {
        Test.startTest();
        Database.executeBatch(new FS_ReplacementDMBatchScriptAllOthers());
        Test.stopTest();
        Set<String> picklistVals = new Set<String>{'Condemned by Sr. Tech'};
        FS_Installation__c[] replacements = [SELECT Id, FS_Reason_Code__c, FS_Same_incoming_platform__c
                                         FROM FS_Installation__c
                                         WHERE RecordType.Name = 'Replacement'
                                         AND FS_Reason_Code__c IN ('Condemned by Sr. Tech')
                                         ORDER BY FS_Outlet__c];
        System.assertEquals(replacements.size(), 1);
        for(FS_Installation__c replacement : replacements) {
            System.assert(picklistVals.contains(replacement.FS_Reason_Code__c));
            System.assertEquals(replacement.FS_Same_incoming_platform__c, 'Yes');
        }
    }
}