force-app/main/default/objects/Account/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Outlet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <displayFormat>EP-{0000}</displayFormat>
    <label>Execution Plan#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Platform_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform_Type__c</fullName>
    <description>multi select picklist</description>
    <label>Platform Type/s</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlet Info Summary</relationshipLabel>
    <relationshipName>Outlet_Info_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Platform1__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform1__c</fullName>
    <label>Platform 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Platform2__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform2__c</fullName>
    <label>Platform 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Platform3__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform3__c</fullName>
    <label>Platform 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/Type_of_Dispenser_Platform__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Dispenser_Platform__c</fullName>
    <description>multi select pick list</description>
    <label>Platform Type/s</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Platform_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3100</fullName>
    </customValue>
    <customValue>
        <fullName>6000</fullName>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
    </customValue>
    <customValue>
        <fullName>7100</fullName>
    </customValue>
    <customValue>
        <fullName>8000</fullName>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
    </customValue>
    <masterLabel>Platform Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FSPlatformDetailsInstallationTest.cls
/*************************************************************************************
Apex Class Name     : FSPlatformDetailsInstallationTest
Version             : 1.0
Function            : This test class is for FSPlatformDetailsInstallationExtension Class code coverage. 
Modification Log    :
* Developer         :    Date              Description
* ----------------------------------------------------------------------------                 
* Venkat	FET5.0 			01/05/2018			Original Version
************************************************************************************/

@isTest
public class FSPlatformDetailsInstallationTest {
    private static Account headquartersAcc,outletAcc;
    private static FS_Execution_Plan__c executionPlan;
    private static FS_Installation__c installation;
    public static final String PLATFORM='7000;8000;9000';
     private static Profile fetSysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_FETADMIN);
    
    private static FS_Installation__c createTestData(){
        //creating test Data
        FSTestFactory.createTestDisableTriggerSetting();
        final List<Account> insertAccounts = new List<Account>();
        headquartersAcc = FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,false);
        outletAcc= FSTestUtil.createAccountOutlet('Test Outlet 1',FSConstants.RECORD_TYPE_OUTLET,headquartersAcc.id,false);           
        insertAccounts.add(headquartersAcc);
        insertAccounts.add(outletAcc);            
        insert insertAccounts;
        executionPlan = FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,headquartersAcc.Id, false);
        executionPlan.FS_Platform_Type__c=PLATFORM;
        insert executionPlan; 
        installation = FSTestUtil.createInstallationAcc(FSConstants.NEWINSTALLATION,executionPlan.Id,outletAcc.id , false);
        installation.Type_of_Dispenser_Platform__c=PLATFORM;
         
        return installation;
    }
    private static testmethod void platformDetailCheck(){    
        createTestData();
        Test.startTest();
        //inserting Installation
        installation.FS_Platform1__c=FSConstants.RECTYPE_7k;
        installation.FS_Platform2__c=FSConstants.RECTYPE_8k;
        installation.FS_Platform3__c=FSConstants.RECTYPE_9k;
        insert installation;
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
        system.runAs(fetSysAdminUser){
            final ApexPages.StandardController stdcon = new ApexPages.standardController(installation);            
            final FSPlatformDetailsInstallationExtension controller= new FSPlatformDetailsInstallationExtension(stdcon);
            
            system.assertEquals(3, controller.platformList.size());
        }
        Test.stopTest();      
    }
    private static testmethod void platformDetailCheckBlank(){    
        createTestData();
        Test.startTest();  
        //creating Installation
        installation.Type_of_Dispenser_Platform__c=FSConstants.STRING_NULL;
        insert installation;
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
        system.runAs(fetSysAdminUser){
            final ApexPages.StandardController stdcon = new ApexPages.standardController(installation);            
            final FSPlatformDetailsInstallationExtension controller= new FSPlatformDetailsInstallationExtension(stdcon);
            system.assertEquals(new FS_Installation__c(), controller.mapInstallRecords.get('Platform 1'));
        }
        Test.stopTest();      
    }
    
}