force-app/main/default/objects/Account/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Outlet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_SP_Aligned_Zip__c.field-meta.xml
<CustomField>
    <fullName>FS_SP_Aligned_Zip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SP Aligned Zip</label>
    <referenceTo>FS_SP_Aligned_Zip__c</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CIF_Header__c/CIF_Header__c.object-meta.xml
<CustomObject>
    <description>CIF Header</description>
    <label>CIF Header</label>
    <nameField>
        <label>CIF Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CIF Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CIF_Header__c/fields/FS_HQ__c.field-meta.xml
<CustomField>
    <fullName>FS_HQ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HQ Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>CIF_Head</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FS_SP_Contact_Active__c.field-meta.xml
<CustomField>
    <fullName>FS_SP_Contact_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FS_SP_Role__c.field-meta.xml
<CustomField>
    <fullName>FS_SP_Role__c</fullName>
    <label>SP Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Backup</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>FSS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disable_Trigger__c/Disable_Trigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is only used in case there is a need to deactivate a trigger during data migration. The triggers must be kept activated at all times...</description>
    <label>Disable Trigger</label>
</CustomObject>

force-app/main/default/objects/FS_CIF__c/FS_CIF__c.object-meta.xml
<CustomObject>
    <label>CIF</label>
    <nameField>
        <label>CIF Outlet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CIF</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_CIF__c/fields/CIF_Head__c.field-meta.xml
<CustomField>
    <fullName>CIF_Head__c</fullName>
    <label>CIF Header Name</label>
    <referenceTo>CIF_Header__c</referenceTo>
    <relationshipLabel>CIF</relationshipLabel>
    <relationshipName>CIF</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_CIF__c/fields/FS_Account__c.field-meta.xml
<CustomField>
    <fullName>FS_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related CIF</relationshipLabel>
    <relationshipName>CIF9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_CIF__c/fields/FS_Installation__c.field-meta.xml
<CustomField>
    <fullName>FS_Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>CIF</relationshipLabel>
    <relationshipName>CIF</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_CIF__c/fields/FS_Platform1__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform1__c</fullName>
    <label>Platform 1 for Install</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_CIF__c/fields/FS_Platform2__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform2__c</fullName>
    <label>Platform 2 for Install</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_CIF__c/fields/FS_Platform3__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform3__c</fullName>
    <label>Platform 3 for Install</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <displayFormat>EP-{0000}</displayFormat>
    <label>Execution Plan#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Platform_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform_Type__c</fullName>
    <description>multi select picklist</description>
    <label>Platform Type/s</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_CIF__c.field-meta.xml
<CustomField>
    <fullName>FS_CIF__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CIF</label>
    <referenceTo>FS_CIF__c</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlet Info Summary</relationshipLabel>
    <relationshipName>Outlet_Info_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Platform1__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform1__c</fullName>
    <label>Platform 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Platform2__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform2__c</fullName>
    <label>Platform 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Platform3__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform3__c</fullName>
    <label>Platform 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Type_of_Dispenser_Platform__c.field-meta.xml
<CustomField>
    <fullName>FS_Type_of_Dispenser_Platform__c</fullName>
    <description>pick list field with platform values</description>
    <label>Type of Dispenser Platform</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>7000</fullName>
            </value>
            <value>
                <fullName>8000</fullName>
            </value>
            <value>
                <fullName>9000</fullName>
            </value>
            <value>
                <fullName>8000; 9000</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/recordTypes/Relocation.recordType-meta.xml
<RecordType>
    <fullName>Relocation</fullName>
    <active>true</active>
    <description>Relocation (I4W) Record Type..</description>
    <label>Relocation (I4W)</label>
</RecordType>

force-app/main/default/objects/FS_SP_Aligned_Zip__c/FS_SP_Aligned_Zip__c.object-meta.xml
<CustomObject>
    <description>Establishes the default Service Provider for a given Zip Code. Every record is a Zip Code (unique), and each one aligns to a Service Provider account via lookup.</description>
    <label>SP Aligned Zip</label>
    <nameField>
        <displayFormat>SPZ-{000000}</displayFormat>
        <label>SP Aligned Zip</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SP Aligned Zips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_SP_Aligned_Zip__c/fields/FS_Platform_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform_Type__c</fullName>
    <label>Platform Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_SP_Aligned_Zip__c/fields/FS_Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>FS_Service_Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Provider</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The lookup account must be of the &quot;FS Service Provider&quot; recordtype</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Service Provider</value>
        </filterItems>
        <infoMessage>Select the Service Provider account that should be linked to the zip code.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SP Aligned Zips</relationshipLabel>
    <relationshipName>SP_Aligned_Zips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_SP_Aligned_Zip__c/fields/FS_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>FS_Zip_Code__c</fullName>
    <description>The 5-char Zip Code, including leading zeroes</description>
    <externalId>true</externalId>
    <inlineHelpText>Zip Code must be exactly 5 digits, include leading zeroes.</inlineHelpText>
    <label>Zip Code</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Platform_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3100</fullName>
    </customValue>
    <customValue>
        <fullName>6000</fullName>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
    </customValue>
    <customValue>
        <fullName>7100</fullName>
    </customValue>
    <customValue>
        <fullName>8000</fullName>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
    </customValue>
    <masterLabel>Platform Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FsPostInstalltionDMBatchTest.cls
@isTest
private class FsPostInstalltionDMBatchTest {

    private static Account headquartersAcc,outletAcc,serviceProvider,serviceProvider1;
    private static FS_Execution_Plan__c executionPlan;
    private static FS_Installation__c installation;
    private static Contact spContact;
    
    private static String recTypeNewInstall=Schema.SObjectType.FS_Installation__c.getRecordTypeInfosByName().get(FSConstants.NEWINSTALLATION).getRecordTypeId() ;
   private static String recServcProvider=Schema.SObjectType.Account.getRecordTypeInfosByName().get('FS Service Provider').getRecordTypeId();
    private static String recServcProvdCnt=Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Service Provider').getRecordTypeId();
   
    private static Profile fetSysAdmin;
    
    private static final String TESTCONTACT ='Test Contact';
    private static final String SPNAME ='Service Provider';
    private static final String PHONENO='1023456789';
    private static final String PRIMARY='Primary';
    private static final String EMAILADDR='email@email.com';
   
    
    private static FS_Installation__c createTestData(){
        
        List<Account> insertAccounts = new List<Account>();
        //HQ Record
        headquartersAcc = FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,false);
        //Outlet Records
        outletAcc= FSTestUtil.createAccountOutlet('Test Outlet 1',FSConstants.RECORD_TYPE_OUTLET,headquartersAcc.id,false);
        outletAcc.ShippingPostalCode='1234';
        
        //Inserting Account Records
        serviceProvider=new Account(Name=SPNAME,RecordtypeId=recServcProvider);        
        serviceProvider1=new Account(Name=SPNAME,RecordtypeId=recServcProvider);        
        insertAccounts.add(headquartersAcc);
        insertAccounts.add(outletAcc);
        insertAccounts.add(serviceProvider);
        insertAccounts.add(serviceProvider1);
        insert insertAccounts;
        final CIF_Header__c cifHead=new CIF_Header__c(FS_HQ__c=headquartersAcc.Id);
        insert cifHead;
        insert new Disable_Trigger__c(name='FSCOMNotifications',IsActive__c=false);
        final FS_CIF__c cifRec=new FS_CIF__c(CIF_Head__c=cifHead.Id,FS_Account__c=outletAcc.Id,FS_Platform1__c='7000',FS_Platform2__c='8000',FS_Platform3__c='8000');
        insert cifRec;        
        //FET 7.0 FNF-823
        insert new Disable_Trigger__c(name='FSContactTriggerHandler',IsActive__c=false);
        //FET 7.0 FNF-823
        List<Contact> conList=new List<Contact>();
        conList.add(new Contact(AccountId=serviceProvider.Id,LastName=TESTCONTACT,RecordtypeId=recServcProvdCnt,FS_SP_Contact_Active__c=true,FS_SP_Role__c=PRIMARY,Phone=PHONENO,Email=EMAILADDR));
        conList.add(new Contact(AccountId=serviceProvider1.Id,LastName=TESTCONTACT,RecordtypeId=recServcProvdCnt,FS_SP_Contact_Active__c=true,FS_SP_Role__c=PRIMARY,Phone=PHONENO,Email=EMAILADDR));
        insert conList;
        final List<FS_SP_Aligned_Zip__c> spAlignedList=new List<FS_SP_Aligned_Zip__c>();
        spAlignedList.add(new FS_SP_Aligned_Zip__c(FS_Zip_Code__c=outletAcc.ShippingPostalCode,FS_Service_Provider__c=serviceProvider.id,FS_Platform_Type__c='7000'));
        spAlignedList.add(new FS_SP_Aligned_Zip__c(FS_Zip_Code__c=outletAcc.ShippingPostalCode,FS_Service_Provider__c=serviceProvider.id,FS_Platform_Type__c='8000' ));
        spAlignedList.add(new FS_SP_Aligned_Zip__c(FS_Zip_Code__c=outletAcc.ShippingPostalCode,FS_Service_Provider__c=serviceProvider.id,FS_Platform_Type__c='9000'));
        spAlignedList.add(new FS_SP_Aligned_Zip__c(FS_Zip_Code__c=outletAcc.ShippingPostalCode,FS_Service_Provider__c=serviceProvider.id,FS_Platform_Type__c='9100'));
        insert spAlignedList;
       
       
        //Creating Execution Plan Record
        executionPlan = FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,headquartersAcc.Id, false);
        executionPlan.FS_Platform_Type__c='7000;8000;9000;9100';
        insert executionPlan;
        fetSysAdmin=FSTestFactory.getProfileId(FSConstants.USER_POFILE_FETADMIN);
        FSTestFactory.createTestDisableTriggerSetting();
        installation = FSTestUtil.createInstallationAcc(FSConstants.NEWINSTALLATION,executionPlan.Id,outletAcc.id,false);      
        installation.FS_CIF__c= cifRec.Id;
        return installation;
    }
    
     //New Relocation record with Platform Type/s Changes
    private static testmethod void testNewRemovalPlatformRec(){   
        createTestData();
        
        final User fetSysAdminUser=FSTestFactory.createUser(fetSysAdmin.id);
        insert fetSysAdminUser;
        
        system.runAs(fetSysAdminUser){            
            installation.FS_Type_of_Dispenser_Platform__c='8000;9000';
            installation.RecordTypeId=recTypeNewInstall;
            insert installation; 
            Test.startTest();
        	Database.executeBatch(new FsPostInstalltionDMBatch(),200);
        	Test.stopTest();           
        }
        system.assertEquals('8000;9000', installation.FS_Type_of_Dispenser_Platform__c);
	        
    }
}