force-app/main/default/objects/Account/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Outlet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountTeamMember__c/AccountTeamMember__c.object-meta.xml
<CustomObject>
    <label>Account Team Member</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>AccountTeamMember Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountTeamMember__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>AccountId</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Team Members</relationshipLabel>
    <relationshipName>AccountTeamMembers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountTeamMember__c/fields/FS_Email__c.field-meta.xml
<CustomField>
    <fullName>FS_Email__c</fullName>
    <description>Email Field</description>
    <label>Team Member Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/AccountTeamMember__c/fields/TeamMemberRole__c.field-meta.xml
<CustomField>
    <fullName>TeamMemberRole__c</fullName>
    <label>Team Member Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>COM</fullName>
            </value>
            <value>
                <fullName>COM Backup</fullName>
            </value>
            <value>
                <fullName>JCOM</fullName>
            </value>
            <value>
                <fullName>Sales Team Member</fullName>
            </value>
            <value>
                <fullName>PM</fullName>
            </value>
            <value>
                <fullName>PIC</fullName>
            </value>
            <value>
                <fullName>Sales Support</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>FDC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountTeamMember__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AccountTeamMembers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CIF_Header__c/CIF_Header__c.object-meta.xml
<CustomObject>
    <description>CIF Header</description>
    <label>CIF Header</label>
    <nameField>
        <label>CIF Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CIF Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CIF_Header__c/fields/FS_FPS__c.field-meta.xml
<CustomField>
    <fullName>FS_FPS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FPS User</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>FS FPS_P</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>FS AC_P</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>FS PM_P</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>FS Admin PM_P</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>CIF_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CIF_Header__c/fields/FS_HQ__c.field-meta.xml
<CustomField>
    <fullName>FS_HQ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HQ Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>CIF_Head</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CIF_Header__c/fields/FS_Sales_Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>FS_Sales_Rep_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AccountTeamMember__c.AccountId__r.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <filterItems>
            <field>AccountTeamMember__c.AccountId__c</field>
            <operation>equals</operation>
            <valueField>$Source.FS_HQ__c</valueField>
        </filterItems>
        <filterItems>
            <field>AccountTeamMember__c.TeamMemberRole__c</field>
            <operation>equals</operation>
            <value>Sales Team Member</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AccountTeamMember__c</referenceTo>
    <relationshipLabel>CIF Headers</relationshipLabel>
    <relationshipName>CIF_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CIF_Header__c/fields/FS_Version__c.field-meta.xml
<CustomField>
    <fullName>FS_Version__c</fullName>
    <label>Version</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CIF_Header__c/fields/FSCOM__c.field-meta.xml
<CustomField>
    <fullName>FSCOM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>COM User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AccountTeamMember__c.TeamMemberRole__c</field>
            <operation>equals</operation>
            <value>COM</value>
        </filterItems>
        <filterItems>
            <field>AccountTeamMember__c.AccountId__c</field>
            <operation>equals</operation>
            <valueField>$Source.FS_HQ__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AccountTeamMember__c</referenceTo>
    <relationshipLabel>CIF Headers (COM)</relationshipLabel>
    <relationshipName>CIF_Headers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_CIF__c/FS_CIF__c.object-meta.xml
<CustomObject>
    <label>CIF</label>
    <nameField>
        <label>CIF Outlet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CIF</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_CIF__c/fields/CIF_Head__c.field-meta.xml
<CustomField>
    <fullName>CIF_Head__c</fullName>
    <label>CIF Header Name</label>
    <referenceTo>CIF_Header__c</referenceTo>
    <relationshipLabel>CIF</relationshipLabel>
    <relationshipName>CIF</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_CIF__c/fields/FS_Account__c.field-meta.xml
<CustomField>
    <fullName>FS_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Related CIF</relationshipLabel>
    <relationshipName>CIF9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_CIF__c/fields/FS_Installation__c.field-meta.xml
<CustomField>
    <fullName>FS_Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>CIF</relationshipLabel>
    <relationshipName>CIF</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_CIF__c/fields/FS_Platform1__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform1__c</fullName>
    <label>Platform 1 for Install</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_CIF__c/fields/FS_Platform2__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform2__c</fullName>
    <label>Platform 2 for Install</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_CIF__c/fields/FS_Platform3__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform3__c</fullName>
    <label>Platform 3 for Install</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <displayFormat>EP-{0000}</displayFormat>
    <label>Execution Plan#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_FPS__c.field-meta.xml
<CustomField>
    <fullName>FS_FPS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FPS</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>FS FPS_P</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>FS PM_P</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>FS Admin PM_P</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>FS AC_P</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Execution_Plans4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_New_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_New_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Relocation_New_Outlet</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Platform_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform_Type__c</fullName>
    <description>multi select picklist</description>
    <label>Platform Type/s</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_CIF__c.field-meta.xml
<CustomField>
    <fullName>FS_CIF__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CIF</label>
    <referenceTo>FS_CIF__c</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlet Info Summary</relationshipLabel>
    <relationshipName>Outlet_Info_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_New_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_New_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installations (New Outlet)</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Platform1__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform1__c</fullName>
    <label>Platform 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Platform2__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform2__c</fullName>
    <label>Platform 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Platform3__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform3__c</fullName>
    <label>Platform 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Platform_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3100</fullName>
    </customValue>
    <customValue>
        <fullName>6000</fullName>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
    </customValue>
    <customValue>
        <fullName>7100</fullName>
    </customValue>
    <customValue>
        <fullName>8000</fullName>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
    </customValue>
    <masterLabel>Platform Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FS_ContentDocumentLink_Handler_Test.cls
/*=================================================================================================================
* Date         : 21-01-2019
* Developer    : Goutham Rapolu
* Purpose      : Test class for FS_ContentDocumentLinkTrigger_Handler which will update Attachment ID, Attachment URL 
*				 field on FS_CIF__c.
*=================================================================================================================
*                                 Update History
*                                 ---------------
*   Date        Developer       Tag   Description
*============+================+=====+=============================================================================
* 21-01-2019 | Goutham Rapolu |     | Initial Version                                         
*===========+=================+=====+=============================================================================
*/

@isTest
public class FS_ContentDocumentLink_Handler_Test {
    
    private static final String USER_EMAIL = 'test@test.com';
    private static final String LOCALE = 'en_US';
    public static List<Account> outCustList;
    public static List<Account> outletCustList;
    private static testmethod void testTrigger(){
        outCustList= FSTestFactory.createTestAccount(false,1,FSUtil.getObjectRecordTypeId(Account.SObjectType,'FS Headquarters'));
        insert outCustList;   
        
        final List<User> userList = new List<User>();
        final User user1 = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'FS PM_P'].Id,
            LastName = 'TestCodeCOM',
            Email = USER_EMAIL,
            Username = 'test12344444343467@test.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = LOCALE,
            LocaleSidKey = LOCALE
            
        );
        userList.add(user1);
        final User user2 = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
            LastName = 'TestCodeCOM1',
            Email = USER_EMAIL,
            Username = 'test12344444343467@test1.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title1',
            Alias = 'alias1',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = LOCALE,
            LocaleSidKey = LOCALE
            
        );
        final User user3 = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'FS Sales_P'].Id,
            LastName = 'TestCodeC3',
            Email = USER_EMAIL,
            Username = 'test12344444343467@test13.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title11',
            Alias = 'alias111',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = LOCALE,
            LocaleSidKey = LOCALE
            
        );
        Test.startTest();
        userList.add(user2);
        userList.add(user3);
        insert userList;
        System.runAs(userList[1]) {
            final List<AccountTeamMember__c> accTeamLst= new List<AccountTeamMember__c>();
            final AccountTeamMember__c accName1 = new AccountTeamMember__c(AccountId__c=outCustList[0].id,TeamMemberRole__c= 'COM',UserId__c=userList[1].id, FS_Email__c=USER_EMAIL);
            final AccountTeamMember__c accName2 = new AccountTeamMember__c(AccountId__c=outCustList[0].id,TeamMemberRole__c= 'Sales Team Member',UserId__c=userList[1].id, FS_Email__c=USER_EMAIL);
            accTeamLst.add(accName1);
            accTeamLst.add(accName2);
            insert accTeamLst;
            
            
            final CIF_Header__c cheader =new CIF_Header__c(Name='FS CIF Header');
            cheader.FS_FPS__c=userList[0].Id;
            cheader.FSCOM__c=accTeamLst[0].Id;
            cheader.FS_Sales_Rep_Name__c=accTeamLst[1].Id;
            cheader.FS_Version__c = 10.02;
            cheader.FS_HQ__c=outCustList[0].id;
            insert cheader;
            
            
            final FS_CIF__c fscif=new FS_CIF__c(Name='FS CIF'); 
            fscif.CIF_Head__c=cheader.Id;
            insert fscif;
            
            ContentVersion contentVersion = new ContentVersion(
                Title = 'Penguins',
                PathOnClient = 'Penguins.jpg',
                VersionData = Blob.valueOf('Test Content'),
                IsMajorVersion = true
            );
            insert contentVersion; 
            
            ContentVersion contentVersion2 = new ContentVersion(
                Title = 'Penguins2',
                PathOnClient = 'Penguins2.jpg',
                VersionData = Blob.valueOf('Test Content2'),
                IsMajorVersion = true
            );
            insert contentVersion2; 
            
            List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
            
            //create ContentDocumentLink  record 
            ContentDocumentLink cdl = New ContentDocumentLink();
            cdl.LinkedEntityId = fscif.id;
            cdl.ContentDocumentId = documents[0].Id;
            cdl.shareType = 'V';
            insert cdl;
            system.assertNotEquals(null, cdl.id);
            
            //create ContentDocumentLink  record 
            ContentDocumentLink cdl2 = New ContentDocumentLink();
            cdl2.LinkedEntityId = fscif.id;
            cdl2.ContentDocumentId = documents[1].Id;
            cdl2.shareType = 'V';
            insert cdl2;
            system.assertNotEquals(null, cdl2.id);
            Delete cdl;
            Delete cdl2;
        }
        
        Test.stopTest();
    }
    
   private static testmethod void testTriggerforRO4W(){ 
    final User user3 = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'FS Sales_P'].Id,
            LastName = 'TestCodeC3',
            Email = USER_EMAIL,
            Username = 'test12344444343467@test13.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title11',
            Alias = 'alias111',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = LOCALE,
            LocaleSidKey = LOCALE
            
        );
        Test.startTest();
        
        insert user3;
    
    List<Account> AccList = new List<Account>();
            final Account headquartersAcc = FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,false);
            AccList.add(headquartersAcc);
            
            final Account outletAcc=FSTestUtil.createAccountOutlet('Test Outlet 2',FSConstants.RECORD_TYPE_OUTLET,headquartersAcc.id,false);
            outletAcc.ShippingPostalCode='1234';
            AccList.add(outletAcc);
            
            insert AccList;
            
            final CIF_Header__c cifHead=new CIF_Header__c(FS_HQ__c=headquartersAcc.Id);
            insert cifHead;
            
            final FS_CIF__c cifRec=new FS_CIF__c(CIF_Head__c=cifHead.Id,FS_Account__c=outletAcc.Id,FS_Platform1__c='7000',FS_Platform2__c='8000',FS_Platform3__c='8000');
            insert cifRec;
            
            final FS_Execution_Plan__c executionPlan = FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,headquartersAcc.Id, false);
            executionPlan.FS_Platform_Type__c='7000;8000;9000;9100';
            insert executionPlan;
            
            FS_Installation__c createinstallation = new FS_Installation__c();
            createinstallation = FSTestUtil.createInstallationAcc(Label.IP_Relocation_O4W_Rec_Type,executionPlan.Id,outletacc.id,false);      
            createinstallation.FS_CIF__c= cifRec.Id;
            createinstallation.FS_New_Outlet__c= outletAcc.id;
            createinstallation.FS_Install_Doc__c= '123';
            insert createinstallation;
            system.assertNotEquals(null, createinstallation.id);
        system.runas(user3){
         try{
             
            ContentVersion contentVersion2 = new ContentVersion(
                Title = 'Penguins2',
                PathOnClient = 'Penguins2.jpg',
                VersionData = Blob.valueOf('Test Content2'),
                IsMajorVersion = true
            );
            insert contentVersion2; 
            
            List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
            
            //create ContentDocumentLink  record 
            ContentDocumentLink cdl = New ContentDocumentLink();
            cdl.LinkedEntityId = createinstallation.id;
            cdl.ContentDocumentId = documents[0].Id;
            cdl.shareType = 'V';
            insert cdl;
            system.assertEquals('Penguins2', contentVersion2.Title);
        }Catch(exception e){}
        }
        
     
        Test.stopTest();
    }
       
        
        
    @testSetup  
    static void mytestSetup() {
        Disable_Trigger__c disableTriggerSetting = new Disable_Trigger__c();
        disableTriggerSetting.name='FSCOMNotifications';
        disableTriggerSetting.IsActive__c=true;
        disableTriggerSetting.Trigger_Name__c='FSCOMNotifications' ; 
        insert disableTriggerSetting;   
    }
    
    //Added as part of FET-7.0 FNF 850
    private static testmethod void testInstallTrigger(){
        
        List<Account> AccList = new List<Account>();
        final Account headquartersAcc = FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,false);
        AccList.add(headquartersAcc);
        
        final Account outletAcc=FSTestUtil.createAccountOutlet('Test Outlet 2',FSConstants.RECORD_TYPE_OUTLET,headquartersAcc.id,false);
        outletAcc.ShippingPostalCode='1234';
        AccList.add(outletAcc);
        
        insert AccList;
        
        final CIF_Header__c cifHead=new CIF_Header__c(FS_HQ__c=headquartersAcc.Id);
        insert cifHead;
        
        final FS_CIF__c cifRec=new FS_CIF__c(CIF_Head__c=cifHead.Id,FS_Account__c=outletAcc.Id,FS_Platform1__c='7000',FS_Platform2__c='8000',FS_Platform3__c='8000');
        insert cifRec;
        
        final FS_Execution_Plan__c executionPlan = FSTestUtil.createExecutionPlan(FSConstants.EXECUTIONPLAN,headquartersAcc.Id, false);
        executionPlan.FS_Platform_Type__c='7000;8000;9000;9100';
        insert executionPlan;
        
        FS_Installation__c createinstallation = new FS_Installation__c();
        createinstallation = FSTestUtil.createInstallationAcc(Label.IP_Relocation_O4W_Rec_Type,executionPlan.Id,outletacc.id,false);      
        createinstallation.FS_CIF__c= cifRec.Id;
        createinstallation.FS_New_Outlet__c= outletAcc.id;
        createinstallation.FS_Install_Doc__c= '123';
        createinstallation.Overall_Status2__c = FSConstants.PIA_PENDINGTONEWOUTLET;
        createinstallation.FS_Asset_Tracking_Form_AMOA_Status__c = FSConstants.AMOASUBMIT;
        createinstallation.FS_To_Outlet_Name__c= outletAcc.id;
        insert createinstallation;
        
        test.startTest();
        
        ContentVersion contentVersion = new ContentVersion(
            Title = 'AMOA From 0005303029 to 0001071503',
            PathOnClient = 'AMOA From 0005303029 to 0001071503.xlsx',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        insert contentVersion; 
        
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        
        //create ContentDocumentLink  record 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = createinstallation.id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        insert cdl;
        system.assertNotEquals(null, cdl.id);
        
        Delete cdl;
        delete documents[0];
        
        Test.stopTest();
    }
}