force-app/main/default/objects/Account/fields/FS_FSM_Review__c.field-meta.xml
<CustomField>
    <fullName>FS_FSM_Review__c</fullName>
    <label>FSM Review</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Reviewed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Revenue_Center__c.field-meta.xml
<CustomField>
    <fullName>FS_Revenue_Center__c</fullName>
    <label>Revenue Center</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Site_Assessment_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>FS_Site_Assessment_Contact_Email__c</fullName>
    <label>Site Assessment Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Site_Assessment_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>FS_Site_Assessment_Contact_Phone__c</fullName>
    <label>Site Assessment Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/FS_CI_Required_Fields_Region__c/FS_CI_Required_Fields_Region__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>FS CI Required Fields Region</label>
</CustomObject>

force-app/main/default/objects/FS_CI_Required_Fields_Region__c/fields/Field_API__c.field-meta.xml
<CustomField>
    <fullName>Field_API__c</fullName>
    <label>Field API</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_CI_Required_Fields_Region__c/fields/Field_Lable__c.field-meta.xml
<CustomField>
    <fullName>Field_Lable__c</fullName>
    <label>Field Label</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Customer_Input__c/FS_Customer_Input__c.object-meta.xml
<CustomObject>
    <label>Customer Input</label>
    <nameField>
        <label>Customer Input Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Inputs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Customer_Input__c/fields/FS_7000_Series_Top_Mnt_Ice_Maker_Instld__c.field-meta.xml
<CustomField>
    <fullName>FS_7000_Series_Top_Mnt_Ice_Maker_Instld__c</fullName>
    <inlineHelpText>7000 Series</inlineHelpText>
    <label>#Planned Top-Mount Ice Maker</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Customer_Input__c/fields/FS_Account__c.field-meta.xml
<CustomField>
    <fullName>FS_Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customer Inputs</relationshipLabel>
    <relationshipName>Customer_Inputs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Customer_Input__c/fields/FS_Customer_Input_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Customer_Input_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Input Type</label>
    <referenceTo>FS_Customer_Input_Type__c</referenceTo>
    <relationshipLabel>Customer Inputs</relationshipLabel>
    <relationshipName>Customer_Inputs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Customer_Input__c/fields/FS_Number_7000_unit__c.field-meta.xml
<CustomField>
    <fullName>FS_Number_7000_unit__c</fullName>
    <label>#Planned 7000 Series Freestyle Dispenser</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <default>true</default>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Customer_Input__c/fields/FS_Number_crew_serve_unit__c.field-meta.xml
<CustomField>
    <fullName>FS_Number_crew_serve_unit__c</fullName>
    <label>#Planned 8000 Series Freestyle Dispenser</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Customer_Input__c/fields/FS_Number_self_serve_units__c.field-meta.xml
<CustomField>
    <fullName>FS_Number_self_serve_units__c</fullName>
    <label>#Planned 9000 Series Freestyle Dispenser</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Customer_Input__c/fields/FS_Requested_Cartridge_Order_Method__c.field-meta.xml
<CustomField>
    <fullName>FS_Requested_Cartridge_Order_Method__c</fullName>
    <label>Requested Cartridge Order Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CokeSmart</fullName>
            </value>
            <value>
                <fullName>Bottler</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Customer_Input__c/fields/FS_Self_Serve_Top_Mnt_Ice_Maker_Instld__c.field-meta.xml
<CustomField>
    <fullName>FS_Self_Serve_Top_Mnt_Ice_Maker_Instld__c</fullName>
    <inlineHelpText>9000 series</inlineHelpText>
    <label>#Planned Top-Mount Ice Maker</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <default>true</default>
                <label>0</label>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Customer_Input__c/fields/FS_Site_Assessment_contact_email__c.field-meta.xml
<CustomField>
    <fullName>FS_Site_Assessment_contact_email__c</fullName>
    <label>Site Assessment contact email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/FS_Customer_Input__c/fields/FS_Site_Assessment_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>FS_Site_Assessment_Contact_Phone__c</fullName>
    <label>Site Assessment Contact Phone-(primary)</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/FS_Customer_Input__c/fields/FS_Site_Assessment_Required__c.field-meta.xml
<CustomField>
    <fullName>FS_Site_Assessment_Required__c</fullName>
    <label>Select Site Assessment Requirements</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Davaco: Site Assessment + GFE</fullName>
            </value>
            <value>
                <fullName>Davaco: Site Assessment + Detailed Scope Summary</fullName>
            </value>
            <value>
                <fullName>Davaco: Site Assessment Only</fullName>
            </value>
            <value>
                <fullName>Davaco: New Construction Site Assessment</fullName>
            </value>
            <value>
                <fullName>No Site Assessment Required</fullName>
            </value>
            <value>
                <fullName>Power House</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Customer_Input_Type__c/FS_Customer_Input_Type__c.object-meta.xml
<CustomObject>
    <label>Customer Input Type</label>
    <nameField>
        <label>Customer Input Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Input Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Customer_Input_Type__c/fields/FS_7000_Series_Top_Mnt_Ice_Maker_Instld__c.field-meta.xml
<CustomField>
    <fullName>FS_7000_Series_Top_Mnt_Ice_Maker_Instld__c</fullName>
    <defaultValue>true</defaultValue>
    <description>7000 Series</description>
    <label>#Planned Top-Mount Ice Maker</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Customer_Input_Type__c/fields/FS_Number_crew_serve_unit__c.field-meta.xml
<CustomField>
    <fullName>FS_Number_crew_serve_unit__c</fullName>
    <defaultValue>true</defaultValue>
    <label>#Planned 8000 Series Freestyle Dispenser</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Customer_Input_Type__c/fields/FS_Number_self_serve_units__c.field-meta.xml
<CustomField>
    <fullName>FS_Number_self_serve_units__c</fullName>
    <defaultValue>true</defaultValue>
    <label>#Planned 9000 Series Freestyle Dispenser</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Customer_Input_Type__c/fields/FS_Requested_Cartridge_Order_Method__c.field-meta.xml
<CustomField>
    <fullName>FS_Requested_Cartridge_Order_Method__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requested Cartridge Order Method</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Customer_Input_Type__c/fields/FS_Self_Serve_Top_Mnt_Ice_Maker_Instld__c.field-meta.xml
<CustomField>
    <fullName>FS_Self_Serve_Top_Mnt_Ice_Maker_Instld__c</fullName>
    <defaultValue>true</defaultValue>
    <description>9000 series</description>
    <label>#Planned Top-Mount Ice Maker</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Customer_Input_Type__c/fields/FS_Site_Assessment_contact_email__c.field-meta.xml
<CustomField>
    <fullName>FS_Site_Assessment_contact_email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Site Assessment contact email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Customer_Input_Type__c/fields/FS_Site_Assessment_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>FS_Site_Assessment_Contact_Phone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Site Assessment Contact Phone-(primary)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Customer_Input_Type__c/fields/FS_Site_Assessment_Required__c.field-meta.xml
<CustomField>
    <fullName>FS_Site_Assessment_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Select Site Assessment Requirements</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FSHQPageServicesTest.cls
/***************************************************************************
 Name         : FSHQPageServicesTest
 Created By   : Mohit Parnami
 Description  : Test class of FSHQPageServices
 Created Date : Sept 24, 2013
****************************************************************************/
@isTest
private class FSHQPageServicesTest { 

    //Headquarter Account
    static Account accHeadQtr,accHeadQtr2, accChain, accHeadQtr1;
    static FS_Customer_Input__c custInput,custInput1;
    static Contact con;
	static FS_CI_Required_Fields_Region__c requiredTypes,requiredTypes1,requiredTypes2,requiredTypes3,requiredTypes4,requiredTypes5,requiredTypes6,requiredTypes7,requiredTypes8,requiredTypes9,requiredTypes10;
    static testmethod void testHQPageServices(){
        createTestData();
		accHeadQtr2 = FSTestUtil.createAccountOutlet('Test Outlet 1',FSConstants.RECORD_TYPE_OUTLET,accHeadQtr1.id,false);       
        accHeadQtr2.FS_Revenue_Center__c = 'East';
        accHeadQtr2.FS_FSM_Review__c='Reviewed';        
        insert accHeadQtr2;
        FSHQPageServices.createCustomerInput(string.ValueOf(accHeadQtr.Id));
        FSHQPageServices.createCustomerInput(string.ValueOf(accHeadQtr2.Id));
        
        FSHQPageServices.initiateExecutionPlan(string.ValueOf(accHeadQtr.Id));
        FSHQPageServices.initiateExecutionPlan(string.ValueOf(accHeadQtr2.Id));
        
        FSHQPageServices.createExecutionPlan(string.ValueOf(accHeadQtr1.Id));
        FSHQPageServices.copyToOutlets(string.ValueOf(accHeadQtr.Id));
        FSHQPageServices.copyToOutlets(string.ValueOf(accHeadQtr2.Id));
        //FSHQPageServices.checkRequiredFields(custInput,null);
		accHeadQtr2.FS_FSM_Review__c=null;
		update accHeadQtr2;
        FSHQPageServices.initiateExecutionPlan(string.ValueOf(accHeadQtr2.Id));
        custInput.FS_Site_Assessment_Required__c = 'Test';
        custInput.FS_Account__c=string.ValueOf(accHeadQtr1.Id);
        update custInput;
        FSHQPageServices.createExecutionPlan(string.ValueOf(accHeadQtr.Id));

        custInput.FS_Number_self_serve_units__c = '1';
        custInput.FS_Number_crew_serve_unit__c = '1';
        custInput.FS_Self_Serve_Top_Mnt_Ice_Maker_Instld__c = '1';
        update custInput;
        //FSHQPageServices.checkRequiredFields(custInput,null);        
        //FSHQPageServices.checkPlannedDispensersIsNotNull(custInput);
        //FSHQPageServices.checkSAContactInformationIsNotNull(custInput);
        //FSHQPageServices.checkStandaredConactHasRole_SA(accHeadQtr.id);
    }
    
    static testmethod void testHQPageServices1(){  
        //createTestData();
        //Create Headquarter Account
        accHeadQtr1 = FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,false); 
        accHeadQtr1.FS_Revenue_Center__c = 'East';
        insert accHeadQtr1;		
        FSHQPageServices.initiateExecutionPlan(string.ValueOf(accHeadQtr1.Id));
        FS_Customer_Input_Type__c custInputType = FSTestUtil.createCustomerInputType(true);

        custInput = new FS_Customer_Input__c();
        custInput.FS_Account__c = accHeadQtr1.Id;
        custInput.FS_Customer_Input_Type__c = custInputType.Id;        
        custInput.FS_Site_Assessment_Contact_Phone__c = '9799559433';
        custInput.FS_Site_Assessment_contact_email__c = 'xyz@test.com';
        custInput.FS_Requested_Cartridge_Order_Method__c = '';
        insert custInput;
         FSHQPageServices.copyToOutlets(string.ValueOf(accHeadQtr1.Id));
        //FSHQPageServices.createExecutionPlan(string.ValueOf(accHeadQtr1.Id));
    }

    static void createTestData(){
		List<FS_CI_Required_Fields_Region__c> requiredList = new List<FS_CI_Required_Fields_Region__c>();
		requiredTypes=new FS_CI_Required_Fields_Region__c();
        requiredTypes.Name='#Planned 7000S Top-Mount IM';
		requiredTypes.Field_API__c='FS_7000_Series_Top_Mnt_Ice_Maker_Instld__c';
        requiredTypes.Field_Lable__c='#Planned 7000 Series Top-Mount Ice Maker';
        requiredList.add(requiredTypes);
        requiredTypes1=new FS_CI_Required_Fields_Region__c();
        requiredTypes1.Name='Number 7000 series unit';
		requiredTypes1.Field_API__c='FS_Number_7000_unit__c';
        requiredTypes1.Field_Lable__c='# Planned Freestyle 7000 Dispensers';
        requiredList.add(requiredTypes1);
        requiredTypes2=new FS_CI_Required_Fields_Region__c();
        requiredTypes2.Name='Number crew serve unit';
		requiredTypes2.Field_API__c='FS_Number_crew_serve_unit__c';
        requiredTypes2.Field_Lable__c='#Planned Crew-Serve Freestyle Dispensers';
        requiredList.add(requiredTypes2);
        requiredTypes3=new FS_CI_Required_Fields_Region__c();
        requiredTypes3.Name='Number self serve units';
		requiredTypes3.Field_API__c='FS_Number_self_serve_units__c';
        requiredTypes3.Field_Lable__c='#Planned Self-Serve Freestyle Dispensers';
        requiredList.add(requiredTypes3);
        requiredTypes4=new FS_CI_Required_Fields_Region__c();
        requiredTypes4.Name='Self Serv Top Mnt Ice Maker Instld';
		requiredTypes4.Field_API__c='FS_Self_Serve_Top_Mnt_Ice_Maker_Instld__c';
        requiredTypes4.Field_Lable__c='#Planned Self-Serve Top-Mount Ice Makers';
        requiredList.add(requiredTypes4);
        requiredTypes5=new FS_CI_Required_Fields_Region__c();
        requiredTypes5.Name='Site Assessment Contact Cel';
		requiredTypes5.Field_API__c='FS_Site_Assessment_Contact_Cell__c';
        requiredTypes5.Field_Lable__c='Site Assessment Contact Phone(Alternate)';
        requiredList.add(requiredTypes5);
        requiredTypes6=new FS_CI_Required_Fields_Region__c();
        requiredTypes6.Name='Site Assessment contact email';
		requiredTypes6.Field_API__c='FS_Site_Assessment_contact_email__c';
        requiredTypes6.Field_Lable__c='Site Assessment contact email';
        requiredList.add(requiredTypes6);
        requiredTypes7=new FS_CI_Required_Fields_Region__c();
        requiredTypes7.Name='Site Assessment Contact name';
		requiredTypes7.Field_API__c='FS_Site_Assessment_Contact_name__c';
        requiredTypes7.Field_Lable__c='Site Assessment Contact name';
        requiredList.add(requiredTypes7);
        requiredTypes8=new FS_CI_Required_Fields_Region__c();
        requiredTypes8.Name='Site Assessment Contact Phone';
		requiredTypes8.Field_API__c='FS_Site_Assessment_Contact_Phone__c';
        requiredTypes8.Field_Lable__c='Site Assessment Contact Phone-(primary)';
        requiredList.add(requiredTypes8);
        requiredTypes9=new FS_CI_Required_Fields_Region__c();
        requiredTypes9.Name='Site Assessment Contact Title';
		requiredTypes9.Field_API__c='FS_Site_Assessment_Contact_Title__c';
        requiredTypes9.Field_Lable__c='Site Assessment Contact Title';
        requiredList.add(requiredTypes9);
        requiredTypes10=new FS_CI_Required_Fields_Region__c();
        requiredTypes10.Name='Site Assessment Required';
		requiredTypes10.Field_API__c='FS_Site_Assessment_Required__c';
        requiredTypes10.Field_Lable__c='Select Davaco Requirements for Project?';
        requiredList.add(requiredTypes10);
        insert requiredList;
        //Create Chain Account
        accChain = FSTestUtil.createTestAccount('Test Chain 1',FSConstants.RECORD_TYPE_CHAIN,false);
        accChain.FS_FSM_Review__c = 'Reviewed';
        insert accChain;

        //Create Headquarter Account
        accHeadQtr1 = FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,false); 
        accHeadQtr1.FS_Revenue_Center__c = 'East';
        insert accHeadQtr1;

        accHeadQtr = FSTestUtil.createAccountOutlet('Test Outlet 1',FSConstants.RECORD_TYPE_OUTLET,accHeadQtr1.id,false);        
        accHeadQtr.FS_Chain__c = accChain.Id;
        accHeadQtr.FS_Revenue_Center__c = 'East';
        accHeadQtr.FS_Headquarters__c = accHeadQtr1.Id;
        insert accHeadQtr;

        con = FSTestUtil.createTestContact(accHeadQtr.Id, 'contact', false);
        con.FS_Execution_Plan_Role__c = 'Primary Contact';
        //con.FS_Contact_Info_Complete__c = true  ;
        insert con;

        FS_Customer_Input_Type__c custInputType = FSTestUtil.createCustomerInputType(true);

        custInput = new FS_Customer_Input__c();
        custInput.FS_Account__c = accHeadQtr.Id;
        custInput.FS_Customer_Input_Type__c = custInputType.Id;
        //custInput.FS_Site_Assessment_Required__c = ;
        custInput.FS_Site_Assessment_Contact_name__c = 'testName';
        custInput.FS_Site_Assessment_Contact_Phone__c = '9799559433';
        custInput.FS_Site_Assessment_contact_email__c = 'xyz@test.com';
        custInput.FS_Requested_Cartridge_Order_Method__c = '';
        custInput.FS_Number_self_serve_units__c='10';
        custInput.FS_Number_crew_serve_unit__c='11';
        custInput.FS_Self_Serve_Top_Mnt_Ice_Maker_Instld__c='12';
        insert custInput;
        custInput1 = new FS_Customer_Input__c();
        custInput1.FS_Account__c = accHeadQtr1.Id;
        custInput1.FS_Customer_Input_Type__c = custInputType.Id;
        //custInput.FS_Site_Assessment_Required__c = ;
        custInput1.FS_Site_Assessment_Contact_name__c = 'testName';
        custInput1.FS_Site_Assessment_Contact_Phone__c = '9799559433';
        custInput1.FS_Site_Assessment_contact_email__c = 'xyz@test.com';
        custInput1.FS_Requested_Cartridge_Order_Method__c = '';
        custInput1.FS_Number_self_serve_units__c='10';
        custInput1.FS_Number_crew_serve_unit__c='11';
        custInput1.FS_Self_Serve_Top_Mnt_Ice_Maker_Instld__c='12';
        insert custInput1;

        FS_CI_Required_Fields_Region__c fsReqField =
            new FS_CI_Required_Fields_Region__c(Name = 'Id', Field_Lable__c = 'Id',
                             Field_API__c = 'Id');
        insert fsReqField;
    }
}