force-app/main/default/objects/Account/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Headquarters</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for HQ.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Headquarters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/FS_Association_Brandset__c.object-meta.xml
<CustomObject>
    <label>Default Brandset</label>
    <nameField>
        <displayFormat>AB-{00000}</displayFormat>
        <label>Account Brandset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Brandsets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Headquarters</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Default Brandset</relationshipLabel>
    <relationshipName>FSHeadquarters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Installation__c.field-meta.xml
<CustomField>
    <fullName>FS_Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation Plan</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Selected Brandsets</relationshipLabel>
    <relationshipName>Account_Brandsets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_IP_RecordType__c.field-meta.xml
<CustomField>
    <fullName>FS_IP_RecordType__c</fullName>
    <formula>FS_Installation__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Installation Record Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Outlet_Dispenser__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_Dispenser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet Dispenser</label>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipLabel>Brandset Details (Current)</relationshipLabel>
    <relationshipName>OutletDispensers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/NewBrandsetOverrideController.cls
/*=================================================================================================================
* Date         : 01-30-2019
* Developer    : Goutham Rapolu
* Purpose      : AuraEnabled Controller for NewEditBrandsetOverride lightning component to return Parent record ID & Delete Brandset
*=================================================================================================================
*                                 Update History
*                                 ---------------
*   Date        Developer       Tag   Description
*============+================+=====+=============================================================================
* 01-30-2019 | Goutham Rapolu |     | Initial Version                                         
*===========+=================+=====+=============================================================================
*/

public class NewBrandsetOverrideController {
    
    @AuraEnabled
    public static Id getHQRecordId(id brandsetId, string ObjName){
        id hqID;
        Blob afterblob = EncodingUtil.base64Decode(ObjName);
        String ObjectName = afterblob.toString();
        System.debug('decoded as: ' + afterblob.toString());
        if(brandsetId != null) {
            //Query Parent ID from Default Brandset.
            FS_Association_Brandset__c assBrandset= [select id, name,FS_Headquarters__c, FS_Installation__c, FS_Outlet_Dispenser__c from FS_Association_Brandset__c
                                                     where id =:brandsetId] ;
            hqID = null;
            //Check if Parent ID is Installation / Account.
            if(ObjectName.contains('FS_Installation__c')  || ObjectName.contains('Account_Brandsets__r')){
                    hqID = assBrandset.FS_Installation__c;
            }else if(ObjectName.contains('Account') || ObjectName.contains('FSHeadquarters__r')){
                hqID = assBrandset.FS_Headquarters__c;
            } else if(ObjectName.contains('FS_Outlet_Dispenser__c') || ObjectName.contains('OutletDispensers__r')) {
            	 hqID = assBrandset.FS_Outlet_Dispenser__c;
            }
            else if(ObjectName.contains('FS_Association_Brandset__c')){
               hqID = assBrandset.id;
            }    
        }
        return hqID;
    }
    //Check User profile to give access to record Edit/Delete.
    @AuraEnabled
    public static boolean getProfileAccess(id brandsetId, string ObjName){
        id hqID;
        Blob afterblob = EncodingUtil.base64Decode(ObjName);
        String ObjectName = afterblob.toString();
        System.debug('decoded as: ' + afterblob.toString());
        
        boolean profileHasAccess=false;
        String usrProfileName = [select u.Profile.Name from User u where u.id = :Userinfo.getUserId()].Profile.Name;
        
        if(string.isNotBlank(usrProfileName) && !ObjectName.contains('FS_Outlet_Dispenser__c') && !ObjectName.contains('OutletDispensers__r') 
           && (usrProfileName.contains('FS Admin PM_P') || usrProfileName.contains('FS AC_P') || usrProfileName.contains('FS PM_P') || 
               usrProfileName.contains('System Administrator') || usrProfileName.contains('FET System Admin'))){
            profileHasAccess=true;
        }
        if(string.isNotBlank(usrProfileName) && (ObjectName.contains('FS_Outlet_Dispenser__c') || ObjectName.contains('OutletDispensers__r')) 
           && (usrProfileName.contains('System Administrator') || usrProfileName.contains('FET System Admin'))){
            profileHasAccess=true;
        }
        
        
        return profileHasAccess;
    }
    
    //Check if Installation record type is New Install.
     @AuraEnabled
    public static boolean getInstallationRT(id brandsetId, string ObjName){
        Boolean RTisNewInstall = true;
        Blob afterblob = EncodingUtil.base64Decode(ObjName);
        String ObjectName = afterblob.toString();
        System.debug('decoded as: ' + afterblob.toString());
        if(brandsetId != null) {
            //Query Parent ID from Default Brandset.
            FS_Association_Brandset__c assBrandset= [select id, name,FS_Headquarters__c, FS_Installation__c, FS_IP_RecordType__c from FS_Association_Brandset__c
                                                     where id =:brandsetId] ;
            if(ObjectName.contains('FS_Installation__c') || ObjectName.contains('Account_Brandsets__r')){
                RTisNewInstall = false;
                system.debug('@@IP_New_Install_Rec_Type'+Label.IP_New_Install_Rec_Type );
                system.debug('@@assBrandset.FS_IP_RecordType__c'+assBrandset.FS_IP_RecordType__c );
                if(assBrandset.FS_IP_RecordType__c == Label.IP_New_Install_Rec_Type){
                    RTisNewInstall = true;
                }
            }
        }
        system.debug('@@RTisNewInstall'+RTisNewInstall);
        return RTisNewInstall;
    }
    //Delete Brandset.
    @AuraEnabled
    public static void deleteBrandSet(id brandsetId) {
        FS_Association_Brandset__c assBrandset= [select id, name,FS_Headquarters__c,FS_Installation__c from FS_Association_Brandset__c
                                                 where id =:brandsetId] ;
        delete assBrandset;
    }
    
    @AuraEnabled
    public static string getdecodeurl(string decodeurl){
        Blob afterblob = EncodingUtil.base64Decode(decodeurl);
        String ObjectName = afterblob.toString();
        String FinalValue = '';
        if( ObjectName.contains('Account_Brandsets__r')){
            FinalValue = 'Account_Brandsets__r';            
        }
        if (ObjectName.contains('FSHeadquarters__r')){
            FinalValue = 'FSHeadquarters__r';
        }
        if (ObjectName.contains('OutletDispensers__r')){
            FinalValue = 'OutletDispensers__r';
        }
        
        
        return FinalValue;
    }
}