force-app/main/default/objects/Account/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Headquarters</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for HQ.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Headquarters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/FS_Valid_Fill__c.field-meta.xml
<CustomField>
    <fullName>FS_Valid_Fill__c</fullName>
    <label>Valid Fill</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/FS_Valid_Fill__c.object-meta.xml
<CustomObject>
    <label>Valid Fill</label>
    <nameField>
        <displayFormat>VF-{0000}</displayFormat>
        <label>Valid Fill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Valid Fill</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Valid_Fill__c/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <formula>FS_Outlet__r.FS_Headquarters__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Headquarters</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Post-Install Valid Fill</relationshipLabel>
    <relationshipName>Vailid_Fill</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FSCopytoLower_Cancel_ValidFill_Test.cls
/**************************************************************************************
Apex Class Name     : FSCopytoLower_Cancel_ValidFill_Test
Version             : 1.0
Function            : This is a Test class for FSCopytoLower_Cancel_ValidFill_Extension Apex Class
Modification Log    :
* Developer         :    Date              Description
* ----------------------------------------------------------------------------                 
* Venkat FNF 6.0         02/12/2019        Original Version
*************************************************************************************/
@isTest
public class FSCopytoLower_Cancel_ValidFill_Test {
    
    
    public static testMethod void copyCancelvalidFillTest(){
        
        //Create HeadQuarters       
        final List<Account> headQuarterList= FSTestFactory.createTestAccount(true,1,FSUtil.getObjectRecordTypeId(Account.SObjectType,FSConstants.RECORD_TYPE_NAME_HQ));
        //creating outlet
        final List<Account> outletLst = FSTestFactory.createTestAccount(false,1,FSUtil.getObjectRecordTypeId(Account.SObjectType,FSConstants.RECORD_TYPE_NAME_OUTLET));
        for(Account outlet : outletLst){
            outlet.FS_Headquarters__c =  headQuarterList[0].id;
        }
        insert outletLst;
        FSTestFactory.createTestDisableTriggerSetting();
        final List<FS_Valid_Fill__c> validFillList=new List<FS_Valid_Fill__c>();
        FS_Valid_Fill__c validFill = new FS_Valid_Fill__c();
        validFill =FSTestUtil.createValidFill('7000',false);
        validFill.FS_Outlet__c=outletLst[0].id;      
        validFillList.add(validFill);  
        insert validFillList;
        Test.startTest();
        final PageReference pageRef=Page.FSCopytoLowerValidFill;
        pageRef.getParameters().put('id',outletLst[0].id);   
        //Sets the current PageReference for the controller
        Test.setCurrentPage(pageRef);
        
        final ApexPages.StandardSetController stdcon = new ApexPages.StandardSetController(validFillList);   
        stdcon.setSelected(validFillList);
        stdcon.getSelected();
        final FSCopytoLower_Cancel_ValidFill_Extension controller= new FSCopytoLower_Cancel_ValidFill_Extension(stdcon);
        
        Test.stopTest();   
        
    }
}