force-app/main/default/objects/Account/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Headquarters</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for HQ.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Headquarters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountTeamMember__c/AccountTeamMember__c.object-meta.xml
<CustomObject>
    <label>Account Team Member</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>AccountTeamMember Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountTeamMember__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>AccountId</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Team Members</relationshipLabel>
    <relationshipName>AccountTeamMembers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountTeamMember__c/fields/FS_Email__c.field-meta.xml
<CustomField>
    <fullName>FS_Email__c</fullName>
    <description>Email Field</description>
    <label>Team Member Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/AccountTeamMember__c/fields/TeamMemberRole__c.field-meta.xml
<CustomField>
    <fullName>TeamMemberRole__c</fullName>
    <label>Team Member Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>COM</fullName>
            </value>
            <value>
                <fullName>COM Backup</fullName>
            </value>
            <value>
                <fullName>JCOM</fullName>
            </value>
            <value>
                <fullName>Sales Team Member</fullName>
            </value>
            <value>
                <fullName>PM</fullName>
            </value>
            <value>
                <fullName>PIC</fullName>
            </value>
            <value>
                <fullName>Sales Support</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>FDC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountTeamMember__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AccountTeamMembers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CIF_Header__c/CIF_Header__c.object-meta.xml
<CustomObject>
    <description>CIF Header</description>
    <label>CIF Header</label>
    <nameField>
        <label>CIF Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CIF Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CIF_Header__c/fields/FS_FPS__c.field-meta.xml
<CustomField>
    <fullName>FS_FPS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FPS User</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>FS FPS_P</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>FS AC_P</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>FS PM_P</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>FS Admin PM_P</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>CIF_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CIF_Header__c/fields/FS_HQ__c.field-meta.xml
<CustomField>
    <fullName>FS_HQ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HQ Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>CIF_Head</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CIF_Header__c/fields/FS_Sales_Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>FS_Sales_Rep_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AccountTeamMember__c.AccountId__r.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <filterItems>
            <field>AccountTeamMember__c.AccountId__c</field>
            <operation>equals</operation>
            <valueField>$Source.FS_HQ__c</valueField>
        </filterItems>
        <filterItems>
            <field>AccountTeamMember__c.TeamMemberRole__c</field>
            <operation>equals</operation>
            <value>Sales Team Member</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AccountTeamMember__c</referenceTo>
    <relationshipLabel>CIF Headers</relationshipLabel>
    <relationshipName>CIF_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CIF_Header__c/fields/FS_Version__c.field-meta.xml
<CustomField>
    <fullName>FS_Version__c</fullName>
    <label>Version</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CIF_Header__c/fields/FSCOM__c.field-meta.xml
<CustomField>
    <fullName>FSCOM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>COM User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AccountTeamMember__c.TeamMemberRole__c</field>
            <operation>equals</operation>
            <value>COM</value>
        </filterItems>
        <filterItems>
            <field>AccountTeamMember__c.AccountId__c</field>
            <operation>equals</operation>
            <valueField>$Source.FS_HQ__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AccountTeamMember__c</referenceTo>
    <relationshipLabel>CIF Headers (COM)</relationshipLabel>
    <relationshipName>CIF_Headers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_CIF__c/FS_CIF__c.object-meta.xml
<CustomObject>
    <label>CIF</label>
    <nameField>
        <label>CIF Outlet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CIF</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_CIF__c/fields/CIF_Head__c.field-meta.xml
<CustomField>
    <fullName>CIF_Head__c</fullName>
    <label>CIF Header Name</label>
    <referenceTo>CIF_Header__c</referenceTo>
    <relationshipLabel>CIF</relationshipLabel>
    <relationshipName>CIF</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_CIF__c/fields/FS_Customer_s_disposition_after_review__c.field-meta.xml
<CustomField>
    <fullName>FS_Customer_s_disposition_after_review__c</fullName>
    <description>Picklist values for CustomerÃ¢â‚¬â„¢s Disposition after review</description>
    <label>CustomerÃ¢â‚¬â„¢s disposition after review</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved by Customer</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Pending Site Survey</fullName>
                <default>true</default>
                <label>Pending Site Survey</label>
            </value>
            <value>
                <fullName>Second Site Survey Pending</fullName>
            </value>
            <value>
                <fullName>Awaiting Customer Decision</fullName>
            </value>
            <value>
                <fullName>Ready for COM</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
                <isActive>false</isActive>
                <label>Approved</label>
            </value>
            <value>
                <fullName>Reviewed Awaiting Customer Decision</fullName>
                <isActive>false</isActive>
                <label>Reviewed Awaiting Customer Decision</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_CIF__c/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Headquarters</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CIF</relationshipLabel>
    <relationshipName>CIF</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_FPS__c.field-meta.xml
<CustomField>
    <fullName>FS_FPS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FPS</label>
    <lookupFilter>
        <active>false</active>
        <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>FS FPS_P</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>FS PM_P</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>FS Admin PM_P</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>FS AC_P</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Execution_Plans4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <label>Headquarters</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Value does not exist or does not match filter criteria for HQ on EP.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Execution Plans (Headquarters)</relationshipLabel>
    <relationshipName>Execution_Plans1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_CIF__c.field-meta.xml
<CustomField>
    <fullName>FS_CIF__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CIF</label>
    <referenceTo>FS_CIF__c</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Rush_Install_Recipient_List__c/FS_Rush_Install_Recipient_List__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Recipient list to send the notification for Rush Install.</description>
    <label>Rush Install Recipient List</label>
</CustomObject>

force-app/main/default/objects/FS_Rush_Install_Recipient_List__c/fields/FS_Email__c.field-meta.xml
<CustomField>
    <fullName>FS_Email__c</fullName>
    <description>FS_Email</description>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/FSCOMNotificationsTest.cls
@isTest
public with sharing class FSCOMNotificationsTest{

	private static final String USER_EMAIL = 'amanseth7827@gmail.com';
    private static final String LOCALE = 'en_US';
    public static List<Account> outCustList;
    public static List<Account> outletCustList;
    private static testmethod void testTrigger(){
        outCustList= FSTestFactory.createTestAccount(false,1,FSUtil.getObjectRecordTypeId(Account.SObjectType,'FS Headquarters'));
        insert outCustList;   

        	final List<User> userList = new List<User>();
        	final User user1 = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'FS PM_P'].Id,
            LastName = 'TestCodeCOM',
            Email = USER_EMAIL,
            Username = 'test12344444343467@test.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title',
            Alias = 'alias',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = LOCALE,
            LocaleSidKey = LOCALE
            
        );
      userList.add(user1);
        final User user2 = new User(
            ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
            LastName = 'TestCodeCOM1',
            Email = USER_EMAIL,
            Username = 'test12344444343467@test1.com' + System.currentTimeMillis(),
            CompanyName = 'TEST',
            Title = 'title1',
            Alias = 'alias1',
            TimeZoneSidKey = 'America/Los_Angeles',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = LOCALE,
            LocaleSidKey = LOCALE
            
        );
        Test.startTest();
        userList.add(user2);
        insert userList;
        FS_Rush_Install_Recipient_List__c rushInstallRecipientList = new FS_Rush_Install_Recipient_List__c();
       	rushInstallRecipientList.FS_Email__c = user2.Email;
        rushInstallRecipientList.Name = 'Recipient';
        insert rushInstallRecipientList;
        
        System.runAs(userList[1]) {
            final List<AccountTeamMember__c> accTeamLst= new List<AccountTeamMember__c>();
            final AccountTeamMember__c accName1 = new AccountTeamMember__c(AccountId__c=outCustList[0].id,TeamMemberRole__c= 'COM',UserId__c=userList[1].id, FS_Email__c=USER_EMAIL);
            final AccountTeamMember__c accName2 = new AccountTeamMember__c(AccountId__c=outCustList[0].id,TeamMemberRole__c= 'Sales Team Member',UserId__c=userList[1].id, FS_Email__c=USER_EMAIL);
            accTeamLst.add(accName1);
            accTeamLst.add(accName2);
            insert accTeamLst;
                     
            
            final CIF_Header__c cheader =new CIF_Header__c(Name='FS CIF Header');
            cheader.FS_FPS__c=userList[0].Id;
            cheader.FSCOM__c=accTeamLst[0].Id;
            cheader.FS_Sales_Rep_Name__c=accTeamLst[1].Id;
            cheader.FS_Version__c = 10.02;
            cheader.FS_HQ__c=outCustList[0].id;
            insert cheader;
            
                        
            final FS_CIF__c fscif=new FS_CIF__c(Name='FS CIF'); 
            fscif.CIF_Head__c=cheader.Id;
            fscif.FS_Headquarters__c = outCustList[0].id;
            fscif.FS_Customer_s_disposition_after_review__c='On Hold';            
            fscif.FS_Reason_if_applicable__c='Test';
            fscif.FS_SA_Completed_Date__c=System.TODAY();
            fscif.FS_Second_Site_Assessment_Completed_Date__c=System.TODAY();
            fscif.FS_What_type_of_Site_Assessment__c = 'New Construction SA - Proceed w/Scheduling';
            fscif.FS_Platform1__c = '9000'; 
            insert fscif;
            
            fscif.FS_Customer_s_disposition_after_review__c='Approved by Customer';            
            fscif.FS_SA_Completed_Date__c=System.TODAY()+7;
            fscif.FS_Second_Site_Assessment_Completed_Date__c=System.TODAY()+7; 
            fscif.FS_What_type_of_Site_Assessment__c = 'Rush – New Construction SA – Proceed w/Scheduling';
            fscif.FS_Perf_Site_Assessment__c = 'Yes';
            fscif.FS_Platform1__c = '7000';
            update fscif;            
            Test.stopTest();
            System.assertEquals('Approved by Customer', fscif.FS_Customer_s_disposition_after_review__c);
            System.assertEquals(System.TODAY()+7, fscif.FS_SA_Completed_Date__c);
            System.assertEquals(System.TODAY()+7, fscif.FS_Second_Site_Assessment_Completed_Date__c);
            
        }
    }
    private static testMethod void testPopulateCIFToInstall(){
        final Id recordTypeId=Schema.SObjectType.FS_Installation__c.getRecordTypeInfosByName().get('New Install').getRecordTypeId();
        outCustList= FSTestFactory.createTestAccount(true,1,FSUtil.getObjectRecordTypeId(Account.SObjectType,'FS Headquarters'));
        outletCustList=FSTestFactory.createTestAccount(false,50,FSUtil.getObjectRecordTypeId(Account.SObjectType,'FS Outlet'));
        for(Account acc:outletCustList){
            acc.FS_Headquarters__c=outCustList[0].id;
        }
        insert outletCustList;        
        final CIF_Header__c cHeader =new CIF_Header__c(Name='FS CIF Header',FS_Version__c = 1.0,FS_HQ__c=outCustList[0].id);            
        insert cHeader;        
         List<FS_CIF__c> cifLinelist=FSTestFactory.createTestCif(outletCustList,cHeader.Id,50,true);        
         List<FS_Execution_Plan__c> executionPlanLst = FSTestFactory.createTestExecutionPlan(outCustList[0].id,true,1,FSUtil.getObjectRecordTypeId(FS_Execution_Plan__c.SObjectType,'Execution Plan'));        
         List<FS_Installation__c> installList=FSTestFactory.createTestInstallationPlan(executionPlanLst[0].id,outletCustList[0].Id,false,50,recordTypeId);
        for(Integer i=0;i<50;i++){
            final FS_Installation__c install=installList[i];
        	install.FS_Outlet__c=outCustList[0].id;
            install.FS_CIF__C=cifLinelist[0].id;            
        }
         Test.startTest();
        insert installList;        
        final List<FS_CIF__c> listUpdateCIF=new List<FS_CIF__c>();
        for(Integer i=0;i<50;i++){
            final FS_CIF__c cif=cifLinelist[i];
        	cif.FS_Installation__c=installList[0].id;           
            cif.FS_Second_SA_Incomplete_reason__c='Test Reason';
            listUpdateCIF.add(cif);
        }
		FSCOMNotificationhandler.mapMethodCheck=false;
        update listUpdateCIF;        
         Test.stopTest();
    }
    @testSetup  
     static void mytestSetup() {
       Disable_Trigger__c disableTriggerSetting = new Disable_Trigger__c();
       disableTriggerSetting.name='FSCOMNotifications';
       disableTriggerSetting.IsActive__c=true;
       disableTriggerSetting.Trigger_Name__c='FSCOMNotifications' ; 
       insert disableTriggerSetting;   
      } 
}