force-app/main/default/objects/Account/fields/FS_Is_Address_Validated__c.field-meta.xml
<CustomField>
    <fullName>FS_Is_Address_Validated__c</fullName>
    <inlineHelpText>Checked when the Address field is validated</inlineHelpText>
    <label>Is Address Validated?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Default_FET_International_Outlet__c.field-meta.xml
<CustomField>
    <fullName>Is_Default_FET_International_Outlet__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Default INT outlet used to assign the ODs when OD not assigned to actual outlet.</inlineHelpText>
    <label>Is Default FET International Outlet?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_OD_Settings__c/FS_OD_Settings__c.object-meta.xml
<CustomObject>
    <description>OD Settings</description>
    <label>OD Settings</label>
    <nameField>
        <displayFormat>ODS-{0000000}</displayFormat>
        <label>OD Settings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OD Settings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_OD_Settings__c/fields/FS_OD_RecId__c.field-meta.xml
<CustomField>
    <fullName>FS_OD_RecId__c</fullName>
    <description>OD Record ID</description>
    <label>OD RecID</label>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipLabel>OD Settings</relationshipLabel>
    <relationshipName>Settings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_OD_SettingsReadOnly__c/FS_OD_SettingsReadOnly__c.object-meta.xml
<CustomObject>
    <description>OD SettingsReadOnly</description>
    <label>OD SettingsReadOnly</label>
    <nameField>
        <displayFormat>ODSR-{0000000}</displayFormat>
        <label>OD SettingsReadOnly Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OD SettingsReadOnly</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_OD_SettingsReadOnly__c/fields/FS_OD_RecId__c.field-meta.xml
<CustomField>
    <fullName>FS_OD_RecId__c</fullName>
    <description>OD Record ID</description>
    <label>OD RecID</label>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipName>OD_Editable_Settings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_IsActive__c.field-meta.xml
<CustomField>
    <fullName>FS_IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>active or inactive</description>
    <label>Active (A) / Inactive (I)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <description>Outlet field.</description>
    <label>Outlet</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 3) OR (2 AND 4 AND (5 OR 7)) OR (2 AND 4 AND 6)</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for Outlet.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Outlet</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Outlet</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>7000, 8000, 9000, CCNA Dispenser</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Dispenser</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value>No, Yes</value>
        </filterItems>
        <filterItems>
            <field>Account.Is_Default_FET_International_Outlet__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlet Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Planned_Install_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Planned_Install_Date__c</fullName>
    <inlineHelpText>Enter the date format in mm/dd/yyyy</inlineHelpText>
    <label>FET Scheduled Install Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Serial_Number2__c.field-meta.xml
<CustomField>
    <fullName>FS_Serial_Number2__c</fullName>
    <description>Serial Number/Asset Tag.</description>
    <label>JDE Serial Number/Asset Tag</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Status__c.field-meta.xml
<CustomField>
    <fullName>FS_Status__c</fullName>
    <description>Status.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Enroll</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Hibernate</fullName>
            </value>
            <value>
                <fullName>Wakeup</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Booking Complete</fullName>
            </value>
            <value>
                <fullName>Dispenser Pickup</fullName>
            </value>
            <value>
                <fullName>Dispenser Delivered</fullName>
            </value>
            <value>
                <fullName>In Inventory</fullName>
            </value>
            <value>
                <fullName>Assigned to Outlet</fullName>
            </value>
            <value>
                <fullName>Winterized</fullName>
            </value>
            <value>
                <fullName>Rough Stock</fullName>
            </value>
            <value>
                <fullName>Remaned</fullName>
            </value>
            <value>
                <fullName>To be scrapped by Bottler</fullName>
            </value>
            <value>
                <fullName>To be scrapped by CM</fullName>
            </value>
            <value>
                <fullName>Confirmed Scrapped</fullName>
            </value>
            <value>
                <fullName>Sold to Bottler</fullName>
            </value>
            <value>
                <fullName>Purchased from Bottler</fullName>
            </value>
            <value>
                <fullName>To be Remanufactured</fullName>
            </value>
            <value>
                <fullName>Unenrolled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FOT_UpdateSettings_Batch_Test.cls
@isTest
public class FOT_UpdateSettings_Batch_Test {
    public static Account headquartersAcc,acc,headquartersAcc1,acc1;
    @testSetup
    static void testSetup1(){ 
        
        headquartersAcc = FSTestUtil.createTestAccount('Test',FSConstants.RECORD_TYPE_HQ,true);
        acc = FSTestUtil.createAccountOutlet('Test Outlet',FSConstants.RECORD_TYPE_OUTLET,headquartersAcc.id, false);
        acc.RecordTypeId=FSConstants.RECORD_TYPE_OUTLET1;
        acc.FS_Is_Address_Validated__c='Yes';
        acc.Is_Default_FET_International_Outlet__c=true; 
        insert acc;

        FSTestUtil.insertPlatformTypeCustomSettings();

        FS_Outlet_Dispenser__c od=new FS_Outlet_Dispenser__c();
        FS_Outlet_Dispenser__c od1=new FS_Outlet_Dispenser__c();
        od= FSTestUtil.createOutletDispenserAllTypes(FSConstants.OD_RECORD_TYPE_INT,null,acc.id,null,false);
        od.FS_Serial_Number2__c = 'TEST_7687';
        od.FS_IsActive__c = true;
        od.FS_Outlet__c = acc.id;
        od.FS_Planned_Install_Date__c =system.now().date();
        od.FS_Status__c = 'Assigned to Outlet'; 
        insert od; 
        
        FS_OD_Settings__c editableSetting = new FS_OD_Settings__c();
        editableSetting.FS_OD_RecId__c = od.id;
        insert editableSetting;
    }
    
    private static testMethod void test1(){
        Test.startTest();
        //List<FS_Outlet_Dispenser__c > oDList=new List<FS_Outlet_Dispenser__c>(); 
        //oDList = [SELECT id FROM FS_Outlet_Dispenser__c WHERE Id NOT IN (SELECT FS_OD_RecId__c FROM FS_OD_SettingsReadOnly__c) LIMIT 200];
        //system.debug('oDList:-'+oDList);
        try{
            DataBase.executeBatch(new FOT_UpdateSettings_Batch());
        }catch(exception e) {}
        Test.stopTest();
    }
    
}