force-app/main/default/objects/Account/fields/FS_Is_Address_Validated__c.field-meta.xml
<CustomField>
    <fullName>FS_Is_Address_Validated__c</fullName>
    <inlineHelpText>Checked when the Address field is validated</inlineHelpText>
    <label>Is Address Validated?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Is_Default_FET_International_Outlet__c.field-meta.xml
<CustomField>
    <fullName>Is_Default_FET_International_Outlet__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Default INT outlet used to assign the ODs when OD not assigned to actual outlet.</inlineHelpText>
    <label>Is Default FET International Outlet?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_OD_Show_Hide__c/FS_OD_Show_Hide__c.object-meta.xml
<CustomObject>
    <label>Show/ Hide</label>
    <nameField>
        <label>Show/ Hide Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ShowHide</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_OD_Show_Hide__c/fields/beverage_id__c.field-meta.xml
<CustomField>
    <fullName>beverage_id__c</fullName>
    <label>Beverage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_OD_Show_Hide__c/fields/FS_ODRecID__c.field-meta.xml
<CustomField>
    <fullName>FS_ODRecID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ODRecID</label>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipLabel>ShowHide</relationshipLabel>
    <relationshipName>ODRecID</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_OD_Show_Hide__c/fields/show_hide_setting__c.field-meta.xml
<CustomField>
    <fullName>show_hide_setting__c</fullName>
    <label>Show/Hide</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Show</fullName>
            </value>
            <value>
                <fullName>Hide</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_IsActive__c.field-meta.xml
<CustomField>
    <fullName>FS_IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>active or inactive</description>
    <label>Active (A) / Inactive (I)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <description>Outlet field.</description>
    <label>Outlet</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 3) OR (2 AND 4 AND (5 OR 7)) OR (2 AND 4 AND 6)</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for Outlet.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Outlet</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Outlet</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>7000, 8000, 9000, CCNA Dispenser</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Dispenser</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value>No, Yes</value>
        </filterItems>
        <filterItems>
            <field>Account.Is_Default_FET_International_Outlet__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlet Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Planned_Install_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Planned_Install_Date__c</fullName>
    <inlineHelpText>Enter the date format in mm/dd/yyyy</inlineHelpText>
    <label>FET Scheduled Install Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Serial_Number2__c.field-meta.xml
<CustomField>
    <fullName>FS_Serial_Number2__c</fullName>
    <description>Serial Number/Asset Tag.</description>
    <label>JDE Serial Number/Asset Tag</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Status__c.field-meta.xml
<CustomField>
    <fullName>FS_Status__c</fullName>
    <description>Status.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre-Enroll</fullName>
            </value>
            <value>
                <fullName>Enrolled</fullName>
            </value>
            <value>
                <fullName>Hibernate</fullName>
            </value>
            <value>
                <fullName>Wakeup</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Booking Complete</fullName>
            </value>
            <value>
                <fullName>Dispenser Pickup</fullName>
            </value>
            <value>
                <fullName>Dispenser Delivered</fullName>
            </value>
            <value>
                <fullName>In Inventory</fullName>
            </value>
            <value>
                <fullName>Assigned to Outlet</fullName>
            </value>
            <value>
                <fullName>Winterized</fullName>
            </value>
            <value>
                <fullName>Rough Stock</fullName>
            </value>
            <value>
                <fullName>Remaned</fullName>
            </value>
            <value>
                <fullName>To be scrapped by Bottler</fullName>
            </value>
            <value>
                <fullName>To be scrapped by CM</fullName>
            </value>
            <value>
                <fullName>Confirmed Scrapped</fullName>
            </value>
            <value>
                <fullName>Sold to Bottler</fullName>
            </value>
            <value>
                <fullName>Purchased from Bottler</fullName>
            </value>
            <value>
                <fullName>To be Remanufactured</fullName>
            </value>
            <value>
                <fullName>Unenrolled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FOT_ShowHideControllerTest.cls
@istest
public class FOT_ShowHideControllerTest {

    public static Account headquartersAcc, outletacc,headquartersAcc1,acc1;
    public static FS_OD_Show_Hide__c testshowhide = new FS_OD_Show_Hide__c();
    public static FS_Outlet_Dispenser__c od=new FS_Outlet_Dispenser__c();
    
    @testSetup static void testsetupshowhide()
    {
        headquartersAcc = FSTestUtil.createTestAccount('Test',FSConstants.RECORD_TYPE_HQ,true);
        outletacc = FSTestUtil.createAccountOutlet('Test Outlet',FSConstants.RECORD_TYPE_OUTLET,headquartersAcc.id, false);
        outletacc.RecordTypeId=FSConstants.RECORD_TYPE_OUTLET1;
        outletacc.FS_Is_Address_Validated__c='Yes';
        outletacc.Is_Default_FET_International_Outlet__c=true; 
        insert outletacc;
        FSTestUtil.insertPlatformTypeCustomSettings();
        
        FS_Outlet_Dispenser__c od=new FS_Outlet_Dispenser__c();
        od= FSTestUtil.createOutletDispenserAllTypes(FSConstants.OD_RECORD_TYPE_INT,null,outletacc.id,null,false);
        od.FS_Serial_Number2__c = 'TEST_7687';
        od.FS_IsActive__c = true;
        od.FS_Outlet__c = outletacc.id;
        od.FS_Planned_Install_Date__c =system.now().date();
        od.FS_Status__c = 'Assigned to Outlet'; 
        insert od; 
        
        testshowhide.FS_ODRecID__c = od.id;
        testshowhide.show_hide_setting__c = 'Show';
        testshowhide.beverage_id__c = 'testbevarage';
        testshowhide.Name = 'testbevarage';
        insert testshowhide;
        system.debug('****testshowhide.FS_ODRecID__c1****:' +testshowhide.FS_ODRecID__c);
    }
    
    @isTest static void testuserProfileAccess()
    {
        String usrname = FOT_ShowHideController.userProfileAccess();
    }
    
    @isTest static void testShowHideRecordDetails() 
    {
        system.debug('****od id****:' +od.id);
        system.debug('****testshowhide.FS_ODRecID__c****:' +testshowhide.FS_ODRecID__c);
        FS_Outlet_Dispenser__c odrec = [select id from FS_Outlet_Dispenser__c limit 1];
        
        List<FS_OD_Show_Hide__c> showhidelist = FOT_ShowHideController.ShowHideRecordDetails(odrec.id);
    }
}