force-app/main/default/objects/Account/fields/FS_Market_ID__c.field-meta.xml
<CustomField>
    <fullName>FS_Market_ID__c</fullName>
    <label>Market ID</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Market_ID__c/FS_Market_ID__c.object-meta.xml
<CustomObject>
    <label>Market ID</label>
    <nameField>
        <displayFormat>MI-{0000}</displayFormat>
        <label>Market ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Market IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Market_ID__c/fields/FS_KO_ID__c.field-meta.xml
<CustomField>
    <fullName>FS_KO_ID__c</fullName>
    <label>KO-ID</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Market_ID__c/fields/FS_Market_ID_Value__c.field-meta.xml
<CustomField>
    <fullName>FS_Market_ID_Value__c</fullName>
    <externalId>true</externalId>
    <label>Market ID</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/FS_Market_ID__c/fields/FS_User__c.field-meta.xml
<CustomField>
    <fullName>FS_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Market_IDs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MarketAccountTeamJunction__c/MarketAccountTeamJunction__c.object-meta.xml
<CustomObject>
    <label>MarketAccountTeamJunction</label>
    <nameField>
        <label>MarketAccountTeamJunction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MarketAccountTeamJunctions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MarketAccountTeamJunction__c/fields/AccountTeamMemberIds__c.field-meta.xml
<CustomField>
    <fullName>AccountTeamMemberIds__c</fullName>
    <label>AccountTeamMemberIds</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MarketAccountTeamJunction__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market ID</label>
    <referenceTo>FS_Market_ID__c</referenceTo>
    <relationshipLabel>MarketAccountTeamJunctions</relationshipLabel>
    <relationshipName>MarketAccountTeamJunctions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/FS_KO_ID__c.field-meta.xml
<CustomField>
    <fullName>FS_KO_ID__c</fullName>
    <description>Field added 10/14/13 by H.Whitacre to support storage of Coke KO-ID for each user.</description>
    <externalId>true</externalId>
    <label>KO-ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/FS_Market_ID__c.field-meta.xml
<CustomField>
    <fullName>FS_Market_ID__c</fullName>
    <label>Market ID</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FSMarketAccountTeamBatch_Test.cls
@isTest 
public Class FSMarketAccountTeamBatch_Test{    
    static testMethod void FSMarketAccountTeamBatch_Test1(){
        
        recordtype recId = [Select Id from recordtype Where SobjectType = 'Account' and Name='FS Chain'];
        //Profile p = [select id,name from profile where name='System Administrator'];
           User testUser=FSTestUtil.createUser(null,1,'System Administrator',false);
           testUser.FirstName='Anthony';
           testUser.LastName ='Marcello1';
           insert testUser;
           
        FS_Market_ID__c testMarketId = new FS_Market_ID__c();
        testMarketId.FS_KO_ID__c = 'E62216';
        testMarketId.FS_Market_ID_Value__c = '400001';
        testMarketId.FS_User__c = [SELECT Id FROM User WHERE Name = 'Anthony Marcello1' LIMIT 1].Id;
        insert testMarketId;
        
        MarketAccountTeamJunction__c testMarketAccountTeamJunction = new MarketAccountTeamJunction__c();
        testMarketAccountTeamJunction.Name = 'Test Market Account Team Junction';
        testMarketAccountTeamJunction.AccountTeamMemberIds__c = 'Test';
        testMarketAccountTeamJunction.Market__c = testMarketId.Id;
        insert testMarketAccountTeamJunction;
                
        Account acc = new Account();
        acc.Name = 'Test Account';
        acc.FS_Market_ID__c= '400001';
        acc.RecordTypeId=recId.id;
        insert acc;
        
        AccountTeamMember testAccountTeamMember = new AccountTeamMember();
       // testAccountTeamMember.UserId = [SELECT Id FROM User WHERE Name = 'Anthony Marcello1' LIMIT 1].Id;
        testAccountTeamMember.UserId = testUser.Id;
        testAccountTeamMember.TeamMemberRole = 'PM';
        testAccountTeamMember.AccountId = acc.Id;
        
        insert testAccountTeamMember;
        
        Map<String, MarketAccountTeamJunction__c> testMapMarketJunctionWithAtm = new Map<String, MarketAccountTeamJunction__c>();
        testMapMarketJunctionWithAtm.put(testAccountTeamMember.Id,testMarketAccountTeamJunction);
        
        Map<Id,FS_Market_ID__c> testModifiedMarkets = new Map<Id,FS_Market_ID__c>();
        testModifiedMarkets.put(testMarketId.Id, testMarketId);
        
        Test.startTest();
            FSMarketAccountTeamBatch controller = new FSMarketAccountTeamBatch(testMapMarketJunctionWithAtm, testModifiedMarkets);
            Database.executeBatch(controller);
        Test.stopTest();
    }
}