force-app/main/default/objects/Account/fields/FS_Site_Assessment_Contact__c.field-meta.xml
<CustomField>
    <fullName>FS_Site_Assessment_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Site Assessment Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts (Site Assessment Contact)</relationshipLabel>
    <relationshipName>Accounts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FS_Execution_Plan_Contact__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan_Contact__c</fullName>
    <formula>NOT(ISBLANK(FS_Execution_Plan_Role__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Execution Plan Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FS_Execution_Plan_Role__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan_Role__c</fullName>
    <label>Contact Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary Contact</fullName>
            </value>
            <value>
                <fullName>Secondary Contact</fullName>
            </value>
            <value>
                <fullName>Accounts Payable Contact</fullName>
            </value>
            <value>
                <fullName>Site Assessment Contact</fullName>
            </value>
            <value>
                <fullName>Secondary Site Assessment Contact</fullName>
            </value>
            <value>
                <fullName>Contractor Contact</fullName>
            </value>
            <value>
                <fullName>On-Board Training Contact</fullName>
            </value>
            <value>
                <fullName>Installation Contact</fullName>
            </value>
            <value>
                <fullName>Coke Smart Admin User</fullName>
            </value>
            <value>
                <fullName>Coke Smart Standard User</fullName>
            </value>
            <value>
                <fullName>Order Confirmation Contact</fullName>
            </value>
            <value>
                <fullName>Shipment Confirmation Contact</fullName>
            </value>
            <value>
                <fullName>Credit Confirmation Contact</fullName>
            </value>
            <value>
                <fullName>Water Filter Contact</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disable_Trigger__c/Disable_Trigger__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting is only used in case there is a need to deactivate a trigger during data migration. The triggers must be kept activated at all times...</description>
    <label>Disable Trigger</label>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan_Contact__c/FS_Execution_Plan_Contact__c.object-meta.xml
<CustomObject>
    <label>Outlet Contact</label>
    <nameField>
        <displayFormat>EC-{0000}</displayFormat>
        <label>Outlet Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan_Contact__c/fields/FS_Execution_Plan_Contact__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan_Contact__c</fullName>
    <label>Headquarter Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 5) OR (2 AND 3 AND 4)</booleanFilter>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.FS_Headquarters__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Outlet, BoE Outlet</value>
        </filterItems>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Outlet__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.FS_Headquarters__c</field>
            <operation>equals</operation>
            <valueField>Contact.Account.FS_Headquarters__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Outlet Contacts</relationshipLabel>
    <relationshipName>Outlet_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan_Contact__c/fields/FS_Execution_Plan_Role__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan_Role__c</fullName>
    <formula>IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;Primary Contact&quot;), &quot;Primary Contact;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;Secondary Contact&quot;), &quot;Secondary Contact;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;Accounts Payable Contact&quot;), &quot;Accounts Payable Contact;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;Site Assessment Contact&quot;), &quot;Site Assessment Contact;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;Secondary Site Assessment Contact&quot;), &quot;Secondary Site Assessment Contact;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;Contractor Contact&quot;), &quot;Contractor Contact;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;On-Board Training Contact&quot;), &quot;On-Board Training Contact;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;Installation Contact&quot;), &quot;Installation Contact;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;Coke Smart Admin User&quot;), &quot;Coke Smart Admin User;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;Coke Smart Standard User&quot;), &quot;Coke Smart Standard User;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;VMS Admin User&quot;), &quot;VMS Admin User;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;VMS Standard User&quot;), &quot;VMS Standard User;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;Order Confirmation Contact&quot;), &quot;Order Confirmation Contact;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;Shipment Confirmation Contact&quot;), &quot;Shipment Confirmation Contact;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;Credit Confirmation Contact&quot;), &quot;Credit Confirmation Contact;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;Water Filter Contact&quot;), &quot;Water Filter Contact;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;Other&quot;), &quot;Other&quot;,&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Role</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan_Contact__c/fields/Outlet__c.field-meta.xml
<CustomField>
    <fullName>Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlet Contacts</relationshipLabel>
    <relationshipName>Outlet_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FSExecutionPlanContactTriggerHandlerTest.cls
/**
 * Created By   : Satyanarayan Choudhary(JDC Developer)
 * Description  : test class for FSExecutionPlanContactTriggerHandler
 		*/
@isTest
private class FSExecutionPlanContactTriggerHandlerTest {
 
    static testMethod void testCopyExecutionPlanContactsToOutlet() {
        
        final List<Account> accList=new List<Account>();
        
        final User sysAdminUser=FSTestUtil.createUser(null, 1, FSConstants.USER_POFILE_SYSADMIN, true);
        system.runAs(sysAdminUser){
        Test.startTest();
        // create test data
        Account acc = new Account(Name = 'Test Account',RecordTypeId = FSConstants.RECORD_TYPE_OUTLET);
        accList.add(acc);
            
        final Account hqAcc = new Account(Name = 'Test HQ Account',RecordTypeId = FSConstants.RECORD_TYPE_HQ);
        accList.add(hqAcc);
        
        insert accList;
            
        final Account contactAcc = new Account(Name = 'Contact Account',RecordTypeId = FSConstants.RECORD_TYPE_OUTLET);
        insert contactAcc;
        final Contact testCon1 = new Contact(LastName = 'Test Contact',AccountId = contactAcc.Id,FS_Execution_Plan_Role__c = 'Site Assessment Contact;Coke Smart Admin User;Installation Contact');
        insert testCon1;
        
        final FS_Execution_Plan_Contact__c epCon1 = new FS_Execution_Plan_Contact__c(FS_Execution_Plan_Contact__c = testCon1.Id, Outlet__c = contactAcc.Id);
        insert epCon1;
        
        // verify functionality
       	acc= [Select Id, FS_Site_Assessment_Contact__c FROM Account WHERE Id = :contactAcc.Id];
        System.assertEquals(acc.FS_Site_Assessment_Contact__c,testCon1.Id);
        update epcon1;
        Test.stopTest();
        }
        
    }
            @testSetup  
     static void mytestSetup() {
       final Disable_Trigger__c disableTriggerSetting = new Disable_Trigger__c();
       
       disableTriggerSetting.name='FSExecutionPlanContactTriggerHandler';
       disableTriggerSetting.IsActive__c=true;
       disableTriggerSetting.Trigger_Name__c='FSExecutionPlanContactTrigger' ; 
       insert disableTriggerSetting;   
      }    
}