force-app/main/default/objects/Account/fields/FS_SP_Aligned_Zip__c.field-meta.xml
<CustomField>
    <fullName>FS_SP_Aligned_Zip__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SP Aligned Zip</label>
    <referenceTo>FS_SP_Aligned_Zip__c</referenceTo>
    <relationshipLabel>Outlets</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apex_Error_Log__c/Apex_Error_Log__c.object-meta.xml
<CustomObject>
    <description>Custom Object used to store all the errors in exception blocks along with system.debug statements. Mostly useful in case of triggers, batch classes etc.</description>
    <label>Apex Error Log</label>
    <nameField>
        <label>Apex Error Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Errors Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Error_Log__c/fields/Application_Name__c.field-meta.xml
<CustomField>
    <fullName>Application_Name__c</fullName>
    <description>Name of the application</description>
    <label>Application Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Error_Log__c/fields/Class_Name__c.field-meta.xml
<CustomField>
    <fullName>Class_Name__c</fullName>
    <description>Name of the Class or Component or File or Reference from where the error or exception reported.</description>
    <label>Class Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Error_Log__c/fields/Error_Severity__c.field-meta.xml
<CustomField>
    <fullName>Error_Severity__c</fullName>
    <description>Error Serverity</description>
    <label>Error Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>High</fullName>
                <default>true</default>
                <label>High</label>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Cosmetic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Apex_Error_Log__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <description>Name of the Function or Method from where the error or exception reported.</description>
    <label>Method Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Error_Log__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <description>Any Notes for future reference or Information.</description>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Error_Log__c/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <description>Name of the object associated with error reported.</description>
    <label>Object Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_Market__c.field-meta.xml
<CustomField>
    <fullName>FS_Market__c</fullName>
    <formula>FS_Market_Text__c</formula>
    <label>Selling Activity Market</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Market_Text__c.field-meta.xml
<CustomField>
    <fullName>FS_Market_Text__c</fullName>
    <label>Market</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installations (Outlet)</relationshipLabel>
    <relationshipName>Installations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Scope_of_Work__c.field-meta.xml
<CustomField>
    <fullName>FS_Scope_of_Work__c</fullName>
    <label>Scope of Work</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_SP__c.field-meta.xml
<CustomField>
    <fullName>FS_SP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Default Service Provider Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Service Provider</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installations (SP)</relationshipLabel>
    <relationshipName>Installations2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Type_of_Dispenser_Platform__c.field-meta.xml
<CustomField>
    <fullName>FS_Type_of_Dispenser_Platform__c</fullName>
    <description>pick list field with platform values</description>
    <label>Type of Dispenser Platform</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>7000</fullName>
            </value>
            <value>
                <fullName>8000</fullName>
            </value>
            <value>
                <fullName>9000</fullName>
            </value>
            <value>
                <fullName>8000; 9000</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/Overall_Status2__c.field-meta.xml
<CustomField>
    <fullName>Overall_Status2__c</fullName>
    <label>Transaction Status</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/SP_Override__c.field-meta.xml
<CustomField>
    <fullName>SP_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Service Provider Name Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/Type_of_Dispenser_Platform__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Dispenser_Platform__c</fullName>
    <description>multi select pick list</description>
    <label>Platform Type/s</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/recordTypes/Relocation.recordType-meta.xml
<RecordType>
    <fullName>Relocation</fullName>
    <active>true</active>
    <description>Relocation (I4W) Record Type..</description>
    <label>Relocation (I4W)</label>
</RecordType>

force-app/main/default/objects/FS_Installation__c/recordTypes/Removal.recordType-meta.xml
<RecordType>
    <fullName>Removal</fullName>
    <active>true</active>
    <description>Removal Record Type.</description>
    <label>Removal</label>
</RecordType>

force-app/main/default/objects/FS_Installation__c/recordTypes/Replacement.recordType-meta.xml
<RecordType>
    <fullName>Replacement</fullName>
    <active>true</active>
    <description>Replacement Record Type...</description>
    <label>Replacement</label>
</RecordType>

force-app/main/default/objects/FS_SP_Aligned_Zip__c/FS_SP_Aligned_Zip__c.object-meta.xml
<CustomObject>
    <description>Establishes the default Service Provider for a given Zip Code. Every record is a Zip Code (unique), and each one aligns to a Service Provider account via lookup.</description>
    <label>SP Aligned Zip</label>
    <nameField>
        <displayFormat>SPZ-{000000}</displayFormat>
        <label>SP Aligned Zip</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SP Aligned Zips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_SP_Aligned_Zip__c/fields/FS_Market__c.field-meta.xml
<CustomField>
    <fullName>FS_Market__c</fullName>
    <label>Market</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_SP_Aligned_Zip__c/fields/FS_Platform_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform_Type__c</fullName>
    <label>Platform Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_SP_Aligned_Zip__c/fields/FS_Selling_Activity_Market__c.field-meta.xml
<CustomField>
    <fullName>FS_Selling_Activity_Market__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Selling Activity Market</label>
    <referenceTo>Selling_Activity_Market__c</referenceTo>
    <relationshipLabel>SP Aligned Zips</relationshipLabel>
    <relationshipName>SP_Aligned_Zips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_SP_Aligned_Zip__c/fields/FS_Selling_Market_Activation_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Selling_Market_Activation_Date__c</fullName>
    <formula>FS_Selling_Activity_Market__r.Market_Activation_Date__c</formula>
    <label>Market Activation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_SP_Aligned_Zip__c/fields/FS_Service_Provider__c.field-meta.xml
<CustomField>
    <fullName>FS_Service_Provider__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Provider</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The lookup account must be of the &quot;FS Service Provider&quot; recordtype</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Service Provider</value>
        </filterItems>
        <infoMessage>Select the Service Provider account that should be linked to the zip code.</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SP Aligned Zips</relationshipLabel>
    <relationshipName>SP_Aligned_Zips</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_SP_Aligned_Zip__c/fields/FS_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>FS_Zip_Code__c</fullName>
    <description>The 5-char Zip Code, including leading zeroes</description>
    <externalId>true</externalId>
    <inlineHelpText>Zip Code must be exactly 5 digits, include leading zeroes.</inlineHelpText>
    <label>Zip Code</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Selling_Activity_Market__c/Selling_Activity_Market__c.object-meta.xml
<CustomObject>
    <label>Selling Activity Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selling Activity Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Platform_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3100</fullName>
    </customValue>
    <customValue>
        <fullName>6000</fullName>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
    </customValue>
    <customValue>
        <fullName>7100</fullName>
    </customValue>
    <customValue>
        <fullName>8000</fullName>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
    </customValue>
    <masterLabel>Platform Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FsPostInstalltionDMBatch.cls
global without sharing class FsPostInstalltionDMBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {
    
    global String query;
    public static final Integer INT_FIVE = 5;
    global String relocateO4W=Schema.SObjectType.FS_Installation__c.getRecordTypeInfosByName().get('Relocation (O4W)').getRecordTypeId();
    global String relocate=Schema.SObjectType.FS_Installation__c.getRecordTypeInfosByName().get('Relocation (I4W)').getRecordTypeId();
    global String removal=Schema.SObjectType.FS_Installation__c.getRecordTypeInfosByName().get('Removal').getRecordTypeId();
    global String replace=Schema.SObjectType.FS_Installation__c.getRecordTypeInfosByName().get('Replacement').getRecordTypeId();
    global String newInstall=Schema.SObjectType.FS_Installation__c.getRecordTypeInfosByName().get('New Install').getRecordTypeId();
    global String complete='Complete';
    global String cancel='Cancelled';
    
    
    /****************************************************************************
//Start the batch
/***************************************************************************/
    global Database.QueryLocator start(Database.BatchableContext BC){
        
        final Set<Id> recordTypeIds=new Set<Id>();   
        //recordTypeIds.add(relocate);  recordTypeIds.add(removal); recordTypeIds.add(replace); recordTypeIds.add(relocateO4W);
        recordTypeIds.add(newInstall);
        
        String qry = 'Select id,name,recordtypeId,FS_Outlet__c,Overall_Status2__c,FS_Outlet__r.ShippingPostalCode,Type_of_Dispenser_Platform__c,FS_Market_Text__c,FS_SP__c,'+
            'FS_Scope_of_Work__c,FS_Type_of_Dispenser_Platform__c,SP_Override__c '+
            'from FS_Installation__c WHERE RecordTypeId IN:recordTypeIds and Overall_Status2__c!=:complete and Overall_Status2__c!=:cancel';
        
        return Database.getQueryLocator(qry);
    }
    
    
    
    global void execute(Database.BatchableContext BC, List<sObject> lstIP){
        String zipCode;
        final Set<String> postalCodeList = new Set<String>();
        final Map<String,FS_SP_Aligned_Zip__c> spZipMap=new Map<String,FS_SP_Aligned_Zip__c>();
        final List<FS_Installation__c> ipListUpdate=new List<FS_Installation__c>();
        final Set<Id> outletIdSet=new Set<Id>(); 
        final Map<Id, String> outletMap = new Map<Id, String>(); 
        
        for(FS_Installation__c install:(List<FS_Installation__c>)lstIP){
            if(install.FS_Outlet__c!=FSConstants.NULLVALUE){
                outletIdSet.add(install.FS_Outlet__c);
                if(install.FS_Outlet__r.ShippingPostalCode != null  && install.FS_Outlet__r.ShippingPostalCode != '') {                    
                    if(install.FS_Outlet__r.ShippingPostalCode.length() > INT_FIVE) {  zipCode = install.FS_Outlet__r.ShippingPostalCode.substring(FSConstants.ZERO,INT_FIVE);   }                    
                    else{ zipCode = install.FS_Outlet__r.ShippingPostalCode;        }                    
                    postalCodeList.add(zipCode);
                    outletMap.put(install.FS_Outlet__c, zipCode);
                }                
            }
        }
        
        //Fetch Sp aligned zip records based on ZIP codes
        if(!postalCodeList.isEmpty()){
            for(FS_SP_Aligned_Zip__c alignedZip: [SELECT FS_Platform_Type__c, FS_Zip_Code__c, FS_Service_Provider__c,FS_Selling_Market_Activation_Date__c,FS_Market__c,FS_Selling_Activity_Market__r.Name FROM FS_SP_Aligned_Zip__c WHERE FS_Zip_Code__c IN : postalCodeList]){
                
                spZipMap.put(alignedZip.FS_Zip_Code__c+alignedZip.FS_Platform_Type__c,alignedZip);
                spZipMap.put(alignedZip.FS_Zip_Code__c,alignedZip);
            }    
        } 
        
        for(FS_Installation__c install:(List<FS_Installation__c>)lstIP){
            if(install.FS_Outlet__c!=null && outletMap.containskey(install.FS_Outlet__c) && spZipMap.containsKey(outletMap.get(install.FS_Outlet__c))){                                                    
                   if(!install.SP_Override__c){
                    install.FS_SP__c=spZipMap.get(outletMap.get(install.FS_Outlet__c)).FS_Service_Provider__c;
                } 
            }
            else{
                install.FS_SP__c=FSConstants.ID_NULL;
            } 
            ipListUpdate.add(install);
        }              
         if(!ipListUpdate.isEmpty()){            
            final List<Database.SaveResult> resList = Database.update(ipListUpdate,false);
            errorCheckMethod(resList,ipListUpdate,'ipListUpdate','FS_Installation__c');
        }
    }
    
    /*****************************************************************
Method: errorCheckMethod
Description: errorCheckMethod method is used to create Apex error loger records.
to know the details of failed insert/update records while batch processing
*******************************************************************/
    public void errorCheckMethod(final List<Database.SaveResult> resList,final List<sObject> ipList,final String listName,final String objectName){
        
        final List<Apex_Error_Log__c> apexErrorList=new List<Apex_Error_Log__c>();
        for(Integer i=0; i < ipList.size() ; i++){
            final Database.SaveResult res = resList.get(i);
            if(!res.isSuccess()){
                for(Database.Error error : res.getErrors()){
                    apexErrorList.add(new Apex_Error_Log__c(Application_Name__c=FSConstants.FET,Class_Name__c='FsPostInstalltionDMBatch',Method_Name__c='errorCheckMethod',Object_Name__c=objectName,Error_Severity__c=FSConstants.MediumPriority,Notes__c=listName+FSConstants.HYPHEN+error.getMessage()+FSConstants.HYPHEN+ ipList[i].Id));                    
                }
            }            
        }
        if(!apexErrorList.isEmpty()){  insert apexErrorList;    }
    }
    
    
    global void finish(Database.BatchableContext BC){
        
    }
}