force-app/main/default/objects/Account/fields/FS_SAP_ID__c.field-meta.xml
<CustomField>
    <fullName>FS_SAP_ID__c</fullName>
    <inlineHelpText>SAP ID is an auto generated field for International Outlets.</inlineHelpText>
    <label>SAP ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispenser_Model__c/Dispenser_Model__c.object-meta.xml
<CustomObject>
    <label>Dispenser Model</label>
    <nameField>
        <label>Dispenser Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dispenser Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dispenser_Model__c/fields/Dimension_unit_of_measure__c.field-meta.xml
<CustomField>
    <fullName>Dimension_unit_of_measure__c</fullName>
    <label>Dimension Unit of Measure</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inch</fullName>
            </value>
            <value>
                <fullName>cm</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dispenser_Model__c/fields/Dimensions__c.field-meta.xml
<CustomField>
    <fullName>Dimensions__c</fullName>
    <label>Dimensions</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispenser_Model__c/fields/Dispenser_Type__c.field-meta.xml
<CustomField>
    <fullName>Dispenser_Type__c</fullName>
    <label>Equipment Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispenser_Model__c/fields/IC_Code__c.field-meta.xml
<CustomField>
    <fullName>IC_Code__c</fullName>
    <label>IC Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispenser_Model__c/fields/IC_Code_Description__c.field-meta.xml
<CustomField>
    <fullName>IC_Code_Description__c</fullName>
    <label>IC Code Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispenser_Model__c/fields/Series__c.field-meta.xml
<CustomField>
    <fullName>Series__c</fullName>
    <label>Series</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispenser_Model__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>Weight</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dispenser_Model__c/fields/Weight_unit_of_measure__c.field-meta.xml
<CustomField>
    <fullName>Weight_unit_of_measure__c</fullName>
    <label>Weight unit of measure</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>lbs</fullName>
            </value>
            <value>
                <fullName>kgs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_IsActive__c.field-meta.xml
<CustomField>
    <fullName>FS_IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>active or inactive</description>
    <label>Active (A) / Inactive (I)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Model__c.field-meta.xml
<CustomField>
    <fullName>FS_Model__c</fullName>
    <inlineHelpText>For International OD&#39;s Platform value is derived from Dispenser Model.</inlineHelpText>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2000</fullName>
            </value>
            <value>
                <fullName>7000</fullName>
            </value>
            <value>
                <fullName>8000</fullName>
            </value>
            <value>
                <fullName>9000</fullName>
            </value>
            <value>
                <fullName>3100</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_SAP_ID__c.field-meta.xml
<CustomField>
    <fullName>FS_SAP_ID__c</fullName>
    <formula>FS_Outlet__r.FS_SAP_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SAP Customer Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Serial_Number2__c.field-meta.xml
<CustomField>
    <fullName>FS_Serial_Number2__c</fullName>
    <description>Serial Number/Asset Tag.</description>
    <label>JDE Serial Number/Asset Tag</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FSInt_Dispenser_Type__c.field-meta.xml
<CustomField>
    <fullName>FSInt_Dispenser_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dispenser Model</label>
    <referenceTo>Dispenser_Model__c</referenceTo>
    <relationshipLabel>Outlet Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/IC_Code__c.field-meta.xml
<CustomField>
    <fullName>IC_Code__c</fullName>
    <formula>FSInt_Dispenser_Type__r.IC_Code__c</formula>
    <inlineHelpText>For International OD&#39;s IC Code value is derived from Dispenser Model.</inlineHelpText>
    <label>IC Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Ownership_Type__c.field-meta.xml
<CustomField>
    <fullName>Ownership_Type__c</fullName>
    <label>Ownership Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Coca-Cola Business Unit</fullName>
            </value>
            <value>
                <fullName>Bottler</fullName>
            </value>
            <value>
                <fullName>Coca-Cola Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Shipping_Form__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Form</label>
    <referenceTo>Shipping_Form__c</referenceTo>
    <relationshipLabel>Outlet Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <formula>FSInt_Dispenser_Type__r.Weight__c</formula>
    <label>Weight</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Weight_unit_of_measure__c.field-meta.xml
<CustomField>
    <fullName>Weight_unit_of_measure__c</fullName>
    <formula>TEXT( FSInt_Dispenser_Type__r.Weight_unit_of_measure__c )</formula>
    <label>Weight unit of measure</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipping_Form__c/Shipping_Form__c.object-meta.xml
<CustomObject>
    <label>Shipping Form</label>
    <nameField>
        <label>Shipping Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipping Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipping_Form__c/fields/FS_PO_Number__c.field-meta.xml
<CustomField>
    <fullName>FS_PO_Number__c</fullName>
    <label>PO Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Shipping_Form__c/fields/IC_Code__c.field-meta.xml
<CustomField>
    <fullName>IC_Code__c</fullName>
    <label>IC Code</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1795457</fullName>
            </value>
            <value>
                <fullName>1795458</fullName>
            </value>
            <value>
                <fullName>1795459</fullName>
            </value>
            <value>
                <fullName>1795460</fullName>
            </value>
            <value>
                <fullName>1700710</fullName>
            </value>
            <value>
                <fullName>1700711</fullName>
            </value>
            <value>
                <fullName>1700712</fullName>
            </value>
            <value>
                <fullName>1700713</fullName>
            </value>
            <value>
                <fullName>1700714</fullName>
            </value>
            <value>
                <fullName>1700715</fullName>
            </value>
            <value>
                <fullName>1700716</fullName>
            </value>
            <value>
                <fullName>1700717</fullName>
            </value>
            <value>
                <fullName>1700718</fullName>
            </value>
            <value>
                <fullName>1700719</fullName>
            </value>
            <value>
                <fullName>1700720</fullName>
            </value>
            <value>
                <fullName>1700721</fullName>
            </value>
            <value>
                <fullName>1702648</fullName>
            </value>
            <value>
                <fullName>46100</fullName>
            </value>
            <value>
                <fullName>46101</fullName>
            </value>
            <value>
                <fullName>46099</fullName>
            </value>
            <value>
                <fullName>46127</fullName>
            </value>
            <value>
                <fullName>46128</fullName>
            </value>
            <value>
                <fullName>46126</fullName>
            </value>
            <value>
                <fullName>46102</fullName>
            </value>
            <value>
                <fullName>46129</fullName>
            </value>
            <value>
                <fullName>46401</fullName>
            </value>
            <value>
                <fullName>46379</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/IC_Code__c.field-meta.xml
<CustomField>
    <fullName>IC_Code__c</fullName>
    <label>IC Code</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1795457</fullName>
            </value>
            <value>
                <fullName>1795458</fullName>
            </value>
            <value>
                <fullName>1795459</fullName>
            </value>
            <value>
                <fullName>1795460</fullName>
            </value>
            <value>
                <fullName>1700710</fullName>
            </value>
            <value>
                <fullName>1700711</fullName>
            </value>
            <value>
                <fullName>1700712</fullName>
            </value>
            <value>
                <fullName>1700713</fullName>
            </value>
            <value>
                <fullName>1700714</fullName>
            </value>
            <value>
                <fullName>1700715</fullName>
            </value>
            <value>
                <fullName>1700716</fullName>
            </value>
            <value>
                <fullName>1700717</fullName>
            </value>
            <value>
                <fullName>1700718</fullName>
            </value>
            <value>
                <fullName>1700719</fullName>
            </value>
            <value>
                <fullName>1700720</fullName>
            </value>
            <value>
                <fullName>1700721</fullName>
            </value>
            <value>
                <fullName>1702648</fullName>
            </value>
            <value>
                <fullName>46100</fullName>
            </value>
            <value>
                <fullName>46101</fullName>
            </value>
            <value>
                <fullName>46099</fullName>
            </value>
            <value>
                <fullName>46127</fullName>
            </value>
            <value>
                <fullName>46128</fullName>
            </value>
            <value>
                <fullName>46126</fullName>
            </value>
            <value>
                <fullName>46102</fullName>
            </value>
            <value>
                <fullName>46129</fullName>
            </value>
            <value>
                <fullName>46401</fullName>
            </value>
            <value>
                <fullName>46379</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Ownership_Type__c.field-meta.xml
<CustomField>
    <fullName>Ownership_Type__c</fullName>
    <label>Ownership Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Coca-Cola Business Unit</fullName>
            </value>
            <value>
                <fullName>Bottler</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ChangeSAPNumberControllerTest.cls
/**************************************************************************************
// (c) 2015 Appirio, Inc.
Apex Class Name     : ChangeSAPNumberControllerTest
Version             : 1.0
Function            : This test class is for ChangeSAPNumberController Class code coverage. 
Modification Log    : 
* Developer         :    Date              Description
* ----------------------------------------------------------------------------                 
* Infosys             05/21/2015          Original Version 
*					  05/29/2018		  Removed usage of OutboundServiceDetails__c customSetting as part of FOT project
*************************************************************************************/
@isTest
private Class ChangeSAPNumberControllerTest{
    
    static Shipping_Form__c shippingForm;
    static Dispenser_Model__c dispenerModel;
    static FS_Outlet_Dispenser__c dispenser = FSTestUtil.createOutletDispenserAllTypes(null,null,null,null,false);
    static Account hqAccount = FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,true);  
    static Account outletAccount = FSTestUtil.createAccountOutlet('Test Outlet 1',FSConstants.RECORD_TYPE_OUTLET,hqAccount.id, false);
    static User manufacturerUser = FSTestUtil.createUser(null,1,'FET SE Manufacturer Profile',true);
    
    static testMethod void test1(){
        //create platform type custom settings
        FSTestUtil.insertPlatformTypeCustomSettings();
        
        //set mock callout
        Test.setMock(HttpCalloutMock.class, new FSFETNMSConnectorMock());
        
        System.debug('>>>>>>>>1  '+hqAccount.Id);
        System.debug('>>>>>>>>1  '+hqAccount.Name);
        outletAccount.FS_SAP_ID__c = '87687687968';
        insert outletAccount;

        shippingForm = new Shipping_Form__c();
        shippingForm.Name='Test Shipping Form 07-07-2015';
        shippingForm.FS_PO_Number__c='12345';
        system.runAs(manufacturerUser){
            insert shippingForm;
       }
        
        dispenser.Shipping_Form__c=shippingForm.Id;
        dispenser.Ownership_Type__c='Coca-Cola Business Unit';
        dispenser.FS_Serial_Number2__c='Asset Tag 123';
        //dispenser.FS_Model__c='2000';
        dispenerModel = new Dispenser_Model__c();
        dispenerModel.Name='Test Dispenser Model 07-07-2015';
        dispenerModel.Dimensions__c='Test Dimensions';
        dispenerModel.Dimension_unit_of_measure__c='Inch';
        dispenerModel.Dispenser_Type__c='2000';
        dispenerModel.IC_Code__c='Test IC Code';
        dispenerModel.IC_Code_Description__c='Test Description';
        dispenerModel.Series__c='Test Series';
        dispenerModel.Weight__c='Test Weight';
        dispenerModel.Weight_unit_of_measure__c='lbs';
        insert dispenerModel;
        dispenser.FSInt_Dispenser_Type__c=dispenerModel.Id;
        dispenser.FS_IsActive__c = true;
        dispenser.FS_Outlet__c = outletAccount.Id;
        insert dispenser;
        System.debug('>>>>>>>>>>>>>>>>>>Outlet Dispenser Inserted' + dispenser);
        ApexPages.StandardController stdCont = new ApexPages.StandardController(dispenser);
        Test.startTest();
        ChangeSAPNumberController ctrlObj = new ChangeSAPNumberController(stdCont);
        // system.assert(null,ctrlObj.newdisp.id);
        ctrlObj.cloneDispenser();
        
        system.assert(true, ctrlObj.newdisp.FS_IsActive__c);
        Test.stopTest();
    }
}