force-app/main/default/objects/Account/fields/FS_Valid_Fill__c.field-meta.xml
<CustomField>
    <fullName>FS_Valid_Fill__c</fullName>
    <label>Valid Fill</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_of_7000_Series_Units_being_relocated__c.field-meta.xml
<CustomField>
    <fullName>FS_of_7000_Series_Units_being_relocated__c</fullName>
    <label># of 7000 Series Units being relocated</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_of_8000_Series_units_being_relocated__c.field-meta.xml
<CustomField>
    <fullName>FS_of_8000_Series_units_being_relocated__c</fullName>
    <label># of 8000 Series units being relocated</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_of_9000_Series_units_being_relocated__c.field-meta.xml
<CustomField>
    <fullName>FS_of_9000_Series_units_being_relocated__c</fullName>
    <label># of 9000 Series units being relocated</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installations (Outlet)</relationshipLabel>
    <relationshipName>Installations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Remove_Disconnect_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Remove_Disconnect_Date__c</fullName>
    <label>Initially Remove/Disconnect Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Valid_Fill__c.field-meta.xml
<CustomField>
    <fullName>FS_Valid_Fill__c</fullName>
    <label>Valid Fill</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>46245 : Valid Fill Conversion Kit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_ACN_NBR__c.field-meta.xml
<CustomField>
    <fullName>FS_ACN_NBR__c</fullName>
    <description>Customer  ACN</description>
    <formula>FS_Outlet__r.FS_ACN__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Populated by the ACN Number found on the Outlet Record.</inlineHelpText>
    <label>Outlet ACN</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Date_Installed2__c.field-meta.xml
<CustomField>
    <fullName>FS_Date_Installed2__c</fullName>
    <description>.</description>
    <inlineHelpText>Last Enrollment Date 
[Enter the date format in mm/dd/yyyy]</inlineHelpText>
    <label>MDM latest Enrollment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Dispenser_Location__c.field-meta.xml
<CustomField>
    <fullName>FS_Dispenser_Location__c</fullName>
    <description>this is a location of dispenser</description>
    <label>Dispenser Location</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Dispenser_Type2__c.field-meta.xml
<CustomField>
    <fullName>FS_Dispenser_Type2__c</fullName>
    <inlineHelpText>For International OD&#39;s Dispenser Type value is derived from Dispenser Model.</inlineHelpText>
    <label>Dispenser Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Self Serve</fullName>
            </value>
            <value>
                <fullName>Crew Serve</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Equip_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Equip_Type__c</fullName>
    <description>equip type</description>
    <inlineHelpText>This is the JDE Equipment Type value</inlineHelpText>
    <label>Equipment Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_IsActive__c.field-meta.xml
<CustomField>
    <fullName>FS_IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>active or inactive</description>
    <label>Active (A) / Inactive (I)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <description>Outlet field.</description>
    <label>Outlet</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 3) OR (2 AND 4 AND (5 OR 7)) OR (2 AND 4 AND 6)</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for Outlet.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Outlet</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Outlet</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>7000, 8000, 9000, CCNA Dispenser</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Dispenser</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value>No, Yes</value>
        </filterItems>
        <filterItems>
            <field>Account.Is_Default_FET_International_Outlet__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlet Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Removal_Request_Submitted__c.field-meta.xml
<CustomField>
    <fullName>FS_Removal_Request_Submitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Removal Request Submitted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Serial_Number2__c.field-meta.xml
<CustomField>
    <fullName>FS_Serial_Number2__c</fullName>
    <description>Serial Number/Asset Tag.</description>
    <label>JDE Serial Number/Asset Tag</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_User_Defined_Location__c.field-meta.xml
<CustomField>
    <fullName>FS_User_Defined_Location__c</fullName>
    <label>User Define Location</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Valid_Fill__c.field-meta.xml
<CustomField>
    <fullName>FS_Valid_Fill__c</fullName>
    <label>Valid Fill Required</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 OR 2) AND 4) OR 3 OR 5</booleanFilter>
        <errorMessage>The installation referenced by this dispenser is linked to a different outlet than the outlet on the dispenser.</errorMessage>
        <filterItems>
            <field>FS_Installation__c.FS_Outlet__c</field>
            <operation>equals</operation>
            <valueField>$Source.FS_Outlet__c</valueField>
        </filterItems>
        <filterItems>
            <field>FS_Installation__c.FS_New_Outlet__c</field>
            <operation>equals</operation>
            <valueField>$Source.FS_Outlet__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Dispenser</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>CCNA Dispenser, 7000, 8000, 9000</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Installed Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Planned_Remove_Date__c.field-meta.xml
<CustomField>
    <fullName>Planned_Remove_Date__c</fullName>
    <inlineHelpText>Enter the date format in mm/dd/yyyy</inlineHelpText>
    <label>JDE Removal date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Relocated_Installation__c.field-meta.xml
<CustomField>
    <fullName>Relocated_Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Installation Lookup only for RI4W Type</description>
    <label>Relocated Installation</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Outlet Dispensers (Relocated Installation)</relationshipLabel>
    <relationshipName>Outlet_Dispensers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/FS_Valid_Fill__c.object-meta.xml
<CustomObject>
    <label>Valid Fill</label>
    <nameField>
        <displayFormat>VF-{0000}</displayFormat>
        <label>Valid Fill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Valid Fill</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Valid_Fill__c/fields/FS_Installation__c.field-meta.xml
<CustomField>
    <fullName>FS_Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Post Install Valid Fill</relationshipLabel>
    <relationshipName>Valid_Fill</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Post-Install Valid Fill</relationshipLabel>
    <relationshipName>Vailid_Fill</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/fields/FS_Outlet_Dispenser__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_Dispenser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet Dispenser</label>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipLabel>Post Install Valid Fill</relationshipLabel>
    <relationshipName>Valid_Fill</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FS_SelectOutletDispenserRemoveRelocate.cls
public with sharing class FS_SelectOutletDispenserRemoveRelocate {
    public static Integer ZERO = 0;
    public static String EQUIP_7K = FSConstants.RECTYPE_7k;
    public static String EQUIP_8K = FSConstants.RECTYPE_8k;
    public static String EQUIP_9K = FSConstants.RECTYPE_9k; 
    
    public static Boolean FALSE_VAL = false;
    public List <FS_Outlet_Dispenser__c> toUpdatedOD = new list <FS_Outlet_Dispenser__c> ();
    public List<Id> installationId=new List<Id>();
    public FS_Outlet_Dispenser__c tempOD {get; set;}
    public Date DisconnectDate {get;set;}
    public FS_Installation__c currentInstallation {get; set;}
    
    public FS_SelectOutletDispenserRemoveRelocate(final ApexPages.StandardController controller) {
        tempOD = new FS_Outlet_Dispenser__c();        
        currentInstallation = [SELECT RecordType.name,FS_Outlet__r.id, FS_of_7000_Series_Units_being_relocated__c , FS_of_8000_Series_units_being_relocated__c , FS_of_9000_Series_units_being_relocated__c, FS_Remove_Disconnect_Date__c FROM FS_Installation__c WHERE Id = :ApexPages.currentPage().getParameters().get('id')];         
    }    
    public List<FS_Outlet_DispenserWrapper> FS_OutletList {get; set;}
    
    public List<FS_Outlet_DispenserWrapper> getFS_Outlet_Dispensers() {        
        
        if(FS_OutletList == null) {
            FS_OutletList = new List<FS_Outlet_DispenserWrapper>();
            
            for(FS_Outlet_Dispenser__c c: [Select id,FS_ACN_NBR__c,  name ,Installation__r.id, FS_outlet__r.name , Planned_Remove_Date__c,FS_Date_Installed2__c , Relocated_Installation__c,
                                           FS_Serial_Number2__c,FS_Dispenser_Location__c,FS_User_Defined_Location__c, FS_Valid_Fill__c, FS_Dispenser_Type2__c, FS_Equip_Type__c, FS_Removal_Request_Submitted__c
                                           from FS_Outlet_Dispenser__c where FS_outlet__r.Id =: currentInstallation.FS_Outlet__r.id and FS_IsActive__c=true]) {
                                               
                                               FS_OutletList.add(new FS_Outlet_DispenserWrapper(c));
                                           }
        }
        return FS_OutletList ;
    }
    
    public PageReference DeleteProcess() {
        
        //We create a new list of records that we be populated only if they are selected
        final List<FS_Outlet_Dispenser__c> selectedODs = new List<FS_Outlet_Dispenser__c>();
        
        
        
        for(FS_Outlet_DispenserWrapper cCon: getFS_Outlet_Dispensers()) {
            
            if(DisconnectDate!=null  && (currentInstallation.RecordType.Name==Label.IP_Relocation_I4W_Rec_Type 
                                         || currentInstallation.RecordType.Name==Label.IP_Removal_Rec_Type 
                                         || currentInstallation.RecordType.Name==Label.IP_Replacement_Rec_Type) && cCon.selected == true){
                                             
                                             
                                             selectedODs.add(cCon.con);
                                             
                                         }   
            if(DisconnectDate==null && (currentInstallation.RecordType.Name==Label.IP_Relocation_I4W_Rec_Type
                                        || currentInstallation.RecordType.Name==Label.IP_Removal_Rec_Type 
                                        || currentInstallation.RecordType.Name==Label.IP_Replacement_Rec_Type) ){
                                            Apexpages.addMessage(new ApexPages.message(ApexPages.severity.ERROR, 'Please Select Disconnect Date to proceed'));
                                            return null;
                                            break;
                                        }          
            
        }
        
        // Now we have our list of selected records 
        
        
        toUpdatedOD.clear(); //Removing previously stored values
        
        
        final List<FS_Installation__c> installationList=[select id,FS_of_7000_Series_Units_being_relocated__c,FS_of_8000_Series_Units_being_relocated__c,FS_of_9000_Series_Units_being_relocated__c from FS_Installation__c where id =:currentInstallation.id  limit 1];
        if(installationList.size()> ZERO){
            
            for(FS_Outlet_Dispenser__c oDisp1: selectedODs) {
                for(FS_Installation__c inst :installationList){
                    if(oDisp1.FS_Removal_Request_Submitted__c==FALSE_VAL){
                        if(oDisp1.FS_Equip_Type__c ==EQUIP_7K){
                            if(inst.FS_of_7000_Series_Units_being_relocated__c == null || inst.FS_of_7000_Series_Units_being_relocated__c == 0) {
                                inst.FS_of_7000_Series_Units_being_relocated__c = 1 ; 
                            }      
                            else {
                                inst.FS_of_7000_Series_units_being_relocated__c += 1; 
                            }
                        }
                        if(oDisp1.FS_Equip_Type__c ==EQUIP_8K){
                            if(inst.FS_of_8000_Series_Units_being_relocated__c == null || inst.FS_of_8000_Series_Units_being_relocated__c == 0) {
                                inst.FS_of_8000_Series_Units_being_relocated__c = 1 ; 
                                
                            }
                            else {
                                inst.FS_of_8000_Series_units_being_relocated__c += 1;
                                
                            }
                        }
                        if(oDisp1.FS_Equip_Type__c ==EQUIP_9K){
                            if(inst.FS_of_9000_Series_units_being_relocated__c == null || inst.FS_of_9000_Series_units_being_relocated__c == 0) {
                                inst.FS_of_9000_Series_units_being_relocated__c = 1 ; 
                                
                            }
                            else {
                                
                                inst.FS_of_9000_Series_units_being_relocated__c+= 1;
                                final Decimal tempUnit=inst.FS_of_9000_Series_units_being_relocated__c;
                                
                            }
                            
                        }
                        
                    }
                    
                }
            }
        }
        try{
            
            //Update the Installation Record
            final Database.SaveResult[] updateOp= Database.update(installationList,false);
            for(Database.SaveResult sr: updateOp){
                if(sr.isSuccess()){                    
                    
                }
                else{
                    system.debug('error  '+sr.getErrors());
                    
                }
            }           
        }
        catch(Exception e){
            system.debug('Error message::' +e);
        }
        
        
        
        for(FS_Outlet_Dispenser__c oDisp: selectedODs) {
            
            oDisp.Planned_Remove_Date__c = DisconnectDate ;
            oDisp.FS_Removal_Request_Submitted__c=true;
            oDisp.Relocated_Installation__c=currentInstallation.Id;
            toUpdatedOD.add(oDisp); 
            DisconnectDate=FSConstants.DATE_NULL;
            
        }
        
        //Updating OD records   
        if(toUpdatedOD.size()>ZERO){
            update toUpdatedOD;
        }
        
        
        
        
        
        
        final map<String,String> numberList = new map<String,String>(); //added by Bhanu
        final Set<ID> dispeserIDSet=new set<ID>();
        for(FS_Outlet_Dispenser__c dispenserObj : toUpdatedOD) {
            if(dispenserObj.FS_Serial_Number2__c != null
               && dispenserObj.FS_Date_Installed2__c == null
               && dispenserObj.FS_Status__c == null
               && dispenserObj.FS_Equip_Type__c == '7000'){
                   
                   numberList.put(dispenserObj.FS_Serial_Number2__c,dispenserObj.FS_ACN_NBR__c);
                   dispeserIDSet.add(dispenserObj.id);
               }
        }
        
        
        if(dispeserIDSet.size() > ZERO ){
            FSFETNMSConnector.deleteMasterAssetData(dispeserIDSet);
        }
        
        FS_OutletList =null; 
        return null;
    }
    
    
    
    
    
    public class FS_Outlet_DispenserWrapper {
        public FS_Outlet_Dispenser__c con {get; set;}
        public Boolean selected {get; set;}
        
        
        public FS_Outlet_DispenserWrapper(final FS_Outlet_Dispenser__c c) {
            con = c;
            selected = false;
        }
    }
}