force-app/main/default/objects/Account/fields/FS_Valid_Fill__c.field-meta.xml
<CustomField>
    <fullName>FS_Valid_Fill__c</fullName>
    <label>Valid Fill</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installations (Outlet)</relationshipLabel>
    <relationshipName>Installations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Valid_Fill__c.field-meta.xml
<CustomField>
    <fullName>FS_Valid_Fill__c</fullName>
    <label>Valid Fill</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>46245 : Valid Fill Conversion Kit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Msg_Copy_to_lower_levels__c/FS_Msg_Copy_to_lower_levels__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Message to Display while Coping Post install flavor changes to lower levels is done</description>
    <label>Messages For Copy Lower to Levels</label>
</CustomObject>

force-app/main/default/objects/FS_Msg_Copy_to_lower_levels__c/fields/FS_Success_Copy_to_Lower_Levels__c.field-meta.xml
<CustomField>
    <fullName>FS_Success_Copy_to_Lower_Levels__c</fullName>
    <label>Success Copy to Lower Levels</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <description>Outlet field.</description>
    <label>Outlet</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 3) OR (2 AND 4 AND (5 OR 7)) OR (2 AND 4 AND 6)</booleanFilter>
        <errorMessage>Value does not exist or does not match filter criteria for Outlet.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Outlet</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Outlet</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>7000, 8000, 9000, CCNA Dispenser</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Dispenser</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value>No, Yes</value>
        </filterItems>
        <filterItems>
            <field>Account.Is_Default_FET_International_Outlet__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.FS_Is_Address_Validated__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlet Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Valid_Fill__c.field-meta.xml
<CustomField>
    <fullName>FS_Valid_Fill__c</fullName>
    <label>Valid Fill Required</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Post_Install_Marketing__c/FS_Post_Install_Marketing__c.object-meta.xml
<CustomObject>
    <label>Post Install Marketing</label>
    <nameField>
        <displayFormat>PIM-{0000}</displayFormat>
        <label>Post Install Marketing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Post Install Marketing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Post_Install_Marketing__c/fields/FS_Account__c.field-meta.xml
<CustomField>
    <fullName>FS_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Post Install Marketing</relationshipLabel>
    <relationshipName>Post_Install_Marketing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Post_Install_Marketing__c/fields/FS_Cncl_Post_Install_Marketting_fields__c.field-meta.xml
<CustomField>
    <fullName>FS_Cncl_Post_Install_Marketting_fields__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Cancelled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Post_Install_Marketing__c/fields/FS_Installation__c.field-meta.xml
<CustomField>
    <fullName>FS_Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Post Install Marketing</relationshipLabel>
    <relationshipName>Post_Install_Marketing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Post_Install_Marketing__c/fields/FS_Outlet_Dispenser__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_Dispenser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet Dispenser</label>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipLabel>Post Install Marketing</relationshipLabel>
    <relationshipName>Post_Install_Marketing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Post_Install_Marketing__c/fields/FS_RcdIDForCncl__c.field-meta.xml
<CustomField>
    <fullName>FS_RcdIDForCncl__c</fullName>
    <label>Record ID For Cancel</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/FS_Valid_Fill__c.object-meta.xml
<CustomObject>
    <label>Valid Fill</label>
    <nameField>
        <displayFormat>VF-{0000}</displayFormat>
        <label>Valid Fill Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Valid Fill</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Valid_Fill__c/fields/FS_Cancel_Valid_Fill__c.field-meta.xml
<CustomField>
    <fullName>FS_Cancel_Valid_Fill__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Cancelled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/fields/FS_Installation__c.field-meta.xml
<CustomField>
    <fullName>FS_Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Post Install Valid Fill</relationshipLabel>
    <relationshipName>Valid_Fill</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Post-Install Valid Fill</relationshipLabel>
    <relationshipName>Vailid_Fill</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/fields/FS_Outlet_Dispenser__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_Dispenser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet Dispenser</label>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipLabel>Post Install Valid Fill</relationshipLabel>
    <relationshipName>Valid_Fill</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Valid_Fill__c/fields/FS_RcdIDForCncl__c.field-meta.xml
<CustomField>
    <fullName>FS_RcdIDForCncl__c</fullName>
    <label>Record ID For Cancel</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FSCopyPostInstallActivity.cls
global class FSCopyPostInstallActivity {
    
    webservice static String ChaintoHqMarketing(String recId,String pmid,String Obj)  {
        FS_Post_Install_Marketing__c PM;
        String qryPM = FSUtil.getSelectQuery('FS_Post_Install_Marketing__c') + ' WHERE Id=:pmid';
        List<FS_Post_Install_Marketing__c> ListPM = (List<FS_Post_Install_Marketing__c>)database.query(qryPM);
        For(FS_Post_Install_Marketing__c PIM:ListPM ){
            PM=PIM;
        }
        if(PM.FS_Cncl_Post_Install_Marketting_fields__c==false){
            PM.FS_Outlet_Dispenser__c=null;
            if(PM.FS_RcdIDForCncl__c==null){            
                PM.FS_RcdIDForCncl__c=PM.id;            
            }
            if(Obj=='Account'){
                String AccountRecType= [SELECT RecordType.Name from Account where id=:recid ].RecordType.Name;
                PM.FS_Installation__c=null;            
                update PM;  
                if(AccountRecType==FSConstants.RECORD_TYPE_NAME_CHAIN){                
                    Database.executeBatch(New FSBatchCopyChaintoHq(recId,Null,PM,null),10);             
                }
                if(AccountRecType==FSConstants.RECORD_TYPE_NAME_HQ){                 
                    Database.executeBatch(New FSBatchCopyHqtoOutlet(recId,NUll,PM,null,null),10);
                }
                if(AccountRecType==FSConstants.RECORD_TYPE_NAME_OUTLET){                
                    Database.executeBatch(New FSBatchCopyOutletToOD(recId,null,PM,null,null),10);
                }   
                
            }
            /*
            if(Obj=='Installation'){ 
                PM.FS_Account__c=null;            
                update PM; 
                Database.executeBatch(New FSBatchCopyInstallToOD (recId,null,PM,null,null),10);
            }*/ 
            FS_Msg_Copy_to_lower_levels__c mc = FS_Msg_Copy_to_lower_levels__c.getValues('Successfully Copied to lower level');
            return mc.FS_Success_Copy_to_Lower_Levels__c;
            
        }
        else{return 'You can not copy already canceled Post Install Marketing record ';}
    }      
    
    webservice static String ChaintoHqValidFill(String recId,String vfid,String Obj)  {
        FS_Valid_Fill__c VF ;
        String qryVF = FSUtil.getSelectQuery('FS_Valid_Fill__c') + ' WHERE Id=:vfid';
        List<FS_Valid_Fill__c> ListVF = (List<FS_Valid_Fill__c>)database.query(qryVF);
        For(FS_Valid_Fill__c VlF:ListVF ){
            VF=VlF;
        }
        if(VF.FS_Cancel_Valid_Fill__c==false){      
            VF.FS_Outlet_Dispenser__c=null;
            if(VF.FS_RcdIDForCncl__c==null){            
                VF.FS_RcdIDForCncl__c=VF.id;            
            }
            if(Obj=='Account'){
                String AccountRecType= [SELECT RecordType.Name from Account where id=:recid ].RecordType.Name;
                VF.FS_Installation__c=null;           
                update VF;      
                if(AccountRecType==FSConstants.RECORD_TYPE_NAME_CHAIN){                
                    Database.executeBatch(New FSBatchCopyChaintoHq(recId,null,null,VF),10);                 
                }
                if(AccountRecType==FSConstants.RECORD_TYPE_NAME_HQ){               
                    Database.executeBatch(New FSBatchCopyHqtoOutlet(recId,null,null,VF,null),10);
                }
                if(AccountRecType==FSConstants.RECORD_TYPE_NAME_OUTLET){               
                    Database.executeBatch(New FSBatchCopyOutletToOD(recId,null,null,VF,null),10);
                }       
            }
            /*if(Obj=='Installation'){
            VF.FS_Outlet__c=null;            
            update VF;
            Database.executeBatch(New FSBatchCopyInstallToOD (recId,null,null,VF,null),10);  
            }*/ 
            FS_Msg_Copy_to_lower_levels__c mc = FS_Msg_Copy_to_lower_levels__c.getValues('Successfully Copied to lower level');
            return mc.FS_Success_Copy_to_Lower_Levels__c;
            
        }
        else{return 'You can not copy already canceled Post Install Valid Fill record'; }      
    }
}