force-app/main/default/objects/Account/fields/FS_Water_Filter_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>FS_Water_Filter_Contact_Name__c</fullName>
    <label>Water Filter Contact Name</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CIF_Header__c/CIF_Header__c.object-meta.xml
<CustomObject>
    <description>CIF Header</description>
    <label>CIF Header</label>
    <nameField>
        <label>CIF Header Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CIF Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CIF_Header__c/fields/FS_FPS__c.field-meta.xml
<CustomField>
    <fullName>FS_FPS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>FPS User</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2 OR 3 OR 4</booleanFilter>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>FS FPS_P</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>FS AC_P</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>FS PM_P</value>
        </filterItems>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>FS Admin PM_P</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>CIF_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CIF_Header__c/fields/FS_HQ__c.field-meta.xml
<CustomField>
    <fullName>FS_HQ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>HQ Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>CIF_Head</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CIF_Header__c/fields/FS_Reparent_CIF__c.field-meta.xml
<CustomField>
    <fullName>FS_Reparent_CIF__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to check whether the CIF is Re-parented.</description>
    <label>Reparent CIF</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CIF_Header__c/fields/FS_Sales_Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>FS_Sales_Rep_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AccountTeamMember__c.AccountId__r.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <filterItems>
            <field>AccountTeamMember__c.AccountId__c</field>
            <operation>equals</operation>
            <valueField>$Source.FS_HQ__c</valueField>
        </filterItems>
        <filterItems>
            <field>AccountTeamMember__c.TeamMemberRole__c</field>
            <operation>equals</operation>
            <value>Sales Team Member</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AccountTeamMember__c</referenceTo>
    <relationshipLabel>CIF Headers</relationshipLabel>
    <relationshipName>CIF_Headers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CIF_Header__c/fields/FS_Status__c.field-meta.xml
<CustomField>
    <fullName>FS_Status__c</fullName>
    <inlineHelpText>In Progress Ã¢â‚¬â€œ CIF is still open or a site assessment is still opens
Closed Ã¢â‚¬â€œ Cancelled or Not Approved Ã¢â‚¬â€œ All outlets are either cancelled or not approved to move forward
Closed Ã¢â‚¬â€œ Converted to EP. The CIF has been converted to an EP and closed</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>SS Submitted</fullName>
            </value>
            <value>
                <fullName>SA Submitted</fullName>
            </value>
            <value>
                <fullName>EP Submitted</fullName>
            </value>
            <value>
                <fullName>SS Approved</fullName>
            </value>
            <value>
                <fullName>SA Approved</fullName>
            </value>
            <value>
                <fullName>EP Created</fullName>
            </value>
            <value>
                <fullName>Closed Ã¢â‚¬â€œ Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed Ã¢â‚¬â€œ Converted to EP</fullName>
            </value>
            <value>
                <fullName>Closed Ã¢â‚¬â€œ Cancelled or Not Approved</fullName>
            </value>
            <value>
                <fullName>Closed Ã¢â‚¬â€œNot Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CIF_Header__c/fields/FSCOM__c.field-meta.xml
<CustomField>
    <fullName>FSCOM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>COM User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AccountTeamMember__c.TeamMemberRole__c</field>
            <operation>equals</operation>
            <value>COM</value>
        </filterItems>
        <filterItems>
            <field>AccountTeamMember__c.AccountId__c</field>
            <operation>equals</operation>
            <valueField>$Source.FS_HQ__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AccountTeamMember__c</referenceTo>
    <relationshipLabel>CIF Headers (COM)</relationshipLabel>
    <relationshipName>CIF_Headers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_CIF__c/FS_CIF__c.object-meta.xml
<CustomObject>
    <label>CIF</label>
    <nameField>
        <label>CIF Outlet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CIF</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_CIF__c/fields/FS_Contractor_Contact__c.field-meta.xml
<CustomField>
    <fullName>FS_Contractor_Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Contractor Contact of Installation</description>
    <label>Contractor Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Contact not found or incomplete.</errorMessage>
        <filterItems>
            <field>Contact.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.FS_Headquarters__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Email</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>Contact.Phone</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>Contact.FS_Contact_Info_Complete__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CIF (Contractor Contact)</relationshipLabel>
    <relationshipName>CIF5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_CIF__c/fields/FS_On_Boarding_Contact__c.field-meta.xml
<CustomField>
    <fullName>FS_On_Boarding_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Select On-Boarding Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.FS_Headquarters__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Email</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>Contact.Phone</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>Contact.FS_Contact_Info_Complete__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CIF (On-Boarding Contact)</relationshipLabel>
    <relationshipName>CIFContact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_CIF__c/fields/FS_Outlet_Contact__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Contact not found or incomplete.</errorMessage>
        <filterItems>
            <field>Contact.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.FS_Headquarters__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.FS_Contact_Info_Complete__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.Email</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>Contact.Phone</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CIF (Outlet Contact)</relationshipLabel>
    <relationshipName>CIF7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_CIF__c/fields/FS_Select_Site_assessment_contact__c.field-meta.xml
<CustomField>
    <fullName>FS_Select_Site_assessment_contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Used to select the Site assessment outlet contact name</description>
    <label>Site Assessment Contact Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Contact not found or incomplete.</errorMessage>
        <filterItems>
            <field>Contact.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.FS_Headquarters__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.FS_Contact_Info_Complete__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Contact.Email</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <filterItems>
            <field>Contact.Phone</field>
            <operation>notEqual</operation>
            <value/>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CIF (Select Site assessment contact)</relationshipLabel>
    <relationshipName>CIFDUjK</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_CIF__c/fields/FS_Training_Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>FS_Training_Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Training Customer Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.FS_Headquarters__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CIF</relationshipLabel>
    <relationshipName>CIF</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_CIF__c/fields/FS_Water_Filter_Contact__c.field-meta.xml
<CustomField>
    <fullName>FS_Water_Filter_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Water Filter Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.FS_Headquarters__c</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>CIF (Water Filter Contact)</relationshipLabel>
    <relationshipName>CIF3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FsCIFReParentTriggerHelper.cls
global class FsCIFReParentTriggerHelper {
    public static Set<Id> CifHeadId = New Set<Id>();
    public static Map<id,id> cifHeaders = new Map<id,id>();
    public static Map<id,id> cifHeadHQMap = new Map<id,id>();
    public static string olAcn;
    public static Set<Id> cifHeadHqIds = new Set<Id>();
    public static Map<Id,String> HQNameMap = new Map<Id,String>();
    public static List<CIF_Header__c> cifHeadListnew = new List<CIF_Header__c>();
    public static set<id> oldcifHeadIds = new set<id>();
    public static List<Account> CifoldHqdetails = new List<Account>();
    public static Map<String,String> notifiBody = new Map<String,String>();
    public static String cifHeadNumstr = '';
    public static String emailSub;
    public static Map<Id,CIF_Header__c> oldCIFHeaderMap = new Map<Id,CIF_Header__c>();
    
    //Method to get the CIF details of the header.
    public static void getCIFdetails(List<CIF_Header__c> cifHeadList, Map<Id,CIF_Header__c> oldCIFHeadMap)
    {
        Datetime hqDT = Datetime.now(); // Returns the current Datetime based on a GMT calendar.
        String hqDate = hqDT.format('YYMMdd'); // formats the date
        String hqTime = hqDT.format('HHmm');
        cifHeadListnew =  cifHeadList;
        oldCIFHeaderMap = oldCIFHeadMap;
        
        //Loop the cifHeader List which is trigger.new , and build a Set with IDs.
        for(CIF_Header__c CifHeadnew: cifHeadList)
        {
            cifHeadHqIds.add(CifHeadnew.FS_HQ__c);
        }
        
        List<Account> CifHqdetails = [select Id,name from Account where Id in :cifHeadHqIds];
        
        for(CIF_Header__c CifHeadnew1: cifHeadList)
        {
            for(Account CifHqdetail: CifHqdetails)
            {
            	If(CifHeadnew1.FS_HQ__c == CifHqdetail.id)   
                HQNameMap.put(CifHeadnew1.id, CifHqdetail.name)  ;  
            }
            oldcifHeadIds.add(oldCIFHeadMap.get(CifHeadnew1.id).FS_HQ__c);
        }
        
        CifoldHqdetails = [select Id,name from Account where Id in :oldcifHeadIds];
        
        for(CIF_Header__c CifHead: cifHeadList)
        {        
            If(CifHead.FS_HQ__c <> oldCIFHeadMap.get(CifHead.id).FS_HQ__c )
            {
                system.debug('new CIF head:' +CifHead);
                CifHead.FSCOM__c=null;
            	CifHead.FS_Sales_Rep_Name__c=null;
                CifHead.FS_FPS__c = null;
                system.debug('HQNameMap' +HQNameMap.get(CifHead.FS_HQ__c));
                CifHead.name = HQNameMap.get(CifHead.id)+'-'+UserInfo.getLastName()+'-'+hqDate+hqTime+'_V.1';
                CifHeadId.add(CifHead.Id);
                If(CifHead.FS_Status__c == 'Closed – Converted to EP')
                {
                 	CifHead.FS_Status__c = 'In Progress';
                    CifHead.FS_Reparent_CIF__c = true;
                }
                //cifHeaders.put(oldCIFHeadMap.get(CifHead.id).FS_HQ__c,CifHead.FS_HQ__c);
                cifHeadHQMap.put(CifHead.id, CifHead.FS_HQ__c);
            }
        }
        
        //Query the CIF object and get all the details for all the cif header Ids.
        List<FS_CIF__c> cifList = [select FS_Contractor_Contact__c, FS_Outlet_Contact__c, FS_On_Boarding_Contact__c, FS_Select_Site_assessment_contact__c,
                        FS_Training_Customer_Contact__c, FS_Water_Filter_Contact__c, FS_Water_Filter_Contact_Name__c,   Water_Filter_Installer_Name__c,
                        FS_Headquarters__c,CIF_Head__c,CIF_Head__r.FSCOM__c,CIF_Head__r.FS_Sales_Rep_Name__c,FS_Order_Administrator__c,FS_Order_Standard_User__c,
                        FS_Account__r.FS_Concatenated_Address__c,FS_Account__r.ShippingStreet,FS_Account__r.ShippingCity,FS_Account__r.ShippingState,
                        FS_Account__r.ShippingPostalCode,FS_Account__r.ShippingCountry,FS_Account__r.FS_ACN__c From FS_CIF__c where CIF_Head__c in :CifHeadId];
        
        //Call updateContacts method which updates the contacts on CIF.
        updateContacts(cifList);
    }
    
    //Method to update the CIF contact fields to null and create a related record to hold old contact values.
    public static void updateContacts(List<FS_CIF__c> cifList)
    {
        String emailBody;
        for(FS_CIF__c cif: cifList)
        {   
            //Make all the CIF contacts empty.
            Cif.FS_Contractor_Contact__c=null;
            Cif.FS_Outlet_Contact__c=null;
            Cif.FS_On_Boarding_Contact__c=null;
            Cif.FS_Select_Site_assessment_contact__c=null;
            Cif.FS_Training_Customer_Contact__c=null;
            Cif.FS_Water_Filter_Contact__c=null;
            Cif.FS_Water_Filter_Contact_Name__c=null;
            Cif.Water_Filter_Installer_Name__c=null;
            cif.FS_Order_Administrator__c=null;
            cif.FS_Order_Standard_User__c=null;
            Cif.CIF_Head__r.FSCOM__c=null;
            Cif.FS_Secondary_Site_Assessment_Contact__c = null;
            Cif.CIF_Head__r.FS_Sales_Rep_Name__c=null;
            Cif.CIF_Head__r.FS_FPS__c = null;
            //Cif.FS_Headquarters__c = cifHeaders.get(Cif.FS_Headquarters__c);
            Cif.FS_Headquarters__c = cifHeadHQMap.get(Cif.CIF_Head__c);
            olAcn = 'Outlet ACN: ' + Cif.FS_Account__r.FS_ACN__c;
            emailBody = Cif.FS_Account__r.ShippingStreet+ Cif.FS_Account__r.ShippingCity +Cif.FS_Account__r.ShippingState+Cif.FS_Account__r.ShippingPostalCode + Cif.FS_Account__r.ShippingCountry+ ' has been recently re-parented to HDQ ' + HQNameMap.get(cifHeadListnew[0].id) + ' from HDQ ' +
                    CifoldHqdetails[0].Name + ' as a result the CIF has been moved.'+
                    ' All previous CIF contacts have been removed since the contacts within the CIF are specific to a HDQ. Please update the CIF with the point of contacts and validate the remaining CIF details. \n' +
                    System.URL.getSalesforceBaseUrl().toExternalForm() + '/apex/FSCustomerInputForm?id='+Cif.CIF_Head__c;
            notifiBody.put(olAcn,emailBody);
        }
        
        //Update the CIF records.
        if(cifList.size()>0){
            update cifList;
        }
        If(cifHeadListnew[0].FS_HQ__c != oldCIFHeaderMap.get(cifHeadListnew[0].id).FS_HQ__c)
        {
            cifHeadNumstr = cifHeadListnew[0].FS_CIF_Number__c;
            emailSub = cifHeadNumstr + ' has been moved for Re-Parented Outlet/s ' ;
            FsCIF_SendEmail_Helper.sendReparentNotif(cifHeadListnew[0],cifHeadNumstr,notifiBody,emailSub);
        }
        
    }
}