force-app/main/default/objects/Account/fields/Is_Default_FET_International_Outlet__c.field-meta.xml
<CustomField>
    <fullName>Is_Default_FET_International_Outlet__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Default INT outlet used to assign the ODs when OD not assigned to actual outlet.</inlineHelpText>
    <label>Is Default FET International Outlet?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dispenser_Model__c/Dispenser_Model__c.object-meta.xml
<CustomObject>
    <label>Dispenser Model</label>
    <nameField>
        <label>Dispenser Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dispenser Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Brand_Set__c.field-meta.xml
<CustomField>
    <fullName>Brand_Set__c</fullName>
    <label>Brand Set</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Warehouse_Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>CAN Default Collection</fullName>
            </value>
            <value>
                <fullName>CAN McDonalds Collection</fullName>
            </value>
            <value>
                <fullName>GER Default Collection</fullName>
            </value>
            <value>
                <fullName>FRA Default Collection</fullName>
            </value>
            <value>
                <fullName>NZ Default Collection</fullName>
            </value>
            <value>
                <fullName>SGP Default Collection</fullName>
            </value>
            <value>
                <fullName>Gandalf GER Collection</fullName>
            </value>
            <value>
                <fullName>Gandalf JAPAN Collection</fullName>
            </value>
            <value>
                <fullName>Bluebird CAN Default</fullName>
            </value>
            <value>
                <fullName>GB Default Collection</fullName>
            </value>
            <value>
                <fullName>LUX Default Collection</fullName>
            </value>
            <value>
                <fullName>BE Default Collection</fullName>
            </value>
            <value>
                <fullName>Ireland Default Collection</fullName>
            </value>
            <value>
                <fullName>TUK Default Collection</fullName>
            </value>
            <value>
                <fullName>Spain Default Collection</fullName>
            </value>
            <value>
                <fullName>Denmark Default Collection</fullName>
            </value>
            <value>
                <fullName>Sweden Default Collection</fullName>
            </value>
            <value>
                <fullName>Netherlands Default Collection</fullName>
            </value>
            <value>
                <fullName>Japan Default Collection</fullName>
            </value>
            <value>
                <fullName>Thailand Default Collection</fullName>
            </value>
            <value>
                <fullName>Philippines Default Collection</fullName>
            </value>
            <value>
                <fullName>Australia Default Collection</fullName>
            </value>
            <value>
                <fullName>Switzerland Default Collection</fullName>
            </value>
            <value>
                <fullName>MA Default Collection</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_IsActive__c.field-meta.xml
<CustomField>
    <fullName>FS_IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>active or inactive</description>
    <label>Active (A) / Inactive (I)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Model__c.field-meta.xml
<CustomField>
    <fullName>FS_Model__c</fullName>
    <inlineHelpText>For International OD&#39;s Platform value is derived from Dispenser Model.</inlineHelpText>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2000</fullName>
            </value>
            <value>
                <fullName>7000</fullName>
            </value>
            <value>
                <fullName>8000</fullName>
            </value>
            <value>
                <fullName>9000</fullName>
            </value>
            <value>
                <fullName>3100</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Serial_Number2__c.field-meta.xml
<CustomField>
    <fullName>FS_Serial_Number2__c</fullName>
    <description>Serial Number/Asset Tag.</description>
    <label>JDE Serial Number/Asset Tag</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FSInt_Dispenser_Type__c.field-meta.xml
<CustomField>
    <fullName>FSInt_Dispenser_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dispenser Model</label>
    <referenceTo>Dispenser_Model__c</referenceTo>
    <relationshipLabel>Outlet Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Shipping_Form__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Form__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Form</label>
    <referenceTo>Shipping_Form__c</referenceTo>
    <relationshipLabel>Outlet Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Warehouse_Country__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Country__c</fullName>
    <label>â€‹Warehouse Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>Luxembourg</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>Netherlands</fullName>
            </value>
            <value>
                <fullName>New Zealand</fullName>
            </value>
            <value>
                <fullName>Philippines</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>Sweden</fullName>
            </value>
            <value>
                <fullName>Switzerland</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Warehouse_Name__c.field-meta.xml
<CustomField>
    <fullName>Warehouse_Name__c</fullName>
    <label>Warehouse Name</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Warehouse_Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Chatham</fullName>
            </value>
            <value>
                <fullName>Regina</fullName>
            </value>
            <value>
                <fullName>LÃ¢â‚¬â„¢Assomption</fullName>
            </value>
            <value>
                <fullName>Daventry</fullName>
            </value>
            <value>
                <fullName>London Colney</fullName>
            </value>
            <value>
                <fullName>United Kingdom #3</fullName>
            </value>
            <value>
                <fullName>Hamm</fullName>
            </value>
            <value>
                <fullName>Hamburg</fullName>
            </value>
            <value>
                <fullName>Mainz</fullName>
            </value>
            <value>
                <fullName>LES ULIS</fullName>
            </value>
            <value>
                <fullName>France #2</fullName>
            </value>
            <value>
                <fullName>France #3</fullName>
            </value>
            <value>
                <fullName>Singapore #1</fullName>
            </value>
            <value>
                <fullName>Singapore #2</fullName>
            </value>
            <value>
                <fullName>Singapore #3</fullName>
            </value>
            <value>
                <fullName>New Zealand #1</fullName>
            </value>
            <value>
                <fullName>New Zealand #2</fullName>
            </value>
            <value>
                <fullName>New Zealand #3</fullName>
            </value>
            <value>
                <fullName>Luxembourg #1</fullName>
            </value>
            <value>
                <fullName>Londerzeel Belgium</fullName>
            </value>
            <value>
                <fullName>CBS, Omagh.</fullName>
            </value>
            <value>
                <fullName>Madrid</fullName>
            </value>
            <value>
                <fullName>Spain #2</fullName>
            </value>
            <value>
                <fullName>Spain #3</fullName>
            </value>
            <value>
                <fullName>Denmark #1</fullName>
            </value>
            <value>
                <fullName>Denmark #2</fullName>
            </value>
            <value>
                <fullName>Denmark #3</fullName>
            </value>
            <value>
                <fullName>Jordbro Warehouse</fullName>
            </value>
            <value>
                <fullName>SkÃƒÂ¤rholmen TVS</fullName>
            </value>
            <value>
                <fullName>Sweden #3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipping_Form__c/Shipping_Form__c.object-meta.xml
<CustomObject>
    <label>Shipping Form</label>
    <nameField>
        <label>Shipping Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shipping Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Dispenser_Country__c.field-meta.xml
<CustomField>
    <fullName>Dispenser_Country__c</fullName>
    <label>Dispenser Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>NZ</fullName>
            </value>
            <value>
                <fullName>SG</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>GB</fullName>
            </value>
            <value>
                <fullName>IE</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>JP</fullName>
            </value>
            <value>
                <fullName>TR</fullName>
            </value>
            <value>
                <fullName>LU</fullName>
            </value>
            <value>
                <fullName>TH</fullName>
            </value>
            <value>
                <fullName>PH</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FETIntDefaultAccountControllerTest.cls
/**
* This class contains unit tests for validating the behavior of Apex classes
* and triggers.
*
* Unit tests are class methods that verify whether a particular piece
* of code is working properly. Unit test methods take no arguments,
* commit no data to the database, and are flagged with the testMethod
* keyword in the method definition.
*
* All test methods in an organization are executed whenever Apex code is deployed
* to a production organization to confirm correctness, ensure code
* coverage, and prevent regressions. All Apex classes are
* required to have at least 75% code coverage in order to be deployed
* to a production organization. In addition, all triggers must have some code coverage.
* 
* The @isTest class annotation indicates this class only contains test
* methods. Classes defined with the @isTest annotation do not count against
* the organization size limit for all Apex scripts.
*
* See the Apex Language Reference for more information about Testing and Code Coverage.
*/
@isTest
private class FETIntDefaultAccountControllerTest {
    public static Shipping_Form__c shippingForm;
    public static Dispenser_Model__c dispenserModel;
    public static User coordinatorUser;
    public static Account headquartersAcc, acc, normalAcc;
    public static final string ONE='1';
    private static testMethod void myUnitTest() {
        Test.startTest();
        
        coordinatorUser = FSTestUtil.createUser(null,1,FSConstants.dispenserCoordinatorProfile,false);
        coordinatorUser.Dispenser_Country__c = 'GB';
        insert coordinatorUser;          
        system.runAs(coordinatorUser){  
            shippingForm = FSTestUtil.createShippingForm(true);
            headquartersAcc = FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,true);
            acc = FSTestUtil.createAccountOutlet(FSConstants.defaultOutletName,FSConstants.RECORD_TYPE_OUTLET,headquartersAcc.id,false);                
            acc.Is_Default_FET_International_Outlet__c=true;
            insert acc;
            system.debug('hq acc : ' + headquartersAcc +  ' acc : ' + acc); 
            normalAcc = FSTestUtil.createAccountOutlet('Test Outlet 1',FSConstants.RECORD_TYPE_OUTLET,headquartersAcc.id, true);
        }
        dispenserModel = FSTestUtil.createDispenserModel(true, '2000');
        ApexPages.currentPage().getParameters().put('sfdc.override',ONE);
        ApexPages.currentPage().getParameters().put('scontrolCaching',ONE);
        ApexPages.currentPage().getParameters().put('save_new',ONE);
        
        system.runAs(coordinatorUser){                 
            final FS_Outlet_Dispenser__c outletDispenserInt1 = FSTestUtil.createOutletDispenserAllTypes(Label.INT_OD_RECORD_TYPE,null,acc.id,null,false);
            //outletDispenserInt1.FS_Model__c = '7000';        
            outletDispenserInt1.Shipping_Form__c = shippingForm.id;
            outletDispenserInt1.FSInt_Dispenser_Type__c = dispenserModel.id;
            outletDispenserInt1.FS_Serial_Number2__c = 'TEST_7687';
            outletDispenserInt1.Warehouse_Country__c = 'New Zealand';
            outletDispenserInt1.Warehouse_Name__c = 'New Zealand #1';
            outletDispenserInt1.Brand_Set__c = 'NZ Default Collection';
            outletDispenserInt1.FS_IsActive__c = true;
            
            
            final ApexPages.StandardController stdCont = new ApexPages.StandardController(outletDispenserInt1);
            final FETIntDefaultAccountController defaultController = new FETIntDefaultAccountController(stdCont);
            defaultController.setOutletAccountDefault();
            ApexPages.currentPage().getParameters().put('sfdc.override',ONE);
            ApexPages.currentPage().getParameters().put('scontrolCaching',ONE);
            ApexPages.currentPage().getParameters().put('save_new',ONE);
            
            final FS_Outlet_Dispenser__c outletDispenserInt = FSTestUtil.createOutletDispenserAllTypes(FSConstants.RT_NAME_CCNA_OD,null,normalAcc.id,null,false);
            final ApexPages.StandardController stdCont1 = new ApexPages.StandardController(outletDispenserInt);
            final FETIntDefaultAccountController defaultController1 = new FETIntDefaultAccountController(stdCont1);
            defaultController1.setOutletAccountDefault();
            //insert outletDispenserInt1;
            //system.assertNotEquals(outletDispenserInt1.Id, null);
        }
        
        Test.stopTest();
    }
}