force-app/main/default/objects/AccountTeamMember__c/AccountTeamMember__c.object-meta.xml
<CustomObject>
    <label>Account Team Member</label>
    <nameField>
        <displayFormat>AT-{0000}</displayFormat>
        <label>AccountTeamMember Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountTeamMember__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>AccountId</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Team Members</relationshipLabel>
    <relationshipName>AccountTeamMembers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountTeamMember__c/fields/TeamMemberRole__c.field-meta.xml
<CustomField>
    <fullName>TeamMemberRole__c</fullName>
    <label>Team Member Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>COM</fullName>
            </value>
            <value>
                <fullName>COM Backup</fullName>
            </value>
            <value>
                <fullName>JCOM</fullName>
            </value>
            <value>
                <fullName>Sales Team Member</fullName>
            </value>
            <value>
                <fullName>PM</fullName>
            </value>
            <value>
                <fullName>PIC</fullName>
            </value>
            <value>
                <fullName>Sales Support</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>SME</fullName>
            </value>
            <value>
                <fullName>FDC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountTeamMember__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team Member</label>
    <referenceTo>User</referenceTo>
    <relationshipName>AccountTeamMembers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Temp_Chain_Account__c/Temp_Chain_Account__c.object-meta.xml
<CustomObject>
    <label>Temp Chain Account</label>
    <nameField>
        <label>Temp Chain Account Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Temp Chain Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FSUpdateAccntTeamMemHeirarchyBatchITest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 *
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class FSUpdateAccntTeamMemHeirarchyBatchITest {
  static User tuser;
  static Account HeadQuarterAcc;
  static Account outletAcc;

  static testMethod void myUnitTest() {  
  
    try{
    tuser = FSTestUtil.createUser(null,0,FSConstants.USER_POFILE_FETADMIN,true);
    }
    catch(Exception Ex){
    }

      HeadQuarterAcc = FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,true);

      outletAcc = FSTestUtil.createAccountOutlet('Test Outlet 1',FSConstants.RECORD_TYPE_OUTLET,HeadQuarterAcc.id, true);
       // Create some test merchandise items to be deleted
       //   by the batch job.
       Temp_Chain_Account__c tempChain =new Temp_Chain_Account__c(Name=String.valueOf(HeadQuarterAcc.Id));
       insert tempChain;
       
       
       List<AccountTeamMember__c> atmList = new List<AccountTeamMember__c>();
       for (Integer i=0;i<10;i++) {
           AccountTeamMember__c member = new AccountTeamMember__c(
               AccountId__c= HeadQuarterAcc.Id,
               TeamMemberRole__c='Test Role',
               UserId__c= tuser.Id);
           atmList.add(member);
       }
       insert atmList;

        atmList = new List<AccountTeamMember__c>();
       for (Integer i=0;i<10;i++) {
           AccountTeamMember__c member = new AccountTeamMember__c(
               AccountId__c= outletAcc.Id,
               TeamMemberRole__c='Test Role',
               UserId__c= tuser.Id);
           atmList.add(member);
       }
       insert atmList;
       Test.startTest();
       FSUpdateAccountTeamMemberHeirarchyBatchI batchHierarchy = new FSUpdateAccountTeamMemberHeirarchyBatchI();
       Database.executeBatch(batchHierarchy);
       Test.stopTest();

  }
  
  static testMethod void FSUpdateAccntTeamMemHeirarchyBatchTest(){
       Test.startTest();
        String CRON_EXP = '0 0 23 * * ?';
            FSAccountTeamMemberHeirarchyScheduler  scheObj = new FSAccountTeamMemberHeirarchyScheduler();
            system.schedule('Account Team Member Sharing', CRON_EXP, scheObj);
       Test.stopTest();
    
  }
}