force-app/main/default/objects/Dispenser_Model__c/Dispenser_Model__c.object-meta.xml
<CustomObject>
    <label>Dispenser Model</label>
    <nameField>
        <label>Dispenser Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dispenser Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Selling_Activity__c/Selling_Activity__c.object-meta.xml
<CustomObject>
    <description>Selling Activities are presales requests to open up a market prior to the Market Activation Date. The Market Activation date is stored in a separate object called the Selling Activity Market object. These two object combine to create the Selling Activities tool.</description>
    <label>Selling Activity</label>
    <nameField>
        <displayFormat>SA-{00000000}</displayFormat>
        <label>Selling Activity Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Selling Activities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Selling_Activity__c/fields/Average_Dispenser__c.field-meta.xml
<CustomField>
    <fullName>Average_Dispenser__c</fullName>
    <label>Average Dispenser #</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Selling_Activity__c/fields/Disp_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Disp_Configuration__c</fullName>
    <label>Disp. Configuration</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Drip Tray/Standard Splash plate/Legs</fullName>
            </value>
            <value>
                <fullName>Extended Splash plate no legs</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Selling_Activity__c/fields/Dispenser_Model__c.field-meta.xml
<CustomField>
    <fullName>Dispenser_Model__c</fullName>
    <label>Dispenser Model</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>7000 series</fullName>
            </value>
            <value>
                <fullName>8000/9000 Series</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Selling_Activity__c/fields/FS_Headquarter__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Headquarter</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Selling Activity</relationshipLabel>
    <relationshipName>Selling_Activity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Selling_Activity__c/fields/FS_Of_Outlets_For_Launch__c.field-meta.xml
<CustomField>
    <fullName>FS_Of_Outlets_For_Launch__c</fullName>
    <label># Of Outlets For Launch</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Selling_Activity__c/fields/Market_Name__c.field-meta.xml
<CustomField>
    <fullName>Market_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Market Name</label>
    <referenceTo>Selling_Activity_Market__c</referenceTo>
    <relationshipLabel>Selling Acitvities</relationshipLabel>
    <relationshipName>Selling_Acitvities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Selling_Activity__c/fields/Requested_Accelerated_Market_Activation__c.field-meta.xml
<CustomField>
    <fullName>Requested_Accelerated_Market_Activation__c</fullName>
    <label>Requested Accelerated Market Activation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Selling_Activity__c/fields/Selling_Status__c.field-meta.xml
<CustomField>
    <fullName>Selling_Status__c</fullName>
    <label>Selling Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pre-sold</fullName>
            </value>
            <value>
                <fullName>Presented</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Activity Moved to installation Process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Selling_Activity_Market__c/Selling_Activity_Market__c.object-meta.xml
<CustomObject>
    <label>Selling Activity Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selling Activity Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Selling_Activity_Market__c/fields/Dispenser_Model__c.field-meta.xml
<CustomField>
    <fullName>Dispenser_Model__c</fullName>
    <label>Platform Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Selling_Activity_Market__c/fields/Market_Activation_Date__c.field-meta.xml
<CustomField>
    <fullName>Market_Activation_Date__c</fullName>
    <label>Market Activation Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/Platform_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3100</fullName>
    </customValue>
    <customValue>
        <fullName>6000</fullName>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
    </customValue>
    <customValue>
        <fullName>7100</fullName>
    </customValue>
    <customValue>
        <fullName>8000</fullName>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
    </customValue>
    <masterLabel>Platform Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FSCreateSellingActivityExtension_Test.cls
@isTest
private class FSCreateSellingActivityExtension_Test{    
    
    static testMethod void testPageControllerFunctionality(){
        Account accHeadQtr1 = FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,true);
        String soql = 'SELECT Id, Name FROM Selling_Activity_Market__c WHERE Name != null';
        Selling_Activity_Market__c marketActivityObject = new Selling_Activity_Market__c();
        marketActivityObject.Name='test';
        marketActivityObject.Dispenser_Model__c='7000';
        marketActivityObject.Market_Activation_Date__c = System.today().addDays(4);
        insert marketActivityObject;
        Selling_Activity__c activityObject=new Selling_Activity__c();
        activityObject.Market_Name__c = marketActivityObject.Id;
        activityObject.FS_Of_Outlets_For_Launch__c=10;
        activityObject.Disp_Configuration__c='Extended Splash plate no legs';
        activityObject.Average_Dispenser__c = 10;
        activityObject.FS_Headquarter__c=accHeadQtr1.Id;
        activityObject.Selling_Status__c='Pre-sold';
        activityObject.Requested_Accelerated_Market_Activation__c=System.today().addDays(2);
        insert activityObject;
        List<SelectOption> myList=new List<SelectOption>();
        myList.add(new SelectOption(activityObject.Market_Name__c, marketActivityObject.Name));
        Test.startTest();
        Apexpages.Standardcontroller stdCntrl = new Apexpages.Standardcontroller(activityObject);
        Apexpages.currentPage().getParameters().put('CF00Ne0000001CjE5_lkid', accHeadQtr1.Id);
        Apexpages.currentPage().getParameters().put(Label.FS_Selling_Acitvitys_Account_ID, accHeadQtr1.Id);
        
        Apexpages.currentPage().getParameters().put('firstname',marketActivityObject.Name);
        
        FSCreateSellingActivityExtension controller = new FSCreateSellingActivityExtension(stdCntrl);
        controller.dispenserVal='7000';
		controller.marketVal=marketActivityObject.Id;
        controller.populateMarket();
        controller.selectedFields=myList;
        controller.addMarket();
        controller.saveRecord();
        PageReference pr=controller.saveCloseRecord();
        //System.assert(pr!=null);
        
        controller.recordIndex='0.';
       controller.deleteRecord();
        pr=controller.cancelRecord();
        System.assert(pr!=null);

        Test.stopTest();
    }
    
    static testMethod void testCreateSellingActivity(){
        Account accHeadQtr1 = FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,true);
        String soql = 'SELECT Id, Name FROM Selling_Activity_Market__c WHERE Name != null';
        Selling_Activity_Market__c marketActivityObject = new Selling_Activity_Market__c();
        marketActivityObject.Name='test';
        marketActivityObject.Dispenser_Model__c='7000';
        marketActivityObject.Market_Activation_Date__c = System.today().addDays(4);
        insert marketActivityObject;
        Selling_Activity__c activityObject=new Selling_Activity__c();
        activityObject.Market_Name__c = marketActivityObject.Id;
        activityObject.FS_Of_Outlets_For_Launch__c=10;
        activityObject.Disp_Configuration__c='Extended Splash plate no legs';
        activityObject.Average_Dispenser__c = null;
        activityObject.FS_Headquarter__c=accHeadQtr1.Id;
        activityObject.Selling_Status__c='Pre-sold';
        activityObject.Requested_Accelerated_Market_Activation__c=System.today().addDays(2);
        insert activityObject;
        List<SelectOption> myList=new List<SelectOption>();
        myList.add(new SelectOption(activityObject.Market_Name__c, marketActivityObject.Name));
        Test.startTest();
        Apexpages.Standardcontroller stdCntrl = new Apexpages.Standardcontroller(activityObject);
        Apexpages.currentPage().getParameters().put('CF00Ne0000001CjE5_lkid', accHeadQtr1.Id);
        Apexpages.currentPage().getParameters().put(Label.FS_Selling_Acitvitys_Account_ID, accHeadQtr1.Id);
        
        Apexpages.currentPage().getParameters().put('firstname',marketActivityObject.Name);
        
        FSCreateSellingActivityExtension controller = new FSCreateSellingActivityExtension(stdCntrl);
        controller.dispenserVal='7000';
        controller.marketVal=marketActivityObject.Id;

        Boolean isValid = controller.validateSellingActivity();
        
        activityObject.Disp_Configuration__c=null;
        activityObject.Average_Dispenser__c = 10;
        
        update activityObject;
        stdCntrl = new Apexpages.Standardcontroller(activityObject);
        
        controller = new FSCreateSellingActivityExtension(stdCntrl);
        controller.dispenserVal='7000';
        controller.marketVal=marketActivityObject.Id;
        
        isValid = controller.validateSellingActivity();
        
        activityObject.Selling_Status__c=null;
        activityObject.Disp_Configuration__c='Extended Splash plate no legs';
        
        update activityObject;
        stdCntrl = new Apexpages.Standardcontroller(activityObject);
        
        controller = new FSCreateSellingActivityExtension(stdCntrl);
        controller.dispenserVal='7000';
        controller.marketVal=marketActivityObject.Id;
        
        isValid = controller.validateSellingActivity();        
        
        controller.runQuery(soql);
        System.assertNotEquals(controller.marketOptions.size(),0);
        System.assertNotEquals(controller.allFields.size(),0);
        System.assertNotEquals(controller.avaliableFields.size(),0);
        
        Pagereference pr = controller.runSearch();
        System.assertEquals(null, pr);
        
        
        
        Test.stopTest();
    }
}