force-app/main/default/objects/Dispenser_Model__c/Dispenser_Model__c.object-meta.xml
<CustomObject>
    <label>Dispenser Model</label>
    <nameField>
        <label>Dispenser Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dispenser Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dispenser_Model__c/fields/Dispenser_Type1__c.field-meta.xml
<CustomField>
    <fullName>Dispenser_Type1__c</fullName>
    <label>Dispenser Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Self Serve</fullName>
            </value>
            <value>
                <fullName>Crew Serve</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dispenser_Model__c/fields/Dispenser_Type__c.field-meta.xml
<CustomField>
    <fullName>Dispenser_Type__c</fullName>
    <label>Equipment Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Dispenser_Type2__c.field-meta.xml
<CustomField>
    <fullName>FS_Dispenser_Type2__c</fullName>
    <inlineHelpText>For International OD&#39;s Dispenser Type value is derived from Dispenser Model.</inlineHelpText>
    <label>Dispenser Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Self Serve</fullName>
            </value>
            <value>
                <fullName>Crew Serve</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Equip_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Equip_Type__c</fullName>
    <description>equip type</description>
    <inlineHelpText>This is the JDE Equipment Type value</inlineHelpText>
    <label>Equipment Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_IsActive__c.field-meta.xml
<CustomField>
    <fullName>FS_IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>active or inactive</description>
    <label>Active (A) / Inactive (I)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FSInt_Dispenser_Type__c.field-meta.xml
<CustomField>
    <fullName>FSInt_Dispenser_Type__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dispenser Model</label>
    <referenceTo>Dispenser_Model__c</referenceTo>
    <relationshipLabel>Outlet Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FsUpdateODofDispModelBatch.cls
global class FsUpdateODofDispModelBatch implements Database.batchable <sobject>,Database.AllowsCallouts {
    
    public  String recTypeODInternational=Schema.SObjectType.FS_Outlet_Dispenser__c.getRecordTypeInfosByName().get(Label.INT_OD_RECORD_TYPE).getRecordTypeId();
    
    Map<Id,Dispenser_Model__c> dispModelMap = new Map<Id,Dispenser_Model__c>();
        
    /****************************************************************************
//Constructor
/***************************************************************************/
    global FsUpdateODofDispModelBatch(final Map<Id,Dispenser_Model__c> dispModelMap){
        this.dispModelMap=dispModelMap;
    }    
    
    /****************************************************************************
//Start the batch and query
/***************************************************************************/
    global Database.QueryLocator start(final Database.BatchableContext batchContext){
        return Database.getQueryLocator([SELECT ID,FS_IsActive__c,FS_Equip_Type__c,FS_Dispenser_Type2__c,FSInt_Dispenser_Type__c FROM FS_Outlet_Dispenser__c 
                                         WHERE RecordtypeID =:recTypeODInternational and FSInt_Dispenser_Type__c!=null and FSInt_Dispenser_Type__c IN :dispModelMap.keySet()]);       
    }
    
    /****************************************************************************
//Process batch
/***************************************************************************/
    
    global void execute(final Database.BatchableContext batchContext, final List<sObject> scope){
        
        List<FS_Outlet_Dispenser__c> dispenserToUpdate=new List<FS_Outlet_Dispenser__c>();
        set<id> dispenserIds =new set<id>();
        Map<id,FS_Outlet_Dispenser__c> dispenserToUpdateMap= new Map<id,FS_Outlet_Dispenser__c>();
        
        for( FS_Outlet_Dispenser__c outletDispenser : (List<FS_Outlet_Dispenser__c>)scope){
            if(dispModelMap.containskey(outletDispenser.FSInt_Dispenser_Type__c)){
                outletDispenser.FS_Equip_Type__c=dispModelMap.get(outletDispenser.FSInt_Dispenser_Type__c).Dispenser_Type__c;
                outletDispenser.FS_Dispenser_Type2__c=dispModelMap.get(outletDispenser.FSInt_Dispenser_Type__c).Dispenser_Type1__c;
                dispenserToUpdateMap.put(outletDispenser.Id,outletDispenser);
                if(outletDispenser.FS_IsActive__c){
                    dispenserIds.add(outletDispenser.id);
                }
            }
        }
        
        FSFETNMSConnector.isUpdateSAPIDBatchChange = true;
        FSFETNMSConnector.airWatchSynchronousCall(dispenserIds,null); 
        
        if(dispenserToUpdateMap!=null && !dispenserToUpdateMap.isEmpty()){
            final Database.SaveResult [] updateODResult= Database.update(dispenserToUpdateMap.values(),false);
        }
    }
    
    /****************************************************************************
//finish the batch
/***************************************************************************/
    
    global void finish(final Database.BatchableContext info){   
        
    } 
    
}