force-app/main/default/objects/Dispenser_Model__c/Dispenser_Model__c.object-meta.xml
<CustomObject>
    <label>Dispenser Model</label>
    <nameField>
        <label>Dispenser Model Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dispenser Models</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dispenser_Model__c/fields/Dispenser_Type1__c.field-meta.xml
<CustomField>
    <fullName>Dispenser_Type1__c</fullName>
    <label>Dispenser Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Self Serve</fullName>
            </value>
            <value>
                <fullName>Crew Serve</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dispenser_Model__c/fields/Dispenser_Type__c.field-meta.xml
<CustomField>
    <fullName>Dispenser_Type__c</fullName>
    <label>Equipment Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FSDispenserModelTriggerHandler.cls
/******************************************************************************************
*  Purpose : FSDispenserModelTriggerHandler class to perform updates on International Outlet Dispenser when corresponding Dispenser Model Values are updated.
*  Author  : Lavanya Valluru
*  Date    : November 02, 2016
*******************************************************************************************/ 
public class FSDispenserModelTriggerHandler {
    
    public static void updateOD(Map<Id,Dispenser_Model__c> oldMapDM, Map<Id,Dispenser_Model__c> newMapDM){      
        Map<Id,Dispenser_Model__c> toUpdateODMap = new Map<Id,Dispenser_Model__c>();    
        
        for(Dispenser_Model__c dispModel:newMapDM.values()){
            if(oldMapDM.containsKey(dispModel.id) 
               && (dispModel.Dispenser_Type__c!=oldMapDM.get(dispModel.id).Dispenser_Type__c 
                   || dispModel.Dispenser_Type1__c!=oldMapDM.get(dispModel.id).Dispenser_Type1__c)){
                       toUpdateODMap.put(dispModel.id,dispModel);
                   }
        }
        database.executebatch(new FsUpdateODofDispModelBatch(toUpdateODMap),100);
        
    }
}