force-app/main/default/objects/FS_Post_Install_Marketing__c/FS_Post_Install_Marketing__c.object-meta.xml
<CustomObject>
    <label>Post Install Marketing</label>
    <nameField>
        <displayFormat>PIM-{0000}</displayFormat>
        <label>Post Install Marketing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Post Install Marketing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Post_Install_Marketing__c/fields/FS_Account__c.field-meta.xml
<CustomField>
    <fullName>FS_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Post Install Marketing</relationshipLabel>
    <relationshipName>Post_Install_Marketing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FSCopytoLower_Cancel_PIM_Extension.cls
public class FSCopytoLower_Cancel_PIM_Extension {
    
    public String pimId {get; set;}
    public String accId {get; set;}
    public Integer pimCount {get; set;}
    
    
    public FSCopytoLower_Cancel_PIM_Extension(ApexPages.StandardSetController controller){        
        
        List<FS_Post_Install_Marketing__c> listPIM = (List<FS_Post_Install_Marketing__c>)controller.getSelected();
        pimCount=listPIM.size();
        
        for(FS_Post_Install_Marketing__c pim:listPIM){
            PIMId=pim.id;
        }  
        for(FS_Post_Install_Marketing__c pim: [select id,FS_Account__c from FS_Post_Install_Marketing__c where id=:PIMId]){
            accid=pim.FS_Account__c;
        }              
    } 
}