force-app/main/default/objects/FS_Post_Install_Marketing__c/FS_Post_Install_Marketing__c.object-meta.xml
<CustomObject>
    <label>Post Install Marketing</label>
    <nameField>
        <displayFormat>PIM-{0000}</displayFormat>
        <label>Post Install Marketing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Post Install Marketing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Post_Install_Marketing__c/fields/FS_Account__c.field-meta.xml
<CustomField>
    <fullName>FS_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Post Install Marketing</relationshipLabel>
    <relationshipName>Post_Install_Marketing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Post_Install_Marketing__c/fields/FS_Enable_CE_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Enable_CE_Effective_Date__c</fullName>
    <label>FET Enable CE Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Post_Install_Marketing__c/fields/FS_Enable_Consumer_Engagement__c.field-meta.xml
<CustomField>
    <fullName>FS_Enable_Consumer_Engagement__c</fullName>
    <label>FET Enable Consumer Engagement</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FSCopytoLower_Cancel_PIM_ExtensionTest.cls
@isTest
public class FSCopytoLower_Cancel_PIM_ExtensionTest {
    private static Account headquartersAcc,outletAcc;
    Private static FS_Post_Install_Marketing__c pim;
    
    public static testMethod void createtestData(){
        //HQ Record
        headquartersAcc = FSTestUtil.createTestAccount('Test Headquarters',FSConstants.RECORD_TYPE_HQ,false);
        insert headquartersAcc;
        
        //PIM Record under HQ
        List<FS_Post_Install_Marketing__c> listPim = new List<FS_Post_Install_Marketing__c>();
        pim=new FS_Post_Install_Marketing__c();
        pim.FS_Account__c=headquartersAcc.id;
        pim.FS_Enable_Consumer_Engagement__c='Yes';
        pim.FS_Enable_CE_Effective_Date__c=System.today()+1;
        listPim.add(pim);        
        insert listpim;
        
        test.startTest();
        ApexPages.PageReference myVfPage = Page.FSCopytoLowerPIM;
        test.setCurrentPage(myVfPage);
        ApexPages.standardSetController sc = new ApexPages.standardSetController(listpim);
        sc.setSelected(listpim);
        sc.getSelected();
        final FSCopytoLower_Cancel_PIM_Extension controller= new FSCopytoLower_Cancel_PIM_Extension(sc);
        
        test.stopTest();
        
    }
}