force-app/main/default/objects/FS_OD_Show_Hide__c/FS_OD_Show_Hide__c.object-meta.xml
<CustomObject>
    <label>Show/ Hide</label>
    <nameField>
        <label>Show/ Hide Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ShowHide</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_OD_Show_Hide__c/fields/beverage_id__c.field-meta.xml
<CustomField>
    <fullName>beverage_id__c</fullName>
    <label>Beverage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_OD_Show_Hide__c/fields/FS_ODRecID__c.field-meta.xml
<CustomField>
    <fullName>FS_ODRecID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ODRecID</label>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipLabel>ShowHide</relationshipLabel>
    <relationshipName>ODRecID</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_OD_Show_Hide__c/fields/show_hide_setting__c.field-meta.xml
<CustomField>
    <fullName>show_hide_setting__c</fullName>
    <label>Show/Hide</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Show</fullName>
            </value>
            <value>
                <fullName>Hide</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FOT_ShowHideController.cls
public class FOT_ShowHideController {
    public static final String MEDIUM ='Medium';
	
    /*****************************************************************
	Method: ShowHideRecordDetails
	Description: ShowHideDetails method is to get OD setting record details associated to OD.
	Added as part of FOT
	*********************************/
    @AuraEnabled
    public static List<FS_OD_Show_Hide__c> ShowHideRecordDetails(id recordId){
        
        final id showHideId; 
		List<FS_OD_Show_Hide__c> showHideRec= new List<FS_OD_Show_Hide__c>();
        try
        {
            if(recordId!=null)
            {
                showHideRec = [Select id,beverage_id__c,show_hide_setting__c,Name,FS_ODRecID__c from FS_OD_Show_Hide__c where FS_ODRecID__c =: recordId];
            } 
        }
        catch(QueryException e){ApexErrorLogger.addApexErrorLog('FOT', 'FOT_ShowHideController', 'ShowHideRecordDetails', 'FS_OD_Show_Hide__c',MEDIUM, e,e.getMessage());      }
        return showHideRec;
    }
    
     /*****************************************************************
	Method: userProfileAccess
	Description: userProfileAccess method is to get logged-in user's profile name.
	Added as part of FOT
	*********************************/
    @AuraEnabled
    public static string userProfileAccess(){
        User usr=[select profile.name from user where id=:userinfo.getUserId()];
        return usr.profile.name;
    }
}