force-app/main/default/objects/FS_Artifact__c/FS_Artifact__c.object-meta.xml
<CustomObject>
    <description>Artifact</description>
    <label>Artifact</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Artifacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Artifact__c/fields/DependancyBreakVersion__c.field-meta.xml
<CustomField>
    <fullName>DependancyBreakVersion__c</fullName>
    <label>Dependency Break Version</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Artifact__c/fields/FS_Artifact_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Artifact_Type__c</fullName>
    <description>Artifact Type</description>
    <label>Artifact Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bundle</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Settings</fullName>
            </value>
            <value>
                <fullName>RoundingRules</fullName>
            </value>
            <value>
                <fullName>CUI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Artifact__c/fields/FS_Dependency_Artifact_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Dependency_Artifact_Type__c</fullName>
    <description>Dependency Artifact Type</description>
    <label>Dependency Artifact Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bundle</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Settings</fullName>
            </value>
            <value>
                <fullName>RoundingRules</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Artifact__c/fields/FS_Dependency_M_in_Version__c.field-meta.xml
<CustomField>
    <fullName>FS_Dependency_M_in_Version__c</fullName>
    <description>DependencyMinVersion</description>
    <label>Dependency Minimum Version</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Artifact__c/fields/FS_Deployment_Group_Rule__c.field-meta.xml
<CustomField>
    <fullName>FS_Deployment_Group_Rule__c</fullName>
    <label>Deployment Group Rule</label>
    <length>4048</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FS_Artifact__c/fields/FS_Enabled__c.field-meta.xml
<CustomField>
    <fullName>FS_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enabled</description>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Artifact__c/fields/FS_Overide_Group_Rule__c.field-meta.xml
<CustomField>
    <fullName>FS_Overide_Group_Rule__c</fullName>
    <label>Override Rule</label>
    <length>4048</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FS_Artifact__c/fields/FS_Rank__c.field-meta.xml
<CustomField>
    <fullName>FS_Rank__c</fullName>
    <description>Rank</description>
    <label>Rank</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FS_Artifact__c/fields/FS_Rule__c.field-meta.xml
<CustomField>
    <fullName>FS_Rule__c</fullName>
    <description>Rule</description>
    <label>Rule</label>
    <length>4048</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FS_Artifact__c/fields/FS_Ruleset__c.field-meta.xml
<CustomField>
    <fullName>FS_Ruleset__c</fullName>
    <label>Rule Set</label>
    <referenceTo>FS_Artifact_Ruleset__c</referenceTo>
    <relationshipLabel>Artifacts</relationshipLabel>
    <relationshipName>Artifacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Artifact__c/fields/FS_S3Path__c.field-meta.xml
<CustomField>
    <fullName>FS_S3Path__c</fullName>
    <description>S3Path</description>
    <label>S3 Path</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FS_Artifact__c/fields/FS_UUID__c.field-meta.xml
<CustomField>
    <fullName>FS_UUID__c</fullName>
    <description>UUId</description>
    <label>UUID</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Artifact__c/fields/FS_Version__c.field-meta.xml
<CustomField>
    <fullName>FS_Version__c</fullName>
    <description>version</description>
    <label>Version</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Artifact__c/fields/Settings_Update__c.field-meta.xml
<CustomField>
    <fullName>Settings_Update__c</fullName>
    <label>Settings Update</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FS_Artifact_Ruleset__c/FS_Artifact_Ruleset__c.object-meta.xml
<CustomObject>
    <label>Artifact Ruleset</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rulesets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FOT_RawContentWrapper.cls
/*******************************************************************
	Class: FOT_RawContentWrapper
	Description: FOT_RawContentWrapper is a Wrapper class for A5 API input.
	Added as part of FOT
	*********************************/
public class FOT_RawContentWrapper {
    
    public ArtifactValues artifact{get;set;}
    public FOT_RawContentWrapper(FS_Artifact__c artifactRec)
    {
        artifact=new ArtifactValues(artifactRec);
    }
    class ArtifactValues
    {
        public string id;
        public boolean enabled;
        public String name;
        public Integer rank;
        public String artifactType;
        public String dependancyArtifactType;
        public String deploymentGroupRule;
        public String ruleSet;
        public String rule;
        public String overideRule;
        public String version;
        public String uuid;
        public String s3Path;
        public String dependancyBreakVersion;
        public String dependancyMinVersion;
        public String settingsUpdate;
        
        ArtifactValues(FS_Artifact__c artifact)
        {
            FS_Artifact_Ruleset__c ruleSetRec=[SELECT id,Name FROM FS_Artifact_Ruleset__c where id=:artifact.FS_Ruleset__c];
            id=artifact.id;
            enabled=artifact.FS_Enabled__c;
            name=artifact.name;
            rank=artifact.FS_Rank__c.intvalue();
            artifactType=artifact.FS_Artifact_Type__c;
            dependancyArtifactType = artifact.FS_Dependency_Artifact_Type__c;
            deploymentGroupRule=artifact.FS_Deployment_Group_Rule__c;
           ruleSet=ruleSetRec.name;
           rule=artifact.FS_Rule__c;
            overideRule=artifact.FS_Overide_Group_Rule__c;
            version=artifact.FS_Version__c;
            uuid=artifact.FS_UUID__c;
            s3Path=artifact.FS_S3Path__c;
            dependancyBreakVersion=artifact.DependancyBreakVersion__c;
            dependancyMinVersion=artifact.FS_Dependency_M_in_Version__c;
            settingsUpdate=artifact.Settings_Update__c;
        }
    }
}