force-app/main/default/objects/Leadership_Mail__c/Leadership_Mail__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Leadership_Mail</label>
</CustomObject>

force-app/main/default/objects/Leadership_Mail__c/fields/Email_Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Name__c</fullName>
    <label>Email_Template_Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FSLeadershipMailTest.cls
@isTest
public class FSLeadershipMailTest {
	public static testMethod void testschedule() {
		Leadership_Mail__C ledM = new Leadership_Mail__C();
     	ledM.Email_Template_Name__c='Leadership_Mail';
        insert ledM;
        Test.StartTest();
		FSLeadershipMail lm = new FSLeadershipMail();
		String sch = '0 0 23 * * ?'; 
        system.schedule('Test Territory Check', sch, lm); 
        Test.stopTest(); 
    }
    
}