force-app/main/default/objects/FS_Execution_Plan_Contact__c/FS_Execution_Plan_Contact__c.object-meta.xml
<CustomObject>
    <label>Outlet Contact</label>
    <nameField>
        <displayFormat>EC-{0000}</displayFormat>
        <label>Outlet Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan_Contact__c/fields/FS_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>FS_Contact_Name__c</fullName>
    <formula>FS_Execution_Plan_Contact__r.FirstName &amp;&quot; &quot;&amp; FS_Execution_Plan_Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan_Contact__c/fields/FS_Email__c.field-meta.xml
<CustomField>
    <fullName>FS_Email__c</fullName>
    <formula>FS_Execution_Plan_Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan_Contact__c/fields/FS_Execution_Plan_Contact__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan_Contact__c</fullName>
    <label>Headquarter Contact</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 5) OR (2 AND 3 AND 4)</booleanFilter>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.FS_Headquarters__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Outlet, BoE Outlet</value>
        </filterItems>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <valueField>$Source.Outlet__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.FS_Headquarters__c</field>
            <operation>equals</operation>
            <valueField>Contact.Account.FS_Headquarters__c</valueField>
        </filterItems>
        <filterItems>
            <field>Contact.Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Outlet Contacts</relationshipLabel>
    <relationshipName>Outlet_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan_Contact__c/fields/FS_Execution_Plan_Role__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan_Role__c</fullName>
    <formula>IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;Primary Contact&quot;), &quot;Primary Contact;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;Secondary Contact&quot;), &quot;Secondary Contact;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;Accounts Payable Contact&quot;), &quot;Accounts Payable Contact;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;Site Assessment Contact&quot;), &quot;Site Assessment Contact;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;Secondary Site Assessment Contact&quot;), &quot;Secondary Site Assessment Contact;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;Contractor Contact&quot;), &quot;Contractor Contact;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;On-Board Training Contact&quot;), &quot;On-Board Training Contact;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;Installation Contact&quot;), &quot;Installation Contact;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;Coke Smart Admin User&quot;), &quot;Coke Smart Admin User;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;Coke Smart Standard User&quot;), &quot;Coke Smart Standard User;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;VMS Admin User&quot;), &quot;VMS Admin User;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;VMS Standard User&quot;), &quot;VMS Standard User;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;Order Confirmation Contact&quot;), &quot;Order Confirmation Contact;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;Shipment Confirmation Contact&quot;), &quot;Shipment Confirmation Contact;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;Credit Confirmation Contact&quot;), &quot;Credit Confirmation Contact;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;Water Filter Contact&quot;), &quot;Water Filter Contact;&quot;,&quot;&quot;) &amp; 
IF( INCLUDES(FS_Execution_Plan_Contact__r.FS_Execution_Plan_Role__c , &quot;Other&quot;), &quot;Other&quot;,&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Role</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan_Contact__c/fields/FS_Phone__c.field-meta.xml
<CustomField>
    <fullName>FS_Phone__c</fullName>
    <formula>FS_Execution_Plan_Contact__r.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan_Contact__c/fields/Outlet__c.field-meta.xml
<CustomField>
    <fullName>Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Outlet Contacts</relationshipLabel>
    <relationshipName>Outlet_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_Outlet__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Installations (Outlet)</relationshipLabel>
    <relationshipName>Installations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InstallationRelatedContact.cls
/*********************************************************************************

                  
*********************************************************************************/
public class InstallationRelatedContact {
   
    public FS_Installation__c ep{get;set;}
    public List<FS_Execution_Plan_Contact__c> Con  {get;set;}
    //public String selectedContact{get;set;}
    
    //constructor
    public InstallationRelatedContact(ApexPages.StandardController controller){
        ep = (FS_Installation__c)controller.getRecord();
        ep = [SELECT ID,FS_Outlet__c From FS_Installation__c Where Id=:ep.id];
        prepareContactList();
    }
    
    
    
    //preparing list of related attachment
    public void prepareContactList(){
        con  = new List<FS_Execution_Plan_Contact__c>();
        for(FS_Execution_Plan_Contact__c cnt : [Select Id ,Outlet__c, Name, FS_Execution_Plan_Contact__c,FS_Phone__c,FS_Email__c,FS_Execution_Plan_Role__c,FS_Contact_Name__c From FS_Execution_Plan_Contact__c 
                              where Outlet__c = :ep.FS_Outlet__c]){
            Con.add(cnt);
        }
    }
    
}