force-app/main/default/objects/Error_Message_Resend_Counter__c/Error_Message_Resend_Counter__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Error Message Resend Counter</label>
</CustomObject>

force-app/main/default/objects/Error_Message_Resend_Counter__c/fields/Resend_Number__c.field-meta.xml
<CustomField>
    <fullName>Resend_Number__c</fullName>
    <label>Resend Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FOT_API__mdt/FOT_API__mdt.object-meta.xml
<CustomObject>
    <description>FOT_API</description>
    <label>FOT_API</label>
    <pluralLabel>FOT_APIs</pluralLabel>
</CustomObject>

force-app/main/default/objects/FOT_API__mdt/fields/api_key__c.field-meta.xml
<CustomField>
    <fullName>api_key__c</fullName>
    <description>API Key</description>
    <label>API Key</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FOT_API__mdt/fields/Authorization__c.field-meta.xml
<CustomField>
    <fullName>Authorization__c</fullName>
    <description>Authorization</description>
    <label>Authorization</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FOT_API__mdt/fields/Content_Type__c.field-meta.xml
<CustomField>
    <fullName>Content_Type__c</fullName>
    <description>Content-Type</description>
    <label>Content-Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FOT_API__mdt/fields/End_Point__c.field-meta.xml
<CustomField>
    <fullName>End_Point__c</fullName>
    <description>End Point</description>
    <label>End Point</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_IsActive__c.field-meta.xml
<CustomField>
    <fullName>FS_IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>active or inactive</description>
    <label>Active (A) / Inactive (I)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Last_Updated_Date_Time_to_NMS__c.field-meta.xml
<CustomField>
    <fullName>FS_Last_Updated_Date_Time_to_NMS__c</fullName>
    <description>Recent updated Date/time to NMS/Airwatch</description>
    <inlineHelpText>Recent updated Date/time to NMS/Airwatch</inlineHelpText>
    <label>Last Updated DateTime(GMT) to AW</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_NMS_Response__c.field-meta.xml
<CustomField>
    <fullName>FS_NMS_Response__c</fullName>
    <description>Response received from NMS/Airwatch for the last update</description>
    <inlineHelpText>Response received from NMS/Airwatch for the last update</inlineHelpText>
    <label>AW Response</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/HttpStatusCodes__c/HttpStatusCodes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Stores HTTP status code to that are to be retried for Outlet Dispenser callout</description>
    <label>HttpStatusCodes</label>
</CustomObject>

force-app/main/default/objects/Service_Message_Error_Log__c/Service_Message_Error_Log__c.object-meta.xml
<CustomObject>
    <label>Service Message Error Log</label>
    <nameField>
        <displayFormat>ERR-{00000}</displayFormat>
        <label>Service Message Error Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Message Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Message_Error_Log__c/fields/Error_Code__c.field-meta.xml
<CustomField>
    <fullName>Error_Code__c</fullName>
    <label>Error Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Message_Error_Log__c/fields/FS_Serial_Number_Asset_Tag__c.field-meta.xml
<CustomField>
    <fullName>FS_Serial_Number_Asset_Tag__c</fullName>
    <description>This is the serial number of the Outlet Dispenser</description>
    <inlineHelpText>This is the serial number of the Outlet Dispenser</inlineHelpText>
    <label>Serial Number/Asset Tag</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Message_Error_Log__c/fields/Outlet_Dispenser__c.field-meta.xml
<CustomField>
    <fullName>Outlet_Dispenser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet Dispenser</label>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipLabel>Service Message Error Logs</relationshipLabel>
    <relationshipName>Service_Message_Error_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Message_Error_Log__c/fields/Request_Message__c.field-meta.xml
<CustomField>
    <fullName>Request_Message__c</fullName>
    <label>Request Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Service_Message_Error_Log__c/fields/Resend_Counter__c.field-meta.xml
<CustomField>
    <fullName>Resend_Counter__c</fullName>
    <label>Resend Counter</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Service_Message_Error_Log__c/fields/ServiceName__c.field-meta.xml
<CustomField>
    <fullName>ServiceName__c</fullName>
    <label>ServiceName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchForErrorHandling.cls
// //
// (c) 2014 Appirio, Inc.
// BatchForErrorHandling
//
// 29 Dec 2014     Deepti Maheshwari    Original(Ref:S-273620)
/*
updated by      :Operational Capacity Support   
Date            :20th Sep 2016
Reqirement      : Resend when status code is not 200 or 202.
Purpose         : For retrying records that failed to be sent to Airwatch for 400 and 404 status code from the http request. 
****************************************************************************************************************************/
global without sharing class BatchForErrorHandling implements Database.Batchable<sObject>, Database.AllowsCallouts{

    global Database.QueryLocator start(Database.BatchableContext BC){
        
        //Status Codes of Error Logs that is to be retried
        List<String> statusCodes = new List<String>();
        for(HttpStatusCodes__c sc: HttpStatusCodes__c.getAll().values()){ //Custom Setting(HttpStatusCodes) Stores the http status codes
            statusCodes.add(sc.Name);
        }
        
        String qry = 'SELECT Id, Outlet_Dispenser__c, Outlet_Dispenser__r.FS_Last_Updated_Date_Time_to_NMS__c, Outlet_Dispenser__r.FS_NMS_Response__c, Error_Code__c,Error_Message__c, ' 
                  + ' FS_Serial_Number_Asset_Tag__c, Request_Message__c, Resend__c,Resend_Counter__c, ServiceName__c ' 
              + ' FROM Service_Message_Error_Log__c ' 
              + ' WHERE Resend__c = true ' 
              + ' AND Outlet_Dispenser__r.FS_IsActive__c = true '
              + ' AND Error_Code__c IN:statusCodes ';  //added condition to filter records based on error code
              
        return Database.getQueryLocator(qry);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope){
        HttpResponse response;
        List<Service_Message_Error_Log__c> beList = (List<Service_Message_Error_Log__c>)scope;
        List<Service_Message_Error_Log__c> listToUpdate = new List<Service_Message_Error_Log__c>();
        Set<Id> setDispenserIds = new Set<Id>();
        FOT_API__mdt serviceDetails = [select api_key__c,Authorization__c,Content_Type__c,End_Point__c FROM FOT_API__mdt WHERE DeveloperName='A11'];
        Map<String, Error_Message_Resend_Counter__c> mapNameCounter = Error_Message_Resend_Counter__c.getAll();
        Error_Message_Resend_Counter__c resendNumber;
        if(mapNameCounter.containsKey('Service Message Error')) {
          resendNumber = mapNameCounter.get('Service Message Error');
        } 

        for(Service_Message_Error_Log__c item : beList) {
            setDispenserIds.add(item.Outlet_Dispenser__c);
        }
    
        Map<Id, FS_Outlet_Dispenser__c> mapIdDispenser = new Map<Id, FS_Outlet_Dispenser__c>([SELECT Id, FS_Last_Updated_Date_Time_to_NMS__c, FS_NMS_Response__c 
                                                    FROM FS_Outlet_Dispenser__c 
                                                  WHERE Id IN :setDispenserIds]);
        Map<Id, FS_Outlet_Dispenser__c> mapErrorLogIdDispenser = new Map<Id, FS_Outlet_Dispenser__c>();
    
        for(Service_Message_Error_Log__c item : beList) {
          if(mapIdDispenser.containsKey(item.Outlet_Dispenser__c) && mapIdDispenser.get(item.Outlet_Dispenser__c) != null) {
            mapErrorLogIdDispenser.put(Item.Id, mapIdDispenser.get(item.Outlet_Dispenser__c));
          }
        }
    
        for(Service_Message_Error_Log__c item : beList) {

            response = callServiceForMessageLogs(item, serviceDetails);
            
            if(resendnumber != null && resendnumber.Resend_Number__c < item.Resend_Counter__c) {
               item.Resend__c = false;
            }
            
            if(mapErrorLogIdDispenser.containsKey(item.Id)) {
              mapIdDispenser.get(mapErrorLogIdDispenser.get(item.Id).Id).FS_Last_Updated_Date_Time_to_NMS__c = System.now();
              if(response != null) {
                mapIdDispenser.get(mapErrorLogIdDispenser.get(item.Id).Id).FS_NMS_Response__c = String.valueOf(response.getStatusCode())+'-'+ response.getStatus();
              } else {
                mapIdDispenser.get(mapErrorLogIdDispenser.get(item.Id).Id).FS_NMS_Response__c = 'Response not received in Expected Time Limit.';
              }
              mapIdDispenser.put(mapErrorLogIdDispenser.get(item.Id).Id,mapIdDispenser.get(mapErrorLogIdDispenser.get(item.Id).Id));
            }
            
            listToUpdate.add(item);
        }
        if(listToUpdate.size() > 0) {
            update listToUpdate;
        }
        
        if(mapIdDispenser != null && mapIdDispenser.values().size() > 0) {
            update mapIdDispenser.values();
        }
    }

    private HttpResponse callServiceForMessageLogs(Service_Message_Error_Log__c errorLog, FOT_API__mdt serviceDetail){
        HTTPRequest request = new HttpRequest();
        Http httpCon = new Http();
        HttpResponse response;
        String bodystr;
    
        try{
            request.setEndpoint(serviceDetail.End_Point__c);
            System.debug('this is end point '+serviceDetail.End_Point__c);
            request.setHeader('Content-Type', 'application/xml');
            request.setHeader('Authorization', serviceDetail.Authorization__c);
            request.setHeader('X-KO-HOST', errorLog.FS_Serial_Number_Asset_Tag__c);
            bodystr = errorLog.Request_Message__c;
            system.debug('Body string : ' + bodystr);
            request.setBody(bodystr);
            request.setMethod('POST');
            request.setTimeout(120000);
       
            //if(!Test.isRunningTest()) {
              response = httpCon.send(request);
              if(response !=null && response.getStatusCode() == 200){
                system.debug('Request executed successfully');
                errorLog.resend__c = false;
              } else {
               system.debug('Request failed');
               
               if(!String.valueOf(response.getStatusCode()).contains('200') || !String.valueOf(response.getStatusCode()).contains('202')) 
               errorLog.resend__c = true;
               
               if (errorLog.Resend_Counter__c==null){errorLog.Resend_Counter__c =0;}
               
               errorLog.Resend_Counter__c = errorLog.Resend_Counter__c + 1;
             }
            //}
        }catch(CalloutException ex){
            System.debug('No callout');
            errorLog.resend__c = true;
            if (errorLog.Resend_Counter__c==null){
             errorLog.Resend_Counter__c =0;
             }
            errorLog.Resend_Counter__c = errorLog.Resend_Counter__c + 1;
        }
        
        return response;
    }
    
    global void finish(Database.BatchableContext BC){

    }

}