force-app/main/default/objects/FS_Flavor_Change_Head__c/FS_Flavor_Change_Head__c.object-meta.xml
<CustomObject>
    <label>Flavor Change Header</label>
    <nameField>
        <displayFormat>FCP-{0000}</displayFormat>
        <label>Flavor Change Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flavor Change</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Flavor_Change_Head__c/fields/FS_CDM_Setup_Complete__c.field-meta.xml
<CustomField>
    <fullName>FS_CDM_Setup_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CDM Setup Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Flavor_Change_Head__c/fields/FS_FC_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_FC_Type__c</fullName>
    <label>Flavor Change Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Workflow Flavor Change</fullName>
            </value>
            <value>
                <fullName>File Upload Flavor Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Flavor_Change_Head__c/fields/FS_HQ_Chain__c.field-meta.xml
<CustomField>
    <fullName>FS_HQ_Chain__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entity Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Flavor_Change_Heads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FSFlavorChangeHeaderQueueClassTest.cls
/**************************************************************************
 Name         : FSFlavorChangeHeaderQueueClassTest
 Created By   : Infosys Limited
 Description  : Test class for FSFlavorChangeHeaderQueueClass 
 Created Date : 23-JAN-2017
***************************************************************************/


@isTest
Private class FSFlavorChangeHeaderQueueClassTest {
   
    private static set<ID> recordIdSet = new set<ID>();
     
    private static testMethod void testData()
    {    
        final Id devRecoTypeId = Schema.SObjectType.FS_Flavor_Change_Head__c.getRecordTypeInfosByName().get('FS Flavor Change Chain HQ').getRecordTypeId();
        final List<FS_Flavor_Change_Head__c> fcHeadList=new List<FS_Flavor_Change_Head__c>();
        
        final List<Account> accListForAssignment=FSTestFactory.accListCreate();
        for(Account accVar:accListForAssignment){
            final FS_Flavor_Change_Head__c fcHead=new FS_Flavor_Change_Head__c();
            fcHead.RecordTypeId=devRecoTypeId;
            fcHead.FS_CDM_Setup_Complete__c=false;
            fcHead.FS_FC_Type__c='Workflow Flavor Change';
            fcHead.FS_HQ_Chain__c=accVar.Id;
            fcHeadList.add(fcHead);
        }
        Insert fcHeadList;
        for(FS_Flavor_Change_Head__c fcVar:fcHeadList){
            recordIdSet.add(fcVar.Id);
        }
        
        Test.startTest();
        final FSFlavorChangeHeaderQueueClass hqClass = new FSFlavorChangeHeaderQueueClass(recordIdSet);
        final ID jobID = System.enqueueJob(hqClass);
        Test.stopTest();
            
    }
}