force-app/main/default/objects/FS_Association_Brandset__c/FS_Association_Brandset__c.object-meta.xml
<CustomObject>
    <label>Default Brandset</label>
    <nameField>
        <displayFormat>AB-{00000}</displayFormat>
        <label>Account Brandset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Brandsets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Brandset__c.field-meta.xml
<CustomField>
    <fullName>FS_Brandset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brandset</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Selected Brandset is not available for commercial use</errorMessage>
        <filterItems>
            <field>FS_Brandset__c.FS_Platform_Applicable__c</field>
            <operation>contains</operation>
            <valueField>$Source.FS_Platform__c</valueField>
        </filterItems>
        <filterItems>
            <field>FS_Brandset__c.Available_for_Selection__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FS_Brandset__c</referenceTo>
    <relationshipLabel>Default Brandsets</relationshipLabel>
    <relationshipName>Brandsets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Outlet_Dispenser__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_Dispenser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet Dispenser</label>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipLabel>Brandset Details (Current)</relationshipLabel>
    <relationshipName>OutletDispensers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Brandset__c/FS_Brandset__c.object-meta.xml
<CustomObject>
    <description>FS_Brandset</description>
    <label>Brandset</label>
    <nameField>
        <label>Brandset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brandsets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Brandset__c.field-meta.xml
<CustomField>
    <fullName>FS_Brandset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Brandset Associated to Outlet Dispenser</description>
    <label>Brandset</label>
    <referenceTo>FS_Brandset__c</referenceTo>
    <relationshipLabel>Outlet Dispensers (Brandset)</relationshipLabel>
    <relationshipName>CurrentBrandset</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FSCopyBrandsetsToDispenser.cls
global class FSCopyBrandsetsToDispenser implements Database.Batchable<sObject>{
    
   /*private final static Id NULLOBJ = null;
   private final static Date NULLOBJDATE = null;*/     
   public  String recTypeODInternational=Schema.SObjectType.FS_Outlet_Dispenser__c.getRecordTypeInfosByName().get(Label.INT_OD_RECORD_TYPE).getRecordTypeId();
     /******************************************************************************
    //Start the batch and query
    /***************************************************************************/
    global Database.QueryLocator start(final Database.BatchableContext batchContext){
      return Database.getQueryLocator([SELECT ID,FS_Brandset__c FROM FS_Outlet_Dispenser__c 
                                        WHERE RecordtypeID!=:recTypeODInternational AND FS_Brandset__c=NULL]);       
   }
   
   
    /****************************************************************************
    //Process batch
    /***************************************************************************/
   
   global void execute(final Database.BatchableContext batchContext, final List<sObject> scope){
       
       //Collection variable that stores Outlet Dispenser Ids
       final Set<Id> setOfOutletDispenserIds=new Set<Id>();
       
       final List<FS_Association_Brandset__c> associationBrandsetRecordsToUpdate=new List<FS_Association_Brandset__c>();
       
       //Collection variable with outlet dispnser Id as key and association brandet records as values
       final Map<Id,FS_Association_Brandset__c> dispenserAndAssociationBrandsetMap=new Map<Id,FS_Association_Brandset__c>();
       
       final List<FS_Outlet_Dispenser__c> dispenserRecordsToUpdate= new List<FS_Outlet_Dispenser__c>();
       
       //Fetch Outlet Dispenser Record Ids
       for(FS_Outlet_Dispenser__c outletDispenser : (List<FS_Outlet_Dispenser__c>)scope){
           setOfOutletDispenserIds.add(outletDispenser.Id);
       }
       
       //Fetch association brandet records against each outlet dispenser records
       for(FS_Association_Brandset__c assoBrandset :[SELECT ID,FS_Brandset__c,FS_Outlet_Dispenser__c,Name FROM FS_Association_Brandset__c WHERE FS_Outlet_Dispenser__c=:setOfOutletDispenserIds]){
           dispenserAndAssociationBrandsetMap.put(assoBrandset.FS_Outlet_Dispenser__c,assoBrandset);
       }
       
       for( FS_Outlet_Dispenser__c outletDispenser : (List<FS_Outlet_Dispenser__c>)scope){
       
           if(dispenserAndAssociationBrandsetMap.containsKey(outletDispenser.Id)){
           
              final FS_Association_Brandset__c assoBrandset=dispenserAndAssociationBrandsetMap.get(outletDispenser.Id);
              
               if(assoBrandset.FS_Brandset__c!=NULL && assoBrandset.FS_Brandset__c!=outletDispenser.FS_Brandset__c){
                 
                       
                       outletDispenser.FS_Brandset__c=assoBrandset.FS_Brandset__c;
                       dispenserRecordsToUpdate.add(outletDispenser);
               }
           }
       }
       
       //Update all Assosiation brandsets
       /*final Database.SaveResult [] updateAssoBrandsetResult = Database.update(associationBrandsetRecordsToUpdate,false);*/
       //update Outlet Dispenser records
       final Database.SaveResult [] updateODResult= Database.update(dispenserRecordsToUpdate,false);
   }
   
   
    /****************************************************************************
    //finish the batch
    /***************************************************************************/
   
    global void finish(final Database.BatchableContext info){   
        system.debug('Finish Method of the Batch');
   } 

}