force-app/main/default/objects/FS_Association_Brandset__c/FS_Association_Brandset__c.object-meta.xml
<CustomObject>
    <label>Default Brandset</label>
    <nameField>
        <displayFormat>AB-{00000}</displayFormat>
        <label>Account Brandset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Brandsets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Brandset__c.field-meta.xml
<CustomField>
    <fullName>FS_Brandset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brandset</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Selected Brandset is not available for commercial use</errorMessage>
        <filterItems>
            <field>FS_Brandset__c.FS_Platform_Applicable__c</field>
            <operation>contains</operation>
            <valueField>$Source.FS_Platform__c</valueField>
        </filterItems>
        <filterItems>
            <field>FS_Brandset__c.Available_for_Selection__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FS_Brandset__c</referenceTo>
    <relationshipLabel>Default Brandsets</relationshipLabel>
    <relationshipName>Brandsets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Brandset_Desc__c.field-meta.xml
<CustomField>
    <fullName>FS_Brandset_Desc__c</fullName>
    <formula>FS_Brandset__r.FS_Description__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Brandset Desc</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Brandset_Number__c.field-meta.xml
<CustomField>
    <fullName>FS_Brandset_Number__c</fullName>
    <formula>FS_Brandset__r.FS_Brandset_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Brandset#</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Commercial_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Commercial_Start_Date__c</fullName>
    <formula>FS_Brandset__r.FS_Effective_Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Commercial Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Country__c.field-meta.xml
<CustomField>
    <fullName>FS_Country__c</fullName>
    <formula>IF( FS_Headquarters__c!=null ,FS_Headquarters__r.ShippingCountry ,
IF(FS_Installation__c!=null  , FS_Installation__r.FS_Outlet__r.ShippingCountry ,
IF(FS_Outlet_Dispenser__c!=null,FS_Outlet_Dispenser__r.Outlet_Country__c,&#39;&#39;)))</formula>
    <label>Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Installation__c.field-meta.xml
<CustomField>
    <fullName>FS_Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation Plan</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Selected Brandsets</relationshipLabel>
    <relationshipName>Account_Brandsets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_NonBranded_Water__c.field-meta.xml
<CustomField>
    <fullName>FS_NonBranded_Water__c</fullName>
    <description>NonBranded Water</description>
    <label>NonBranded Water</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hide</fullName>
            </value>
            <value>
                <fullName>Show</fullName>
                <default>true</default>
                <label>Show</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Brandset__c/FS_Brandset__c.object-meta.xml
<CustomObject>
    <description>FS_Brandset</description>
    <label>Brandset</label>
    <nameField>
        <label>Brandset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brandsets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Brandset__c/fields/FS_Brandset_Number__c.field-meta.xml
<CustomField>
    <fullName>FS_Brandset_Number__c</fullName>
    <description>Brandset number</description>
    <displayFormat>B-{0000}</displayFormat>
    <externalId>true</externalId>
    <label>Brandset#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Brandset__c/fields/FS_Country__c.field-meta.xml
<CustomField>
    <fullName>FS_Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AD</fullName>
            </value>
            <value>
                <fullName>AE</fullName>
            </value>
            <value>
                <fullName>AF</fullName>
            </value>
            <value>
                <fullName>AG</fullName>
            </value>
            <value>
                <fullName>AI</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AN</fullName>
            </value>
            <value>
                <fullName>AO</fullName>
            </value>
            <value>
                <fullName>AQ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AT</fullName>
            </value>
            <value>
                <fullName>AU</fullName>
            </value>
            <value>
                <fullName>AW</fullName>
            </value>
            <value>
                <fullName>AX</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BB</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BE</fullName>
            </value>
            <value>
                <fullName>BF</fullName>
            </value>
            <value>
                <fullName>BG</fullName>
            </value>
            <value>
                <fullName>BH</fullName>
            </value>
            <value>
                <fullName>BI</fullName>
            </value>
            <value>
                <fullName>BJ</fullName>
            </value>
            <value>
                <fullName>BL</fullName>
            </value>
            <value>
                <fullName>BM</fullName>
            </value>
            <value>
                <fullName>BN</fullName>
            </value>
            <value>
                <fullName>BO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Brandset__c/fields/FS_Platform__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform__c</fullName>
    <description>Platform</description>
    <label>Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Brandset__c/fields/FS_SAP_Item_Proposal_Number__c.field-meta.xml
<CustomField>
    <fullName>FS_SAP_Item_Proposal_Number__c</fullName>
    <label>SAP Proposal #</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Initial_Order__c/FS_Initial_Order__c.object-meta.xml
<CustomObject>
    <label>Initial Order</label>
    <nameField>
        <label>Initial Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Initial Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Initial_Order__c/fields/FS_Installation__c.field-meta.xml
<CustomField>
    <fullName>FS_Installation__c</fullName>
    <label>Installation</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Initial Orders</relationshipLabel>
    <relationshipName>Initial_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_Brandset__c.field-meta.xml
<CustomField>
    <fullName>FS_Brandset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brandset 7000</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>FS_Brandset__c.FS_Platform_Applicable__c</field>
            <operation>contains</operation>
            <value>7000</value>
        </filterItems>
        <filterItems>
            <field>FS_Brandset__c.Available_for_Selection__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FS_Brandset__c</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Platform_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3100</fullName>
    </customValue>
    <customValue>
        <fullName>6000</fullName>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
    </customValue>
    <customValue>
        <fullName>7100</fullName>
    </customValue>
    <customValue>
        <fullName>8000</fullName>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
    </customValue>
    <masterLabel>Platform Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FSInitialOrderBrandsetsController.cls
public class FSInitialOrderBrandsetsController {
    
   public FS_Initial_Order__c initalOrder{set;get;}
   
    public FSInitialOrderBrandsetsController(final ApexPages.StandardController controller) {
        //Returns the record that is currently in context
        initalOrder=(FS_Initial_Order__c)controller.getRecord();
    }
    
    public List<FS_Association_Brandset__c> getAssosiationBrandsets(){
        return  [SELECT ID,FS_Brandset__c,FS_Brandset__r.name,FS_Platform__c,FS_Brandset__r.FS_SAP_Item_Proposal_Number__c,FS_Brandset__r.FS_Country__c,FS_Brandset_Number__c,FS_Brandset_Desc__c,FS_Commercial_Start_Date__c,FS_NonBranded_Water__c,CreatedByid,LastModifiedById,CreatedDate,	
LastModifiedDate FROM FS_Association_Brandset__c WHERE FS_Installation__c=:initalOrder.FS_Installation__c];
    }

}