force-app/main/default/objects/FS_Association_Brandset__c/FS_Association_Brandset__c.object-meta.xml
<CustomObject>
    <label>Default Brandset</label>
    <nameField>
        <displayFormat>AB-{00000}</displayFormat>
        <label>Account Brandset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Brandsets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Brandset__c.field-meta.xml
<CustomField>
    <fullName>FS_Brandset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brandset</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Selected Brandset is not available for commercial use</errorMessage>
        <filterItems>
            <field>FS_Brandset__c.FS_Platform_Applicable__c</field>
            <operation>contains</operation>
            <valueField>$Source.FS_Platform__c</valueField>
        </filterItems>
        <filterItems>
            <field>FS_Brandset__c.Available_for_Selection__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FS_Brandset__c</referenceTo>
    <relationshipLabel>Default Brandsets</relationshipLabel>
    <relationshipName>Brandsets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Installation__c.field-meta.xml
<CustomField>
    <fullName>FS_Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation Plan</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Selected Brandsets</relationshipLabel>
    <relationshipName>Account_Brandsets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_NonBranded_Water__c.field-meta.xml
<CustomField>
    <fullName>FS_NonBranded_Water__c</fullName>
    <description>NonBranded Water</description>
    <label>NonBranded Water</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hide</fullName>
            </value>
            <value>
                <fullName>Show</fullName>
                <default>true</default>
                <label>Show</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Outlet_Dispenser__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_Dispenser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet Dispenser</label>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipLabel>Brandset Details (Current)</relationshipLabel>
    <relationshipName>OutletDispensers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Platforms__c.field-meta.xml
<CustomField>
    <fullName>FS_Platforms__c</fullName>
    <label>Platforms</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Brandset__c/FS_Brandset__c.object-meta.xml
<CustomObject>
    <description>FS_Brandset</description>
    <label>Brandset</label>
    <nameField>
        <label>Brandset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brandsets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Brandset__c/fields/FS_Platform__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform__c</fullName>
    <description>Platform</description>
    <label>Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <displayFormat>EP-{0000}</displayFormat>
    <label>Execution Plan#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_Brandset__c.field-meta.xml
<CustomField>
    <fullName>FS_Brandset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brandset 7000</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>FS_Brandset__c.FS_Platform_Applicable__c</field>
            <operation>contains</operation>
            <value>7000</value>
        </filterItems>
        <filterItems>
            <field>FS_Brandset__c.Available_for_Selection__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FS_Brandset__c</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_BrandStatus__c.field-meta.xml
<CustomField>
    <fullName>FS_BrandStatus__c</fullName>
    <description>Brand Status</description>
    <label>Brand Status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlet Info Summary</relationshipLabel>
    <relationshipName>Outlet_Info_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Outlet_Information__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_Information__c</fullName>
    <description>Outlet Information</description>
    <formula>FS_Outlet__r.FS_Outlet_Information__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Outlet Information</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/Overall_Status2__c.field-meta.xml
<CustomField>
    <fullName>Overall_Status2__c</fullName>
    <label>Transaction Status</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/Type_of_Dispenser_Platform__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Dispenser_Platform__c</fullName>
    <description>multi select pick list</description>
    <label>Platform Type/s</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Brandset__c.field-meta.xml
<CustomField>
    <fullName>FS_Brandset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Brandset Associated to Outlet Dispenser</description>
    <label>Brandset</label>
    <referenceTo>FS_Brandset__c</referenceTo>
    <relationshipLabel>Outlet Dispensers (Brandset)</relationshipLabel>
    <relationshipName>CurrentBrandset</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Equip_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Equip_Type__c</fullName>
    <description>equip type</description>
    <inlineHelpText>This is the JDE Equipment Type value</inlineHelpText>
    <label>Equipment Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Outlet_Information__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_Information__c</fullName>
    <description>outlet information</description>
    <formula>FS_Outlet__r.FS_Outlet_Information__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Outlet Information</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Installation__c.field-meta.xml
<CustomField>
    <fullName>Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>((1 OR 2) AND 4) OR 3 OR 5</booleanFilter>
        <errorMessage>The installation referenced by this dispenser is linked to a different outlet than the outlet on the dispenser.</errorMessage>
        <filterItems>
            <field>FS_Installation__c.FS_Outlet__c</field>
            <operation>equals</operation>
            <valueField>$Source.FS_Outlet__c</valueField>
        </filterItems>
        <filterItems>
            <field>FS_Installation__c.FS_New_Outlet__c</field>
            <operation>equals</operation>
            <valueField>$Source.FS_Outlet__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>BoE Dispenser</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>CCNA Dispenser, 7000, 8000, 9000</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>API User, MDM API User</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Installed Dispensers</relationshipLabel>
    <relationshipName>Outlet_Dispensers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Platform_Type_ctrl__c/Platform_Type_ctrl__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>PlatformType Ctrl</description>
    <label>PlatformType Ctrl</label>
</CustomObject>

force-app/main/default/objects/Platform_Type_ctrl__c/fields/Platforms__c.field-meta.xml
<CustomField>
    <fullName>Platforms__c</fullName>
    <description>Platforms</description>
    <label>Platforms</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Platform_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3100</fullName>
    </customValue>
    <customValue>
        <fullName>6000</fullName>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
    </customValue>
    <customValue>
        <fullName>7100</fullName>
    </customValue>
    <customValue>
        <fullName>8000</fullName>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
    </customValue>
    <masterLabel>Platform Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FSEnterEditViewFlavorChangeWiredSolCtrl.cls
/*********************************************************************************************************
Name         : FSEnterEditViewFlavorChangeWiredSolCtrl
Created By   : Pallavi Sharma (Appiro)
Created Date : 17 - Sep - 2013
Usage        : Controller for Enter/Edit/View Flavor Change/Wired Sol Page, which is used to edit information about
Installation related to Execution Plan
Modified By  : Harshita Khandelwal 17-12-2014 Ref:T-341592
Modified By : Venkata 13-02-2017	reg FET 4.0 Project for adding extra columns [Brandset,water,dasani]
9th Jan,2019 Modified by: Sai Krishna. Added a new Cancel method for redirection to prev Execution plan record page. Reg: FET 6 Ref:(Jira FNF-115)
***********************************************************************************************************/

public class FSEnterEditViewFlavorChangeWiredSolCtrl {
    
    public  Map<Id,Id> oldBrandsets;
    public  Map<Id,FS_Association_Brandset__c> newAssBrands;
    public  Map<Id,String> ipStatus;
    public List<FS_Installation__c> lstInstallation{get;set;}
    public Id executionPlan{get;set;}      
    public List<String> errorList{get;set;}
    
    
    //Constructor
    //Changes Made as part of FET 4.0 added some fields in the Query
    public FSEnterEditViewFlavorChangeWiredSolCtrl(){
        executionPlan = Apexpages.currentPage().getParameters().get('executionplanid');
        lstInstallation = new List<FS_Installation__c>();        
        oldBrandsets=new  Map<Id,Id>();
        newAssBrands=new  Map<Id,FS_Association_Brandset__c>();
        ipStatus=new Map<Id,String>();
        
        //Get all Installtions related to Execution Plan
        lstInstallation = [Select Id,Name,Overall_Status2__c,FS_Execution_Plan__c, FS_BrandStatus__c, FS_Outlet_Information__c,
                           Type_of_Dispenser_Platform__c,(select id,name,FS_Brandset__c,FS_Installation__c,
                                                          FS_NonBranded_Water__c,FS_Platforms__c,FS_Platform__c from Account_Brandsets__r order by FS_Platforms__c)
                           From FS_Installation__c Where FS_Execution_Plan__c =: executionPlan];
        
        //store old brandsets
        for (FS_Installation__c ip:lstInstallation) {
            for (FS_Association_Brandset__c assBrand : ip.Account_Brandsets__r) {
                oldBrandsets.put(assBrand.id, assBrand.FS_Brandset__c);
            }
            //capture the status of installations
            ipStatus.put(ip.id, ip.Overall_Status2__c);
        }
        
    }
    
    /*****************************************************************
Method: saveInstallation
Description: saveInstallation method is to save the Installation records and return back to the Execution Plan record
Changes Made as part of FET 4.0
*******************************************************************/
    public PageReference saveInstallation(){
        PageReference page;
        final String allPlatforms=Platform_Type_ctrl__c.getAll().get('all_Platform').Platforms__c;
            
        final Map<Id,Id> odMap=new Map<Id,Id>();       
        try{            
            //FET 5.0 logic changed for mulitplatform Installation
            
            // restrict user to change brandset- Production Defect-start
            //Store ODs
            final List<FS_Outlet_Dispenser__c> oDList=[SELECT Id,Installation__c,FS_Equip_Type__c FROM FS_Outlet_Dispenser__c WHERE Installation__c IN:lstInstallation];
            for(FS_Outlet_Dispenser__c od:oDList){
                if (allPlatforms!=null && allPlatforms.contains(od.FS_Equip_Type__c) ) {
                    odMap.put(od.Installation__c,od.Id);
                }                    
            }                
            //store all new association brandsets
            for (FS_Installation__c ip : lstInstallation){
                for (FS_Association_Brandset__c assBrand : ip.Account_Brandsets__r) {
                    newAssBrands.put(assBrand.id, assBrand);
                }
            }
            //check each association brandset for brandset value changed
            for (FS_Association_Brandset__c newAssBrand : newAssBrands.values()){
                final ID installID  = newAssBrand.FS_Installation__c;
                //and Intallation Status is 4 installed scheduled
                if (oldBrandsets.get(newAssBrand.id) != newAssBrand.FS_Brandset__c && ipStatus.get(installID)==FSConstants.x4InstallSchedule && 
                    allPlatforms!=null && allPlatforms.contains(newAssBrand.FS_Platform__c) && odMap.containsKey(installID) && odMap.get(installID)!=null){                                
                        ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,Label.FlavourChangeERRMessage));
                    }                  
            }
            
            
            // restrict user to change brandset- Production Defect-close
            
            //FET 5.0
            //Upsert the related Associate Brandset
            final List<FS_Association_Brandset__c> assBrandsetsUpsert = new List<FS_Association_Brandset__c>();
            
            for (FS_Installation__c install : lstInstallation){
                assBrandsetsUpsert.addAll(install.Account_Brandsets__r);
            }
            
            Boolean isError = false;
            final List<Database.SaveResult> resList = Database.update(assBrandsetsUpsert,false);
            errorList = new List<String>();
            for(Database.SaveResult res : resList){
                if(!res.isSuccess()){
                    for(Database.Error error : res.getErrors()){ errorList.add(error.getMessage());    }
                    isError = true;  
                    break;
                }
            }            
            if(!isError){
                page = new PageReference('/' + executionPlan);
            }                       
        }catch(DMLException e) {    
            apexpages.addMessages(e);
            ApexErrorLogger.addApexErrorLog(FSConstants.FET,'FSEnterEditViewFlavorChangeWiredSolCtrl','saveInstallation',FSConstants.INSTALLATIONOBJECTNAME,FSConstants.MediumPriority,e,e.getMessage());
        }  
        return page;
    }
    /*****************************************************************
  	Method: cancel
  	Description: cancel method helps the user return back to the execution plan record  
	*******************************************************************/
    public PageReference cancel(){
        PageReference pageRef;
        if(executionPlan!= Null){
            pageRef= new PageReference('/' + executionPlan);
        }
        return pageRef;        
    } 
}