force-app/main/default/objects/FS_Association_Brandset__c/FS_Association_Brandset__c.object-meta.xml
<CustomObject>
    <label>Default Brandset</label>
    <nameField>
        <displayFormat>AB-{00000}</displayFormat>
        <label>Account Brandset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Brandsets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Brandset__c.field-meta.xml
<CustomField>
    <fullName>FS_Brandset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brandset</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Selected Brandset is not available for commercial use</errorMessage>
        <filterItems>
            <field>FS_Brandset__c.FS_Platform_Applicable__c</field>
            <operation>contains</operation>
            <valueField>$Source.FS_Platform__c</valueField>
        </filterItems>
        <filterItems>
            <field>FS_Brandset__c.Available_for_Selection__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FS_Brandset__c</referenceTo>
    <relationshipLabel>Default Brandsets</relationshipLabel>
    <relationshipName>Brandsets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Installation__c.field-meta.xml
<CustomField>
    <fullName>FS_Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation Plan</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Selected Brandsets</relationshipLabel>
    <relationshipName>Account_Brandsets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_NonBranded_Water__c.field-meta.xml
<CustomField>
    <fullName>FS_NonBranded_Water__c</fullName>
    <description>NonBranded Water</description>
    <label>NonBranded Water</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hide</fullName>
            </value>
            <value>
                <fullName>Show</fullName>
                <default>true</default>
                <label>Show</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Outlet_Dispenser__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_Dispenser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet Dispenser</label>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipLabel>Brandset Details (Current)</relationshipLabel>
    <relationshipName>OutletDispensers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Brandset__c/FS_Brandset__c.object-meta.xml
<CustomObject>
    <description>FS_Brandset</description>
    <label>Brandset</label>
    <nameField>
        <label>Brandset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brandsets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/FS_Execution_Plan__c.object-meta.xml
<CustomObject>
    <description>FS Execution Plan</description>
    <label>Execution Plan</label>
    <nameField>
        <label>Execution Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Execution Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <displayFormat>EP-{0000}</displayFormat>
    <label>Execution Plan#</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Platform_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform_Type__c</fullName>
    <description>multi select picklist</description>
    <label>Platform Type/s</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Execution_Plan__c/fields/FS_Relocation_from_old_outlet_to_SP_is__c.field-meta.xml
<CustomField>
    <fullName>FS_Relocation_from_old_outlet_to_SP_is__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Removal from old outlet to SP complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_Brandset__c.field-meta.xml
<CustomField>
    <fullName>FS_Brandset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brandset 7000</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>FS_Brandset__c.FS_Platform_Applicable__c</field>
            <operation>contains</operation>
            <value>7000</value>
        </filterItems>
        <filterItems>
            <field>FS_Brandset__c.Available_for_Selection__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FS_Brandset__c</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Disconnect_Final_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Disconnect_Final_Date__c</fullName>
    <label>Disconnect Final Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Execution_Plan__c.field-meta.xml
<CustomField>
    <fullName>FS_Execution_Plan__c</fullName>
    <label>Execution Plan</label>
    <referenceTo>FS_Execution_Plan__c</referenceTo>
    <relationshipLabel>Outlet Info Summary</relationshipLabel>
    <relationshipName>Outlet_Info_Summary</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Install_Reconnect_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Install_Reconnect_Date__c</fullName>
    <label>Initially Install/Reconnect Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Relocation_from_old_outlet_to_SP_is__c.field-meta.xml
<CustomField>
    <fullName>FS_Relocation_from_old_outlet_to_SP_is__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Remove/Disconnect Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Scheduled_Install_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Scheduled_Install_Date__c</fullName>
    <description>This is the replacement of the install date formula field. Which contains latest reschedule date.</description>
    <label>Scheduled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/Overall_Status2__c.field-meta.xml
<CustomField>
    <fullName>Overall_Status2__c</fullName>
    <label>Transaction Status</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/Type_of_Dispenser_Platform__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Dispenser_Platform__c</fullName>
    <description>multi select pick list</description>
    <label>Platform Type/s</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Brandset__c.field-meta.xml
<CustomField>
    <fullName>FS_Brandset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Brandset Associated to Outlet Dispenser</description>
    <label>Brandset</label>
    <referenceTo>FS_Brandset__c</referenceTo>
    <relationshipLabel>Outlet Dispensers (Brandset)</relationshipLabel>
    <relationshipName>CurrentBrandset</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Equip_Type__c.field-meta.xml
<CustomField>
    <fullName>FS_Equip_Type__c</fullName>
    <description>equip type</description>
    <inlineHelpText>This is the JDE Equipment Type value</inlineHelpText>
    <label>Equipment Type</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/FS_Other_PIA_Installation__c.field-meta.xml
<CustomField>
    <fullName>FS_Other_PIA_Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RO4W/Removal/Replacement Transaction</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Outlet Dispensers (Other PIA Installation)</relationshipLabel>
    <relationshipName>Outlet_Dispensers2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Outlet_Dispenser__c/fields/Relocated_Installation__c.field-meta.xml
<CustomField>
    <fullName>Relocated_Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Installation Lookup only for RI4W Type</description>
    <label>Relocated Installation</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Outlet Dispensers (Relocated Installation)</relationshipLabel>
    <relationshipName>Outlet_Dispensers1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Platform_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3100</fullName>
    </customValue>
    <customValue>
        <fullName>6000</fullName>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
    </customValue>
    <customValue>
        <fullName>7100</fullName>
    </customValue>
    <customValue>
        <fullName>8000</fullName>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
    </customValue>
    <masterLabel>Platform Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FS_InstallationWarningAuraController.cls
public class FS_InstallationWarningAuraController {   
    @AuraEnabled public boolean displayError {get; set;}
    @AuraEnabled public boolean displayErrorSync {get; set;}
    @AuraEnabled public boolean IP_I4W_ReconnectDate {get; set;}
    @AuraEnabled public boolean dispSecError {get; set;}
    @AuraEnabled public FS_Installation__c installation {get; set;}
    @AuraEnabled public String recordTypeName {get; set;}
    
    public FS_InstallationWarningAuraController(){
       
    }   
    
    @AuraEnabled
    public static FS_InstallationWarningAuraController checkBrandsetAndSyncValues(id RecID){
        
          
       // FS_Installation__c install1;
        FS_Installation__c installation;
        FS_InstallationWarningAuraController objectCnt = new FS_InstallationWarningAuraController();
        
        installation=[select id,name,RecordTypeId,FS_Execution_Plan__c,FS_Disconnect_Final_Date__c,Type_of_Dispenser_Platform__c,FS_Install_Reconnect_Date__c,
                      FS_Scheduled_Install_Date__c,Overall_Status2__c,FS_Relocation_from_old_outlet_to_SP_is__c,
                      FS_Installation__c.RecordType.Name,
                      (select id,FS_Equip_Type__c,Relocated_Installation__c from Outlet_Dispensers1__r),
                      (select id,FS_Equip_Type__c,FS_Other_PIA_Installation__c from Outlet_Dispensers2__r) from FS_Installation__c where Id=:RecID];
        objectCnt.displayError=false;
        objectCnt.displayErrorSync=false;
        objectCnt.IP_I4W_ReconnectDate=false;
        objectCnt.dispSecError=false;
        if(installation.Overall_Status2__c!=FSConstants.IPCANCELLED){
            
            List<String> platformsInstall=new List<String>();
            if(installation.Type_of_Dispenser_Platform__c!=FSConstants.NULLVALUE){
                platformsInstall=installation.Type_of_Dispenser_Platform__c.split(';');
            }
            
            final List<FS_Association_Brandset__c> assBrandsets =[SELECT FS_Brandset__c, FS_NonBranded_Water__c FROM FS_Association_Brandset__c WHERE FS_Installation__c =: installation.id];
            final Map<Id,FS_Execution_Plan__c> epWithinstallList=new Map<Id,FS_Execution_Plan__c>(
                [SELECT Id,FS_Platform_Type__c, (select id,Type_of_Dispenser_Platform__c from Outlet_Info_Summary__r where recordtypeId=:FSInstallationValidateAndSet.ipNewRecType)
                 from FS_Execution_Plan__c where Id =:installation.FS_Execution_Plan__c]);
            
            for (FS_Association_Brandset__c brandset : assBrandsets){
                if (brandset.FS_Brandset__c==FSConstants.ID_NULL || brandset.FS_NonBranded_Water__c==FSConstants.STR_NULL){
                    objectCnt.displayError=true;
                }
            }
            if(installation.RecordTypeId==FSInstallationValidateAndSet.ipNewRecType && installation.Type_of_Dispenser_Platform__c!=FSConstants.STR_NULL){
                final Set<string> allIpPlatformSet=new Set<String>();            
                List<String> platformsEP=new List<String>();
                
                
                final FS_Execution_Plan__c epItem=epWithinstallList.get(installation.FS_Execution_Plan__c);
                if(epItem.FS_Platform_Type__c!=FSConstants.NULLVALUE){
                    platformsEP= epItem.FS_Platform_Type__c.split(';');
                }
                if(!platformsInstall.isEmpty() ){
                    allIpPlatformSet.addAll(platformsInstall);
                }
                for(FS_Installation__c install:epItem.Outlet_Info_Summary__r){
                    if(install.Id!=installation.Id && install.Type_of_Dispenser_Platform__c!=FSConstants.NULLVALUE){                   
                        final List<String> platformIPList=install.Type_of_Dispenser_Platform__c.split(';');
                        allIpPlatformSet.addAll(platformIPList);                    
                    }                  
                }
                for(String platform: platformsInstall){
                    if(epItem.FS_Platform_Type__c==FSConstants.NULLVALUE || !epItem.FS_Platform_Type__c.contains(platform)){
                        objectCnt.displayErrorSync=true;
                    }
                }
                for(string platform: platformsEP){ 
                    if(!allIpPlatformSet.contains(platform)){
                        objectCnt.displayErrorSync=true;
                    }
                }
            }
            if (installation.RecordTypeId==FSInstallationValidateAndSet.ipRecTypeRelocation
                && installation.FS_Relocation_from_old_outlet_to_SP_is__c
                && installation.FS_Scheduled_Install_Date__c == installation.FS_Disconnect_Final_Date__c
                && installation.FS_Install_Reconnect_Date__c < installation.FS_Disconnect_Final_Date__c 
               ) {
                   objectCnt.IP_I4W_ReconnectDate=true;
               }
               /*   Commenting as part of  FNF-747 change : to remove the warning message for all PIA records*/
          /*  if(installation.RecordTypeId!=FSInstallationValidateAndSet.ipNewRecType && installation.Overall_Status2__c!=FSConstants.IPCANCELLED ){
                final Set<String> equipTypeSet=new Set<String>();
                List<String> equipTypeList=new List<String>();
                List<FS_Outlet_Dispenser__c> odRecList=new List<FS_Outlet_Dispenser__c>();            
                odRecList=installation.RecordTypeId==FSInstallationValidateAndSet.ipRecTypeRelocation?installation.Outlet_Dispensers1__r:installation.Outlet_Dispensers2__r;
                
                for(FS_Outlet_Dispenser__c od:odRecList){ 
                    //FET-1249 Changes END
                    equipTypeSet.add(od.FS_Equip_Type__c);
                }
                equipTypeList.addAll(equipTypeSet);
                system.debug('equipTypeList'+equipTypeList);
                system.debug('platformsInstall'+platformsInstall);
                for(String plat:equipTypeList){       if(!platformsInstall.contains(plat)){     objectCnt.dispSecError=true;  }  }
                for(String plat:platformsInstall){    if(!equipTypeList.contains(plat)){        objectCnt.dispSecError=true;  }  }
                
            }*/
            
        }
        objectCnt.recordTypeName = installation.RecordType.Name;
        objectCnt.installation = installation;
        return objectCnt;
    }   
    
    
}