force-app/main/default/objects/FS_Association_Brandset__c/FS_Association_Brandset__c.object-meta.xml
<CustomObject>
    <label>Default Brandset</label>
    <nameField>
        <displayFormat>AB-{00000}</displayFormat>
        <label>Account Brandset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Brandsets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Brandset__c.field-meta.xml
<CustomField>
    <fullName>FS_Brandset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brandset</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Selected Brandset is not available for commercial use</errorMessage>
        <filterItems>
            <field>FS_Brandset__c.FS_Platform_Applicable__c</field>
            <operation>contains</operation>
            <valueField>$Source.FS_Platform__c</valueField>
        </filterItems>
        <filterItems>
            <field>FS_Brandset__c.Available_for_Selection__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FS_Brandset__c</referenceTo>
    <relationshipLabel>Default Brandsets</relationshipLabel>
    <relationshipName>Brandsets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Installation__c.field-meta.xml
<CustomField>
    <fullName>FS_Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation Plan</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Selected Brandsets</relationshipLabel>
    <relationshipName>Account_Brandsets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Brandset__c/FS_Brandset__c.object-meta.xml
<CustomObject>
    <description>FS_Brandset</description>
    <label>Brandset</label>
    <nameField>
        <label>Brandset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brandsets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Brandset__c/fields/FS_Effective_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Effective_Start_Date__c</fullName>
    <inlineHelpText>Date when Brandset becomes available for commercial use</inlineHelpText>
    <label>Commercial Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Brandset__c/fields/FS_Platform__c.field-meta.xml
<CustomField>
    <fullName>FS_Platform__c</fullName>
    <description>Platform</description>
    <label>Platform</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Platform_Types</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation__c/fields/FS_Brandset__c.field-meta.xml
<CustomField>
    <fullName>FS_Brandset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Brandset 7000</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Value does not exist or does not match filter criteria.</errorMessage>
        <filterItems>
            <field>FS_Brandset__c.FS_Platform_Applicable__c</field>
            <operation>contains</operation>
            <value>7000</value>
        </filterItems>
        <filterItems>
            <field>FS_Brandset__c.Available_for_Selection__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>FS_Brandset__c</referenceTo>
    <relationshipLabel>Installations</relationshipLabel>
    <relationshipName>Installations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Change_Onboarding_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Change_Onboarding_Date__c</fullName>
    <label>Reschedule Onboarding Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Disconnect_Final_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Disconnect_Final_Date__c</fullName>
    <label>Disconnect Final Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Dry_Install__c.field-meta.xml
<CustomField>
    <fullName>FS_Dry_Install__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Dry Install</description>
    <inlineHelpText>Please ensure the On-Boarding date is equal or greater than the Fire Up date
(This may not apply to a PIA replacement form )</inlineHelpText>
    <label>Dry Install</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_HowManyDaysAfterInstallOnboarding__c.field-meta.xml
<CustomField>
    <fullName>FS_HowManyDaysAfterInstallOnboarding__c</fullName>
    <label>How Many Days After Install Onboarding</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Install_Reconnect_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Install_Reconnect_Date__c</fullName>
    <label>Initially Install/Reconnect Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_NewRemodelOutletOnlyProjectedFireUp__c.field-meta.xml
<CustomField>
    <fullName>FS_NewRemodelOutletOnlyProjectedFireUp__c</fullName>
    <label>Projected Fire-Up Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_No_SP_Storage_Relocation_complete__c.field-meta.xml
<CustomField>
    <fullName>FS_No_SP_Storage_Relocation_complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>No SP Storage - Relocation complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Orginal_Install_Stamp_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Orginal_Install_Stamp_Date__c</fullName>
    <description>This Captures the original Install date.</description>
    <label>Initially Scheduled Updated Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Original_Install_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Original_Install_Date__c</fullName>
    <label>Initially Scheduled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Original_Onboarding_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Original_Onboarding_Date__c</fullName>
    <formula>IF(OR(Overall_Status2__c= &#39;Pending Reschedule&#39;, ISNULL( FS_Scheduled_Install_Date__c), FS_Survey_Install_On_Hold__c = true , AND(ISNULL(FS_NewRemodelOutletOnlyProjectedFireUp__c), FS_Dry_Install__c = true)) , Date(2020, 12, 31), 
   IF( NOT(ISNULL(FS_Change_Onboarding_Date__c))  , FS_Change_Onboarding_Date__c , 
        IF( NOT(ISNULL(FS_NewRemodelOutletOnlyProjectedFireUp__c)) , FS_NewRemodelOutletOnlyProjectedFireUp__c +  FS_HowManyDaysAfterInstallOnboarding__c  , 
                        FS_Scheduled_Install_Date__c + FS_HowManyDaysAfterInstallOnboarding__c )
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Original Onboarding Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Pending_for_Reschedule__c.field-meta.xml
<CustomField>
    <fullName>FS_Pending_for_Reschedule__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pending Reschedule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Relocation_from_old_outlet_to_SP_is__c.field-meta.xml
<CustomField>
    <fullName>FS_Relocation_from_old_outlet_to_SP_is__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Remove/Disconnect Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_relocation_new_outlet_Complete__c.field-meta.xml
<CustomField>
    <fullName>FS_relocation_new_outlet_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Install/Reconnect complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Rush_Install_Reason__c.field-meta.xml
<CustomField>
    <fullName>FS_Rush_Install_Reason__c</fullName>
    <label>Rush Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Store Opening</fullName>
            </value>
            <value>
                <fullName>Marketing/Media</fullName>
            </value>
            <value>
                <fullName>Remodel</fullName>
            </value>
            <value>
                <fullName>Legacy Equipment Failure</fullName>
            </value>
            <value>
                <fullName>Customer Request</fullName>
            </value>
            <value>
                <fullName>Rebuild</fullName>
            </value>
            <value>
                <fullName>Health Inspection</fullName>
            </value>
            <value>
                <fullName>Coordinator Error</fullName>
            </value>
            <value>
                <fullName>NRA</fullName>
            </value>
            <value>
                <fullName>SA Not Uploaded</fullName>
            </value>
            <value>
                <fullName>Customer Unable to Pour Product</fullName>
            </value>
            <value>
                <fullName>Limited Dispenser Accessibility</fullName>
            </value>
            <value>
                <fullName>External Process Failure</fullName>
            </value>
            <value>
                <fullName>Acts of God</fullName>
            </value>
            <value>
                <fullName>Trade Show</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/FS_Survey_Install_On_Hold__c.field-meta.xml
<CustomField>
    <fullName>FS_Survey_Install_On_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Survey/Install - On Hold</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/fields/Overall_Status2__c.field-meta.xml
<CustomField>
    <fullName>Overall_Status2__c</fullName>
    <label>Transaction Status</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FS_Installation_Reschedule__c/FS_Installation_Reschedule__c.object-meta.xml
<CustomObject>
    <description>This object stores the reschedule information and is created as part of FET 5.0 release..</description>
    <label>Reschedule</label>
    <nameField>
        <displayFormat>RS-{0000000}</displayFormat>
        <label>Reschedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reschedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Installation_Reschedule__c/fields/FS_Ignore_Brandset_Check__c.field-meta.xml
<CustomField>
    <fullName>FS_Ignore_Brandset_Check__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check box will be used in back end to invoke the trigger based on the conditions</description>
    <label>Ignore Brandset Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Installation_Reschedule__c/fields/FS_Ignore_brandset_commercial_date__c.field-meta.xml
<CustomField>
    <fullName>FS_Ignore_brandset_commercial_date__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ignore brandset commercial approval date</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Installation_Reschedule__c/fields/FS_Installation__c.field-meta.xml
<CustomField>
    <fullName>FS_Installation__c</fullName>
    <label>Installation Name</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Transaction Reschedule/s</relationshipLabel>
    <relationshipName>Installation_Reschedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FS_Installation_Reschedule__c/fields/FS_Reschedule_Install_Date__c.field-meta.xml
<CustomField>
    <fullName>FS_Reschedule_Install_Date__c</fullName>
    <label>Reschedule Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/FS_Installation_Reschedule__c/fields/FS_Rush_Install_Check__c.field-meta.xml
<CustomField>
    <fullName>FS_Rush_Install_Check__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check box will be used in back end to invoke the trigger based on the conditions</description>
    <label>Rush Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FS_Installation_Reschedule__c/fields/FS_Rush_Install_Reason__c.field-meta.xml
<CustomField>
    <fullName>FS_Rush_Install_Reason__c</fullName>
    <label>Rush Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Store Opening</fullName>
            </value>
            <value>
                <fullName>Marketing/Media</fullName>
            </value>
            <value>
                <fullName>Remodel</fullName>
            </value>
            <value>
                <fullName>Legacy Equipment Failure</fullName>
            </value>
            <value>
                <fullName>Customer Request</fullName>
            </value>
            <value>
                <fullName>Rebuild</fullName>
            </value>
            <value>
                <fullName>Health Inspection</fullName>
            </value>
            <value>
                <fullName>PIC Error</fullName>
            </value>
            <value>
                <fullName>NRA</fullName>
            </value>
            <value>
                <fullName>SA Not Uploaded</fullName>
            </value>
            <value>
                <fullName>Customer Unable to Pour Product</fullName>
            </value>
            <value>
                <fullName>Limited Dispenser Accessibility</fullName>
            </value>
            <value>
                <fullName>External Process Failure</fullName>
            </value>
            <value>
                <fullName>Acts of God</fullName>
            </value>
            <value>
                <fullName>Trade Show</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Platform_Types.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>3100</fullName>
    </customValue>
    <customValue>
        <fullName>6000</fullName>
    </customValue>
    <customValue>
        <fullName>7000</fullName>
    </customValue>
    <customValue>
        <fullName>7100</fullName>
    </customValue>
    <customValue>
        <fullName>8000</fullName>
    </customValue>
    <customValue>
        <fullName>9000</fullName>
    </customValue>
    <customValue>
        <fullName>9100</fullName>
    </customValue>
    <masterLabel>Platform Types</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FSInstallRescheduleTriggerhandler.cls
/*****************************
Name         : FSInstallRescheduleTriggerhandler
Created By   : Infosys
Created Date : 19/03/2018
Usage        : This class holds the business logic of the installation Reschedule object.
*****************************/
public class FSInstallRescheduleTriggerhandler {  
    
    public static final Integer INTFIVE = 5;
    public static final Integer INTSEVEN = 7;
    public static final String CLASSNAME='FSInstallRescheduleTriggerhandler';
    public static Map<Id,FS_Installation__c> installMap;
    public static void isBeforeInsert(final List<FS_Installation_Reschedule__c> newList,final Map<Id,FS_Installation_Reschedule__c> newMap,final Map<Id,FS_Installation_Reschedule__c> oldMap){
        validateInstallRecords(newList,newMap,oldMap);
        system.debug('No of Queries used Reschedule BeforeInsert: ' + Limits.getQueries());
    }
    //  update the installation records 
    public static void isAfterInsert(final List<FS_Installation_Reschedule__c> newList,final Map<Id,FS_Installation_Reschedule__c> newMap,final Map<Id,FS_Installation_Reschedule__c> oldMap){
        copyRescheduleValuesToInstall(newList,newMap,oldMap);
        system.debug('No of Queries used Reschedule AfterInsert: ' + Limits.getQueries());
        FSInstallationBusinessProcess.runRescheduleOnce=false;
    }
    
     /*****************************************************************
Method: validateInstallRecords
Description: validateInstallRecords method to Validate the Rush Install and Ignore Brandset from installation records
New:Venkat as part of FET 5.0 FET 120 To validate Rush Install and Ignore Branset Scenarios 
*******************************************************************/ 
    
    public static void validateInstallRecords(final List<FS_Installation_Reschedule__c> newList,final Map<Id,FS_Installation_Reschedule__c> newMap,final Map<Id,FS_Installation_Reschedule__c> oldMap){
        final Set<Id> installIdSet=new Set<Id>();
        Boolean ignoreBrandCheck;
        for(FS_Installation_Reschedule__c ipResch:newList){ 
            installIdSet.add(ipResch.FS_Installation__c);      
        }
        // Query to retrive  installation object with associated brandset values for given installation 
         installMap=new Map<Id,FS_Installation__c>(
            [select id,name,RecordTypeId,RecordType.Name,FS_Install_Reconnect_Date__c,FS_Original_Install_Date__c,FS_Orginal_Install_Stamp_Date__c,FS_Rush_Install_Reason__c,Overall_Status2__c,
             FS_Original_Onboarding_Date__c,FS_Survey_Install_On_Hold__c,FS_NewRemodelOutletOnlyProjectedFireUp__c,FS_Dry_Install__c,
             FS_Change_Onboarding_Date__c,FS_HowManyDaysAfterInstallOnboarding__c, 
             FS_Relocation_from_old_outlet_to_SP_is__c,FS_relocation_new_outlet_Complete__c,FS_No_SP_Storage_Relocation_complete__c,FS_Disconnect_Final_Date__c,
             	(select id,FS_Brandset__c,FS_Platform__c,FS_Brandset__r.FS_Effective_Start_Date__c,FS_Installation__c from Account_Brandsets__r) 
             from FS_Installation__c where Id IN:installIdSet]);
        
        final  date defaultDate= date.newInstance(1900, 1, 8);//set date for calculations
        Integer numberDaysDue;//to calculate difference between given dates. 
        Integer numberDaysDue2;
        Boolean rushCheck;
        Double eDays;//to hold value of elapse days
        for(FS_Installation_Reschedule__c ipResch:newList){
            ignoreBrandCheck=false; //Checkbox to check Brandset date less than Scheduled date
            final FS_Installation__c install=installMap.get(ipResch.FS_Installation__c);
            rushCheck=false;//Boolean to check for rush install reason
            rushCheck=install.FS_Rush_Install_Reason__c==FSConstants.NULLVALUE?True:false;//assigning TRUE if Install rush reason is null
            rushCheck=(rushCheck && ipResch.FS_Rush_Install_Reason__c==FSConstants.NULLVALUE)?True:false;//assigning TRUE if both IP and Reschdule rush reason is NULL
            
            //Cannot provide Reschedule date or Pending Reschedule once Install/Reconnect complete check box is checked
                if (install.RecordType.Name==Label.IP_Relocation_I4W_Rec_Type && install.FS_relocation_new_outlet_Complete__c && install.FS_Relocation_from_old_outlet_to_SP_is__c){
                    ipResch.addError(Label.IP_I4W_Reschedule_Error);
                }
            
            //Reschedule Date Null Check
            if(ipResch.FS_Reschedule_Install_Date__c!=FSConstants.NULLVALUE){
                
                if(install.RecordType.Name==FSConstants.NEWINSTALLATION){
                    Date dateinst=Date.newInstance(2020, 12, 31);
                    Integer addDaysValue=Integer.valueOf(install.FS_HowManyDaysAfterInstallOnboarding__c);
                    if(install.FS_Survey_Install_On_Hold__c || (install.FS_NewRemodelOutletOnlyProjectedFireUp__c==null && install.FS_Dry_Install__c)){
                        dateinst=Date.newInstance(2020, 12, 31);
                    }
                    else if(install.FS_Change_Onboarding_Date__c!=null){  dateinst=install.FS_Change_Onboarding_Date__c;     }
                    
                    else if(install.FS_NewRemodelOutletOnlyProjectedFireUp__c!=null){
                        dateInst= install.FS_NewRemodelOutletOnlyProjectedFireUp__c;
                        
                        if(addDaysValue!=null){ dateInst=dateInst.addDays(addDaysValue);        }                        
                    }
                    else{
                        dateInst=ipResch.FS_Reschedule_Install_Date__c;                       
                        if(addDaysValue!=null){ dateInst=dateInst.addDays(addDaysValue);        }  
                    }
                    if(dateInst<ipResch.FS_Reschedule_Install_Date__c){                   
                        ipResch.addError('New Onboarding Date Needs to Be Equal or Greater than Installation Date. ['+dateInst.format()+']');
                    }
                }
                
                
                //Rescheduled Date should reflect a date later than the date provided on Original Install/Reconnect Date
                //if(install.FS_Install_Reconnect_Date__c!=FSConstants.NULLVALUE && install.FS_Relocation_from_old_outlet_to_SP_is__c && !install.FS_relocation_new_outlet_Complete__c&& ipResch.FS_Reschedule_Install_Date__c<install.FS_Install_Reconnect_Date__c){
                   // ipResch.FS_Reschedule_Install_Date__c.addError('Rescheduled Date should reflect a date later than the date provided on Original Install/Reconnect Date');
                //}
                
                //POC Reschedule Date should be later than last Remove/Disconnect scheduled date
                if(install.RecordType.Name==Label.IP_Relocation_I4W_Rec_Type && install.FS_Relocation_from_old_outlet_to_SP_is__c && ipResch.FS_Reschedule_Install_Date__c<install.FS_Disconnect_Final_Date__c	){
                    Date discDate = install.FS_Disconnect_Final_Date__c;
                    ipResch.addError('Rescheduled Date should reflect a date later than the last Remove/Disconnect scheduled date of ('+discDate.month()+'/'+discDate.day()+'/'+discDate.year()+')');
                }
                
                //Installation Original Stamp Date Null Check
                if(install.FS_Orginal_Install_Stamp_Date__c!=FSConstants.NULLVALUE){
                    final Date originalInstallStampDate=install.FS_Orginal_Install_Stamp_Date__c;
                    numberDaysDue = defaultDate.daysBetween(originalInstallStampDate);
                    numberDaysDue2 = defaultDate.daysBetween(ipResch.FS_Reschedule_Install_Date__c);
                    //Calculating business Days between Reschdule Date and Install Stamp Date
                    eDays= (INTFIVE * ( math.floor(( defaultDate.daysBetween(ipResch.FS_Reschedule_Install_Date__c)  ) / INTSEVEN) ) + math.MIN( INTFIVE, math.MOD( numberDaysDue2,INTSEVEN) ) )
                        -(INTFIVE * ( math.floor( defaultDate.daysBetween(originalInstallStampDate) / INTSEVEN)) + math.MIN( INTFIVE, math.MOD(numberDaysDue,INTSEVEN ) ) );
                    //if days <=16 and rush install reason Not filled in installation and re-scheduled 
                    if(eDays<=16 && rushCheck){
                        //assigning value to check box to initiate validation Rule
                        ipResch.FS_Rush_Install_Check__c=true;                        
                    } 
                    else{
                        ipResch.FS_Rush_Install_Check__c=false;
                    }
                }
                system.debug('ipResch.FS_Rush_Install_Check__c'+ipResch.FS_Rush_Install_Check__c);
                if((install.Overall_Status2__c==FSConstants.x3PendingSchedu ||  install.Overall_Status2__c==FSConstants.x4InstallSchedule) && (install.RecordType.Name==Label.IP_New_Install_Rec_Type || install.RecordType.Name==Label.IP_Replacement_Rec_Type || install.RecordType.Name==Label.IP_Relocation_I4W_Rec_Type)){
                    for(FS_Association_Brandset__c brands:install.Account_Brandsets__r){ 
                        //Brandset Not Null and Reschedule date less than Brandset Effective date
                        if(brands.FS_Brandset__c!=FSConstants.NULLVALUE && ipResch.FS_Reschedule_Install_Date__c<brands.FS_Brandset__r.FS_Effective_Start_Date__c 
                           && !ipResch.FS_Ignore_brandset_commercial_date__c){                            
                            //assigning value to check box to initiate validation Rule
                            ignoreBrandCheck=true;                           
                        }                
                    }
                    ipResch.FS_Ignore_Brandset_Check__c=ignoreBrandCheck; 
                }
            }
        }
    }  
    
    
    /*****************************************************************
Method: copyRescheduleValuesToInstall
Description: copyRescheduleValuesToInstall method to update installation fields after validation    
New:Venkat as part of FET 5.0 FET 120 copy values from installation Reschedule to Installation
*******************************************************************/ 
    public static void copyRescheduleValuesToInstall(final List<FS_Installation_Reschedule__c> newList,final Map<Id,FS_Installation_Reschedule__c> newMap,final Map<Id,FS_Installation_Reschedule__c> oldMap){
        final Map<Id,FS_Installation__c> installMapUpdate=new Map<Id,FS_Installation__c>();        
        FS_installation__c install;
        
        for(FS_Installation_Reschedule__c ipResch:newList){          
            //Checking the Installation refrence in Map
            if(installMap.containsKey(ipResch.FS_Installation__c)){
                install=installMap.get(ipResch.FS_Installation__c);                
                install.FS_Pending_for_Reschedule__c=ipResch.FS_Pending_for_Reschedule__c;
                install.FS_Scheduled_Install_Date__c=ipResch.FS_Reschedule_Install_Date__c;
                install.FS_Confirm_Install_Date__c=ipResch.FS_Ignore_brandset_commercial_date__c;
                //Assigning Rush Install Reason to Install if Not NULL
                if(ipResch.FS_Rush_Install_Reason__c!=FSConstants.NULLVALUE){
                    install.FS_Rush_Install_Reason__c=ipResch.FS_Rush_Install_Reason__c;
                }
                //Is Transaction Currently a Rush? field value to switch to "No" when
                //Pending Reschedule check box on reschedule is true
                if(ipResch.FS_Pending_for_Reschedule__c==True){
                    install.Is_Install_Currently_a_Rush__c='No';
                    install.Fs_Elapse_Days__c=null;
                }
                
                installMapUpdate.put(install.Id, install); 
            }                                         
        }
        
        //Updating Installation if Map is not empty
        if(!installMapUpdate.isEmpty()){ 
            //Creating error logger instance with required information
            final Apex_Error_Log__c apexError=new Apex_Error_Log__c(Application_Name__c=FSConstants.FET,Class_Name__c=CLASSNAME,Object_Name__c=FSConstants.INSTALLATIONOBJECTNAME,
                                                                    Method_Name__c='copyRescheduleValuesToInstall',Error_Severity__c=FSConstants.MediumPriority);                                                                    
            //Updating Installation records
            FSUtil.dmlProcessorUpdate(installMapUpdate.values(),true,apexError);
            
        }
    }    
}