force-app/main/default/objects/FS_Association_Brandset__c/FS_Association_Brandset__c.object-meta.xml
<CustomObject>
    <label>Default Brandset</label>
    <nameField>
        <displayFormat>AB-{00000}</displayFormat>
        <label>Account Brandset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Default Brandsets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Headquarters__c.field-meta.xml
<CustomField>
    <fullName>FS_Headquarters__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Headquarters</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>FS Headquarters</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Default Brandset</relationshipLabel>
    <relationshipName>FSHeadquarters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Installation__c.field-meta.xml
<CustomField>
    <fullName>FS_Installation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installation Plan</label>
    <referenceTo>FS_Installation__c</referenceTo>
    <relationshipLabel>Selected Brandsets</relationshipLabel>
    <relationshipName>Account_Brandsets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Association_Brandset__c/fields/FS_Outlet_Dispenser__c.field-meta.xml
<CustomField>
    <fullName>FS_Outlet_Dispenser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Outlet Dispenser</label>
    <referenceTo>FS_Outlet_Dispenser__c</referenceTo>
    <relationshipLabel>Brandset Details (Current)</relationshipLabel>
    <relationshipName>OutletDispensers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FS_Installation__c/FS_Installation__c.object-meta.xml
<CustomObject>
    <description>Installation</description>
    <label>Installation</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Installation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Installations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FS_Outlet_Dispenser__c/FS_Outlet_Dispenser__c.object-meta.xml
<CustomObject>
    <description>Outlet Dispenser.</description>
    <label>Outlet Dispenser</label>
    <nameField>
        <displayFormat>OD-{0000}</displayFormat>
        <label>Outlet Dispensers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Outlet Dispensers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/deleteDefaultBrandSetController.cls
public class deleteDefaultBrandSetController {
	public static String accId {get; set;}
    String retUrl;
    public Boolean parentrecordChk {get; set;}
    String usrProfileName {get; set;}
    public static String hqId {get; set;}
    public deleteDefaultBrandSetController(ApexPages.StandardController controller) {
        system.debug('in Constructor ');
        system.debug('!!!!' + ApexPages.currentPage().getUrl());
        
        retUrl = ApexPages.currentPage().getUrl();
        String [] listaccId= retUrl.split('&id=',2);
        accid=listaccId[1].subString(0,15);
        parentrecordChk = true;
        id recid = id.valueof(accid);
        String sObjName = recid.getSObjectType().getDescribe().getName();
        system.debug('sObjName:' +sObjName);

        //usrProfileName = [select u.Profile.Name from User u where u.id = :Userinfo.getUserId()].Profile.Name;
    }
    
    public void deleteBrandSet()
    {
        system.debug('inside delete method');
        system.debug('brandsetId '+accID );
        List<FS_Association_Brandset__c> deleteBs = [select id,name,FS_Headquarters__c,FS_Installation__c,FS_Outlet_Dispenser__c,LastModifiedById from FS_Association_Brandset__c where id = :accid];
        
        If(deleteBs[0].FS_Headquarters__c != null)
        {
            system.debug('inside delete if');
            hqId = deleteBs[0].FS_Headquarters__c;
            delete deleteBs;
            
        }
        else
        {
            parentrecordChk = false;
            
        }
    }
    
    
}